### ISSUE TITLE
Collectors authentication (ADFS/OAuth)

### ISSUE THREAD

**Issue by mmullerbr** [Hygieia/Hygieia#1053]
Hi,

we are trying to consume Jira, BitBucket, Jenkins and Sonar hosted behind a federations service (ADFS).  OAuth is also available. Do you offer any means to authenticate the collector so we can retrieve the data? Note that I do not want to federate the Hygieia Application it self, only the collectors (for now).

My HL architecture is described as follows: Collectors (running on AWS) -> DevOps Tools (running on Enterprise network, behind federation).

**Comment by pess0a** [comment]
+1 oAuth

**Comment by tabladrum** [comment]
We have similar situations in some cases - meaning some tool (such as SVN for example) is in Enterprise Network. All you need (I think) is an admin level system account on those tools and your AWS security group allowing outbound traffic to your enterprise network.

**Comment by mmullerbr** [comment]
@tabladrum the point is when the request gets to the enterprise reverse proxy it identifies the call as an unauthenticated one, and redirects the call to the federation authentication page. Once this is a collector request, there is no user to provide credentials, and the request fails.  All this happens before the collector request reach the destination tool. I was wondering if it is possible to provide user credentials to the collectors, so it can use the credential when requesting data.
