### ISSUE TITLE
Deploy widget grouping is incorrect

### ISSUE THREAD

**Issue by tabladrum** [Hygieia/Hygieia#1057]
I set up three deployment jobs from my "TestJenkins" for three different apps: "MyTestApp", "MySecondApp", "AnotherTestApp". On the deploy widget config they show up as just one entry:

![image](https://cloud.githubusercontent.com/assets/6014941/21530925/3c300b0c-cd12-11e6-90c6-826e1e76be4e.png)

@MarkRx I think this logic in UI/src/components/widgets/deploy/config.js is not quite correct 
link to the diff: https://github.com/capitalone/Hygieia/pull/891/files?diff=split

**Comment by MarkRx** [comment]
Do the created collector items have unique options.applicationId's? Can you post them? The assumption would be that "MyTestApp", "MySecondApp", and "AnotherTestApp" would each have their own unique applicationId. If not then they will be treated as the same application if they all have the same instanceUrl.

```
var dataGrouped = dataGrouped = _(data)
                	.groupBy(function(d) { return (!multiServerEquality ? d.options.instanceUrl + "#" : "" ) + d.options.applicationId; })
                	.map(function(d) { return d; });
```

**Comment by tabladrum** [comment]
Ah. Got it. In my case (testing jenkins plugin) I had the same instanceUrl. And no applicationId in the collector item option. May be the workaround is to put Job url in the "instanceUrl". Not sure yet. But manually editing the json document to make the instance url the job url did work. 

Noticed that if I turn the grouping off, it still groups.

**Comment by tabladrum** [comment]
@MarkRx the following code should work both ways:
``` 
var dataGrouped =  _(data)
                	.groupBy(function(d) { return (!multiServerEquality || d.options.applicationId == null ? d.options.instanceUrl + "#"+d.options.applicationName : "" ) + d.options.applicationId; })
                	.map(function(d) { return d; });
```
Can you test this change locally?

**Comment by MarkRx** [comment]
I think the proper solution should be to have the jenkins plugin assign each application an applicationId. That field really shouldn't be nullable as it is meant to be an identifier. The identifier could be something arbitrary like the md5sum of the instanceUrl + applicationName. It's possible there are other parts of the code that will choke if it is null.



Since a.applicationId == b.applicationId implies a.applicationName == b.applicationName you can use this:

```
var dataGrouped = dataGrouped = _(data)
                	.groupBy(function(d) { return (!multiServerEquality ? d.options.instanceUrl + "#" : "" ) + d.options.applicationName + "#" + d.options.applicationId; })
                	.map(function(d) { return d; });
```

**Comment by tabladrum** [comment]
The origin of applicationID was from uDeploy that had some kind of of UUID for each applicationID. I am sure this ID will change if the same App was setup in another "Prod" uDeploy server. May be we should create another ID (some kind of CMDB identifier)? In your case, how are you keeping this ID same across multiple deployment server?

**Comment by MarkRx** [comment]
I kind of "cheated". XLD uses composite path keys based on the names of items in the path. Since this is the case the applicationId remains the same so long as they have the same path.

For example:

Server1:
Id: Applications/Foo/Bar
Name: Bar

Server2:
Id: Applications/Foo/Bar
Name: Bar

**Comment by tabladrum** [comment]
@MarkRx @amitmawkin @satishc1 @mrpudn please review these following change proposal before I submit it in a PR form:

With PR https://github.com/capitalone/Hygieia/pull/891 there was a change in how deployed Apps were grouped together by "deploying server"s. Nice change. This allows to visualize an App deployment where different deployment servers (such as QA Jenkins, Prod Jenkins or whatever) are deploying the same app.

There are two major changes in that PR:
1. New API for to return a boolean attribute (systemConfig.multipleDeploymentServers) to the API properties file that determines if servers need to be grouped. 
2. UI changes to group the servers in https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/deploy/config.js and https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/deploy/config.html

I am proposing a refactor of #1 and slight change to #2.

**Slight Change to #2**: Instead of relying on non-null applicationId, I am proposing a non-null applicationName + applicationId check in grouping of elements:

*Old code* (https://github.com/capitalone/Hygieia/blob/master/UI/src/components/widgets/deploy/config.js)
```
                var dataGrouped = _(data)
                    .groupBy(function(d) { return (!multiServerEquality ? d.options.instanceUrl + "#" : "" ) + d.options.applicationId; })
                    .map(function(d) { return d; });
```

*Proposed change*

```
                var dataGrouped = _(data)
                    .groupBy(function(d) { return (!multiServerEquality ? d.options.instanceUrl + "#" : "" ) + d.options.applicationName + d.options.applicationId; })
                    .map(function(d) { return d; });
```



**Refactoring of #1**
Instead of capturing/configuring the "multipleDeploymentServers" property via API, I am proposing that we do that in the UI and store each individual dashboard's choice in the "dashboard" document in dashboard -> widgets -> options section of the json document:

```
        {
            "_id" : ObjectId("5863ed079220ab16e6a1c3c8"),
            "name" : "deploy",
            "componentId" : ObjectId("583394884969c83f6715b588"),
            "options" : {
                "id" : "deploy0",
                "aggregateServers" : true
            }
        }, 
```

Corresponding UI changes are pretty simple. 
*Add a check box in deploy widget config:*
```
        <div class="form-group checkbox">
            <label>
                <input type="checkbox" name="aggregateServers" ng-model="deployConfig.aggregateServers" ng-change="reload()">
                Aggregate Servers
            </label>
        </div>
```
Add a new variables in the corresponding controller (config.js) and add a function that looks like this:

```
        $scope.reload = function() {
            processResponse(ctrl.currentData);
        };
```

And store the currentData in a global variable after the data is obtained from the API calls.

With these changes, there will be no API needed to save/retrieve the config and the config is set for each individual dashboard.

Thoughts?

Screen shots:
![image](https://cloud.githubusercontent.com/assets/6014941/21591810/8f11a27e-d0d5-11e6-8e63-fecc76d3a1c2.png)

![image](https://cloud.githubusercontent.com/assets/6014941/21591823/af2b0668-d0d5-11e6-91e5-3463dcf2bc8c.png)


![image](https://cloud.githubusercontent.com/assets/6014941/21591826/bf23852c-d0d5-11e6-937f-f69b132f0a19.png)

![image](https://cloud.githubusercontent.com/assets/6014941/21591831/d4c68654-d0d5-11e6-8ced-6671732c4a7d.png)

**Comment by mrpudn** [comment]
After reading the thread, I think I follow...

Would it make more sense for the collector to record the deployment server as a compound key?

i.e.
```json
[
  {
    "applicationId": "MyTestApp",
    "deployServer": "TestJenkins"
  },
  {
    "applicationId": "MySecondApp",
    "deployServer": "TestJenkins"
  },
  {
    "applicationId": "AnotherTestApp",
    "deployServer": "TestJenkins"
  }
]
```

I'm not sure exactly what the data looks like that the widget is displaying or if I completely understand the problem, but this data model would make it possible to group/aggregate by deploy server, as proposed.

**Comment by MarkRx** [comment]
@mrpudn changing the collectors / collector_items around would be a big undertaking and would most certainly not be backwards compatible.

@tabladrum Looks fine so long as the same guid implies the same name (meaning we don't care about renaming). Just note I don't see the api endpoint I made going away as there are more uses for it. For example: Configurable Pipeline Stage Names #1020

**Comment by tabladrum** [comment]
@MarkRx The "System Config" API should evolve. For this particular instance we will rely on the UI config ability.

**Comment by MarkRx** [comment]
Sounds good.

**Comment by tabladrum** [comment]
https://github.com/capitalone/Hygieia/pull/1055
