### ISSUE TITLE
Performance Monitoring & Log Aggregator collectors in Hygieia Dashboard

### ISSUE THREAD

**Issue by Mahendra1260** [Hygieia/Hygieia#1087]
@satishc1 @MarkRx @tabladrum 
Hi Team,
Hygieaia documentation mentions about Performance Monitoring integration as well.
Where can I find that collector and which Performance monitoring tools are being integrated with the same. (For e..g. NewRelice/ Dynatrace etc)
Also, can I have any reference to have any log aggregation integration with Hygieia (for E,g Splunk)

**Comment by Mahendra1260** [comment]
Any thought on this ?
@satishc1 @MarkRx @tabladrum

**Comment by MarkRx** [comment]
There are none. @tabladrum was looking at an AppD integration but I don't know what became of that.

**Comment by amitsrivastav** [comment]
i am also looking for these collectors with hygieia. please update if its available for any monitoring solution now.

**Comment by paulberater** [comment]
i need it too! anyone found a solution?

**Comment by rvema** [comment]
Performance metrics were implemented for Appdynamics ([hygieia-perf-appdynamics-collector](https://github.com/Hygieia/hygieia-perf-appdynamics-collector)) and Log aggregation was implemented for AWS cloudwatch ([hygieia-cloud-cloudwatch-collector](https://github.com/Hygieia/hygieia-cloud-cloudwatch-collector)) . For other tools we are open to contributions by taking the mentioned repositories as reference.
