### ISSUE TITLE
Query regarding Product View

### ISSUE THREAD

**Issue by avadhmr** [Hygieia/Hygieia#1120]
Hi,

I want to know if there is any possible way for aggregating various modules which form one complete application.
In our case we have application divided into multiple independent components having separate git repos, jenkins jobs , sonar projects etc.
In the Product view, I can list them as separate rows but is there a way to aggregate the results of all components into one row and give an out look of the application as whole? 

Also any future plans of having a collector for CA release automation deployment tool?

**Comment by tabladrum** [comment]
@avadhmr can you provide some type of wire frames/sketch of what you are looking for?

Would love to integrate as many tools as we can. Unfortunately we don't use CA Release Automation tool. 

Checkout this fork: https://github.com/RLIndia/Hygieia they have developed some collectors but not sure why didn't do a PR.
