### ISSUE TITLE
90 days pipeline - Data mismatch

### ISSUE THREAD

**Issue by BoomaBaskaran** [Hygieia/Hygieia#1148]
Hi,

We are using Jenkins build tool. For every commit, Jenkins job will trigger and it will do Sonar analysis and security scan. Now the issue is, on a particular day my jenkins job has triggered and it did sonar and security analysis - But 90-day Pipeline Health Trend shows the data in **Security Issues** but there is no data in **Code issues** tab. Why this data mismatch happen?

Please let me know the issue.

Thanks,
Booma Baskaran.

**Comment by tabladrum** [comment]
Can you paste a screen shot of your Quality widget?

**Comment by BoomaBaskaran** [comment]
Below are the screen shots,

![quality-widget](https://cloud.githubusercontent.com/assets/5907275/22727478/0fec207c-edff-11e6-90ac-ead38585e56c.jpg)

![90 days - code issues](https://cloud.githubusercontent.com/assets/5907275/22727595/beb844a0-edff-11e6-9a51-5c358037e825.jpg)

![90 days - security issues](https://cloud.githubusercontent.com/assets/5907275/22727596/bebc8966-edff-11e6-84c6-425dc04e7157.jpg)

**Comment by BoomaBaskaran** [comment]
One more clarification. We have fixed some of the Sonar issues and the code issue's trend shows green arrow down. Security issues has increased for the last few days and here also trend shows green arrow down. Which is the opposite of the reality. What is the logic behind trend arrow?

**Comment by BoomaBaskaran** [comment]
Any update on this..

**Comment by BoomaBaskaran** [comment]
I got an answer for data mismatch. Sonar analysis not happening for the days we don't have trend graph. But I am still concerning about Trend arrows.

In the security graph above, security issues has increased for the past few days. The trend should show red arrow going up instead it shows green arrow going down. Why?

Please clarify.

**Comment by BoomaBaskaran** [comment]
Any update on this.
