### ISSUE TITLE
Hygieia plugin for Jenkins supported Test ?

### ISSUE THREAD

**Issue by xpdable** [Hygieia/Hygieia#1158]
Not sure whether duplicated with #666 

I am using Jenkins plugin and try to publish some test result back to Hygieia as what I set below:
![image](https://cloud.githubusercontent.com/assets/2903719/22724068/b03b2f9c-edfe-11e6-95a5-6f86fe56cd72.png)

Before that I have the mvn test execution to trigger those tests.

The log shows that the test file is not correctly parsed.
Thus, could you please advice which TEST file / format/ tools are supported by the plugin to publish?

Log: 

> [INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:37 min
[INFO] Finished at: 2017-02-08T12:39:18+08:00
[INFO] Final Memory: 154M/367M
[INFO] ------------------------------------------------------------------------
Sending e-mails to: xxxxxxxxxxxxxxx
Hygieia: Published Build Complete Data. Response Code: 201. Response Value= 58994f065c61b42a4c683f27
Hygieia Test Result Publisher - Looking for file pattern '*.xml' in directory /home/win-01-jenkins/sharedspace/xxxxxx
Hygieia Test Publisher: Processing file: /home/ejvqa-win-01-jenkins/sharedspace/bimbqm/bimbqm-common/target/surefire-reports/TEST-com.tr.bimbqm.common.MappingCountTest.xml
Hygieia Publisher: Error Parsing File: /home/ejvqa-win-01-jenkins/sharedspace/bimbqm/bimbqm-common/target/surefire-reports/TEST-com.tr.bimbqm.common.MappingCountTest.xml
Hygieia: Published Test Data. Nothing to publish

**Comment by xpdable** [comment]
@tabladrum 
ok... I take a look into the https://github.com/capitalone/Hygieia/blob/master/hygieia-jenkins-plugin/src/main/java/jenkins/plugins/hygieia/workflow/HygieiaTestPublishStep.java#L197 
And it proves to be only cucumber test is supported :( ?
Therefore, back to #666, will JUnit supported ?

**Comment by rvema** [comment]
closing this duplicate issue, same as #666
