### ISSUE TITLE
Bamboo : Is their any way to configure Deployment plans in Hygieia

### ISSUE THREAD

**Issue by smlcodes** [Hygieia/Hygieia#1203]
Iam able to get Build plans & displaying in Hygieia Dashboard. But how to configure Deployment plans & how to display them in dashboard ?

**Comment by smlcodes** [comment]
Some body answer pls!!1

**Comment by baitiandi** [comment]
any update to configure Deployment plans and how to display them in dashboard. or any idea.

**Comment by Sbrenthughes** [comment]
There isn't a way as far as I am aware. We would need the community to contribute this functionality.
