### ISSUE TITLE
The latest build number in the pipeline build stage can't be updated. 

### ISSUE THREAD

**Issue by wdquan1985** [Hygieia/Hygieia#1221]
![latest_build](https://cloud.githubusercontent.com/assets/15209842/23534178/0e7a9990-fff1-11e6-8aa0-ec7ac7e715c5.png)
After a new build info has been imported to hygieia server, the build stage will make a request, such as http://localhost:3000/api/build/?componentId=58aba84b22b4042344b9ac6c&endDateBegins=1488258758706&endDateEnds=1488357136355, to update the latest build number. If the time of jenkins server is earlier than hygieia server, the endTime of the new build info should be earlier than endDateBegins which always use the current time of hygieia server, so the request will never get any info, the latest build number can't be updated.
In order to avoid this issue, I suggest using the endTime of the new build info as the endDateBegins.

**Comment by wdquan1985** [comment]
I have changed the code as following.
diff --git a/build-data_old.js b/build-data_old.js
index b8daffb..cffbc33 100644
--- a/build-data.js
+++ b/build-data.js
@@ -27,8 +27,6 @@
             dateEnds = now.valueOf(),
             ninetyDaysAgo = now.add(-90, 'days').valueOf(),
             dateBegins = ninetyDaysAgo;
-        //bruce
-        var lastBuildEndTime = 0;

         db.lastRequest.where('[type+id]').equals(['build-data', componentId]).first().then(processLastRequestResponse);

@@ -41,12 +39,6 @@
             buildData
                 .details({componentId: componentId, endDateBegins: dateBegins, endDateEnds: dateEnds})
                 .then(function(response) {
-                       //bruce
-                       if(response.result.length){
-                               var bruceObject = response.result[response.result.length -1];
-                               lastBuildEndTime = bruceObject.endTime;
-                       }
-
                     processBuildDetailsResponse(response, lastRequest);
                 })
                 .then(processBuildDetailsData)
@@ -63,30 +55,16 @@

             // save the request object so we can get the delta next time as well
             if(lastRequest) {
-               //bruce
-               if(lastBuildEndTime){
-                       lastRequest.timestamp = lastBuildEndTime;
-               }else{
-                    lastRequest.timestamp = dateEnds;
-               }
+                lastRequest.timestamp = dateEnds;
                 lastRequest.save();
             }
             // need to add a new item
             else {
:...skipping...
diff --git a/build-data_old.js b/build-data_old.js
index b8daffb..cffbc33 100644
--- a/build-data_old.js
+++ b/build-data_old.js
@@ -27,8 +27,6 @@
             dateEnds = now.valueOf(),
             ninetyDaysAgo = now.add(-90, 'days').valueOf(),
             dateBegins = ninetyDaysAgo;
-        //bruce
-        var lastBuildEndTime = 0;

         db.lastRequest.where('[type+id]').equals(['build-data', componentId]).first().then(processLastRequestResponse);

@@ -41,12 +39,6 @@
             buildData
                 .details({componentId: componentId, endDateBegins: dateBegins, endDateEnds: dateEnds})
                 .then(function(response) {
-                       //bruce
-                       if(response.result.length){
-                               var bruceObject = response.result[response.result.length -1];
-                               lastBuildEndTime = bruceObject.endTime;
-                       }
-
                     processBuildDetailsResponse(response, lastRequest);
                 })
                 .then(processBuildDetailsData)
@@ -63,30 +55,16 @@

             // save the request object so we can get the delta next time as well
             if(lastRequest) {
-               //bruce
-               if(lastBuildEndTime){
-                       lastRequest.timestamp = lastBuildEndTime;
-               }else{
-                    lastRequest.timestamp = dateEnds;
-               }
+                lastRequest.timestamp = dateEnds;
                 lastRequest.save();
             }
             // need to add a new item
             else {
-               //bruce
-               if(lastBuildEndTime){
-                    db.lastRequest.add({
-                        id: componentId,
-                        type: 'build-data',
-                        timestamp: lastBuildEndTime
-                    });
-               }else{
-                    db.lastRequest.add({
-                        id: componentId,
-                        type: 'build-data',
-                        timestamp: dateEnds
-                    });
-               }
:...skipping...
diff --git a/build-data_old.js b/build-data_old.js
index b8daffb..cffbc33 100644
--- a/build-data_old.js
+++ b/build-data_old.js
@@ -27,8 +27,6 @@
             dateEnds = now.valueOf(),
             ninetyDaysAgo = now.add(-90, 'days').valueOf(),
             dateBegins = ninetyDaysAgo;
-        //bruce
-        var lastBuildEndTime = 0;

         db.lastRequest.where('[type+id]').equals(['build-data', componentId]).first().then(processLastRequestResponse);

@@ -41,12 +39,6 @@
             buildData
                 .details({componentId: componentId, endDateBegins: dateBegins, endDateEnds: dateEnds})
                 .then(function(response) {
-                       //bruce
-                       if(response.result.length){
-                               var bruceObject = response.result[response.result.length -1];
-                               lastBuildEndTime = bruceObject.endTime;
-                       }
-
                     processBuildDetailsResponse(response, lastRequest);
                 })
                 .then(processBuildDetailsData)
@@ -63,30 +55,16 @@

             // save the request object so we can get the delta next time as well
             if(lastRequest) {
-               //bruce
-               if(lastBuildEndTime){
-                       lastRequest.timestamp = lastBuildEndTime;
-               }else{
-                    lastRequest.timestamp = dateEnds;
-               }
+                lastRequest.timestamp = dateEnds;
                 lastRequest.save();
             }
             // need to add a new item
             else {
-               //bruce
-               if(lastBuildEndTime){
-                    db.lastRequest.add({
-                        id: componentId,
-                        type: 'build-data',
-                        timestamp: lastBuildEndTime
-                    });
-               }else{
-                    db.lastRequest.add({
-                        id: componentId,
-                        type: 'build-data',
-                        timestamp: dateEnds
-                    });
-               }
+                db.lastRequest.add({

**Comment by wdquan1985** [comment]
I have made a code change in file UI\src\components\widgets\product\js\build-data.js as following locally.
diff --git a/build-data.js b/build-data.js
index cffbc33..b8daffb 100644
--- a/build-data.js
+++ b/build-data.js
@@ -27,6 +27,8 @@
             dateEnds = now.valueOf(),
             ninetyDaysAgo = now.add(-90, 'days').valueOf(),
             dateBegins = ninetyDaysAgo;
+        //bruce
+        var lastBuildEndTime = 0;

         db.lastRequest.where('[type+id]').equals(['build-data', componentId]).first().then(processLastRequestResponse);

@@ -39,6 +41,12 @@
             buildData
                 .details({componentId: componentId, endDateBegins: dateBegins, endDateEnds: dateEnds})
                 .then(function(response) {
+                       //bruce
+                       if(response.result.length){
+                               var bruceObject = response.result[response.result.length -1];
+                               lastBuildEndTime = bruceObject.endTime;
+                       }
+
                     processBuildDetailsResponse(response, lastRequest);
                 })
                 .then(processBuildDetailsData)
@@ -55,16 +63,30 @@

             // save the request object so we can get the delta next time as well
             if(lastRequest) {
-                lastRequest.timestamp = dateEnds;
+               //bruce
+               if(lastBuildEndTime){
+                       lastRequest.timestamp = lastBuildEndTime;
+               }else{
+                    lastRequest.timestamp = dateEnds;
+               }
                 lastRequest.save();
             }
             // need to add a new item
             else {
-                db.lastRequest.add({
-                    id: componentId,
-                    type: 'build-data',
-                    timestamp: dateEnds
-                });
+               //bruce
+               if(lastBuildEndTime){
+                    db.lastRequest.add({
+                        id: componentId,
+                        type: 'build-data',
+                        timestamp: lastBuildEndTime
+                    });
+               }else{
+                    db.lastRequest.add({
+                        id: componentId,
+                        type: 'build-data',
+                        timestamp: dateEnds
+                    });
+               }
             }

**Comment by wdquan1985** [comment]
I have made a code change in file UI\src\components\widgets\product\js\build-data.js as following locally.
[diff.txt](https://github.com/capitalone/Hygieia/files/815727/diff.txt)

**Comment by MarkRx** [comment]
Why not correct the times on the Jenkins and Hygieia servers?

**Comment by wdquan1985** [comment]
If Jenkins server and Hygieia server have different time zone, how to correct them?
