### ISSUE TITLE
Hygieia Jenkins Plugin not showing the exact data in Deploy widget

### ISSUE THREAD

**Issue by BoomaBaskaran** [Hygieia/Hygieia#1276]
Hi,

I have successfully configured hygieia jenkins plugin in my jenkins and it's a pipeline job. Have followed the Post build steps to publish deploy information. I can able to configure deploy widget also. But, the deploy widget always showing red color and the server up count is also zero. Please refer the below screen shot.
I referred the table "environment_components" - there deployed status is false always. Based on which condition this deployed status will get changed?

Is there any other table required to show the exact server up count. I see only one table "environment_components" getting created other than collectors, collector_items.

![image](https://cloud.githubusercontent.com/assets/5907275/24403284/cc537b52-13d9-11e7-992b-bee804fca316.png)

Thanks,
Booma Baskaran.

**Comment by BoomaBaskaran** [comment]
Any update on this. How can I get the server up and down count?

**Comment by MarkRx** [comment]
Red means that jenkins is sending a deployed=false as part of the rest call. I don't think Jenkins supports the up/down feature - the only thing that supports it is UDeploy as it has information about a servers health and status.

**Comment by BoomaBaskaran** [comment]
Thanks MarkRx. Is there any possibility to check the server health from Jenkins plugin?

**Comment by MarkRx** [comment]
I do not believe so.

**Comment by tabladrum** [comment]
Possible solution:
1. Expose an API for EnvironmentStatus for data ingestion
2. Set up a Jenkins job (or similar) to ping the server/service and publish the health.

**Comment by BoomaBaskaran** [comment]
Thanks for the response MarkRx and tabladrum.
