### ISSUE TITLE
Go CD Collector

### ISSUE THREAD

**Issue by anuragmishracrest** [Hygieia/Hygieia#1289]
Hi,

Do you have update on Go CD collector?

**Comment by swizzley** [comment]
Our team is currently working on one and has it somewhat working, but it won't be available until https://github.com/capitalone/Hygieia/issues/1305 is resolved.

**Comment by rvema** [comment]
@swizzley issue #1305 is resolved. Can you go ahead and submit PR for Go CD Collector?

**Comment by ysnoussi** [comment]
Hi,
@swizzley  Could you please submit this PR ? we are looking into it as well.

Thanks in advance

**Comment by zerolaser** [comment]
@rvema @swizzley any update on Go CD collector ?

**Comment by kmkalai** [comment]
@swizzley , Any updates on GoCD collector?

**Comment by swizzley** [comment]
The project was abandoned, as was Go CD. We found Go CD did not scale horizontally and we have moved on to [concourse](https://concourse-ci.org/) for CI/CD.

**Comment by ringods** [comment]
@swizzley are you using a Hygieia collector for ConcourseCI? Interested in this.
