### ISSUE TITLE
Jenkins-cucumber -test-collector is getting failed when we run mvn clean install package

### ISSUE THREAD

**Issue by Clement06** [Hygieia/Hygieia#1302]
Hi ,
I have taken the latest code and ran the mvn clean install package from Hygieia-master root. Below is the error message I am getting .
![image](https://cloud.githubusercontent.com/assets/25548421/24764743/43f69440-1aed-11e7-9105-e89274913169.png)

Please help me to get this issue fixed. Thanks for your support and guidance. 

@jdamick  @satishc1  @jaredsmith @MarkRx

**Comment by nireeshT** [comment]
@Clement06  - paste error log

**Comment by Clement06** [comment]
Hi Nireesh , 

I tried running the mvn clean install package and its getting failed in UI alone .

**Comment by Clement06** [comment]
The error message is as below:

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:
npm (npm install) on project UI: Execution npm install of goal com.github.eirsle
tt:frontend-maven-plugin:0.0.29:npm failed: Invalid proxy settings: Illegal char
acter in hostname at index 51: http://***************@***********:** -> [Help 1]

**Comment by nireeshT** [comment]
@Clement06  check you proxy settings in maven-> settings.xml. There must be an extra space or a special character which it is complaining about. Use UrlEncoder to replace character with UTF-8

**Comment by Clement06** [comment]
I tried running the mvn clean clean install package from the root folder, but its getting failed only for UI. Please help me on this.

@nireeshT  @satishc1  @jdamick

**Comment by Clement06** [comment]
Hi All, 

I have tried running mvn clean install package from the root folder, but its getting failed for the below reason
![image](https://cloud.githubusercontent.com/assets/25548421/24864367/eb39b046-1dfb-11e7-9d1a-af4d22a90822.png)


Please help me on this issue.

@nireeshT @tabladrum @jdamick @MarkRx @jdamick

**Comment by nireeshT** [comment]
@Clement06  - It should be cert issue. Unable to connect to https://m2proxy.atlassian.com/repository/public

**Comment by Clement06** [comment]
Thanks Nireesh. Please help me how can I resolve this issue Nireesh.

**Comment by nitin1706** [comment]
@Clement06 : share the complete logs.

**Comment by rvema** [comment]
@Clement06 closing the issue due to inactivity. Please obtain the latest code base and retest, Please reopen if this issue is still occuring.
