### ISSUE TITLE
Update Story regular expression to allow . to match newlines

### ISSUE THREAD

**Issue by darthmachina** [Hygieia/Hygieia#1304]
The regular expression for parsing Story data is used on the toString() of a Jira Story. We have a custom field on our stories that allows multiline text (so \n in the text), which . will not normally match. Changing the regular expression to (?s).*\\[.+\\][^\\]]*(?-s) fixes this. ?s turns on DOTALL mode for Pattern.

I can submit a pull request soon for this change as I'm not setup for that right now, but here is a patch for it.

[regex_patch.txt](https://github.com/capitalone/Hygieia/files/903915/regex_patch.txt)

**Comment by Sbrenthughes** [comment]
Please refer to #2667. As this is the collector rewrite in progress.
