### ISSUE TITLE
Commit details not displayed in product dashboard

### ISSUE THREAD

**Issue by chethanbs** [Hygieia/Hygieia#1333]
I have created a team dashboard which includes details from Subversion,sonarqube and jenkin's.I can see data from all these  3 tools in the team dashboard.

I created product dashboard and added team dashboard into it.
Product dashboard is not showing any commit information.It shows only sonarqube and Jenkin's data.

Please let me know why I am not able to see commit information in product dashboard.

**Comment by rob-miller-777** [comment]
I don't believe the subversion collector has been updated to apply the "CommitType" to a commit when collected, which is needed for a commit to be displayed in that column.  It works for Github, and I recently fixed the Gitlab collector for this issue as well, but I don't believe the subversion collector has been fixed yet.

**Comment by chethanbs** [comment]
Ok thank you.Do you know when it will be available for subversion?

**Comment by Sbrenthughes** [comment]
Please reopen if the feature is still needed.

**Comment by Blessie7** [comment]
Commit data from Subversion is not being displayed in Product dashboard - Has this been resolved? Any update on this please?

**Comment by wwei1896** [comment]
Also want to know if the latest version can support Subversion Commit data in Product dashboard? I can not get data.

**Comment by wwei1896** [comment]
> I don't believe the subversion collector has been updated to apply the "CommitType" to a commit when collected, which is needed for a commit to be displayed in that column. It works for Github, and I recently fixed the Gitlab collector for this issue as well, but I don't believe the subversion collector has been fixed yet.

@rob-miller-777 hi, can you help check if the commit data for subversion can be shown later? thanks a lot

**Comment by ssjoshi123** [comment]
I am not able to see for Github scm. Can you able to let me know what wld be the reson behind

![image](https://user-images.githubusercontent.com/59791973/115411296-fa73c680-a210-11eb-9c6d-0216743f6e5a.png)
