### ISSUE TITLE
Github collector: support oAuth authentication

### ISSUE THREAD

**Issue by declension** [Hygieia/Hygieia#1345]
AFAICT, the current Github collection only uses a username / password transmitted as HTTP Basic Auth (even over plaintext connections if specified :scream: ).

For many people (like us), this is a blocker as individual / system username / password details would not be allowed to be committed. Either way, programmatic access to private Github repositories would be best off using [their oAuth](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization). In the simple case a [personal access token](https://github.com/settings/tokens/new) could be used, I believe. The advantage of course is that this can be controlled / revoked as seen fit by the user.

I couldn't find an existing ticket around this - has it been discussed?

**Comment by Sbrenthughes** [comment]
Looks like access with the Personal access token has been added.
