### ISSUE TITLE
Github Collector is Not working for private repo

### ISSUE THREAD

**Issue by ritusingh16** [Hygieia/Hygieia#1347]
downloaded Hygieia Latest code
maven version :  3.2.1 

Followed all step for configuration of private repo in Hygieia which are as follows

Step 1 
Generation of key for private repo
java -jar core-2.0.5-SNAPSHOT.jar com.capitalone.dashboard.util.Encryption
output of this as follows
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Your secret key is:
x0CDs8cQicRJp9Nby4qG6Wf7gFiivNzV
Sample encrypted string with the above key for 'thisIsMyPassword' is:
ZxBvfKWygjZLEQE5WMRzzTWaqrlw1Io7

Step 2
The highlighted Key added in api.properties file as follows
dbname=dashboarddb
dbhost=hostname
dbport=27017
dbhostport=hostname:27017
server.contextPath=/api
server.port=8888
key= x0CDs8cQicRJp9Nby4qG6Wf7gFiivNzV

Step 3
Same key is added in github.properties file as follows
The highlighted Key added in api.properties file as follows
dbname=dashboarddb
dbhost=hostname
dbport=27017
logging.file=./logs/github.log
github.corn=0 0/5 * * * *
github.host=github.com
github.key= x0CDs8cQicRJp9Nby4qG6Wf7gFiivNzV
while running collector after maven build getting error as follows 
**404 Not Found:http://api.github.com/repos/********/*****/commits?sha=master&since=2017-04-25T23:40Z**

and also from UI while providing username and password it show  **Error encrypting password**

**Comment by nireeshT** [comment]
@ritusingh16  - refer https://github.com/capitalone/Hygieia/issues/1284 workaround helps. I will look into issue meanwhile.

**Comment by Ramya126** [comment]
@nireeshT  : I tried to modify ApiSettings.java as shown below 

    public void setKey(final String key) {
        this.key = "############";   (with my access token)
    }
I then built and ran api and collector . I am still seeing 404 when hitting 
https://api.github.com/repos/company/repo-name/commits?sha=master&since=2017-04-26T12:25Z. 
Also seeing the same error as @ritusingh16 when trying to add username and password . Can someone take a look at it ?

**Comment by Ramya126** [comment]
@ritusingh16 @nireeshT  I updated queryUrl variable in DefaultGitHubClient.java  to include access token in the query parameter as below 

String queryUrl = apiUrl.concat("/commits?access_token=MYTOKEN&sha=" + repo.getBranch()
				+ "&since=" + thisMoment) 

I am able to get the responce from github api . Hope it helps

**Comment by ritusingh16** [comment]
@nireeshT 

Thanks for the reply

I tried to modify but getting same 404 error

**Comment by ritusingh16** [comment]
@Ramya126 

I tried the same as you mentioned in comment,but still same error

Thanks for the reply

**Comment by ritusingh16** [comment]
I tried with latest updated code base of hygieia to configure github private repo still getting 404 error,but this time error have some slight change
[PrivateGithubRepoError.docx](https://github.com/capitalone/Hygieia/files/985996/PrivateGithubRepoError.docx)

Please find the attached document which contain screenshots of error and all configuration details

**Comment by ritusingh04** [comment]
Any update ?

**Comment by satishc1** [comment]
@ritusingh16 Paste the commands you are using to launch the api and github collector modules.

**Comment by ritusingh16** [comment]
Commands as follows:

For api module
java -jar api.jar --spring.config.location=dashboard.properties

For Github collector
java -jar github-scm-collector-2.0.5-SNAPSHOT.jar

**Comment by kwhickey** [comment]
@nireeshT, @satishc1 - 
_*It would seem that the requied `key` property is never built/created in `dashboard.properties` for the running API component to ingest.*_ Do you concur? 

Looking at [properties-builder.sh](https://github.com/capitalone/Hygieia/blob/master/api/docker/properties-builder.sh) file for the API component, it is and _always_ has been missing a line to create a property named `key`, which would get built from an environment variable injected during `docker run` (or `docker-compose up`) and placed into `dashboard.properties` just before the container performs its command of 
```
java -Djava.security.egd=file:/dev/./urandom -jar api.jar --spring.config.location=/hygieia/dashboard.properties
```

So if it's not established during docker run-time... how else should this runtime property get into the running spring boot app? Maybe there's some hidden or missing docs that explain this. If not, then the `properties-builder.sh` needs an update, to add the line:
```
KEY=${KEY:-}
```

Without this, in the UI, if someone tries to create a GitHub repo collector that is password protected, the [rest call](https://github.com/capitalone/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/rest/EncryptionController.java#L25) to `/encryption/{message}` will just return `"ERROR"` giving a message of _Error encrypting password_

If somehow the GitHubRepo object is created in MongoDB with an empty or null password, [this logic](https://github.com/capitalone/Hygieia/blob/master/collectors/scm/github/src/main/java/com/capitalone/dashboard/collector/DefaultGitHubClient.java#L116)
```java
                 // decrypt password
		 String decryptedPassword = "";
		 if (repo.getPassword() != null && !repo.getPassword().isEmpty()) {
		 	try {
		 		decryptedPassword = Encryption.decryptString(
		 				repo.getPassword(), settings.getKey());
		 	} catch (EncryptionException e) {
		 		LOG.error(e.getMessage());
		 	}
		 }
```
Will continue to pass along that empty or null password, which will resulting in requests sent to `getCommits` from the repo failing. 

Also the linked issue above suggest to look at these docs: https://github.com/capitalone/Hygieia/blob/master/UI/README.md#encryption-for-private-repos

But, it refers to `api.properties` when it seems that docker uses `dashboard.properties`

**Comment by kwhickey** [comment]
@ritusingh16, @nireeshT, @satishc1 
I found a decent workaround for this. Spring and its [property source precedence](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) allows for it to pick up config properties from various places, including the environment. 

So, while the `key` property is not declared anywhere as a placeholder in a properties file or in the `properties-builder.sh`  (and it should be), you can inject its value into the container as an environment variable, and spring will pick it up and use it.

Example snippet from `docker-compose.override.yml`:
```yaml
hygieia-api:
  environment:
    - JASYPT_ENCRYPTOR_PASSWORD=hygieiasecret
    - AUTH_SECRET=********
    - KEY=********
```

Could really use some gap-filling in the docs to cover this option though, or to clarify the intended approach.

**Comment by rvema** [comment]
@ritusingh16 closing the issue due to inactivity. Please re open if this issue is still occuring

**Comment by nurhannankhairi** [comment]
I get 401 unauthorized as the private gitlab branch is protected.. anyone knows how to solve this issue? help me..
