### ISSUE TITLE
jenkins plugin compatibility

### ISSUE THREAD

**Issue by agsmorodin** [Hygieia/Hygieia#1381]
Hi,

I am trying to use hygieia plugin for jenkins for retrieving data from jobs. 
The problem is that I am using jenkins 2.34,  and  when hygieia plugin is trying to send data to Hygieia api, plugin throws NPE:
``
May 11, 2017 11:24:23 AM hudson.model.listeners.RunListener report
WARNING: RunListener failed
java.lang.NullPointerException
	at hygieia.builder.BuildBuilder.createBuildRequest(BuildBuilder.java:100)
	at hygieia.builder.BuildBuilder.<init>(BuildBuilder.java:46)
	at jenkins.plugins.hygieia.ActiveNotifier.completed(ActiveNotifier.java:84)
	at jenkins.plugins.hygieia.HygieiaListener.onCompleted(HygieiaListener.java:27)
	at jenkins.plugins.hygieia.HygieiaListener.onCompleted(HygieiaListener.java:15)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:211)
	at hudson.model.Run.execute(Run.java:1773)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
``

I also tried to rebuild plugin locally using 2.3 org.jenkins-ci.plugins parent version  but it fails with the following exceptions:

``
[INFO] Fork Value is true
     [java] May 11, 2017 12:45:32 PM java.util.prefs.FileSystemPreferences$1 run
     [java] INFO: Created user preferences directory.
     [java] Warnings generated: 29
[INFO] Done FindBugs Analysis....
[INFO] 
[INFO] <<< findbugs-maven-plugin:3.0.3:check (findbugs) < :findbugs @ hygieia-publisher <<<
[INFO] 
[INFO] --- findbugs-maven-plugin:3.0.3:check (findbugs) @ hygieia-publisher ---
[INFO] BugInstance size is 29
[INFO] Error size is 0
[INFO] Total bugs: 29
[INFO] Possible null pointer dereference in new hygieia.builder.ArtifactBuilder(AbstractBuild, HygieiaPublisher, TaskListener, String) due to return value of called method [hygieia.builder.ArtifactBuilder, hygieia.builder.ArtifactBuilder] Dereferenced at ArtifactBuilder.java:[line 51]Known null at ArtifactBuilder.java:[line 51] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in hygieia.builder.BuildBuilder.createBuildRequest() due to return value of called method [hygieia.builder.BuildBuilder, hygieia.builder.BuildBuilder] Dereferenced at BuildBuilder.java:[line 94]Known null at BuildBuilder.java:[line 94] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Dead store to envVars in hygieia.builder.CucumberTestBuilder.buildTestResults() [hygieia.builder.CucumberTestBuilder] At CucumberTestBuilder.java:[line 79] DLS_DEAD_LOCAL_STORE
[INFO] Invocation of toString on Throwable.getStackTrace() in hygieia.builder.CucumberTestBuilder.buildTestResults() [hygieia.builder.CucumberTestBuilder, hygieia.builder.CucumberTestBuilder] At CucumberTestBuilder.java:[line 86]Another occurrence at CucumberTestBuilder.java:[line 89] DMI_INVOKING_TOSTRING_ON_ARRAY
[INFO] Possible null pointer dereference in new hygieia.builder.CucumberTestBuilder(AbstractBuild, TaskListener, String, String, String, String, String, String, String) due to return value of called method [hygieia.builder.CucumberTestBuilder, hygieia.builder.CucumberTestBuilder] Dereferenced at CucumberTestBuilder.java:[line 55]Known null at CucumberTestBuilder.java:[line 55] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Null passed for non-null parameter of getCapabilities(List) in hygieia.builder.CucumberTestBuilder.buildTestResults() [hygieia.builder.CucumberTestBuilder, hygieia.builder.CucumberTestBuilder] Method invoked at CucumberTestBuilder.java:[line 91]Known null at CucumberTestBuilder.java:[line 77] NP_NULL_PARAM_DEREF
[INFO] Possible null pointer dereference in new hygieia.builder.DeployBuilder(AbstractBuild, HygieiaPublisher, TaskListener, String) due to return value of called method [hygieia.builder.DeployBuilder, hygieia.builder.DeployBuilder] Dereferenced at DeployBuilder.java:[line 58]Known null at DeployBuilder.java:[line 58] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Dead store to list in hygieia.utils.HygieiaUtils.getRepoBranch(AbstractBuild) [hygieia.utils.HygieiaUtils] At HygieiaUtils.java:[line 237] DLS_DEAD_LOCAL_STORE
[INFO] Possible null pointer dereference in hygieia.utils.HygieiaUtils.getGitHubRepoBranch(GitSCM, Run) due to return value of called method [hygieia.utils.HygieiaUtils, hygieia.utils.HygieiaUtils] Dereferenced at HygieiaUtils.java:[line 275]Known null at HygieiaUtils.java:[line 275] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in hygieia.utils.HygieiaUtils.getGitHubRepoBranch(GitSCM, Run) due to return value of called method [hygieia.utils.HygieiaUtils, hygieia.utils.HygieiaUtils] Dereferenced at HygieiaUtils.java:[line 276]Known null at HygieiaUtils.java:[line 276] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in hygieia.utils.HygieiaUtils.getGitHubRepoBranch(GitSCM, Run) due to return value of called method [hygieia.utils.HygieiaUtils, hygieia.utils.HygieiaUtils] Dereferenced at HygieiaUtils.java:[line 280]Known null at HygieiaUtils.java:[line 280] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] hygieia.utils.HygieiaUtils.getGitHubRepoBranch(GitSCM, Run) makes inefficient use of keySet iterator instead of entrySet iterator [hygieia.utils.HygieiaUtils] At HygieiaUtils.java:[line 283] WMI_WRONG_MAP_ITERATOR
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.ActiveNotifier.completed(AbstractBuild) due to return value of called method [jenkins.plugins.hygieia.ActiveNotifier, jenkins.plugins.hygieia.ActiveNotifier] Dereferenced at ActiveNotifier.java:[line 92]Known null at ActiveNotifier.java:[line 92] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.ActiveNotifier.completed(AbstractBuild) due to return value of called method [jenkins.plugins.hygieia.ActiveNotifier, jenkins.plugins.hygieia.ActiveNotifier] Dereferenced at ActiveNotifier.java:[line 93]Known null at ActiveNotifier.java:[line 93] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.ActiveNotifier.completed(AbstractBuild) due to return value of called method [jenkins.plugins.hygieia.ActiveNotifier, jenkins.plugins.hygieia.ActiveNotifier] Dereferenced at ActiveNotifier.java:[line 116]Known null at ActiveNotifier.java:[line 116] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.ActiveNotifier.completed(AbstractBuild) due to return value of called method [jenkins.plugins.hygieia.ActiveNotifier, jenkins.plugins.hygieia.ActiveNotifier] Method invoked at ActiveNotifier.java:[line 119]Known null at ActiveNotifier.java:[line 117] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Found reliance on default encoding in jenkins.plugins.hygieia.DefaultHygieiaService.publishArtifactData(BinaryArtifactCreateRequest): new String(byte[]) [jenkins.plugins.hygieia.DefaultHygieiaService] At DefaultHygieiaService.java:[line 75] DM_DEFAULT_ENCODING
[INFO] Found reliance on default encoding in jenkins.plugins.hygieia.DefaultHygieiaService.publishBuildData(BuildDataCreateRequest): new String(byte[]) [jenkins.plugins.hygieia.DefaultHygieiaService] At DefaultHygieiaService.java:[line 54] DM_DEFAULT_ENCODING
[INFO] Found reliance on default encoding in jenkins.plugins.hygieia.DefaultHygieiaService.publishDeployData(DeployDataCreateRequest): new String(byte[]) [jenkins.plugins.hygieia.DefaultHygieiaService] At DefaultHygieiaService.java:[line 133] DM_DEFAULT_ENCODING
[INFO] Found reliance on default encoding in jenkins.plugins.hygieia.DefaultHygieiaService.publishSonarResults(CodeQualityCreateRequest): new String(byte[]) [jenkins.plugins.hygieia.DefaultHygieiaService] At DefaultHygieiaService.java:[line 115] DM_DEFAULT_ENCODING
[INFO] Found reliance on default encoding in jenkins.plugins.hygieia.DefaultHygieiaService.publishTestResults(TestDataCreateRequest): new String(byte[]) [jenkins.plugins.hygieia.DefaultHygieiaService] At DefaultHygieiaService.java:[line 95] DM_DEFAULT_ENCODING
[INFO] Redundant nullcheck of testHygieiaService, which is known to be non-null in jenkins.plugins.hygieia.HygieiaPublisher$DescriptorImpl.doTestConnection(String, String, String, String) [jenkins.plugins.hygieia.HygieiaPublisher$DescriptorImpl] Redundant null check at HygieiaPublisher.java:[line 585] RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.RestCall.getHttpClient() due to return value of called method [jenkins.plugins.hygieia.RestCall, jenkins.plugins.hygieia.RestCall] Dereferenced at RestCall.java:[line 39]Known null at RestCall.java:[line 39] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Should jenkins.plugins.hygieia.RestCall$RestCallResponse be a _static_ inner class? [jenkins.plugins.hygieia.RestCall$RestCallResponse] At RestCall.java:[lines 121-140] SIC_INNER_SHOULD_BE_STATIC
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.workflow.HygieiaArtifactPublishStep$HygieiaArtifactPublishStepExecution.run() due to return value of called method [jenkins.plugins.hygieia.workflow.HygieiaArtifactPublishStep$HygieiaArtifactPublishStepExecution, jenkins.plugins.hygieia.workflow.HygieiaArtifactPublishStep$HygieiaArtifactPublishStepExecution] Dereferenced at HygieiaArtifactPublishStep.java:[line 146]Known null at HygieiaArtifactPublishStep.java:[line 140] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.workflow.HygieiaBuildPublishStep$HygieiaBuildPublishStepExecution.run() due to return value of called method [jenkins.plugins.hygieia.workflow.HygieiaBuildPublishStep$HygieiaBuildPublishStepExecution, jenkins.plugins.hygieia.workflow.HygieiaBuildPublishStep$HygieiaBuildPublishStepExecution] Dereferenced at HygieiaBuildPublishStep.java:[line 105]Known null at HygieiaBuildPublishStep.java:[line 99] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.workflow.HygieiaDeployPublishStep$HygieiaDeployPublishStepExecution.run() due to return value of called method [jenkins.plugins.hygieia.workflow.HygieiaDeployPublishStep$HygieiaDeployPublishStepExecution, jenkins.plugins.hygieia.workflow.HygieiaDeployPublishStep$HygieiaDeployPublishStepExecution] Dereferenced at HygieiaDeployPublishStep.java:[line 193]Known null at HygieiaDeployPublishStep.java:[line 187] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.workflow.HygieiaSonarPublishStep$HygieiaSonarPublishStepExecution.run() due to return value of called method [jenkins.plugins.hygieia.workflow.HygieiaSonarPublishStep$HygieiaSonarPublishStepExecution, jenkins.plugins.hygieia.workflow.HygieiaSonarPublishStep$HygieiaSonarPublishStepExecution] Dereferenced at HygieiaSonarPublishStep.java:[line 112]Known null at HygieiaSonarPublishStep.java:[line 106] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] Possible null pointer dereference in jenkins.plugins.hygieia.workflow.HygieiaTestPublishStep$HygieiaArtifactPublishStepExecution.run() due to return value of called method [jenkins.plugins.hygieia.workflow.HygieiaTestPublishStep$HygieiaArtifactPublishStepExecution, jenkins.plugins.hygieia.workflow.HygieiaTestPublishStep$HygieiaArtifactPublishStepExecution] Dereferenced at HygieiaTestPublishStep.java:[line 185]Known null at HygieiaTestPublishStep.java:[line 180] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
[INFO] 

To see bug detail using the Findbugs GUI, use the following command "mvn findbugs:gui"

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:32 min
[INFO] Finished at: 2017-05-11T12:45:46+00:00
[INFO] Final Memory: 69M/194M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:check (findbugs) on project hygieia-publisher: failed with 29 bugs and 0 errors -> [Help 1]
``

Could you please advise,  is jenkins 2.34 version supported or I need to downgrade server to 2.0?  Thank you in advance.

**Comment by nireeshT** [comment]
@agsmorodin  - Jenkins 2.34 must be compatible version for Hygieia publisher plugin. I am using 2.46.2 ,no issues. 
 Follow instructions in http://www.capitalone.io/Hygieia/plugin_webhook.html 
1)  "core" project - mvn clean install
2) "hygieia-jenkins-plugin" project -  mvn test 
3) "hygieia-jenkins-plugin" project -  mvn clean package 
get hpi file from hygieia-jenkins-plugin/target

if you see issue while build, please console log.

**Comment by tabladrum** [comment]
Let me check too. I used it even on Jenkins 1.6.x

**Comment by rrgautam** [comment]
I've similar issue and I am on jenkins 2.19.
Did you guys manage to resolve it?

**Comment by rsans** [comment]
Same issue, I'm using Jenkins 2.32.1.

May be the last comments of this issues can help you to check: https://github.com/capitalone/Hygieia/issues/1426

**Comment by rsans** [comment]
![image](https://user-images.githubusercontent.com/1969636/27553693-482d0928-5aac-11e7-8429-20c840722388.png)

**Comment by rsans** [comment]
![image](https://user-images.githubusercontent.com/1969636/27553914-0c8ee1f6-5aad-11e7-91d2-12a533fef7ed.png)

**Comment by rsans** [comment]
Updated to last Jenkins LTS version 2.60.1 and all plugins up to date. Same problem at BuildBuilder.java:100

**Comment by angelsanchezdck** [comment]
working for me! @rsans thanks

**Comment by rrgautam** [comment]
@rsans much thanks that error is gone and i do get response code 201 after execution of job with Hygieia post build actions, bad thing is I still can't see any jenkins build information on my hygieia dashboard

**Comment by iglunev** [comment]
Shouldn't this be fixed in the repo?

**Comment by rvema** [comment]
@agsmorodin The Jenkins plugin has undergone some changes recently and should fix the issues you are seeing. Please get the latest code base and test the same. Re open this issue if it occurs again
