### ISSUE TITLE
hygieia-jenkins-plugin

### ISSUE THREAD

**Issue by luweiyulin** [Hygieia/Hygieia#1417]
Hello,my Jenkins version is 2.323, I installed hygieia-jenkins-plugin(2.0.5-SNAPSHOT (private-02/21/2017 21:25-root)).when I build a  job  I can add a Post build action "Hygieia Publisher".but In Jenkins pipeline syntax page, I cant't find Hygieia publish steps as flow,what I need  to do ? Please Help me ,Thank you.
![1](https://cloud.githubusercontent.com/assets/26077228/26391807/ca2a35a2-4096-11e7-8b54-bbd194320cc7.png)

**Comment by nireeshT** [comment]
@luweiyulin  - refer Jenkins2.0 w/ pipeline section in https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin

**Comment by luweiyulin** [comment]
@nireeshT Hello ,I followed all the step as mentioned in the following link
https://github.com/capitalone/Hygieia/tree/master/hygieia-jenkins-plugin 
Then  I  used a step method:
step ([$class: 'hygieia', publishBuildData:true])
and the build failed returning the below error message
"no known implementation of interface jenkins.tasks.SimpleBuildStep is named hygieia"
If there is a compatibility problem  in JDK/Jenkins/pipeline plugin/hygieia-jenkins-plugin?

![1](https://cloud.githubusercontent.com/assets/26077228/26440854/b6d2cff8-4160-11e7-99b0-7fb30ff48e49.png)
![2](https://cloud.githubusercontent.com/assets/26077228/26440897/ebcfa500-4160-11e7-8a63-a77b7b356bc4.png)
Jenkins version is 2.32.3, 
 hygieia-jenkins-plugin(2.0.5-SNAPSHOT (private-02/21/2017 21:25-root)).
Java:jdk1.8.0_121

**Comment by preetcam** [comment]
Getting following error when I try to build Hygiea-jenkins-publisher . Build works fine, if I build outer project. I am not able to create the hpi file. Please suggest further steps to follow. 


[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.883 s
[INFO] Finished at: 2017-09-21T11:42:52-07:00
[INFO] Final Memory: 31M/198M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:1.106:test-hpl (default-test-hpl) on project hygieia-publisher: Error preparing the manifest: Failed to open artifact javax.el:javax.el-api:jar:2.2.4:compile at C:\Users\kamakaur\.m2\repository\javax\el\javax.el-api\2.2.4\javax.el-api-2.2.4.jar: 1 problem was encountered while building the effective model for javax.el:javax.el-api:2.2.4
[ERROR] [FATAL] 'parent.artifactId' must be changed, the parent element cannot have the same groupId:artifactId as the project. @ line 44, column 21
[ERROR]  for project javax.el:javax.el-api:2.2.4 for project javax.el:javax.el-api:2.2.4
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by rvema** [comment]
@luweiyulin This issue should be fixed now, Please get the latest hygieia jenkins plugin code and retest. You are free to reopen the issue if this reoccurs.
