### ISSUE TITLE
Product dashboard issues 

### ISSUE THREAD

**Issue by nireeshT** [Hygieia/Hygieia#1512]
WIP for below issues. 
#1504 #1503 #1487 #1472 #1432 #1426 #1333 #1316 #1298 #1221 #1023 #816 #804 #1508

**Comment by nireeshT** [comment]
@rsans  @narayan1ap @luweiyulin @willuk2010 @kavalpatel15 @xiaods @hitorchi @chethanbs
@dhivaharNewt @wdquan1985 @BoomaBaskaran  @MarkRx 

Please provide environment details 
1) Code Repo - Github/Subversion/..etc 
2) Deploy Tool - Hygieia Jenkins Plugin/ UDeploy/ Rundeck /... etc 
3) JDK Version - 
4)  Browser & Version -

**Comment by wdquan1985** [comment]
#1298 , 
1.  Code Repo - gerrit
2.  I use shell script to collect deploy info from jenkins.
3.  jave version "1.8.0_92"
4. firefox with version 53.0.3 (32 bit) and chrome with version 58.0.3029.110 (64-bit)

**Comment by willuk2010** [comment]
Hi @nireeshT 

1) Gitlab (9.2.5)
2) Hygieia Jenkins Plugin
3) jdk1.8.0_131
4) Chrome - Version 54.0.2840.87 m

**Comment by kavalpatel15** [comment]
Code Repo - BitBucket
Deploy Tool - Hygieia Jenkins Plugin
JDK Version - JDK 1.8.0
Browser & Version - Chrome - Version 59.0.3071.115

**Comment by nireeshT** [comment]
@kavalpatel15 @willuk2010  - pull PR https://github.com/capitalone/Hygieia/pull/1526 locally and see if you got the commits forwarded to DEV, QA...till PROD.

**Comment by willuk2010** [comment]
Thanks @nireeshT ill give this a go,

Quick question, i use Docker containers, which containers will need to be rebuilt after applying this PR ? (API/UI ?)

Cheers
Will

**Comment by nireeshT** [comment]
@willuk2010  API and UI

**Comment by willuk2010** [comment]
@nireeshT didnt make a difference to me mate, i'm afraid.. after rebuilding the docker containers, i just deployed them using the same data in mongo, could this cause an issue?

Also, i thought i would just test with and without Dynamic Pipeline.

With "FEATURE_DYNAMIC_PIPELINE=enabled", i have commits in both the commit, and build stages, but nothing in dev stage.

with "FEATURE_DYNAMIC_PIPELINE=disabled" i have no commits in the commit stage, commits in the build stage, but none in dev stage.

We dont have Pre/Pro stages yet btw, not sure if this makes a difference?

**Comment by nireeshT** [comment]
@willuk2010  - FEATURE_DYNAMIC_PIPELINE=disabled flow seems to be working. share a screenshot of your prod dashboard along with Mongodb pipeline collection for team dashboard. Want to see why commits are not moved to DEV. 
Check below configuration
1) Configure post build action for DEV jenkins job 
2) Do a commit and run DEV jenkins job
3) Deploy widget should show up your app name and DEV job 
4) Configure pipeline widget with DEV 
Share screenshots for prod dashboard, team dashboard deploy widget and pipeline widget and MongoDb pipeline collection showing stages -> commits.

5) refresh prod dashboard.

**Comment by nireeshT** [comment]
@willuk2010  @willuk2010  - FEATURE_DYNAMIC_PIPELINE=disabled flow seems to be working. Want to see why commits are not moved to DEV. 
do below steps 
1) Configure post build action for DEV jenkins job 
2) Do a commit and run DEV jenkins job
3) Deploy widget should show up your app name and DEV job 
4) Configure pipeline widget with DEV 
5) refresh prod dashboard. 
Share screenshots for prod dashboard, team dashboard deploy widget and pipeline widget and MongoDb pipeline collection showing stages -> commits.

**Comment by mindietea** [comment]
For #1508 

Code Repo - Gitlab
Deploy Tool - Hygieia Jenkins Plugin
JDK Version - 1.8.0
Browser & Version - Version 59.0.3071.115

**Comment by nireeshT** [comment]
@rsans @narayan1ap @luweiyulin @willuk2010 @kavalpatel15 @xiaods @hitorchi @chethanbs
@dhivaharNewt @wdquan1985 @BoomaBaskaran @MarkRx @srajendaran 
Please update your comments with Jenkins version as well.

**Comment by willuk2010** [comment]
@nireeshT my jenkins version is 2.46.2

I shall follow your steps, and report back

**Comment by MarkRx** [comment]
Code Repo - Bitbucket Server
Deploy Tool - XLDeploy
JDK Version - 1.8
Browser & Version - Chrome, Firefox, IE 11
Jenkins - 2.7.1 LTS

We don't deploy with Jenkins. The dynamic dashboard (#888) was made to stitch together the components on-demand. It basically is a PipelineServiceImpl with additional logic at buildPipeline along with tweaks and disabling the bounding mechanism since it didn't work. I think I made some tweaks to inefficient algorithms while in there. It would be great if these could share the same backbone and only differ in an extra step that way changes to the dynamic pipeline are not overlooked. If you have a branch with changes to the PipelineServiceImpl I can peak and try out the dynamic pipeline.

**Comment by sanchitacool** [comment]
How to create bar chart for issues in hygieia

**Comment by sanchitacool** [comment]
is there any code in github

**Comment by nitin1706** [comment]
@nireeshT :  is this done. Has this code already been merged?
