### ISSUE TITLE
UX - Limit the size of "Issues In Progress" list in Feature Widget with a vertical scroll

### ISSUE THREAD

**Issue by kumarvarun1252** [Hygieia/Hygieia#1637]
Steps to Repro:
* Configure a Feature Widget with valid project information (Cap One Template)
* Once the data is populated, Click on the '+/-' to expand the "Issues In Progress" list

Actual Result:
"Issues In Progress" box is expanded based on the number of items which makes it really long when there are more number of issues. Because of which user have to scroll all the way down to see the information in Code Repo Widget

Expected Result:
Size of "Issues In Progress" list should be limited with a vertical scroll inside. This allows users to access the information in Code Repo Widget easily and a better user experience

<img width="1669" alt="screen shot 2017-08-17 at 1 10 11 pm" src="https://user-images.githubusercontent.com/8548710/29431998-cbf6a00a-834e-11e7-97a9-f543e4bee5fc.png">

**Comment by MarkRx** [comment]
Since the dashboard is intended to also be viewed on a non-interactive panel it might make sense for this scrolling to happen automatically periodically.

**Comment by rvema** [comment]
@kumarvarun1252 : can you check if this is still an issue or needs to be addressed?
