### ISSUE TITLE
Jmeter Performance test result publishing support

### ISSUE THREAD

**Issue by shivam101992** [Hygieia/Hygieia#1682]
I would like to know if we have support for Jmeter and if we can have Jmeter performance test results picked up by Hygieia from Jenkins.

If not, how can I build a custom collector to pick up Jmeter results from Jenkins and have that in Performance column of a team dashboard?

**Comment by subodhbattina** [comment]
shivam101992 : Please take a look at "jenkins-cucumber-test-collector". This currently captures "Functional" tests. This could potentially be updated to cover for "Performance" type results as well. Thanks !

**Comment by subodhbattina** [comment]
@shivam101992 : Do you have any other questions or can I go ahead an close this issue? Thanks !

**Comment by subodhbattina** [comment]
@shivam101992: Assuming you don't have any more questions, if you do, please feel free to reach out. Thanks !
