### ISSUE TITLE
Support for Jenkins with GithubOrganization plugin 

### ISSUE THREAD

**Issue by sujaydevops1** [Hygieia/Hygieia#1714]
Jenkins creates automatically jobs based on branches under github organization . when i setup Hygieia to send build information, 

hygieiaBuildPublishStep buildStatus: 'Success'

 sends job name as "develop" which is a branch. Is there any way we can override default job name variables in hygieiaBuildPublish step?

**Comment by tabladrum** [comment]
Good call. We are experiencing the same thing. I was thinking if the job name should default to github repo+branch.

**Comment by sujaydevops1** [comment]
Hi,

 Do you have any work around to solve the problem for now?

**Comment by sujaydevops1** [comment]
Hi, 

I am getting OrgaizationName-develop in dashboard, whenever there is develop branch triggers for any projects its reporting here.

It should be Organizationname-repo-branch.

I would appreciate if you have any ideas to share.

**Comment by nireeshT** [comment]
@sujaydevops1  -  At present, we have below ways to identify your job based on nicename , in your case nice name is Org name. 

If using Jenkins collector, specify nice name for your jenkins server as below in your jenkins properties. You can specify nice names for all servers based on indexing.  In your case, you can specify customized nice name for your jenkins instance and that should help you find the correct job. This route should work for you.

Eg: jenkins.servers[0]=http://***jenkins.com/job/folder_level/
       jenkins.niceNames[0]= give nice name here 

If using Hygieia plugin in Jenkins, you can specify server name in Jenkins -> Manage Configuration-> Global settings 
     Specify server name field - give nice name here - which is what you are doing now. This does not help much if you wan

While configuring dashboard - build wiget, you can search with format - nicename : jobname 
In you case - nice name (mentioned in prop file) : develop. 

Please update to latest code base as now the delimiter is ":" and not "-"

**Comment by sujaydevops1** [comment]
This works for me in build perspective ! but how about in Deployment perspective? 

There are pipeline driven deployment jobs in github organization.  embedded shared libaries in jenkins drive the pipeline based on user input.

I have this for now  : 

Global config  for hygieia api URL and nicename for Github org name
all deployments coming under same org name , its indexing in the same. Please assist me if you have curl with json call to post deployment info.

Thanks for your help!!

**Comment by rvema** [comment]
Closing the issue since it was resolved
