### ISSUE TITLE
Ldap Integration is not working 

### ISSUE THREAD

**Issue by srujan5** [Hygieia/Hygieia#1731]
Hygieia api jar not reading ldap properties.  i'm using spring v1 3.0.
In hygieia, if user login with Ldap/AD (same configured in jenkins). Is there anyway to show only the jobs executed by user in jenkins
My property file 
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
#dbreplicaset=false
#dbhostport=localhost:27017
auth.ldapServerUrl=ldap://xxxx.xxxxx.xxx:389/
# If using standard ldap
# LDAP User Dn Pattern, where the username is replaced with '{0}'
auth.ldapUserDnPattern=[uid={0},OU=xxxx,dc=xxxxx,dc=xxx]

server.contextPath=/api
server.port=8080.

except ldap integration rest of them are working fine.

**Comment by htvan1** [comment]
try adding this
auth.authenticationProviders=LDAP

**Comment by srujan5** [comment]
Thanks for the quick response, it is reading ldap url now but it is showing DN ' ' .can you provide me any solution for that. thank you.

**Comment by htvan1** [comment]
you are now as far as I was able to get it ; ) 
sorry, I shelved that issue for lots of other bugs I am finding with this app.  : /

**Comment by justinzyw** [comment]
try this for root DN:   ldap://ldapserver:389/dc=company,dc=org

I still have not yet found the way to set userDn for LDAP

**Comment by gars01** [comment]
Some improvement on this issue?

**Comment by SibiVaithara** [comment]
Hi

we had the same error with TDS server as Nithin had

`message=[LDAP: error code 53 - Unwilling To Perform]; nested exception is javax.naming.OperationNotSupportedException: [LDAP: error code 53 - Unwilling To Perform];`

the work around mentioned by @justinzyw works . In application.properties I set the following

`auth.authenticationProviders=STANDARD,LDAP
auth.ldapServerUrl=ldap://ldapserver:389/dc=company,dc=org

auth.ldapUserDnPattern=uid={0}
`

----------------------------------------------------

**To set bind user and password**

Note: we did not have to do the below to get ldap to work but during process of debugging, i could set userDn for binding by editing api module class com.capitalone.dashboard.config.WebSecurityConfig.configureLdap((AuthenticationManagerBuilder auth)) method as follows

`private void configureLdap(AuthenticationManagerBuilder auth) throws Exception {
        String ldapServerUrl = authProperties.getLdapServerUrl();
		String ldapUserDnPattern = authProperties.getLdapUserDnPattern();
		if (StringUtils.isNotBlank(ldapServerUrl) && StringUtils.isNotBlank(ldapUserDnPattern)) {
			
		       ContextSourceBuilder cbuild =auth.ldapAuthentication()
			.userDnPatterns(ldapUserDnPattern)
			.contextSource().url(ldapServerUrl);

                        cbuild.managerDn("cn=user1,dc=company,dc=org");
			
			cbuild.managerPassword("Password");
`

I have hard coded the user and password here but you may move it to applications,properties to be read by authProperties

Thanks
Sibi

**Comment by ham5768** [comment]
this wont work. I have tried this option no luck

**Comment by rvema** [comment]
@ham5768 Are you still having trouble?

**Comment by gars01** [comment]
No longer, thanks

**Comment by ham5768** [comment]
We moved out of hygieia. We removed all our projects.

**Comment by Sbrenthughes** [comment]
@gars01 What did you do to resolve ?

**Comment by gars01** [comment]
Have you seen this https://github.com/Hygieia/Hygieia/pull/2320/files?utf8=%E2%9C%93&diff=unified?
It works for us

**Comment by Sbrenthughes** [comment]
Ah, okay looks like it is waiting for the PR to updated with Unit testing.

**Comment by rvema** [comment]
This PR#2320 has been merged hence closing this request
