### ISSUE TITLE
SCM connector - Repository

### ISSUE THREAD

**Issue by andyct** [Hygieia/Hygieia#1824]
If a project team is working on multiple repositories, it is very time consuming task to continue changing the SCM repository. Whether Hygieia enforces a standard that a team should have one repository only?

**Comment by tabladrum** [comment]
Underneath, the framework handles multiple repo. We cant figure out a good way to visualize it. Any input will be greatly appreciated.

**Comment by andyct** [comment]
Thanks tabladrum. Could you please put a tag for enhancements.

**Comment by rvema** [comment]
#2549 will take care of this enhancement.
