### ISSUE TITLE
Product Dashboard - Values not appearing for Dev, QA , Int and Perf

### ISSUE THREAD

**Issue by Dinkarv** [Hygieia/Hygieia#1859]
I have build a collector for octopus deploy in the same lines as urbancode. I was able to get the deploy dashboard up. After configuring pipeline dashboard is with mappings to the corresponding environments in the project, when the product dasboard is created the Dev, QA , Int and Perf sections are empty. I have deployed the jenkins plugin and it is running as a post build step. I have configured Hygeia in jenkins to publish build and artifact information. After the run both Deployment and artificat Hygiea gives an ID and 201 created message. Are there any documents to help get the product dashboard setup. The current github readme looks like incomplete in the configuration section.

![](https://cloud.githubusercontent.com/assets/7313166/17266805/bab56b76-55b1-11e6-9e3b-05dd19d1929f.png)

![](https://cloud.githubusercontent.com/assets/7313166/17266804/bab46fd2-55b1-11e6-8a25-8cca83ee7cf4.png)

![](https://cloud.githubusercontent.com/assets/7313166/17266807/bab8c4ec-55b1-11e6-8b7e-1faaf3d94990.png)

**Comment by nireeshT** [comment]
@Dinkarv  Once you configure pipeline, can you do a commit on repo, build it and run deploy. That way it will trigger to pipeline to effect product dashboard.

**Comment by Dinkarv** [comment]
@nireeshT Commit and Build are showing in product dashboard perfectly but the problem is persisting for product dashboard.
Either it is not fetching from database or something is not clear at my side. Can you explain its architecture from pipeline to product!! How it is connected!

**Comment by ykfq** [comment]
Same issue for me.
I'm using jenkins pipeline jobs and using `Hygieia-jenkins plugin` to publish datas to Hygieia dashboard, the team dashboards works fine but the product Dashboard only shows "Commit" and "Build" datas, the depoyment steps are empty, press F12 in chrome, it shows an error says 
> TypeError: Cannot read property 'profile' of undefined

Screenshots:
- Team dashboard widget
  ![image](https://user-images.githubusercontent.com/20741596/40823669-c8ae5e8c-65a3-11e8-95c2-71e2ae8f15ac.png)

- Team dashboard pipeline
  ![image](https://user-images.githubusercontent.com/20741596/40823709-ed648e9a-65a3-11e8-9769-0ceb30e77119.png)

- Product dashboard
  ![image](https://user-images.githubusercontent.com/20741596/40823751-20d01718-65a4-11e8-9a93-a9e7b8045ac9.png)

**Comment by rvema** [comment]
closing the issue due to inactivity

**Comment by jjoyneriv** [comment]
@Dinkarv , @ykfq , @rvema @nireeshT , I'm struggling with the same issue here. What was the fix?

**Comment by rogerioagostinho** [comment]
Hello @Dinkarv , @ykfq , @rvema @nireeshT

Is there any fix to this issue? If yes, kindly what are the instructions?
