### ISSUE TITLE
could  we get data  by team name  on jira widget ?

### ISSUE THREAD

**Issue by samalg91** [Hygieia/Hygieia#1865]
I am able  to display data by projects but not by teams  even if i can see the teams.

Thank you

**Comment by subodhbattina** [comment]
Trying to understand your question: 
When you configure your JIRA feature widget, it will ask you to pick the project name and based on that the drop down for the team names gets populated with the teams under that project.
And when you pick the team name, the widget will then display the data for that project and team.
So yes, the widget does show data for a project and team combination.

Please let me know if this answers your question. Thanks !

**Comment by samyzemmouri** [comment]
Thank you for  your reply.

in fact i am able to see the teams  but it's  not by project .

for example if i choose  a  particular  project and  i want to see the  teams  for that project it's gonna  display all  the teams in jira . In addition  if i choose  a particular team it's not gonna display anything but it work  when i put ANY. It's like there is no relation between  teams and  projects.

Thank You

**Comment by subodhbattina** [comment]
Yes, you are right, the team drop down does display all the teams it seems like, and not just specific to the project selected. Please excuse me, I am new to the product too, and just realized this. But thanks for bringing this to my notice. Let me circle back with my team and see if I can take this up and correct or resolve this behavior. Thanks Again !

**Comment by lenalevy** [comment]
any news ?
I also open issue regarding the team list in dropdown 
Issue #1850 (capitalone/Hygieia Feature widget is showing in drop down only default "Any" in Team

**Comment by Sbrenthughes** [comment]
@lenalevy @samalg91 - Please refer to #2667. As this is the collector rewrite in progress
