### ISSUE TITLE
Question: how could we view PMD, Checkstyle, Findbus, JaCoCo reports metrices from jenkins-codequality individually on hygieia dashboard?

### ISSUE THREAD

**Issue by KN5028051** [Hygieia/Hygieia#1952]
how could we view PMD, Checkstyle, Findbus, JaCoCo reports metrices from jenkins-codequality individually on hygieia dashboard?

we have updated our application.properties as well 
#Database Name 
dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8088
#Database HostName - default is localhost
#dbhost=localhost

#Database Port - default is 27017
#dbport=9999

#Database Username - default is blank
#dbusername=dashboarduser

#Database Password - default is blank
#dbpassword=dashboarduser123

jenkins.servers[0]=http://localhost:8080
#Collector schedule (required)
jenkins.cron=0 0/1 * * * *

#Jenkins server (required) - Can provide multiple

#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#jenkins.servers[1]=http://username:token@jenkins.company.com

#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.username=admin
jenkins.apiKey=c3133952869c63cef67aa2a0fab0e723

#Determines if build console log is collected - defaults to false
jenkins.saveLog=true

#Sonar Metrics
sonar.metrics=ncloc,line_coverage,violations,critical_violations,major_violations,sqale_index,test_success_density,test_failures,test_errors,tests,new_violations,alert_status,quality_gate_details,duplicated_lines,sqale_rating,sqale_debt_ratio

sonar.servers[0]=http://localhost:9000
sonar.versions[0]=6.7

#Sonar Authentication Username - default is blank
sonar.username=admin

#Sonar Authentication Password - default is blank
sonar.password=admin

# Collector schedule (required)
		jenkins-codequality.cron=0 0/1 * * * *

		# Collector servers (required) - can be multiple servers
		jenkins-codequality.servers[0]=http://localhost:8080

		# Collector types (not required, but regex should match only the type specified)
		jenkins-codequality.artifactRegex.junit=TEST-.*\\.xml
		jenkins-codequality.artifactRegex.findbugs=findbugsXml.xml
		jenkins-codequality.artifactRegex.pmd=pmd.xml
		jenkins-codequality.artifactRegex.checkstyle=checkstyle-result.xml
		jenkins-codequality.artifactRegex.jacoco=jacoco.xml

		# Collector job depth (required) should be set to at least 1, and more if you use folder jobs, and so on.
		jenkins-codequality.jobDepth=4

**Comment by KN5028051** [comment]
@tabladrum Please answer it

**Comment by rvema** [comment]
@KN5028051 We do not have this feature currently. Please feel free to contribute back by implementing the same.
