### ISSUE TITLE
Hygieia JIRA Collector - ALM JIRA - SSO Issue

### ISSUE THREAD

**Issue by venkiradkris** [Hygieia/Hygieia#2214]
Hi 

I am getting below issue in JIRA Collector.

SSO Failure - Unable to process request. Either the requested URL was not specified in terms of a fully-qualified host name or OHS single sign-on is incorrectly configured. Please notify your administrator.

Please find attached Issue Details.
[BNPPJIRAIssue.txt](https://github.com/capitalone/Hygieia/files/2013324/BNPPJIRAIssue.txt)

I was able to successfully integrate Hygieia with Trail Version of JIRA for normal user. I am now facing to connect with Real Time PRD Version of ALM JIRA for SSO User.

Please suggest.
Thanks & Regards
Venkat

**Comment by nireeshT** [comment]
@venkiradkris  install ALM JIRA cert into cacerts using keytool and restart collector

**Comment by venkiradkris** [comment]
Hi
[1] I have downloaded "-usoraclecomUAT.crt" file via browser from my UAT ALM JIRA Application. 
[2] Have installed into cacerts using below command. Verified the certificate availability in cacerts.
keytool -import -file /home/veradhak/jirauatcert/-usoraclecomUAT.crt -alias jirauat -keystore "/usr/java/jdk1.8.0_161/jre/lib/security/cacerts"
[3] Started JIRA Collector and getting same issue.

**Comment by nireeshT** [comment]
@venkiradkris  make you you are using the correct JDk to install certs.

**Comment by nireeshT** [comment]
@venkiradkris  if that did not work, you can use enterprise proxy to connect to Jira using -Dhttps.proxyHost in jar command to startup collector

**Comment by Sbrenthughes** [comment]
Closing do to inactivity
