### ISSUE TITLE
Rally Widget Not working

### ISSUE THREAD

**Issue by CroCo7** [Hygieia/Hygieia#2218]
![failedrequestfromgui](https://user-images.githubusercontent.com/39383508/40194437-1317b9c8-5a28-11e8-9469-d779c2a01333.jpg)
![rallywidgetnotworking](https://user-images.githubusercontent.com/39383508/40194438-135655b6-5a28-11e8-83c3-c31aa08d8220.jpg)

Added Rally widget not working, i am not able to add the rally widget, by clicking on save after adding the information on widget popup, its sending an empty request to server.

**Comment by Mortagne** [comment]
@CroCo7, do you try to make a "mvn docker:build" ... I have a issue ... no Docker directory with a Dockerfile ... so, it's define in the pom.xml ...

**Comment by CroCo7** [comment]
@nireeshT Can you please help here?
@Mortagne I haven't tried the docker build, not sure if it will help here.

**Comment by rvema** [comment]
@Mortagne & @CroCo7 : Can you get the latest code base and retry and reopen this issue if this happens again.
