### ISSUE TITLE
Cant see anything under my github widget

### ISSUE THREAD

**Issue by trinathtiru** [Hygieia/Hygieia#2231]
Hello all,
I ran github collector. But in the UI i don't see any changes. Please find below SS.
![image](https://user-images.githubusercontent.com/33506201/40406767-978f7bb8-5e7f-11e8-837d-d9245bf3f452.png)
Please let me know how to proceed further to fix this?

**Comment by Phoenix9032** [comment]
I faced the similar issue .See the orange button top right .It means pending data collection ? May be the collector didn't poll the data yet. ?

**Comment by trinathtiru** [comment]
@Phoenix9032  yes you are right.. It shows "Pending Data Collection". What need to be done to fix this?

**Comment by Phoenix9032** [comment]
Two things I checked ..one is the cron schedule to pull the data in the properties and I set it at less value and then checked the collector log for any error

**Comment by trinathtiru** [comment]
i just check the cron in the property file and could see this
# Collector schedule (required)
jenkins.cron=0 0/5 * * * *

Futhermore, I dont see any error for now.

@Phoenix9032

**Comment by matthewbeasley** [comment]
@trinathtiru can you share your github logs, properties file and widget configuration? Also can you telnet your Github server from your Hygieia server to ensure connectivity?

**Comment by panshaobin** [comment]
I have the same problem. How did you solve it?'401 Unauthorized' in red spots

**Comment by Sbrenthughes** [comment]
@panshaobin try https://github.com/capitalone/Hygieia/issues/2219#event-1663858729

**Comment by Sbrenthughes** [comment]
@trinathtiru are you still facing this issue?

**Comment by matthewbeasley** [comment]
@trinathtiru please share the information requested by me in the comment above. Otherwise I'm going to close this issue. We can't help you give only the information provided.
