### ISSUE TITLE
Urbancode deploy widget 

### ISSUE THREAD

**Issue by anayyadav** [Hygieia/Hygieia#2238]
I'm running a ucd collector and it is showing the app name. But the problem is I can see only one app env. at a time. 

![dev41](https://user-images.githubusercontent.com/22302511/40527613-f871db88-600a-11e8-8501-2313bce09b3a.PNG)
![dev](https://user-images.githubusercontent.com/22302511/40527615-01cbf5ec-600b-11e8-8036-da262f4e98cd.PNG)

I want all app env. at the same time. 

Please help me to resolve this problem.

**Comment by rvema** [comment]
@anayyadav Is this still an issue?

**Comment by rvema** [comment]
Closing the issue due to inactivity
