### ISSUE TITLE
RFE: AWS CloudWatch collector

### ISSUE THREAD

**Issue by stevegal** [Hygieia/Hygieia#2270]
It would be nice if we could have a cloudwatch log collector and chart the results. 

We could pull the data from cloudwatch using a filter to collect the log data and count the number of entries in the query in the last collection period. This would give people the ability to perform some log monitoring live on the collected logs. For example, if I had a log entry like `{"eventName":"myEvent"}` the gets logged for each interaction with my service, I could query for them in the collector by getting logs with a defined filter-pattern (in this case `{$.eventName="myEvent"}`) and just counting the number in the collection period that match the filter pattern.

We could then chart them.

I guess the configuration would be something like
```properties
aws.cloudwatch.filters[0].name=mySeries1
aws.cloudwatch.filters[0].filter={$.eventName="myEvent"}

aws.cloudwatch.filters[1].name=mySeries2
aws.cloudwatch.filters[1].filter={$.eventName="myEvent2"}
```

Not sure it we could target different graphs type etc... but that might be too far.

This would give a live insight into the logs without needing to drop to the aws cloudwatch console and would also give insight into usage through time.

**Comment by stevegal** [comment]
Is 2 +1's enough so that if I write this and PR it stands a chance of being accepted, or do I need a few more?

**Comment by rvema** [comment]
this PR is merged. Hence closing the issue
