### ISSUE TITLE
jira Unavailability of data,show 0 0 0 

### ISSUE THREAD

**Issue by panshaobin** [Hygieia/Hygieia#2272]
Please help ,without any mistake,application.properties file  as follow 
#PageSize
feature.pageSize=50

# api.query.folder=${base.config.dir}/jiraapi-queries
feature.queryFolder=jiraapi-queries
# Jira API Query file names (String template requires the files to have .st extension)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo
feature.jiraIssueTypeNames=Story,Task,Issue
feature.todoStatuses=Open
feature.doingStatuses=IN PROGRESS
feature.doneStatuses=Done

#Jira Connection Details
feature.jiraProxyUrl=http://e-proxy.yfb.sunline.cn
feature.jiraProxyPort=8080
feature.jiraBaseUrl=http://e-proxy.yfb.sunline.cn:8080
feature.jiraQueryEndpoint=rest/api/2/
######################
# Trending Query need Number of Days After today to filter out Sprints which ends in future.
# This will used to filter Kanban project which has 20 years of Sprints
feature.sprintDays=30
# Trending Query also need Number of Days prior to look for Sprints which has already Ended
feature.sprintEndPrior=7
######################
#Scheduled Job prior minutes to recover data created during execution time
feature.scheduledPriorMin=2
#Delta change date that modulates the collector item task (which should not see changes often)
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000

######################
#Spring Application Properties
spring.data.mongodb.database=dashboard
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=
spring.data.mongodb.password=

#Jira Connection Details
#cGFuc2hhb2Jpbjo4ODg4ODg=
feature.jiraCredentials=***********************
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
# In Jira, general IssueType IDs are associated to various "issue"
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide the name value reference to your instance's IssueType for
# the lowest level of Issues (e.g., "user story") specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:
# https://[your-jira-domain-name]/rest/api/2/issuetype/.  It is listed as
# attribute "name" in the JSON response.
feature.jiraIssueTypeId=10604,10605,10202
# In Jira, your instance will have its own custom field created for "sprint" or "timebox" details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name <em>com.atlassian.greenhopper.service.sprint.Sprint</em>;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraSprintDataFieldName=customfield_10604
# In Jira, your instance will have its own custom field created for "super story" or "epic" back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (e.g., epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
feature.jiraEpicIdFieldName=customfield_10605
#feature.jiraStoryPointsFieldName=customfield_10003
######################
#Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

#StartDate
feature.deltaStartDate=2018-04-01T00:00:00
feature.masterStartDate=2018-04-01T00:00:00
feature.deltaCollectorItemStartDate=2018-04-01T00:00:00
#Core Artifacts
# These arrays of status mappings must be completed in order for custom source system statuses to be providable by
# Hygieia.  Currently, Hygieia only maps to the following 3 status mappings:  to do, doing, and done.  You can find
# all available issue status mappings by going to your instance's version of the following API call:
# http://fake.jira.com/rest/api/2/status/.  Your statuses are listed in the JSON response as "name."
feature.todoStatuses[0]=Backlog
feature.todoStatuses[1]=Grooming
feature.todoStatuses[2]=Ready
feature.doingStatuses[0]=In Progress
feature.doingStatuses[1]=Waiting
feature.doingStatuses[2]=In Review
feature.doingStatuses[3]=For Build
feature.doneStatuses[0]=Approved
feature.doneStatuses[1]=Done
feature.doneStatuses[2]=Accepted

feature.jiraBoardAsTeam=false
feature.jiraTeamFieldName=
logging.level.com.capitalone.dashboard.collector=DEBUG
logging.level.com.capitalone.dashboard=DEBUG

![1528375366 1](https://user-images.githubusercontent.com/39650187/41100274-80e8e140-6a93-11e8-92d6-51718e683250.jpg)

log information
![1528375511 1](https://user-images.githubusercontent.com/39650187/41100349-b7191924-6a93-11e8-9759-2953048a0915.jpg)

I don't know how to fill this out
![1528375856 1](https://user-images.githubusercontent.com/39650187/41100673-904160c6-6a94-11e8-8995-ec5320ff32a0.jpg)

Thanks for your help, this problem has been bothering me for a long time!
@jdamick

**Comment by nireeshT** [comment]
@panshaobin try using these values 

 ``feature.jiraIssueTypeNames=Story
 feature.jiraSprintDataFieldName=customfield_10007
 feature.jiraEpicIdFieldName=customfield_10003
 feature.jiraStoryPointsFieldName=customfield_10004
 feature.jiraTeamFieldName=customfield_11248
 feature.jiraBoardAsTeam=true
``

**Comment by panshaobin** [comment]
@nireeshT Thank you. I'll give it a try

**Comment by suohaonan** [comment]
@panshaobin I want to know has this problem been solved? I have the same problem

here is my application.properties ：
------------------------------------------------------------------------------------------------------------------
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10001
feature.jiraStoryPointsFieldName=customfield_10006
feature.jiraTeamFieldName=
feature.todoStatuse[0]=issuestatus_10072
feature.doingStatuses[0]=issuestatus_10064
feature.doneStatuses[0]=issuestatus_10065
`feature.jiraBoardAsTeam=false
-------------------------------------------------------------------------------------------------------------------

**Comment by panshaobin** [comment]
@nireeshT Unfortunately, that's not going to work either

**Comment by panshaobin** [comment]
@suohaonan No, I don't know the parameters

**Comment by hanjf2018** [comment]
您好，我也遇到了同样的问题，请问您的问题解决了吗？

**Comment by hanjf2018** [comment]
您好，我也遇到了同样的问题，请问您的问题解决了吗？

**Comment by hanjf2018** [comment]
您好，我也遇到了同样的问题，请问您的问题解决了吗？

**Comment by hanjf2018** [comment]
您好，我也遇到了同样的问题，请问您的问题解决了吗？

**Comment by suohaonan** [comment]
@hanjf2018 把feature.jiraSprintDataFieldName、feature.jiraEpicIdFieldName、feature.jiraStoryPointsFieldName这三个参数配置对了就能正常显示了，我目前只配置出来了epic，story还没弄明白。
这三个参数的值我是在jira数据库customfield这张表里挨个试出来的……

**Comment by hanjf2018** [comment]
厉害，请问这个参数您配不配的？feature.jiraTeamFieldName=

**Comment by suohaonan** [comment]
那个没配置

**Comment by hanjf2018** [comment]
这是jira的customfield表，我试着改了一下，还是不行。可以麻烦您看下是哪三个字段吗？
+-------+--------------------------------------------------------------------+-----------------------------------------------------------------------+--------------------+--------------------------------------------------------------------------+--------------+-----------+---------+-----------+ 
| ID    | CUSTOMFIELDTYPEKEY                                                 | CUSTOMFIELDSEARCHERKEY                                                | cfname             | DESCRIPTION                                                              | defaultvalue | FIELDTYPE | PROJECT | ISSUETYPE | 
+-------+--------------------------------------------------------------------+-----------------------------------------------------------------------+--------------------+--------------------------------------------------------------------------+--------------+-----------+---------+-----------+ 
| 10000 | com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes  | com.atlassian.jira.plugin.system.customfieldtypes:multiselectsearcher | Flagged            | 遇到障碍                                                             | NULL         |      NULL |    NULL | NULL      | 
| 10001 | com.atlassian.jira.plugin.system.customfieldtypes:labels           | com.atlassian.jira.plugin.system.customfieldtypes:labelsearcher       | Epic/Theme         | Field that will help you regroup issues under an Epic or under a theme.  | NULL         |      NULL |    NULL | NULL      | 
| 10002 | com.atlassian.jira.plugin.system.customfieldtypes:float            | com.atlassian.jira.plugin.system.customfieldtypes:exactnumber         | Story Points       | Measurement of complexity and/or size of a requirement.                  | NULL         |      NULL |    NULL | NULL      | 
| 10003 | com.atlassian.jira.plugin.system.customfieldtypes:float            | com.atlassian.jira.plugin.system.customfieldtypes:exactnumber         | Business Value     | Measurement of business value of a requirement.                          | NULL         |      NULL |    NULL | NULL      | 
| 10004 | com.pyxis.greenhopper.jira:gh-global-rank                          | com.pyxis.greenhopper.jira:gh-global-rank-searcher                    | Rank               | Global rank field for JIRA Agile use only.                               | NULL         |      NULL |    NULL | NULL      | 
| 10005 | com.pyxis.greenhopper.jira:gh-sprint                               | com.pyxis.greenhopper.jira:gh-sprint-searcher                         | Sprint             | JIRA Agile sprint field                                                  | NULL         |      NULL |    NULL | NULL      | 
| 10006 | com.pyxis.greenhopper.jira:gh-epic-link                            | com.pyxis.greenhopper.jira:gh-epic-link-searcher                      | Epic Link          | Choose an epic to assign this issue to.                                  | NULL         |      NULL |    NULL | NULL      | 
| 10007 | com.pyxis.greenhopper.jira:gh-epic-label                           | com.pyxis.greenhopper.jira:gh-epic-label-searcher                     | Epic Name          | Provide a short name to identify this epic in the JIRA Agile boards.     | NULL         |      NULL |    NULL | NULL      | 
| 10008 | com.pyxis.greenhopper.jira:gh-epic-status                          | com.pyxis.greenhopper.jira:gh-epic-status-searcher                    | Epic Status        | Epic Status field for JIRA Agile use only.                               | NULL         |      NULL |    NULL | NULL      | 
| 10009 | com.pyxis.greenhopper.jira:gh-epic-color                           | com.pyxis.greenhopper.jira:gh-epic-color-searcher                     | Epic Colour        | Epic Colour field for JIRA Agile use only.                               | NULL         |      NULL |    NULL | NULL      | 
| 10100 | com.pyxis.greenhopper.jira:greenhopper-releasedmultiversionhistory | com.pyxis.greenhopper.jira:versionsearcher                            | 版本发布历史 | 发布的版本，曾经有未完成的任务转到下一个Sprint中。 | NULL         |      NULL |    NULL | NULL      | 
| 10201 | com.atlassian.jira.plugin.system.customfieldtypes:datepicker       | com.atlassian.jira.plugin.system.customfieldtypes:daterange           | 测试通过时间 | 由测试人员填写                                                    | NULL         |      NULL |    NULL | NULL      | 
| 10301 | com.atlassian.jira.plugin.system.customfieldtypes:select           | com.atlassian.jira.plugin.system.customfieldtypes:multiselectsearcher | Team名称         | 小组名称                                                             | NULL         |      NULL |    NULL | NULL      | 
| 10302 | com.atlassian.jira.plugin.system.customfieldtypes:textarea         | com.atlassian.jira.plugin.system.customfieldtypes:textsearcher        | 描述             | 内容描述                                                             | NULL         |      NULL |    NULL | NULL      | 
| 10303 | com.atlassian.jira.plugin.system.customfieldtypes:float            | com.atlassian.jira.plugin.system.customfieldtypes:exactnumber         | 故事优先级    | NULL                                                                     | NULL         |      NULL |    NULL | NULL      | 
| 10304 | com.atlassian.jira.plugin.system.customfieldtypes:textarea         | com.atlassian.jira.plugin.system.customfieldtypes:textsearcher        | AC点              | 验收点                                                                | NULL         |      NULL |    NULL | NULL      | 
| 10305 | com.atlassian.jira.plugin.system.customfieldtypes:datepicker       | com.atlassian.jira.plugin.system.customfieldtypes:daterange           | 验收通过时间 | 关闭issue时填写                                                     | NULL         |      NULL |    NULL | NULL      | 
| 10307 | com.atlassian.jira.plugin.system.customfieldtypes:select           | com.atlassian.jira.plugin.system.customfieldtypes:multiselectsearcher | 批次             | NULL                                                                     | NULL         |      NULL |    NULL | NULL      | 
| 10402 | com.tempoplugin.tempo-accounts:accounts.customfield                | com.tempoplugin.tempo-accounts:accounts.searcher                      | Account            | Link this issue's logged hours and expenses to an account.               | NULL         |      NULL |    NULL | NULL      | 
| 10403 | com.tempoplugin.tempo-teams:team.customfield                       | com.tempoplugin.tempo-teams:team.searcher                             | Team               | Tempo团队自定义字段                                               | NULL         |      NULL |    NULL | NULL      | 
| 10404 | com.tempoplugin.tempo-plan-core:tp.iteration.customfield           | com.tempoplugin.tempo-plan-core:tp.iteration.searcher                 | Iteration          | Iteration field for Tempo Planner use only.                              | NULL         |      NULL |    NULL | NULL      | 
+-------+--------------------------------------------------------------------+-----------------------------------------------------------------------+--------------------+--------------------------------------------------------------------------+--------------+-----------+---------+-----------+ 
21 rows in set (0.00 sec)

**Comment by MummanaSubramanya** [comment]
@nireeshT : Hi Nireesh, could you please explain how to get the custom_fields? I try to do the same as mentioned in the doc but that doesnt help.

**Comment by MummanaSubramanya** [comment]
@nireeshT : I used https://xxx.atlassian.net/rest/api/2/field (should be already logged in to your jira instance) to get the custom fields of your instance . But still I the dashboard show 0 0 0. Am I missing anything.

**Comment by celamb4** [comment]
Same issue. Collector seems to find zero stories. 

`
2018-12-07 20:14:01,535 INFO  c.c.d.collector.CollectorTask - Team Data              55        1s
2018-12-07 20:14:02,435 INFO  c.c.d.collector.CollectorTask - Project Data           48        0s
2018-12-07 20:14:03,539 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 0
2018-12-07 20:14:03,539 INFO  c.c.d.collector.CollectorTask - Story Data              0        1s
2018-12-07 20:14:03,539 INFO  c.c.d.collector.CollectorTask - Finished                         3s
`

**Comment by celamb4** [comment]
So, digged a little more. Cleared the mongo feature collection. Reran the collector, it started parsing everything. Lots of errors from some stories parsing the Sprint.. Regardless, the DB now has fresh documents. I can actually see the documents and see ProjectName. However, when I select the feature widget --> Project=myproject , All issues.. Nothing shows up. Not for scrum or kanban.

Is the API broken? Seems like its unable to GET the documents from the DB.

```
{
    "_id" : ObjectId("5c0eb3e0676a1d2a8f3454a7"),
    "_class" : "com.capitalone.XXshboard.model.Feature",
    "collectorId" : ObjectId("5c0aaf44676a1d0fd86e5a6a"),
    "sId" : "25972",
    "sNumber" : "XX-36",
    "sName" : "My story name",
    "sTypeId" : "10001",
    "sTypeName" : "Story",
    "sStatus" : "Done",
    "sState" : "Done",
    "sEstimate" : "3",
    "sEstimateTime" : 0,
    "sUrl" : "https://mycompany.atlassian.net/browse/XX-36",
    "changeXXte" : "2017-09-07T16:07:47.9030000",
    "isDeleted" : "False",
    "sOwnersID" : [ 
        "jdoe"
    ],
    "sOwnersIsDeleted" : [],
    "sOwnersChangeDate" : [],
    "sOwnersState" : [ 
        "Active"
    ],
    "sOwnersUsername" : [ 
        "jdoe"
    ],
    "sOwnersFullName" : [ 
        "John Doe"
    ],
    "sOwnersShortName" : [ 
        "jdoe"
    ],
    "sTeamIsDeleted" : "False",
    "sTeamAssetState" : "",
    "sTeamChangeDate" : "",
    "sSprintIsDeleted" : "False",
    "sSprintChangeDate" : "",
    "sSprintAssetState" : "CLOSED",
    "sSprintEndDate" : "2017-03-11T02:41:00.0000000",
    "sSprintBeginDate" : "2017-03-06T20:41:42.9760000",
    "sSprintName" : "Mini Goat",
    "sSprintID" : "108",
    "sSprintUrl" : "https://mycompany.atlassian.net/secure/RapidBoard.jspa?rapidView=61&view=reporting&chart=sprintRetrospective&sprint=108",
    "sEpicIsDeleted" : "False",
    "sEpicChangeDate" : "",
    "sEpicAssetState" : "To Do",
    "sEpicType" : "",
    "sEpicEndDate" : "",
    "sEpicBeginDate" : "2016-11-18T22:44:43.0360000",
    "sEpicName" : "My Epic Name",
    "sEpicUrl" : "https://mycompany.atlassian.net/browse/XX-35",
    "sEpicNumber" : "XX-35",
    "sEpicID" : "25971",
    "sProjectPath" : "",
    "sProjectIsDeleted" : "False",
    "sProjectState" : "",
    "sProjectChangeDate" : "",
    "sProjectEndDate" : "",
    "sProjectBeginDate" : "",
    "sProjectName" : "myproject",
    "sProjectID" : "12900",
    "issueLinks" : []
}
```

**Comment by celamb4** [comment]
Running jira collector 3.0.1 which is the latest.

**Comment by celamb4** [comment]
@Sbrenthughes Any thoughts?

**Comment by celamb4** [comment]
Cleaned the feature collection and reran the collector. Seems like parser is having issues with line breaks. I do think this is a separate issue since the DB does end up being populated with documents that include Story, Sprint and Epic name such as my previous comment.

```
2018-12-11 19:14:07,714 ERROR c.c.d.c.story.StoryDataClientImpl - Failed to obtain sprint data from ["com.atlassian.greenhopper.service.sprint.Sprint@2fd228ee[id=363,rapidViewId=61,state=CLOSED,name=Spicy NuGet,goal=* Release 1.44\n* Successful trial launch on website by July 31\n* Successful deployment \n* Improve accuracy,startDate=2018-07-17T14:00:54.484Z,endDate=2018-07-31T14:00:00.000Z,completeDate=2018-07-30T20:34:48.059Z,sequence=320]"]
java.text.ParseException: Unparsable sprint: com.atlassian.greenhopper.service.sprint.Sprint@2fd228ee[id=363,rapidViewId=61,state=CLOSED,name=Spicy NuGet,goal=* Release 1.44
* Successful trial launch on website by July 31
* Successful deployment
* Improve accuracy,startDate=2018-07-17T14:00:54.484Z,endDate=2018-07-31T14:00:00.000Z,completeDate=2018-07-30T20:34:48.059Z,sequence=320]
	at com.capitalone.dashboard.util.ClientUtil.parseSprint(ClientUtil.java:340) ~[jira-feature-collector.jar!/:3.1.0-SNAPSHOT]
	at com.capitalone.dashboard.util.ClientUtil.parseSprints(ClientUtil.java:287) ~[jira-feature-collector.jar!/:3.1.0-SNAPSHOT]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.processSprintData(StoryDataClientImpl.java:521) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateMongoInfo(StoryDataClientImpl.java:250) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:170) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:119) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [jira-feature-collector.jar!/:3.0.1]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.0-SNAPSHOT.jar!/:3.0.1]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

**Comment by Sbrenthughes** [comment]
@panshaobin @MummanaSubramanya  @suohaonan - Please refer to #2667. As this is the collector rewrite in progress

**Comment by lyndomiao** [comment]
@suohaonan @hanjf2018 请问你两解决这个问题了吗？我配置了feature.jiraSprintDataFieldName、feature.jiraEpicIdFieldName、feature.jiraStoryPointsFieldName这三个参数还是没有数据，能不能告诉我怎么解决的
