### ISSUE TITLE
Not able configure widget for GITHUB

### ISSUE THREAD

**Issue by monikanaagar** [Hygieia/Hygieia#2337]
<img width="450" alt="capture" src="https://user-images.githubusercontent.com/26919216/42312976-e3ee7d72-8041-11e8-858e-e2f292fb8318.PNG">

**Comment by ArjunSreepad** [comment]
you should run anothe rprogram to create the encryption and deprtyion key
since you enter the raw password, in order to secure it their is a encryption and decryption program

**Comment by monikanaagar** [comment]
still it is not working

**Comment by matthewbeasley** [comment]
@monikanaagar - don't put '.git' in your Repo URL. Remove this and then wait for data collection. If at that point it is still not work please upload your logs here as a text file.

**Comment by Sbrenthughes** [comment]
Also, this doesn't look like the updated view of that widget.

**Comment by Sbrenthughes** [comment]
@monikanaagar are you still facing this issue?
