### ISSUE TITLE
Not Getting the Score

### ISSUE THREAD

**Issue by MummanaSubramanya** [Hygieia/Hygieia#2342]
I ran the score collector and in the logs it shows as 

`2018-07-07 22:25:00,023 INFO  c.c.d.collector.CollectorTask - Running Collector: Score
2018-07-07 22:25:00,130 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-07-07 22:25:00,167 INFO  c.c.d.collector.CollectorTask - Score
2018-07-07 22:25:00,184 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-07-07 22:25:00,524 INFO  c.c.d.collector.CollectorTask - Score collector id = 5b40e7040564221ec8606f92
2018-07-07 22:25:01,079 INFO  c.c.d.collector.CollectorTask - No of dashboards with score widget=0
2018-07-07 22:25:01,187 INFO  c.c.d.collector.CollectorTask - Finished                         0s`

Below is my properties file configuration:

`
# Database Name
spring.data.mongodb.dbname=dashboarddb

# Database HostName - default is localhost
spring.data.mongodb.host=localhost

# Database Port - default is 27017
spring.data.mongodb.port=27017

# Database Username - default is blank
spring.data.mongodb.username=dashboarduser

# Database Password - default is blank
spring.data.mongodb.password=dbpassword

# Collector schedule (required)
score.cron=0 0/5 * * * *

# Max score to display as 5
score.maxScore=5

# If value is equal or less to 0 show alert for the widget
score.widgetAlert.value=0

# If widget is not found, set value as no score to ignore widget in score calculation
score.criteria.noWidgetFound.scoreType=zero_score

# If widget has no data, score would be 0 for it
score.criteria.noDataFound.scoreType=zero_score

# Weight for github widget
score.scmWidget.weight=50

# Weight for build widget
score.buildWidget.weight=50

score.buildWidget.numberOfDays=14
score.scmWidget.numberOfDays=14
`

**Comment by Sbrenthughes** [comment]
Have you added the score widget for any dashboards?

**Comment by MummanaSubramanya** [comment]
nope I haven't added any score widgets to any dashboard...!! am i missing any configuration?

**Comment by Sbrenthughes** [comment]
Yes when you create a dashboard there is an option to add the score and there is also and option to add the score widget when you edit a dashboard.

**Comment by MummanaSubramanya** [comment]
@Sbrenthughes : sorry I misread your first question. apologies for that. Yes while configuring the dasboard I checked to "Enable Score" option and selected "Display on header". Then I started the score collector with above properties but it still show as "NA"

**Comment by MummanaSubramanya** [comment]
![hygiealatest](https://user-images.githubusercontent.com/25982124/42553129-2ffb1648-84fd-11e8-9cd2-5f059f0d37c6.jpg)

**Comment by MummanaSubramanya** [comment]
![capture](https://user-images.githubusercontent.com/25982124/42553291-e4dba79e-84fd-11e8-8148-e9bf574ecc7b.PNG)

**Comment by MummanaSubramanya** [comment]
any help on this would be appreciated!!

**Comment by Sbrenthughes** [comment]
Does the collector still show that it is not able to find dashboards with the score enabled?

**Comment by MummanaSubramanya** [comment]
as previously mentioned I have checked "Enable Score" option and selected "Display on header". Then I started the score collector with above properties and it shows as "NA"

**Comment by Sbrenthughes** [comment]
Closing due to no response. Please reopen if you are still having issues.

**Comment by awanish3** [comment]
I am also facing the same issue getting in logs No of dashboards with score widget=0
but we have enabled the score as shown below.
![administer your dashboard](https://user-images.githubusercontent.com/13289550/46734532-25304c00-ccb1-11e8-9df0-8b3398b936b1.JPG)

**Comment by prateekasthana** [comment]
Facing same issue as stated by awanish3 . Can any one help on this ? 
Thanks in advance .
Prateek
