### ISSUE TITLE
Problems in Openshift to maintain data in Mongodb after redeployment

### ISSUE THREAD

**Issue by gars01** [Hygieia/Hygieia#2346]
We have deployed Hygieia over Openshift but we have detected a problem. Each time the Mongodb container is redeployed, the data structure is regenerated in such a way that previously saved data is lost, even if the /data/db folder has been associated with a volume. Could it be that the image of Mongodb is ephemeral? What are we doing wrong? Can someone help us? Thanks in advance.

**Comment by Sbrenthughes** [comment]
At least in our case, we take a backup and then restore it during the deployment process.

**Comment by gars01** [comment]
Thanks, although finally we have decided to deploy a new Mongodb service alternatively to Hygieia's one and bind it to a volume to get persistence. Successfully it works. So we don't need to take backup before deploy and restore it after, only in a normal way to preserve data in case server is broken down.

**Comment by yodaqua** [comment]
Hi @gars01 

I've been working on deploying Hygieia in OpenShift. As you did, I've deployed MongoDB with a PV.

I'm experiencing an issue with creating a dashboard, in that I can't create one.

Have you experienced a similar issue?

Also, will you willing to share your OpenShift Hygieia Dockerfiles, please?

**Comment by gars01** [comment]
The only problems I have had when creating a dashboard occur if I enter a business service or business application, so when I am on the screen to create the dashboard I avoid accessing those two fields. I have not investigated for the moment more about this problem.

As for the files dockerfile I have used the ones that come by default in the Hygieia master branch, parameterizing in Openshift using secrets and configmaps the variables that they use. For example for api:
![imagen](https://user-images.githubusercontent.com/33869302/42759195-62afa740-8906-11e8-9bf4-125e5c26930b.png)

where values of configmap mongodb-service are:

puerto: 27017
servicio: mongodb

And "servicio" is the mongodb service name in Openshift
