### ISSUE TITLE
jenkins-cucumber - WARNING: No Enabled Jobs found with artifacts pattern: cucumber.json

### ISSUE THREAD

**Issue by muralikvns** [Hygieia/Hygieia#2372]
Hi Team - We are facing issue while setting up jenkins-cucumber setup using hygieia
hygieia version - 2.0.4

Do have cucumber job running in jenkins and archived the artifact as well

**Logs**
2018-07-24 11:55:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: JenkinsCucumberTest
2018-07-24 11:55:00,083 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-07-24 11:55:00,084 INFO  c.c.d.collector.CollectorTask - http://localhost:8081/jenkins
2018-07-24 11:55:00,086 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-07-24 11:55:00,504 INFO  c.c.d.collector.CollectorTask - Fetched jobs                     0s
2018-07-24 11:55:07,629 INFO  c.c.d.collector.CollectorTask - New jobs                0        7s
2018-07-24 11:55:46,698 INFO  c.c.d.collector.CollectorTask - WARNING: No Enabled Jobs found with artifacts pattern: cucumber.json
2018-07-24 11:55:46,701 INFO  c.c.d.collector.CollectorTask - Finished                        46s

**following are the application.properties used for running the jenkins-cucumber.jar**
...
# Jenkins server (required) - Can provide multiple
jenkins-cucumber.servers[0]=http://localhost:8081/jenkins
#Pattern to find cucumber reports
#jenkins-cucumber.cucumberJsonRegex=${JENKINS_CUCUMBER_JSON_FILENAME:-cucumber.json}
jenkins-cucumber.cucumberJsonRegex=cucumber.json
jenkins-cucumber.username=xxxx
jenkins-cucumber.apiKey=xxxx

**Cucumber Job in Jenkins rest api for reference**
http://localhost:8081/jenkins/job/cucumber-java/lastSuccessfulBuild/api/json

Response
{
    "_class": "hudson.maven.MavenModuleSetBuild",
    "actions": [
        {
            "_class": "hudson.model.CauseAction",
            "causes": [
                {
                    "_class": "hudson.model.Cause$UserIdCause",
                    "shortDescription": "Started by user admin",
                    "userId": "admin",
                    "userName": "admin"
                }
            ]
        },
        {
            "_class": "hudson.maven.reporters.SurefireAggregatedReport",
            "failCount": 0,
            "skipCount": 0,
            "totalCount": 4,
            "urlName": "testReport"
        },
        {
            "_class": "hudson.maven.reporters.MavenAggregatedArtifactRecord"
        },
        {},
        {},
        {},
        {}
    ],
    "artifacts": [
        {
            "displayPath": "cucumber.json",
            "fileName": "cucumber.json",
            "relativePath": "cucumber.json"
        }
    ],
    "building": false,
    "description": null,
    "displayName": "#11",
    "duration": 43578,
    "estimatedDuration": 38819,
    "executor": null,
    "fullDisplayName": "cucumber-java #11",
    "id": "11",
    "keepLog": false,
    "number": 11,
    "queueId": 16,
    "result": "SUCCESS",
    "timestamp": 1532380719901,
    "url": "http://localhost:8081/jenkins/job/cucumber-java/11/",
    "builtOn": "",
    "changeSet": {
        "_class": "hudson.scm.EmptyChangeLogSet",
        "items": [],
        "kind": null
    },
    "culprits": [],
    "mavenArtifacts": {},
    "mavenVersionUsed": "3.2.1"
}

**Comment by Sbrenthughes** [comment]
Is the cucumber.json file in the root of the workspace?

**Comment by Sbrenthughes** [comment]
If that doesn't work you may need to try using the plugin to push the data.

**Comment by muralikvns** [comment]
Thanks for the response. Yes it is in root of the jenkins job workspace  as mentioned <JENKINS_HOME>\workspace\<JENKINS_JOB_NAME>\cucumber.json

**Comment by muralikvns** [comment]
Regarding the plugin to push the data can you please elaborate. I couldn't follow

**Comment by Sbrenthughes** [comment]
https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/hygieia-jenkins-plugin/hygieia-jenkins-plugin.md

You add the test results under the Quality widget > function test section

**Comment by Sbrenthughes** [comment]
And just as an update, we are working on enhancing the plugin to automatic push all jenkins data for each job.  This push will occur by default without any updates to your jenkins job

**Comment by Sbrenthughes** [comment]
@muralikvns any update here?

**Comment by kkorada** [comment]
Hi I am also facing same issue, any update on this ?

**Comment by kkorada** [comment]
My artifacts are having cucumber file, but still it is saying WARNING: No Enabled Jobs found with artifacts pattern: cucumber.json

**Comment by prabhurs123** [comment]
Hi, Anybody has working collector for this Jenkins cucumber.
