### ISSUE TITLE
How to use JIRA API to find the correct value!

### ISSUE THREAD

**Issue by fanfanup** [Hygieia/Hygieia#2373]
use this api  “https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]”
Too many customfield, I didn't know that was what I wanted. and No errors were seen in the JIRA boot log ，please help me。

**Comment by fanfanup** [comment]
Feature widget shows 0 0 0 while JIRA Collector works well

**Comment by MummanaSubramanya** [comment]
@nireeshT could you please help us? We would like to know how to get the accurate customfield.

**Comment by shardulsrivastava** [comment]
You can use this API to get which custom_field belongs to which value : 

https://yourjira.com/rest/api/2/issue/<Your issue Id>?expand=names 

Example : 

https://myjira.net/rest/api/2/issue/RAD-737?expand=names

Just add `?expand=names` in the end of your issues, you will get your custom filed mapping details.

**Comment by Sbrenthughes** [comment]
Closing as it appears the question was answered. Let me know if this is not the case.
