### ISSUE TITLE
How to display "server status (up or down)" in Deploy with curl

### ISSUE THREAD

**Issue by baitiandi** [Hygieia/Hygieia#2380]
Hi All
i am working on push deployment status into deploy widget with curl, but "Number of servers up or down in each environment" aways is zero. so How to display it with curl.
thanks a lot.

**Comment by Sbrenthughes** [comment]
I haven't looked into this. My suggestion would be to see how that value is generated on the UI and track back to the DB. Once you see what values are required in the DB then you can try to figure out what needs to be passed.

**Comment by baitiandi** [comment]
thanks a lot

**Comment by Sbrenthughes** [comment]
Were you able to figure it out?
