### ISSUE TITLE
Bitbucket repository issue about long URL

### ISSUE THREAD

**Issue by baitiandi** [Hygieia/Hygieia#2381]
Hi All
maybe my repository URL is very long, it doesn't dispaly the whole repository lead to is not able to connect my repository, occur connect issue when i fill this long reposiroty into Repo widget of Bitbucket

**Comment by subodhbattina** [comment]
@baitiandi : 
1. Can you please share the values you are using to create the widget?
2. Please open the developer console on your browser, and please share any errors you may be seeing on the console at the point you create the widget.
3. Also, in your MongoDB repository, Run these queries below to check the if the repo url is saved in its entirety:

3.1 Run the below query on "collectors" collection. Make a note of the "_id" value from the result on the query below
**{ "name": "Bitbucket" }**
3.2 Run the below query on "collector_items" collection. 
Put in the repo url you have, and the collector id value from the above query.
See you get back any data.
{ "collectorId": ObjectId("<collector id value>"), $and: [ { "options.url": "<repo url>" } ] }

First lets make sure you have this data, and then go from there.
Please do share the logs, both from the browser console and the api logs. Thanks !

**Comment by subodhbattina** [comment]
@baitiandi: Any updates on this at all?

**Comment by subodhbattina** [comment]
@baitiandi: Following up again, do you have any updates on this at all? Thanks.

**Comment by subodhbattina** [comment]
@baitiandi: Just wanted to follow up on last time if you have any updates at all. Thanks

**Comment by subodhbattina** [comment]
@baitiandi: Since we didn't hear back from you, assuming this issue is resolved at your end. Thanks for reaching out. Thanks !
