### ISSUE TITLE
properties-builder.sh

### ISSUE THREAD

**Issue by xUnholy** [Hygieia/Hygieia#2383]
Issues:

> MONGODB_HOST=`echo $MONGO_PORT|sed 's;.*://\([^:]*\):\(.*\);\1;'`

> MONGODB_PORT=`echo $MONGO_PORT|sed 's;.*://\([^:]*\):\(.*\);\2;'`

This will result in db connection 27017:27017 which is therefore incorrect. Following the docker-compose file format it should be db:27017, therefore it needs to be changed to the following.

> MONGODB_HOST=`echo $MONGO_HOST|sed 's;.*://\([^:]*\):\(.*\);\1;'`

> MONGODB_PORT=`echo $MONGO_PORT|sed 's;.*://\([^:]*\):\(.*\);\2;'`

Also found multiple issues in regards to syntax & consistency, I see variables everywhere referencing MONGODB_HOST, then I'll see MONGO_HOST - this feels very redundant.

Also the lack of double quote to prevent globbing and word splitting, when referencing variables among other things.

**Comment by rvema** [comment]
@xUnholy Please submit a PR if you find a fix to this problem.

**Comment by matthewbeasley** [comment]
@xUnholy - the properties-build.sh files definitely need work. The pattern we want to move to is similar to this one: https://github.com/Hygieia/ExecDashboard/blob/master/exec-ui/docker-util/docker-entrypoint.sh so we don't need `&&` in our CMD. That being said the example you gave for the MONGODB_HOST and MONGODB_PORT is actually correct. It's hard to read I know but if you look closely there are two capture groups in the regex. MONGODB_HOST becomes the first capture group and MONGODB_PORT becomes the second. We want to revamp all of this and would love to hear your thoughts and would be more than happy to work with you to improve this.

**Comment by xUnholy** [comment]
@matthewbeasley 

I haven't had too much time to review the Hygieia - we did a product analysis and decided we would just stay with our current prometheus / grafana stack for monitoring, however I can see Hygieia being much better once there is some more maturity in the product.

I would suggest that the issue I've raised here is also perhaps not the best way to handle it, however if you want I can spend some time looking into some of these small things and raise a PR for you guys to decide on if you'd like? 

I also raised another ticket the same day as this one which doesn't have any current comments as of yet.

Regards,

Michael.

**Comment by spyoungtech** [comment]
The `mongo_port` also threw me for a bit. Key is that the scheme should be included like

```
MONGO_PORT=tcp://hostname:27017
```

Without the `:` in the scheme, the `sed` command groups don't work out.

Honestly, I would find it better if we just uniformly used the environmetn variables `MONGODB_HOST` and `MONGODB_PORT`.

**Comment by rvema** [comment]
This has been fixed as part of PR #2694 . Please retrieve the latest code and retry. Do reopen if you run into this issue.
