### ISSUE TITLE
DefaultBitbucketCloudClient.java

### ISSUE THREAD

**Issue by xUnholy** [Hygieia/Hygieia#2384]
Issues:

both variables hostUrl & apiUrl are essentially from what I can see used in slightly different ways when they can be used exchangeably. Also found that the following use case would cause interesting errors because of how we are appending and reconstructing the apiUrl.

Given provided bitbucket host: https://some.bitbucket.server.com:8443/ 

Note: This is an internal only used server, and its listening on that specific port as is the case.

The apiUrl would result in the following.

https://some.bitbucket.server.com/rest/api/1.0/8443/projects/****/repos/****

Obviously this will result in a 404 error because your logic doesn't cater for a port being appended to the url string.

On my own personal repo I've modified this to declare this abstraction the same way you've done the rest.

```
url = new URL(repoUrl);
hostName = url.getHost();
protocol = url.getProtocol();
port = url.getPort();

String hostUrl = protocol + "://" + hostName + ":" + port;
```

Also needed to modify the substring length with +1

`String repoName = repoUrl.substring(hostUrl.length() + 1, repoUrl.length());
`

I also found bugs with the authorization header in the api call when running the makeRestCall function. I found the logic assume that decryptedPassword will originate from a encrypted password, however in my local instance I'm not encrypting my password in the UI, and therefore it will crash and leave my decryptedPassword as blank resulting in a 401 when querying the bitbucket server.

I think the problem here is the assumption all passwords will follow suit by being encrypted and forcing a decryption on that variable which is not the case. I've modified the code locally to work, however can this also be looked into and resolved?

I am also open to discussing many more things I've found that can be improved / enhanced in the repo, some being problematic in my opinion that would be higher priority, if you could DM I'll communicate further in private.

**Comment by alwaysharsha** [comment]
@xUnholy Can you please share how to deal with the decryptedPassword issue. Even i am getting a crash when i pass credentials.

**Comment by rvema** [comment]
@xUnholy Please submit a PR with the proposed changes. Closing it due to inactivity
