### ISSUE TITLE
Svn collector - Connection Refused error

### ISSUE THREAD

**Issue by Prasanna2104** [Hygieia/Hygieia#2395]
I have installed Hygieia in the Windows 8 Laptop successfully. I tried to configure my svn repository in the widget.

application.properties : 

```
# Database Name
		dbname=dashboarddb

		# Database HostName - default is localhost
		dbhost=localhost

		# Database Port - default is 27017
		dbport=27017

		# MongoDB replicaset
		#dbreplicaset=[false if you are not using MongoDB replicaset]
		#dbhostport=[host1:port1,host2:port2,host3:port3]

		# Database Username - default is blank
		#dbusername=dashboarduser

		# Database Password - default is blank
		#dbpassword=dbpassword

		# Logging File location
		logging.file=./logs/subversion.log

		# Collector schedule (required)
		subversion.cron=0 0/5 * * * *

		# Shared subversion username and password
		subversion.username=svnusername
		subversion.password=svnpassword
		subversion.host=xxx.xxx.xxx.com
		
		#proxy
		subversion.proxy=prosyhost:8080

		# Maximum number of previous days from current date, when fetching commits
		subversion.commitThresholdDays=15
```

When I start the component, getting an error message as 

> 2018-08-08 15:10:21,078 ERROR c.c.d.c.DefaultSubversionClient - Subversion repo: http://xx.xx.xx.com/svn/testing/
> org.tmatesoft.svn.core.SVNException: svn: E175002: connection refused by the server
> svn: E175002: OPTIONS request failed on '/svn/testing'
>         at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:106) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:90) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:775) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:375) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:363) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.performHttpRequest(DAVConnection.java:710) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.exchangeCapabilities(DAVConnection.java:627) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.open(DAVConnection.java:102) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.openConnection(DAVRepository.java:1032) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.getDatedRevision(DAVRepository.java:191) ~[svnkit-1.8.7.jar!/:na]
>         at com.capitalone.dashboard.collector.DefaultSubversionClient.getRevisionClosestTo(DefaultSubversionClient.java:59) ~[subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at com.capitalone.dashboard.collector.SubversionCollectorTask.startRevision(SubversionCollectorTask.java:155) [subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at com.capitalone.dashboard.collector.SubversionCollectorTask.collect(SubversionCollectorTask.java:130) [subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
>         at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
>         at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
> Caused by: java.net.ConnectException: Connection timed out: connect
>         at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_161]
>         at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_161]
>         at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_161]
>         at org.tmatesoft.svn.core.internal.util.SVNSocketFactory.connect(SVNSocketFactory.java:146) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.util.SVNSocketFactory.createPlainSocket(SVNSocketFactory.java:73) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.connect(HTTPConnection.java:281) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:438) ~[svnkit-1.8.7.jar!/:na]
>         ... 20 common frames omitted
> 2018-08-08 15:10:42,154 ERROR c.c.d.c.DefaultSubversionClient - Subversion repo: http://xx.xx.xx.com/svn/testing/
> org.tmatesoft.svn.core.SVNException: svn: E175002: connection refused by the server
> svn: E175002: OPTIONS request failed on '/svn/testing'
>         at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:106) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:90) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:775) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:375) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:363) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.performHttpRequest(DAVConnection.java:710) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.exchangeCapabilities(DAVConnection.java:627) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.open(DAVConnection.java:102) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.openConnection(DAVRepository.java:1032) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.getLatestRevision(DAVRepository.java:175) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.DAVRepository.logImpl(DAVRepository.java:972) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:1038) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:943) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:867) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:1415) ~[svnkit-1.8.7.jar!/:na]
>         at com.capitalone.dashboard.collector.DefaultSubversionClient.getHistory(DefaultSubversionClient.java:72) [subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at com.capitalone.dashboard.collector.DefaultSubversionClient.getCommits(DefaultSubversionClient.java:39) [subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at com.capitalone.dashboard.collector.SubversionCollectorTask.collect(SubversionCollectorTask.java:130) [subversion-collector-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-2.0.5-SNAPSHOT.jar!/:2.0.5-SNAPSHOT]
>         at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
>         at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_161]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_161]
>         at java.lang.Thread.run(Unknown Source) [na:1.8.0_161]
> Caused by: java.net.ConnectException: Connection timed out: connect
>         at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_161]
>         at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_161]
>         at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_161]
>         at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_161]
>         at org.tmatesoft.svn.core.internal.util.SVNSocketFactory.connect(SVNSocketFactory.java:146) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.util.SVNSocketFactory.createPlainSocket(SVNSocketFactory.java:73) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.connect(HTTPConnection.java:281) ~[svnkit-1.8.7.jar!/:na]
>         at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:438) ~[svnkit-1.8.7.jar!/:na]
>         ... 25 common frames omitted

How to fix this issue?

**Comment by Prasanna2104** [comment]
I have also started launched svn collector by passing the proxy also.

`C:\Prasanna\Hygieia-master\Hygieia-master\collectors\scm\subversion\target>java -jar subversion-collector-2.0.5-SNAPSHOT.jar -spring.config.name=subversion --spring.config.location=C:\Prasanna\Hygieia-master\Hygieia-master\collectors\scm\subversion\application.properties -Dhttp.proxyHost=xx.xx.xx.xx Dhttp.proxyPort=8080 -Dhttp.auth.preference=Basic`

But still getting Connection refused error.

**Comment by Sbrenthughes** [comment]
Closing. No user activity. Please reopen if problem persist
