### ISSUE TITLE
Failed to run task: 'gulp.js build' failed

### ISSUE THREAD

**Issue by popularmit** [Hygieia/Hygieia#2408]
[INFO] Hygieia Publisher Plugin ........................... SUCCESS [ 11.934 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [ 26.573 s]
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] FunctionalTest 2.0.5 ............................... SKIPPED
[INFO] com.capitalone.dashboard:pingdom 2.0.5-SNAPSHOT .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min
[INFO] Finished at: 2018-08-16T16:06:33+08:00
[INFO] ------------------------------------------------------------------------
**### [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:
gulp (gulp build) on project UI: Failed to run task: 'gulp.js build' failed. (er
ror code 1) -> [Help 1]**
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :UI

**Comment by rvema** [comment]
@popularmit Can you provide more details as we don't have enough information to debug this issue.

**Comment by rvema** [comment]
@popularmit As requested can you provide more details regarding the issue you are facing? If you no longer see the issue please go ahead and close the issue
