### ISSUE TITLE
Set up Jira widget through API

### ISSUE THREAD

**Issue by caiohcl** [Hygieia/Hygieia#2420]
Hey guys,

I've been unsuccessfully trying to add a Jira widget into my dashboard through hygieia api. I figured out how add build, code analysis and bitbucket widgets so far but Jira I didn't.

Following the data I've been using:
`  "featureEntries": [
  	{
    	"description": "<projectName>",
        "options": {
            "teamName": "<teamName>",
            "projectName": <projectName>",
            "projectId": <projectId>
        }, 
        "toolName": "Jira"
	}
  ],`

Does anyone know how to do it? Am I missing some field/information?

**Comment by subodhbattina** [comment]
@caiohcl Please share what error you are getting? Also, This is a sample of the "featureEntries"

```{
    "featureEntries": [ 
        { 
            "description": "<projectName>", 
            "options" : { 
                "featureTool" : "Jira", 
                "teamName" : "<teamName>", 
                "teamId" : "<teamId>", 
                "projectName" : "<projectName>", 
                "projectId" : "<projectId>", 
                "showStatus" : {
                    "kanban" : true, 
                    "scrum" : false
                }, 
                "estimateMetricType" : "storypoints", 
                "sprintType" : "scrumkanban", 
                "listType" : "epics"
            }, 
            "toolName": "Jira" 
        } 
    ]
}```

Here are the potential values for the below properties

```"estimateMetricType" : "storypoints" or  "count" or "hours"
"listType" : "epics" or "issues"
"sprintType" : "scrum" or "kanban" or "scrumkanban"
```

**Comment by caiohcl** [comment]
Hi @subodhbattina , thanks for the replay.

Actually, Hygieia doesn't pop up any error message. Instead, the widget isn't set up when I call the API. It keeps like this:

![image](https://user-images.githubusercontent.com/2295899/45563372-c0e5ae00-b812-11e8-96df-810e9cc0dfd9.png)

The weird thing is that I've been successfully set up the others widget... I've got this issue only with Jira Widget....

**Comment by subodhbattina** [comment]
Hi @caiohcl Sure, Np. Just to get some clarification, were you able to use the "featureEntries" format I shared earlier, are you still seeing this behavior with that format? Please share the exact message you have used on the call to the API. Thanks !

**Comment by caiohcl** [comment]
Hi @subodhbattina 
Sure. I've been using the following code:
```
  "featureEntries": [
  	{
    	"description": "<ProjectName>",
        "options": {
            "teamName": "<ProjectTeam>",
            "featureTool": "Jira",
            "projectName": "<ProjectName>",
            "projectId": "<ProjectId>",
            "teamId": "<TeamId>",
            "showStatus" : {
            	"kanban" : true, 
                 "scrum" : false
            },
            "estimateMetricType" : "storypoints", 
            "sprintType" : "scrumkanban", 
            "listType" : "epics"
        },
        "pushed": false,
        "toolName": "Jira"
	}
  ], 
```

**Comment by subodhbattina** [comment]
@caiohcl:
Lets do a few check here to see if the widget is created in the dashboard:
1. Pull up your hygieia dashbaord:
In the browser developer console: Look for the URL as below:

**_https://<host_name>/api/dashboard/<dashboard_id>_**

2. Make a note of the ID in the above url, go to your MongoDB dashbaord, and run the below query on the "dashboards" collection:

**Sample Query: {_id : ObjectId("<dashboard_id>")}**

3. Please check if you have widgets such as this in the document that pulls up:

**"widgets" : [
        {
            "_id" :  ObjectId("<dashboard_id>")
            "name" : "feature", 
            "componentId" : ObjectId(<component_id value>), 
            "options" : {
                "id" : "feature0", 
                "featureTool" : "Jira", 
                "teamName" : "<Team Name>", 
                "teamId" : "<team_id>", 
                "projectName" : "<project_name>", 
                "projectId" : "<project_id>", 
                "showStatus" : {
                    "kanban" : true or false, 
                    "scrum" : true or false
                }, 
                "estimateMetricType" : "storypoints", 
                "sprintType" : "scrumkanban", 
                "listType" : "epics"
            }
        }
    ]**

4. Please make a note of the "projectId" and the "teamId" from the document above from MongoDB.

5. And then, in your mongo db, in the "feature" collection, see what data you have for that teamId and projectId

**Sample Query: { "sProjectID": "<projectId>", $and: [ { "sTeamID": "<teamId>" } ] }**

**Comment by subodhbattina** [comment]
@caiohcl : If you are not seeing the data in MongoDB, please share the API logs from when added the Jira widget. We wont to see if there were any error or exceptions at all in the api when you tried to add the widget. Thanks

**Comment by subodhbattina** [comment]
@caiohcl: Following up to check if you have any updates on this at all? Thanks

**Comment by caiohcl** [comment]
Hi @subodhbattina... I'm out of office until Friday. I'll get back to you when I get the information. Thanks for your help.

**Comment by subodhbattina** [comment]
@caiohcl: Sounds Good. Thanks !

**Comment by caiohcl** [comment]
Hi @subodhbattina 
I checked API and JIRA logs, and there's no exception or error message. Also, there's no data regarding JIRA widget into the database.

```
{
    "_id": "5ba515b04cedfd00074d1559",
    "_class": "com.capitalone.dashboard.model.Dashboard",
    "template": "Testing",
    "title": "New Dashboard Through Jenkins",
    "widgets": [
        {
            "_id": "5ba515b04cedfd00074d155b",
            "name": "build",
            "componentId": "5ba515b04cedfd00074d1558",
            "options": {
                "buildDurationThreshold": 3,
                "id": "build0",
                "consecutiveFailureThreshold": 5
            }
        },
        {
            "_id": "5ba515b04cedfd00074d155c",
            "name": "codeanalysis",
            "componentId": "5ba515b04cedfd00074d1558",
            "options": {
                "testJobNames": [
                    ""
                ],
                "id": "codeanalysis0"
            }
        },
        {
            "_id": "5ba515b04cedfd00074d155d",
            "name": "repo",
            "componentId": "5ba515b04cedfd00074d1558",
            "options": {
                "password": "<pwd>",
                "name": "repo",
                "id": "repo0",
                "scm": {
                    "name": "Bitbucket",
                    "value": "Bitbucket"
                },
                "userID": "<user>",
                "branch": "<branch>",
                "url": "<bitbucket url>"
            }
        }
    ],
    "owners": [
        {
            "username": "<user>",
            "authType": "STANDARD"
        }
    ],
    "type": "Team",
    "application": {
        "name": "New Dashboard Through Jenkins",
        "components": [
            {
                "$ref": "components",
                "$id": "5ba515b04cedfd00074d1558",
                "$db": ""
            }
        ]
    },
    "validServiceName": false,
    "validAppName": false,
    "remoteCreated": false,
    "scoreEnabled": false,
    "scoreDisplay": "HEADER",
    "activeWidgets": []
}
```
and the only message that appears in api log file is 
`2018-09-21 16:23:44,045 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:31, serverValue:102}] to mongodb:27017

2018-09-21 16:25:16,921 INFO  org.mongodb.driver.connection - Closed connection [connectionId{localValue:26, serverValue:87}] to mongodb:27017 because it is past its maximum allowed idle time.
`

**Comment by subodhbattina** [comment]
@caiohcl: Clearly the Feature Widget has not been created from the database document you have shared. Can you please send me the entire "post" payload you are using to create the widget? You may be missing some thing in there. Here's a sample payload to create the dashboard: 
```{
    "codeRepoEntries": [],
    "functionalTestEntries": [],
    "buildEntries": [],
    "libraryScanEntries": [],
    "securityScanEntries": [],
    "staticCodeEntries": [],
    "featureEntries": [ 
        { 
            "description": "<projectName>", 
            "options" : { 
                "featureTool" : "Jira", 
                "teamName" : "<teamName>", 
                "teamId" : "<teamId>", 
                "projectName" : "<projectName>", 
                "projectId" : "<projectId>", 
                "showStatus" : {
                    "kanban" : true, 
                    "scrum" : false
                }, 
                "estimateMetricType" : "storypoints", 
                "sprintType" : "scrumkanban", 
                "listType" : "epics"
            }, 
            "toolName": "Jira" 
        } 
    ],
    "deploymentEntries": [],
    "metaData": {
       "template": "<Template>",
       "title": "<Title>",
       "type": "Team",
       "applicationName": "<Application Name>",
       "componentName": "<ComponentName>",
       "businessService": "<ApplicationName>",
       "businessApplication": "<ComponentName>",
       "owner": {
           "username": "<UserName>",
           "authType": "STANDARD or LDAP depending on what you use for the user name"
       }
    }
}```

**Comment by subodhbattina** [comment]
@caiohcl: Do you have any other questions, or can we go ahead and close this issue, please let me know ? Thanks !

**Comment by caiohcl** [comment]
@subodhbattina 

Following the entire body used on the API call.

By the way, I've been calling this API: `<hygieia_url>/api/dashboard/remoteCreate`

```
  "buildEntries": [
    {
      "description": "<job name>",
      "options": {
         "instanceUrl": "<jenkins url>",
         "jobName": "<job name>",
         "jobUrl": "<job url>"
         },
      "pushed": false,
      "toolName": "Hudson"
    }
  ],
  "staticCodeEntries":[
    {
      "description": "<job name> (<job url>)",
      "options": {
          "jobName": "<job name>",
          "jobUrl": "<job name>",
          "instanceUrl": "<job url>"
      },
      "pushed": false,
      "toolName":"JenkinsCodeQuality"
    }
  ],
  "featureEntries": [
  	{
    	"description": "<project name>",
        "options": {
        	"teamName": "<project team>",
            "featureTool": "Jira",
            "projectName": "<project name>",
            "projectId": "<project id>",
            "teamId": "<team id>",
            "showStatus" : {
            	"kanban" : true, 
              "scrum" : false
            },
            "estimateMetricType" : "storypoints", 
            "sprintType" : "scrumkanban", 
            "listType" : "epics"
        },
        "pushed": false,
        "toolName": "Jira"
	}
  ],        
  "codeRepoEntries": [
    {
      "description": "<repo name>",
      "options": {
         "password": "<pwd>",
         "userID": "<user>",
         "url": "<repo url>",
         "branch": "<branch>"
       },
      "pushed": false,
      "toolName": "Bitbucket"
    }
  ],
  "metaData": {
    "applicationName": "<dashboard name>",
    "componentName": "<dashboard name>",
    "owner": {
      "authType": "STANDARD",
      "username": "admin"
    },
    "template": "<template>",
    "title": "<dashboard name>",
    "type": "team"
  }
}' 
```

**Comment by subodhbattina** [comment]
@caiohcl: Ok, let me run this, and see what might be happening, thanks.

**Comment by subodhbattina** [comment]
@caiohcl Thanks for bringing this to our notice, we'll work on fixing this and get back to you. Thanks !

**Comment by caiohcl** [comment]
@subodhbattina, no problem.
Do you have any idea of how long is this fix gonna take to be deployed on master? 
Also, let me know if you need help.

**Comment by caiohcl** [comment]
Hey guys.. any update regarding the fix of this issue?  Thanks!!!

**Comment by caiohcl** [comment]
thanks for the replay @divashdr ! I'm gonna test it and let you know the result.

**Comment by Sbrenthughes** [comment]
Could you contribute that back these changes in a pr?

**Comment by divashdr** [comment]
yes @Sbrenthughes . Thanks

**Comment by divashdr** [comment]
@Sbrenthughes 
As discussed, here is the PR created to address this issue. Please review and merge as per. Thanks

https://github.com/Hygieia/Hygieia/pull/2545

**Comment by divashdr** [comment]
@Sbrenthughes 
Would you please review and merge the PR? Thanks

**Comment by subodhbattina** [comment]
@caiohcl My sincere apologies for not being able to get back to this until now. I did make the changes to fix the issue, and have submitted a PR. I am following up on it.

@divashdr Thanks for your interest, really appreciate it. Since it involved a couple more changes, I went ahead and took care of if for now, thanks again !

**Comment by caiohcl** [comment]
Hey guys,
Sorry for the late reply. I've been testing the changes proposed by @divashdr, however I'm still not able to remotely create this widget. 
I had changed the code, rebuilt API, rebuilt core, rebuilt the container... but I'm getting an error message that states "Jira collector does not support field: teamName". 
I used the same call as @divashdr shared with us btw.
Any ideas?

**Comment by subodhbattina** [comment]
@caiohcl : Bear with us please, working on getting the changes reviewed and merged at this point. Thanks

**Comment by divashdr** [comment]
@caiohcl 
To Find the teamid and projectid details

**TEAM**
![image](https://user-images.githubusercontent.com/6540984/49074070-c2efc400-f1e8-11e8-87dc-57eb28a94d5a.png)

**PROJECT**
![image](https://user-images.githubusercontent.com/6540984/49074093-ce42ef80-f1e8-11e8-94ac-328dade59eb0.png)

Add the above details to the payload request

"featureEntries":[
      {

         "toolName":"Jira",
         "description":"EBS: WFT: Engineering and Architecture(ENA)",
         "pushed":false,
         "options":{
            "teamName":"ENA",
            "featureTool":"Jira",
             "projectName" : "EBS: WFT: Engineering and Architecture(ENA)",
             "projectId" : "1542658246090",
             "teamId" : "1542658246085",
             "estimateMetricType":"count",
             "listType":"issues",
			 "sprintType" : "kanban", 
              "showStatus" : {
                    "kanban" : true,
                    "scrum" : false
                }
         }
      }
   ],

![image](https://user-images.githubusercontent.com/6540984/49073944-71dfd000-f1e8-11e8-9e6e-552e0936a868.png)

![image](https://user-images.githubusercontent.com/6540984/49073999-9b006080-f1e8-11e8-9992-05c5a42793db.png)

**Comment by caiohcl** [comment]
Hey guys, I forgot to change a file. I did it, and it's working now.
@divashdr and @subodhbattina, I really appreciate your help guys!!

**Comment by subodhbattina** [comment]
@caiohcl You are Welcome !
@divashdr and @caiohcl , Thanks for reaching out and your interest, and for your patience.
