### ISSUE TITLE
hygeia artifactory collector

### ISSUE THREAD

**Issue by slkumar969** [Hygieia/Hygieia#2428]
@MarkRx  2018-09-06 13:40:00,014 INFO  c.c.d.collector.CollectorTask - Running Collector: Artifactory
2018-09-06 13:40:00,081 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:6340}] to 10.106.131.79:31996
2018-09-06 13:40:00,182 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-06 13:40:00,182 INFO  c.c.d.collector.CollectorTask - http://10.106.131.18:8018/
2018-09-06 13:40:00,182 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-06 13:40:00,668 ERROR c.c.d.c.DefaultArtifactoryClient - Error with REST url: http://10.106.131.18:8018/api/repositories()
2018-09-06 13:40:00,669 ERROR c.c.d.c.DefaultArtifactoryClient - 404 Not Found
2018-09-06 13:40:00,684 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
![error](https://user-images.githubusercontent.com/30686328/45160002-f2a0b880-b205-11e8-9e75-4ea6f6e67e55.JPG)

my inputs for the hygieia collector 

MONGODB_HOST: 10.106.131.79
MONGODB_PORT: 31996

===========================================
Properties file created Thu Sep  6 13:35:44 UTC 2018:  /hygieia/config/application.properties
Note: passwords hidden
===========================================
#Database Name
dbname=dashboarddb

#Database HostName - default is localhost
dbhost=10.106.131.79

#Database Port - default is 27017
dbport=31996

#Database Username - default is blank
dbusername=dashboarduser

#Collector schedule (required)
artifactory.cron=0 0/5 * * * *

#Artifactory server (required) - Can provide multiple
artifactory.servers[0]=

#Artifactory user name (required)
artifactory.usernames[0]=admin

#Artifactory api key (required)
artifactory.apiKeys[0]=bcf4caf8-e617-467c-8cd7-fcdb70b5c8ff

#The repos to collect artifacts from (required) - Can provide multiple (comma separated for each server)
artifactory.repos[0]=Jenkins-integration,Jenkins-integration-2

# Artifact Regex Patterns
# Each artifact found is matched against the following patterns in order (first one wins)
# The following capture groups are available:
#  - group
#  - module
#  - artifact
#  - version
#  - classifier
#  - ext
artifactory.patterns[0]=(?<group>.+)/(?<module>[^/]+)/(?<version>[^/]+)/(?<artifact>\k<module>)-\k<version>(-(?<classifier>[^\.]+))?(\.(?<ext>.+))?

# Artifactory urls and credentials
artifactory.servers[0]=http://10.106.131.18:8018/
artifactory.usernames[0]=admin
artifactory.apiKeys[0]=bcf4caf8-e617-467c-8cd7-fcdb70b5c8ff
artifactory.repos[0]=Jenkins-integration,Jenkins-integration-2

# Artifactory REST endpoint
artifactory.endpoint=artifactory/

though i have given all the details properly the i can see the URL access issue

and one more thing please give a small meaning statement for the three values which i am not understanding.

artifactory.repos[0] 
artifactory.endpoint
artifactory.patterns[0]

i will be very thankfull to you if you help me on this

**Comment by subodhbattina** [comment]
slkumar969: The issue in this case is that the artifactory server Url (http://10.106.131.18:8018/) is not reachable. Make sure that server (the one you have configured with artifactory.servers[0] in your properties file) is up and running, and the endpoint http://10.106.131.18:8018/api/repositories is reachable. Thanks.

**Comment by battinasubodh** [comment]
slkumar969: Do you have any updates on this, hoping we have answered your question, please let us know. Thanks !

**Comment by subodhbattina** [comment]
@slkumar969: Following up on this again, just checking to see if you have any more questions at all, and if this issue is resolved at your end. Thanks.

**Comment by slkumar969** [comment]
@subodhbattina  thanks for your response but as you said i have given the correct details and they are working fine the artifactory URL it is running as a docker container and it is reachable.
on other hand  i am runnind this hygieia service as a pod in kubernets where i suppose to pass the env variables from the deployment same alike docker while running the container. here i found few env variables were mandatory to pass where i did not get proper understanding in its usage please help me out in describing from below image.


![error1](https://user-images.githubusercontent.com/30686328/45360697-04130780-b5ee-11e8-8aea-1f152ca81d09.JPG)


after the container got up i can see the log like

2018-09-06 13:40:00,081 INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:6340}] to 10.106.131.79:31996
2018-09-06 13:40:00,182 INFO c.c.d.collector.CollectorTask - -----------------------------------
2018-09-06 13:40:00,182 INFO c.c.d.collector.CollectorTask - http://10.106.131.18:8018/
2018-09-06 13:40:00,182 INFO c.c.d.collector.CollectorTask - -----------------------------------
2018-09-06 13:40:00,668 ERROR c.c.d.c.DefaultArtifactoryClient - Error with REST url: http://10.106.131.18:8018/api/repositories()
2018-09-06 13:40:00,669 ERROR c.c.d.c.DefaultArtifactoryClient - 404 Not Found
2018-09-06 13:40:00,684 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.



where i can reach the http://10.106.131.18:8018/artifactory/webapp/#/home
properly by accessing the link seperately. while in the case of container logs the container failing to access the URL  and  as u said i have tried giving the details of the url like http://10.106.131.18:8018/api/repositories but this format i cannot access with container log as well as in browser you can find in below image

![error2](https://user-images.githubusercontent.com/30686328/45361070-f0b46c00-b5ee-11e8-8c70-a5267d45e8af.JPG)



many thanks in advance please give some suggestions.....!
awaiting for you valuable answers..............!

**Comment by subodhbattina** [comment]
@slkumar969 : I am not super familiar with docker or kubernetes, I am working towards gaining that knowledge. But, have you configured your container to use proxy if you have one?

**Comment by subodhbattina** [comment]
@slkumar969 Did you get a chance to check your proxy settings at all? Thanks !

**Comment by subodhbattina** [comment]
@slkumar969 Following up again, just wanted to rule out any proxy configuration related errors, please confirm that you have these in place. Thanks

**Comment by subodhbattina** [comment]
@slkumar969 : Since we didn't hear back from you, assuming this issue is resolved at your end, and therefore closing it out. Thanks !
