### ISSUE TITLE
Deploy package name in Pipeline view

### ISSUE THREAD

**Issue by mohit1606** [Hygieia/Hygieia#2435]
Hello,

We have two scenarios mentioned below:

1. We are using Hygieia plugin 1.2 in few of jenkins instances. In the pipeline view of Hygieia for the deploy jobs we are getting the data like:

                                   ENV1                               ENV2
                               Package1.zip                Package2.zip\
Image:
![image](https://user-images.githubusercontent.com/22495710/45546771-e63ae200-b83b-11e8-9faf-131ba2f00ee9.png)

Means the environment name in the column and the package deployed in them below that. 

2. But for the other jenkins instances we are using the plugin version 1.3 and the result in the pipeline view is like:

                                            ENV1                                                               ENV2

Package1.zp            (only time of deployments)                         (only time of deployments)

Package2.zip            (only time of deployments)                        (only time of deployments)

Image:

![image](https://user-images.githubusercontent.com/22495710/45546128-02d61a80-b83a-11e8-9c62-26e58e4c8214.png)

That means environment name but below instead of deployed package it is only displaying the time.
So would like to know whether there's any difference in the pipeline view while using the different plugins?

**Comment by subodhbattina** [comment]
@mohit1606 : I am looking at the DeployController that the HygieiaPublisher calls, and it does look like the latest version of the API returns List of Environments with their last execution time stamps. Please let me know if you have any other questions. Thanks !

**Comment by subodhbattina** [comment]
@mohit1606: If you don't have any other question, I would like to go ahead and close this issue, please let me know. Thanks !

**Comment by subodhbattina** [comment]
@mohit1606: Closing this issue, thanks !
