### ISSUE TITLE
Provide Document for Monitoring widget

### ISSUE THREAD

**Issue by mohit1606** [Hygieia/Hygieia#2455]
Hello,
Request you to provide me the document regarding setting up the Hygieia service monitoring dashboard. Am not getting any option of adding any service to this monitoring view.

![image](https://user-images.githubusercontent.com/22495710/46067112-ae189500-c193-11e8-878d-a279cb3ba4f7.png)

**Comment by Sbrenthughes** [comment]
You have to click the gear option and add a url to be monitored.
