### ISSUE TITLE
Error showing information on dashboard deploy widget 

### ISSUE THREAD

**Issue by gars01** [Hygieia/Hygieia#2456]
I have seen an error showing the
information in the widget of the deployments. When I click on a display, it shows something like this

![image](https://user-images.githubusercontent.com/33869302/46081377-a7425000-c19c-11e8-8bfb-09b5bf548aca.png)

The labels are not in the correct order with respect to the data. 

Some help? Thanks in advance

**Comment by Sbrenthughes** [comment]
Closing as this is a duplicate. See https://github.com/Hygieia/Hygieia/issues/2056
