### ISSUE TITLE
Hygieia installation setup help required

### ISSUE THREAD

**Issue by sandipkarande** [Hygieia/Hygieia#2461]
I have cloned the hygieia on my ubuntu machine. I am trying to execute mvn install clean packge however getting below errors. Please provide help to fix this issue. I really appreciate quick and response. Thanks.

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.jenkins-ci.plugins:hygieia-publisher:2.1.3-SNAPSHOT (/home/osgdev/sandip_lab/hygieia/Hygieia-master/hygieia-jenkins-plugin/pom.xml) points at com.capitalone.dashboard:Hygieia instead of org.jenkins-ci.plugins:plugin, please verify your project structure @ line 15, column 13
[FATAL] Non-resolvable parent POM for org.jenkins-ci.plugins:hygieia-publisher:2.1.3-SNAPSHOT: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:1.609.2 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Connection reset and 'parent.relativePath' points at wrong local POM @ line 15, column 13
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead. @ 
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: javax.validation:validation-api:jar -> duplicate declaration of version 1.1.0.Final @ com.capitalone.dashboard:api-audit:[unknown-version], /home/osgdev/sandip_lab/hygieia/Hygieia-master/api-audit/pom.xml, line 252, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.hibernate:hibernate-validator:jar -> duplicate declaration of version (?) @ com.capitalone.dashboard:api-audit:[unknown-version], /home/osgdev/sandip_lab/hygieia/Hygieia-master/api-audit/pom.xml, line 257, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.code.gson:gson:jar -> duplicate declaration of version (?) @ com.capitalone.dashboard:api-audit:[unknown-version], /home/osgdev/sandip_lab/hygieia/Hygieia-master/api-audit/pom.xml, line 261, column 21
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead. @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:hygieia-publisher:2.1.3-SNAPSHOT (/home/osgdev/sandip_lab/hygieia/Hygieia-master/hygieia-jenkins-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.jenkins-ci.plugins:hygieia-publisher:2.1.3-SNAPSHOT: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:1.609.2 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Connection reset and 'parent.relativePath' points at wrong local POM @ line 15, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by matthewbeasley** [comment]
@sandipkarande - try running `mvn clean install` from the root directory of your project. My guess is that you are running this from the hygieia-jenkins-plugin directory before you have built the Hygieia core.

**Comment by sandipkarande** [comment]
While executing mvn clean install package , buid fails. It gives below error

[ERROR] Failed to execute goal on project hygieia-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:hygieia-publisher:hpi:2.1.3-SNAPSHOT: The following artifacts could not be resolved: org.jenkins-ci.main:jenkins-war:war:1.609.2, org.jenkins-ci.main:jenkins-war:jar:war-for-test:1.609.2: Could not transfer artifact org.jenkins-ci.main:jenkins-war:war:1.609.2 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): GET request of: org/jenkins-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2.war from repo.jenkins-ci.org failed: Premature end of Content-Length delimited message body (expected: 68976099; received: 33440096 -> [Help 1]

I understood that it is because of following files no more exists at respective locations. I checked by hitting those URL's in browser and download fails.
Downloading from central: https://repo.maven.apache.org/maven2/org/jenkins-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2.war
Downloading from central: https://repo.maven.apache.org/maven2/org/jenkins-ci/main/jenkins-war/1.609.2/jenkins-war-1.609.2-war-for-test.jar

Please suggest how to fix this. Will really appreciate your quick help. Thanks !! @matthewbeasley @rvema

**Comment by sandipkarande** [comment]
can someone knows solution to this problem ? In case I get these files from other sources , where should I place those jenkins-war-1.609.2.war & jenkins-war-1.609.2-war-for-test.jar files ? Please provide exact location. I am new to Maven.. will really appreciate quick help thanks !!
