### ISSUE TITLE
No Data on Product Dashboard for environments

### ISSUE THREAD

**Issue by shardulsrivastava** [Hygieia/Hygieia#2462]
I am not getting any data for product dashboard in environments.

<img width="1219" alt="screen shot 2018-09-28 at 2 50 18 pm" src="https://user-images.githubusercontent.com/9951135/46192539-05526d00-c32e-11e8-9266-e5205add8651.png">

However i can see the data on the pipeline view : 

<img width="1425" alt="screen shot 2018-09-28 at 2 52 30 pm" src="https://user-images.githubusercontent.com/9951135/46192582-27e48600-c32e-11e8-8d6d-8ac4167d951b.png">

I figured from the code that for environment ,it gets the artifacts to show on the products dashboard from the artifact table : 
Reference of the code : 
Class DynamicPipelineServiceImpl  
Flow: 
search() -> buildPipeline() -> processDeployments() -> 
```
   		if (env.getUnits() != null) {
    			for (DeployableUnit du : env.getUnits()) {
    				ArtifactIdentifier id = new ArtifactIdentifier(null, du.getName(), du.getVersion(),null, null);
    				
    				Collection<BinaryArtifact> tmp = artifacts.get(id);
    				if (tmp != null && !tmp.isEmpty()) {
    					artifact = tmp.iterator().next();
    					deployableUnit = du;
    					break;
    				}
    			}
    		}
```

here product view gets the artifacts from the artifacts collection and if we are not using any artifacts collector ( my case) then this will be empty.

**Comment by Sbrenthughes** [comment]
if you are using Jenkins for your build you can using the plugin to push the artifact data easily.

**Comment by shardulsrivastava** [comment]
@Sbrenthughes i am not using jenkins but wrote a custom collector for cloud based CI called Buildkite.
anyways i have modified the code to get it working.

**Comment by shardulsrivastava** [comment]
@Sbrenthughes  the data m getting on the product dashboard for the environments, is not right, coz our builds automatically promote the code to the dev environments and then wait for the user input before promoting them further .

<img width="1395" alt="screen shot 2018-10-03 at 12 46 25 am" src="https://user-images.githubusercontent.com/9951135/46363539-e7766680-c6a5-11e8-821f-e35828963cfe.png">

hence data in  COMMIT,BUILD,DEV should be in mins.
Any idea where can i look in the code for the issue.

As i can see that these details are being calculated from the timestamps with respect to the stages 

<img width="719" alt="screen shot 2018-10-03 at 12 49 46 am" src="https://user-images.githubusercontent.com/9951135/46363687-489e3a00-c6a6-11e8-8bcd-3168f6fdc2a9.png">


these timestamps are being calculated for each commit after getting the deployable units for every environment of the component : 
getEnvironments -> deployService.getDeployStatus -> getDeployStatus() -> Deployable Units are added from environment_component and environment_status tables.

Now assuming that there is only one deployment collector then there will be only one deployable unit for every environment of a component, that too will be the latest deployment i.e deployable unit.

now is it correct to calculate the stage timestamps based on the latest deployment , rather than calculating it based on the deployments for that commit.

**Comment by yuhong02** [comment]
@shardulsrivastava I saw you above screenshot, PROD stage is the information I want, could you please tell me how to configure to get the information? My PROD stage information is similar as your DEV stage.

**Comment by rvema** [comment]
closing the issue due to inactivity
