### ISSUE TITLE
Empty "Repo Type" in the :Configure Code Repo Widget:

### ISSUE THREAD

**Issue by thuyvu45** [Hygieia/Hygieia#2465]
Latest code from Hygieia (3.0).  I have Bitbucket collector run with the following configuration.  Am I missing something?

///////////////

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/bitbucket.log

# Collector schedule (required)
git.cron=0 */1 * * * *

# Mandatory parameters
git.host=api.bitbucket.org
git.api=/2.0/repositories/

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls
#   Only applicable to Bitbucket Server.
#   Only applicable to Bitbucket Cloud.
git.pageSize=25

# Bitbucket product
#   Set to 'cloud' to use Bitbucket Cloud (formerly known as Bitbucket)
#   Set to 'server' to use Bitbucket Server (formerly known as Stash)
#   More information can be found here:	
git.product=cloud
# Bitbucket key for private repos
bitbucket.key=1hr3x6fvgOnH8dwQWJQIaBpFAoqdjJtA
git.key=1hr3x6fvgOnH8dwQWJQIaBpFAoqdjJtA

//////////////////////

Log from collector: 

2018-09-29 16:54:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-29 16:54:00,009 INFO  c.c.d.collector.CollectorTask - Starting...
2018-09-29 16:54:00,009 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-29 16:54:00,013 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2018-09-29 16:54:00,013 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2018-09-29 16:54:00,014 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-29 16:55:00,007 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2018-09-29 16:55:00,014 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-29 16:55:00,015 INFO  c.c.d.collector.CollectorTask - Starting...
2018-09-29 16:55:00,015 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-29 16:55:00,017 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2018-09-29 16:55:00,018 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2018-09-29 16:55:00,018 INFO  c.c.d.collector.CollectorTask - Finished                         0s
2018-09-29 16:56:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2018-09-29 16:56:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-29 16:56:00,008 INFO  c.c.d.collector.CollectorTask - Starting...
2018-09-29 16:56:00,008 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-09-29 16:56:00,012 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2018-09-29 16:56:00,012 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2018-09-29 16:56:00,012 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by thuyvu45** [comment]
Here is the query from mongodb:

> db.collectors.find()
{ "_id" : ObjectId("5bae4b5087f65abfb841b159"), "_class" : "com.capitalone.dashboard.model.HudsonCollector", "buildServers" : [ "http://localhost:7070" ], "niceNames" : [ ], "environments" : [ ], "name" : "Hudson", "collectorType" : "Build", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "jobName" : "", "jobUrl" : "" }, "allFields" : { "jobName" : "", "jobUrl" : "", "instanceUrl" : "" }, "lastExecuted" : NumberLong("1538149200236"), "searchFields" : [ "options.jobName", "niceName" ] }
{ "_id" : ObjectId("5bae500087f65ac3b6ea9d93"), "_class" : "com.capitalone.dashboard.model.Collector", "name" : "Bitbucket", "collectorType" : "SCM", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "branch" : "", "url" : "" }, "allFields" : { "lastUpdateCommit" : "", "password" : "", "lastUpdate" : ISODate("2018-09-29T20:59:00.007Z"), "branch" : "", "userID" : "", "url" : "" }, "lastExecuted" : NumberLong("1538254740015"), "searchFields" : [ "description" ] }
{ "_id" : ObjectId("5bae525887f65ac4bbb17523"), "_class" : "com.capitalone.dashboard.model.RallyCollector", "rallyServers" : [ ], "name" : "Rally", "collectorType" : "AgileTool", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : {  }, "allFields" : {  }, "lastExecuted" : NumberLong("1538167200026"), "searchFields" : [ "description" ] }

**Comment by Sbrenthughes** [comment]
From your query I do not see a repo added

**Comment by thuyvu45** [comment]
Hi Sbrenthughes,

Thanks for getting back to me. Yes it does exist.

So I'm not sure what else is wrong.

Thanks

Phi



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by thuyvu45** [comment]
Attached is the screen captured.


Thanks


Phi


________________________________

**Comment by Sbrenthughes** [comment]
You are pulling from master for the code?

**Comment by thuyvu45** [comment]
Yes I clone the latest code from master.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by thuyvu45** [comment]
See attachments ...


________________________________

**Comment by thuyvu45** [comment]
This is the version that I have: 2.0.5-SNAPSHOT.  Thanks


________________________________

**Comment by Sbrenthughes** [comment]
I don't see any attachments on this thread.

**Comment by thuyvu45** [comment]
<img width="605" alt="screen shot 2018-10-01 at 12 28 27 pm" src="https://user-images.githubusercontent.com/38365153/46314942-0091f100-c59a-11e8-8a64-b4e334f622bf.png">
<img width="599" alt="screen shot 2018-10-01 at 1 45 43 pm" src="https://user-images.githubusercontent.com/38365153/46314963-1b646580-c59a-11e8-8ebd-ddd3a712911e.png">

**Comment by thuyvu45** [comment]
Attached screen captured

**Comment by thuyvu45** [comment]
DB does return one SCM type.  However, Rest call: http://localhost:3000/api/collector/item/type/SCM returns empty result "[]"

See below for db:

> db.collectors.find({ "collectorType" : "SCM"})
{ "_id" : ObjectId("5bb24a2058dd28234bf2a361"), "_class" : "com.capitalone.dashboard.model.Collector", "name" : "Bitbucket", "collectorType" : "SCM", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "branch" : "", "url" : "" }, "allFields" : { "lastUpdateCommit" : "", "password" : "", "lastUpdate" : ISODate("2018-10-02T00:40:00.006Z"), "branch" : "", "userID" : "", "url" : "" }, "lastExecuted" : NumberLong("1538440800178"), "searchFields" : [ "description" ] }
>

**Comment by thuyvu45** [comment]
Hi Sbrenthughes,

Any update on this?

Thanks

Phi

**Comment by Sbrenthughes** [comment]
Try `/api/collector/type/scm` this works for me but `/api/collector/item/type/SCM` doesn't

**Comment by thuyvu45** [comment]
Close this issue since it is resolved.  I've mistake in the API configuration where it points to different mongodb instance than the one used by the collectors.

**Comment by MilindDivre** [comment]
@thuyvu45  can you please let me know which Db should API configuration point to?

**Comment by thuyvu45** [comment]
Hi there,

The tool is designed to work with mongodb only. So you need to install mongodb and configure it first.

Thanks

Phi


Sent from my Samsung Galaxy smartphone.


-------- Original message --------
