### ISSUE TITLE
Unable to see deployment history/frequency in deploy widget(XL Deploy)

### ISSUE THREAD

**Issue by arunmk108** [Hygieia/Hygieia#2469]
Anyone please help on the below issue.
Iam able to display latest deployment in deploy widget(used for XL deploy) but iam unable to see last n deployments history. Its listing only latest deployment. Can anyone suggest why its not displaying deployment history for XL deploy.
![image](https://user-images.githubusercontent.com/28533803/46341724-f65a0c00-c606-11e8-8d29-b38443ebcd64.png)

Arun Mulka,
mail2arunmk@gmail.com

**Comment by shardulsrivastava** [comment]
@arunmk108 deploy widget doesn't show the deployment history, it only shows the latest deployment as mentioned here in the documentation https://hygieia.github.io/Hygieia/widget_view.html#what-information-is-displayed-on-the-widget-4
