### ISSUE TITLE
Gitlab SCM 401 unauthorized

### ISSUE THREAD

**Issue by nurhannankhairi** [Hygieia/Hygieia#2473]
Hi team. 

I currently configured Gitlab SCM on Hygieia for REPO WIDGET
However, when I run the JAR file, it shows:

Failed to retrieve data, the repo or collector is most likey misconfigured: http://XX.XX.XX.XXX/YMCA/Ytlc-Ymca, 401 Unauthorized
2018-10-03 17:38:00,098 INFO  c.c.d.collector.CollectorTask - Repo Count              1        0s
2018-10-03 17:38:00,100 INFO  c.c.d.collector.CollectorTask - New Commits          0        0s
2018-10-03 17:38:00,100 INFO  c.c.d.collector.CollectorTask - Finished                              0s

this is my properties file:

		# Database Name
		dbname=dashboarddb

		# Database HostName - default is localhost
		dbhost=localhost

		# Database Port - default is 27017
		dbport=27017

		# MongoDB replicaset
		dbreplicaset=[false if you are not using MongoDB replicaset]
		dbhostport=[host1:port1,host2:port2,host3:port3]

		# Database Username - default is blank
		dbusername=admin

		# Database Password - default is blank
		dbpassword=adminpassword

		# Logging File location
		logging.file=./logs/gitlab.log

		#Collector schedule (required)
		gitlab.cron=0 0/1 * * * *

		#Gitlab host (optional, defaults to 'gitlab.com')
		gitlab.host=XX.XX.XX.XXX
		  
		#Gitlab protocol (optional, defaults to 'http')
		gitlab.protocol=http

		#Gitlab port (optional, defaults to protocol default port)
		gitlab.port=80

		#Gitlab path (optional, if your instance of gitlab requires a path)
		#gitlab.path=/gitlab/resides/here
		gitlab.path=/YMCA/Ytlc-Ymca.git
		
		#If your instance of Gitlab is using a self-signed certificate, set to true, default is false
		gitlab.selfSignedCertificate=false

		#Gitlab API Token (required, user token the collector will use by default, can be overridden on a per repo basis from the UI. API token provided by Gitlab)
		gitlab.apiToken=XXXXXXXXXXXXXXXXXX
     
		#Maximum number of previous days from current date, when fetching commits
		gitlab.commitThresholdDays=15
		
		# Gitlab key for private repos
		gitlab.key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	
	

for your info, this is internal repo.
help me..

**Comment by Sbrenthughes** [comment]
`gitlab.path=/YMCA/Ytlc-Ymca.git` matches the repo you  are trying to collect from. I am not completely sure how gitlab works specifically but I am thinking this may not be the right path.

**Comment by nurhannankhairi** [comment]
> `gitlab.path=/YMCA/Ytlc-Ymca.git` matches the repo you are trying to collect from. I am not completely sure how gitlab works specifically but I am thinking this may not be the right path.

the path is correct as the URL for Gitlab is: http://XX.XX.XX.XXX/YMCA/Ytlc-Ymca.git

**Comment by Sbrenthughes** [comment]
After looking at the code, I don't believe the path is correct. If you look at the method `buildApiUrl` in https://github.com/Hygieia/Hygieia/blob/40b4242e2740b3b0bbc4aba4aaabb087e99dcbff/collectors/scm/gitlab/src/main/java/com/capitalone/dashboard/gitlab/GitlabUrlUtility.java, you will see that the path is used to construct the api url. 

Now I may be wrong but to me it doesn't make sense the the api url would be `http://XX.XX.XX.XXX/YMCA/Ytlc-Ymca.git/api/V4/Ytlc-Ymca/repository/commits/... etc`

**Comment by nurhannankhairi** [comment]
where to get the path Sir?

**Comment by nurhannankhairi** [comment]
![image](https://user-images.githubusercontent.com/26562484/46591173-8a3a4500-caeb-11e8-803f-417f8f2f7d89.png)
I can access the repo.

**Comment by Sbrenthughes** [comment]
Have you tried no path?

**Comment by nurhannankhairi** [comment]
yes I have tried. and it still shows 401 unauthorized.

**Comment by Sbrenthughes** [comment]
Does `gitlab.key=` match your match the `key=` in your api properties

**Comment by Sbrenthughes** [comment]
This is what I did to test:
1) find a public repo with a master branch that has been updated within the last 14 days
2) configure widget to point to that repo
3) properties:

`dbname=dashboarddb
dbhost=localhost
dbport=27017
#Collector schedule (required)
gitlab.cron=0/10 * * * * *

#Gitlab host (optional, defaults to 'gitlab.com')
gitlab.host=gitlab.com

#Gitlab protocol (optional, defaults to 'http')
gitlab.protocol=https

#Gitlab port (optional, defaults to protocol default port)
#gitlab.port=80

#Gitlab path (optional, if your instance of gitlab requires a path)
gitlab.path=

#If your instance of Gitlab is using a self-signed certificate, set to true, default is false
gitlab.selfSignedCertificate=false

#Gitlab API Token (required, user token the collector will use by default, can be overridden on a per repo basis from the UI. API token provided by Gitlab)
gitlab.apiToken=

#Maximum number of previous days from current date, when fetching commits
gitlab.commitThresholdDays=15

# Gitlab key for private repos
#gitlab.key=`

**Comment by nurhannankhairi** [comment]
yes my repo is public.

**Comment by nurhannankhairi** [comment]
![image](https://user-images.githubusercontent.com/26562484/46846400-25942880-ce12-11e8-88c4-26e6f45a18d9.png)
I test my private access token and it works.

**Comment by nurhannankhairi** [comment]
but still hygieia cant access and it still the same error =401 unauthorized

**Comment by nurhannankhairi** [comment]
I create gitlab.key in Hygieia ui, and also have put it in dashboard.properties file. the gitlab.apitoken i took from my gitlab credentials. when I run the gitlab on hygieia, i try many ways.. input apitoken,input the gitlab key..but nothing seems work. i also try to change path. i try with variety of path. also 401 unauthorized

**Comment by Sbrenthughes** [comment]
You do not need a `path=` for you instance... Please leave it blank.

I created a private repo on gitlab.com and using the properties below I was able to pull data from it. If you are still getting 401 then I would suggest generating a new key and trying that
```
dbname=dashboarddb

dbhost=localhost
dbport=27017


#Collector schedule (required)
gitlab.cron=0/10 * * * * *

#Gitlab host (optional, defaults to 'gitlab.com')
gitlab.host=gitlab.com

#Gitlab protocol (optional, defaults to 'http')
gitlab.protocol=https

#Gitlab port (optional, defaults to protocol default port)
#gitlab.port=80

#Gitlab path (optional, if your instance of gitlab requires a path)
gitlab.path=

#If your instance of Gitlab is using a self-signed certificate, set to true, default is false
gitlab.selfSignedCertificate=false

#Gitlab API Token (required, user token the collector will use by default, can be overridden on a per repo basis from the UI. API token provided by Gitlab)
gitlab.apiToken=Nh92q-oow9rk7g8VwmQj

#Maximum number of previous days from current date, when fetching commits
gitlab.commitThresholdDays=15

# Gitlab key for private repos
#gitlab.key= XXXXXXXXXXXXXXXXXX
``

**Comment by nurhannankhairi** [comment]
can I have link for public repo? and is there any differences btween private repo & internal repo as my repo is internal.

**Comment by Sbrenthughes** [comment]
Just create a public repo on your internal

**Comment by nurhannankhairi** [comment]
owhk okay. i will do it. 
one more question, i run the api using dashboard.properties. is it ok? and is there  any problem as i dont run n configure audit-api?

**Comment by Sbrenthughes** [comment]
The audit-api is independent of the UI and API. It needs to be ran separately but for your case right now I wouldn't bother with it.

**Comment by Sbrenthughes** [comment]
Also, on your project do you see something like but your project name instead of **TestProject**:
![image](https://user-images.githubusercontent.com/26173728/46878689-e665d780-ce11-11e8-84cd-da907ad56571.png)

**Comment by nurhannankhairi** [comment]
i dont see any project id on my internal repo..

**Comment by nurhannankhairi** [comment]
I can fetch the data from our internal host . thank you so much for your help.
