### ISSUE TITLE
Hygieia UI container connection with API container

### ISSUE THREAD

**Issue by mohit1606** [Hygieia/Hygieia#2475]
Hello,

In our test environment we are running Hygieia's UI, API and mongodb container. I was able to link mongodb with API container and getting the response using url: `http://:/api/dashboard`" as mentioned in the document.
For UI  i have spun an image which was present in the dockerhub and also linked it with the API container using "docker run -itd -p 3000:80 --link hygieia-api_1 --name=hygieia-ui_1 hygieia-ui:latest /bin/bash" command. But while accessing the UI from the browser im not getting the  "api connected" message as mentioned in the documents. 
Attaching the screenshot:
![image](https://user-images.githubusercontent.com/22495710/46468720-e735b280-c7ee-11e8-8a3a-2fd376d04526.png)

Could you please let me know is there any modification i need to do while running the UI container?

**Comment by matthewbeasley** [comment]
@mohit1606 please don’t use our containers from dockerhub because they are out of date. Build the UI image on your local and run it that. Also I would recommend running “docker-compose up -d” from the root of your project in order to spin up the containers.

**Comment by mohit1606** [comment]
Thank you @matthewbeasley. I will try building our own own UI image.

**Comment by matthewbeasley** [comment]
@mohit1606 - it should be linked automatically. Will you run `docker ps` and paste the output here?

**Comment by mohit1606** [comment]
PFA
![image](https://user-images.githubusercontent.com/22495710/46521757-325ace80-c89e-11e8-8995-0e13d643d30f.png)

i have tried running the below command as well to run the hygieia UI:

docker run -itd -p 3000:80 --link hygieia_api_1 --net hygieia_default --name=hygieia-ui_1 hygieia-ui:latest /bin/bash

But even this dint work and the UI page is down now.

**Comment by mohit1606** [comment]
Currently gulp and bower are also not installed in my server. output for node -v is v0.10.30 . @matthewbeasley do you think this might be an issue?

**Comment by mohit1606** [comment]
Is there any update for this issue? Any correction i need to make in my setup?

**Comment by shardulsrivastava** [comment]
@mohit1606 can you please share your docker-compose.yml files??

**Comment by shardulsrivastava** [comment]
this looks good, can you share your UI container logs as well to find the issue

**Comment by mohit1606** [comment]
@shardulsrivastava 
error:
host - - [08/Oct/2018:14:06:45 +0000] "GET /api/dashboard/mydashboard/undefined HTTP/1.1" 404 151 "http://<ip>:port/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"

and my application.properties file under api container looks like this:

#Database Name - default is test
dbname=dashboarddb

#Database HostName - default is localhost
dbhost=<db conatainer ip>

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=dashboarduser

#Database Password - default is blank
dbpassword=dbpassword

server.contextPath=/api
server.port=8080

**Comment by mohit1606** [comment]
UI page screenshot:
![image](https://user-images.githubusercontent.com/22495710/46611808-80850180-cb2c-11e8-9608-558bdb329d3b.png)

There's no "api connected" green tick in the UI page.

All the containers are in same network.

**Comment by shardulsrivastava** [comment]
@mohit1606 the normal log will look something like this 

`172.18.0.1 - - [08/Oct/2018:14:48:54 +0000] "GET /api/dashboard/count/undefined HTTP/1.1" 200 11 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "-"`

However in your case it's : 

`host - - [08/Oct/2018:14:06:45 +0000] "GET /api/dashboard/mydashboard/undefined HTTP/1.1" 404 151 "http://:port/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"`

I see the difference here as `"http://:port/"` i.e your UI is not pointing to the api perhaps somehow..

Can you try hitting these URLs in your browser and provide the result : 
`http://localhost:3000/api/appinfo`

`http://localhost:8080/api/appinfo`

and also can you please go to login page of your hygieia in chrome and open the developer console n send the screenshot like this : 

<img width="1438" alt="screen shot 2018-10-08 at 10 55 49 pm" src="https://user-images.githubusercontent.com/9951135/46616541-57289d80-cb4d-11e8-8032-0ddefd84bd24.png">

**Comment by Sbrenthughes** [comment]
@mohit1606 You are trying to use an old version of Hygieia UI. I would recommend using the latest deployed to master.  Please start here before doing anything else.

**Comment by Sbrenthughes** [comment]
Please reopen if you didn’t solve this.

**Comment by Oracle-Service** [comment]
In docker compose file, add unique container name and  that container name will serve as host name of that container. 
Below will be the updated docker compose file:
version: '3'
services:
db:
image: mongo:latest
ports:
- "27017:27017"
volumes:
- "db-data:/data/db"

db-setup:
build: db
container_name: mongodb
depends_on:
- db

api:
build: api
image: hygieia-api
container_name: hygieia-api
depends_on:
- db-setup
ports:
- "8080:8080"

ui:
build: UI
image: hygieia-ui
container_name: hygieia-ui
depends_on:
- api
ports:
- "3000:80"
volumes:
db-data:

and need to update other application properties file also like below:

#Database Name - default is test
dbname=dashboarddb

#Database HostName - default is localhost
dbhost=mongodb

#Database Port - default is 27017
dbport=27017

#Database Username - default is blank
dbusername=dashboarduser

#Database Password - default is blank
dbpassword=dbpassword

server.contextPath=/api
server.port=8080

Also need to update httpd.conf file. 

At bottom of httpd.conf you will get below statement:
ProxyPass /api http://localhost:8080/api
ProxyPassReverse /api http://localhost:8080/api

where you need to replace localhost with api container name and port no with api container port. New entry of ProxyPass and ProxyPassReverse will be like below:
ProxyPass /api http://hygieia-api:8080/api
ProxyPassReverse /api http://hygieia-api:8080/api

after changing above details, your hygieia UI can able to connect to hygieia-api.
