### ISSUE TITLE
Commit repo display is in-consistent

### ISSUE THREAD

**Issue by arunmk108** [Hygieia/Hygieia#2482]
I have setup commit repo widget to retrieve the metrics from gitlab repo. Iam able to retrieve the all metrics fine and able to display the graph also(refer Screen-1). When we open dashboard to see the repo metrics, its displaying well but suddenly after 30seconds automatically graph is vanishing(refer screen-2 below). Anyone please suggest what could be the issue.
Hygieia version -2.0.5 

properties file(gitlab.properties):
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=xxxxxx
dbhost=awsxxxxxxx.xxx.com
dbport=27017
logging.file=./logs/gitlab.log
gitlab.port=80
gitlab.cron=0 0/1 * * * *
gitlab.protocol=http
gitlab.host=gitlab.xxxx.com
gitlab.apiToken=xxxxxxx

sudo java -jar gitlab-scm-collector-2.0.5-SNAPSHOT.jar --spring.config.name=gitlab.properties --spring.config.location=/vol/hygieia/Hygieia/collectors/scm/gitlab/gitlab.properties &

Screen-1:
![image](https://user-images.githubusercontent.com/28533803/46542852-742f4900-c88d-11e8-8dcf-024f9bfb7ee4.png)

Screen-2:
![image](https://user-images.githubusercontent.com/28533803/46542892-8f9a5400-c88d-11e8-84ee-38191a8d979a.png)

**Comment by subodhbattina** [comment]
@arunmk108 : 
1. Noticed that you have set your collector to run every minute "gitlab.cron=0 0/1 * * * *", can you please reduce the frequency of this (run may be every 10 mins or more), so it doesn't interfere with the view refreshes on the UI widget just in case.

2. On your browser, on the developer tools, network tab, can you please check these 3 api calls below:

http://<host>:<port>/api/commit?componentId=<component Id>&numberOfDays=14

http://<host>:<port>/api/gitrequests/type/pull/state/all?componentId=<component Id>&numberOfDays=14

http://<host>:<port>/api/gitrequests/type/issue/state/all?componentId=<component Id>&numberOfDays=14

These get called every minute or so (or may be 30 seconds).
Please check the second time they get called, if you are getting any response back, please check the response on the network tab.

If you are seeing an empty response, please share the API logs for the three calls below.

If do see a non-empty response, then please check your browser console tab on the developer tools, and see if there any errors at all. Thanks.

**Comment by arunmk108** [comment]
I can see below metrics when i checked. But not getting much clue on this. Did you get anything on this?

URL                                                                                             Protocol Method  Result  Type    Received        Taken   Initiator   Wait‏‏  Start‏‏ Request‏‏       Response‏‏      Cache read‏‏    Gap‏‏ 

/api/commit?componentId=5ba3694e73c38a65269b70ef&numberOfDays=14                                HTTP     GET     200     application/json        17.05 KB 156 ms     XMLHttpRequest  55271   31      47      78      0       61386

/api/gitrequests/type/pull/state/all?componentId=5ba3694e73c38a65269b70ef&numberOfDays=14       HTTP     GET     200     application/json        399 B    156 ms     XMLHttpRequest  55271   109     47      0       0       61386

/api/gitrequests/type/issue/state/all?componentId=5ba3694e73c38a65269b70ef&numberOfDays=14      HTTP     GET     200     application/json        399 B    281 ms     XMLHttpRequest  55271   156     125     0       0       61261 "

**Comment by arunmk108** [comment]
changed gitlab crontab(gitlab.cron=0 0/10 * * * *) to 10min also. Still graph is inconsistent.

**Comment by arunmk108** [comment]
@subodbhattina,

I have changed the cron to 10 mins. I observed the dashboard for 10 mins with developer tools. 

when i open the dashboard it takes 60 seconds for the graph to load. if i dont refresh the page i can see the graph , if i refresh it again takes 60 secs for the graph to load.

So in a new session it takes 60 secs for the graph to load. No problems with rest of the widgets.

On those 3 api calls here is the response i get always.

http://:/api/commit?componentId=&numberOfDays=14

_{"result":[{"scmUrl"_ ....... and so on . i see all the revision ids and etc

http://:/api/gitrequests/type/pull/state/all?componentId=&numberOfDays=14

{"result":[],"lastUpdated":1539022201081}

http://:/api/gitrequests/type/issue/state/all?componentId=&numberOfDays=14

{"result":[],"lastUpdated":1539022201081}

No errors in the Api Logs or collector logs...

Please advise how can i resolve this 60 sec delay....

**Comment by Sbrenthughes** [comment]
Are you saying the 60 second refresh is causing issues for you?

**Comment by Sbrenthughes** [comment]
https://github.com/Hygieia/Hygieia/blob/master/UI/gulpfile.js `  config = {` is where the refresh rate is set. If you want to change it.

**Comment by subodhbattina** [comment]
@arunmk108 :  Going back to your original question below: Could you please clarify if this is resolved now? 
Also on the 60 second refresh rate, please see @Sbrenthughes comments on it.
Let us know if you have any other questions. Thanks !

```When we open dashboard to see the repo metrics, its displaying well but suddenly after 30seconds automatically graph is vanishing(refer screen-2 below).```

**Comment by subodhbattina** [comment]
@arunmk108: Wanted to check if you have any updates? Thanks.

**Comment by subodhbattina** [comment]
@arunmk108: Since we didn't hear back from you, assuming this is resolved at your end. Closing this issue. Thanks !
