### ISSUE TITLE
Deploy Widget(XLDeploy) is not showing server status

### ISSUE THREAD

**Issue by arunmk108** [Hygieia/Hygieia#2483]
I have setup Deploy widget with XL deploy and iam successfully able to retrieve deployment application with version and dates. But iam unable to see server status(Up and Down arrows) for deploy widget. Can anyone please help what could be the issue?
Using Hygieia 2.0.5 version.

![image](https://user-images.githubusercontent.com/28533803/46543513-0b48d080-c88f-11e8-8a62-dd8557f87f6a.png)

**Comment by subodhbattina** [comment]
@arunmk108:
Can you please check the data in the database:

1. In the "collectors" collection, find the "_id" for the "XLDeploy" collector name.

2. In the "collector_item" collection, find the items for the "collectorId" having your "applicationName" and "instanceUrl"

3. And in the "environment_status" collection, find if there is data for these list of collector items.
And check if the "online" status is set to true or false.
What you are seeing on the UI for the up arrows is the number of servers with "online" set to "true", and down arrows with "online" set to "false".

**Comment by subodhbattina** [comment]
@arunmk108: Thanks for reaching out, since we didn't hear back from you, going ahead and closing this issue.
