### ISSUE TITLE
Product Dashboard, production stage is not expeced.

### ISSUE THREAD

**Issue by yuhong02** [Hygieia/Hygieia#2486]
![image](https://user-images.githubusercontent.com/6858336/46656569-f5b20e80-cbe0-11e8-89f2-c1e619c06e56.png)
I expect my PROD stage is same as above image. but in fact, it's not.

My PROD is same as PERF, please refer to following screenshot. 
![image](https://user-images.githubusercontent.com/6858336/46656704-43c71200-cbe1-11e8-859b-60823aac99a0.png)
My question is how to set up production stage to make it as the end of the pipeline? Just like the first screenshot.

**Comment by nireeshT** [comment]
@yuhong02  go to pipeline tab, and choose radio button as prod stage 
<img width="600" alt="screen shot 2018-10-10 at 10 54 42 am" src="https://user-images.githubusercontent.com/22962180/46745417-fbf4c900-cc7a-11e8-818e-07ce5b6024e4.png">

**Comment by yuhong02** [comment]
Thanks a lot @nireeshT. It works.
