### ISSUE TITLE
Score collector is not working 

### ISSUE THREAD

**Issue by prateekasthana** [Hygieia/Hygieia#2490]
Score collector is not working .

In the logs its saying .  No of dashboards with score widget=0
 
I have enabled the score in Dashboard form. 

Below is my properties.

#Database Name
spring.data.mongodb.dbname=hygieiadb

# Database HostName - default is localhost
spring.data.mongodb.host=localhost

# Database Port - default is 27017
spring.data.mongodb.port=27017

# Database Username - default is blank
spring.data.mongodb.username=user1

# Database Password - default is blank
spring.data.mongodb.password=pwd1

score.cron=0/10 * * * * *
#Max score to display as 5
score.maxScore=5
#If value is equal or less to 0 show alert for the widget
score.widgetAlert.value=0
#If widget is not found, set value as no score to ignore widget in score calculation

score.criteria.noWidgetFound.scoreType=0

score.criteria.noWidgetFound.scoreType=zero_score
#If widget has no data, score would be 0 for it
score.criteria.noDataFound.scoreType=zero_score

#Weight for github widget
score.scmWidget.weight=50

#Weight for build widget
score.buildWidget.weight=50

Thanks in advance .
Prateek

_Originally posted by @prateekasthana in https://github.com/Hygieia/Hygieia/issue_comments#issuecomment-428870262_

**Comment by Sbrenthughes** [comment]
Are you on gitter? https://gitter.im/capitalone/Hygieia?source=all-rooms-list

**Comment by prateekasthana** [comment]
Hi Sbrenthughes , Yes I have Enabled it from Dashboard and have setup teh dashboard to for Jenkins and SVN widgets .

**Comment by Sbrenthughes** [comment]
Can you post the logs from the score collector running

**Comment by Sbrenthughes** [comment]
I will get that updated! Thank you very much for the feedback
