### ISSUE TITLE
Multiple repo widgets on the same dashboard

### ISSUE THREAD

**Issue by HweeWong** [Hygieia/Hygieia#2495]
Hi,

I am trying to add multiple repo widgets on a dashboard. I managed to get 2 repo widgets on the UI however the two widgets are linked now. How can I create multiple repo widgets? Is it a UI change only or would I need to look at the collectors as well?

Any help would be appreciated!

Thanks
Hwee

**Comment by matthewbeasley** [comment]
@HweeWong #2481 - someone just asked this a couple days ago. Please look at the issue list before creating new issues.
