### ISSUE TITLE
Open Source Label in Codequality Widget

### ISSUE THREAD

**Issue by gars01** [Hygieia/Hygieia#2496]
Can anyone tell me if it's possible to obtain license data and security issues from Artifactory to fill the Opensource label of the Codequality widget?

Thanks in advance.

**Comment by Sbrenthughes** [comment]
It is possible but you’ll next something like XRay to get those details. And build something get/push the data to Hygieia.

**Comment by gars01** [comment]
Thank you, I'll try find out more about this

**Comment by Sbrenthughes** [comment]
It would be a neat addition please feel free to contribute back!
