### ISSUE TITLE
Any Integration with VSTS/Azure DevOps CICD capabilities 

### ISSUE THREAD

**Issue by ashu16815** [Hygieia/Hygieia#2518]
Hi team, 

we are using Azure DevOps for CICD capabilities hence we need a bridge between VSTS/Azure DevOps and Hygieia.

How we can achieve this ? We have all the data available in form of JSON also. 

Kindly help.

thanks and Regards, 
Ankit Gupta.

**Comment by shishirchaturvedi** [comment]
This issue can be closed as discussion for building new widget for Azure DevOps pipeline has started here https://github.com/Hygieia/Hygieia/issues/2538.
