### ISSUE TITLE
The project com.capitalone.dashboard:Hygieia:3.0.1 (C:\Users\xxx\Hygieia\pom.xml) has 1 error

### ISSUE THREAD

**Issue by nagamallesh81** [Hygieia/Hygieia#2527]
Install Package is giving below error

$ mvn clean install package
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.3.0.RELEASE/spring-boot-starter-parent-1.3.0.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:3.0.1: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.3.0.RELEASE from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version and 'parent.relativePath' points at wrong local POM @ line 26, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.capitalone.dashboard:Hygieia:3.0.1 (C:\Users\s.naga.mallesh\Hygieia\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.capitalone.dashboard:Hygieia:3.0.1: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.3.0.RELEASE from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version and 'parent.relativePath' points at wrong local POM @ line 26, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by rvema** [comment]
Can you pull the latest code again and retry?

**Comment by rvema** [comment]
@nagamallesh81 Are you still having issues?

**Comment by Sbrenthughes** [comment]
Please update to the latest and reopen if this still an issue

**Comment by yogeshI** [comment]
I am facing the same ISSUE. The issue is not resolved yet. But my error is " Connection reset and 'parent.relativePath' points at wrong local POM". 
Thanks for the help in advance

**Comment by rvema** [comment]
Did you get the latest core and api and rebuild? Also are you behind a corporate proxy by any chance?
