### ISSUE TITLE
Unable to retrieve data from Gitlab

### ISSUE THREAD

**Issue by mohit1606** [Hygieia/Hygieia#2529]
I have configured the docker container of the SCM collector and trying to fetch the data from our gitlab. I am getting the below mentioned error:

Failed to retrieve data, the repo or collector is most likey misconfigured: https://ip:port2/on-prem/RPC, I/O error on GET request for "https://<ip>:<port>/api/v4/projects/on-prem%2FRPC/repository/commits/?ref_name=master&since=2018-10-11T07:35:00Z&per_page=100": Unrecognized SSL message, plaintext connection?; nested exception is javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

Could you please let me now what is the issue here?
Note: I dont have have root access to the gitlab server we have.

Command which i used to run the container:

docker run -d -t --name gitlab-collector -e "MONGO_PORT=http://ip:27017" -e "HYGIEIA_API_ENV_SPRING_DATA_MONGODB_DATABASE=dashboarddb" -e "HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME=db" -e "HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD=dbpass" -e "GITLAB_PROTOCOL=https" -e "GITLAB_HOST=<ip>" -e "GITLAB_PORT=2222" -e "GITLAB_API_TOKEN=<my token>" hygieia-gitlab-scm-collector:latest

**Comment by Sbrenthughes** [comment]
Did you pass in the host and just removed it for display ?

**Comment by mohit1606** [comment]
Yes.. IP address i have removed for the display.

**Comment by mohit1606** [comment]
Now i am getting a different error " Failed to retrieve data, the repo or collector is most likey misconfigured: http://dlax2chfc27.XXXXXX.com/user/test_hygieia, 404 Not Found"

**Comment by Sbrenthughes** [comment]
Is the repo private?

**Comment by Sbrenthughes** [comment]
@mohit1606 any update here?

**Comment by Sbrenthughes** [comment]
Closed due to inactivity
