### ISSUE TITLE
How to create custom collector for PivotalTracker?

### ISSUE THREAD

**Issue by yadurajshakti** [Hygieia/Hygieia#2530]
There is an example given in documentation but need more help such as :-

1) Prerequisite/Tech stack to create collector [I referred this one](https://medium.com/@prashant.parekh/how-to-build-a-collector-for-hygieia-open-source-devops-project-dfe27e0217c3)
2) Do I need to create new **Model classes and Repositories**.
3) Do I need to add something in **MongoDB**.
4) Do I need to change/add something in **Hygieia\core** project.
5) How ** Hygieia\api** will communicate with this custom collector.
6) Do I need to create separate widget or can I use existing one like feature.
7) It would be great to provide a simple Data Flow from UI to Collector.

Thanks in advance!
May be my questions are so fresher level but yeah I am new to Java platform :)

_And please add more such questions to help others in building a nice Custom Collector for any tool_

**Comment by Sbrenthughes** [comment]
2) Yes if you are creating a collector for data that has not been collect previous
3) it depends if the collector is collection new data or not. Ex. We have several different SCM collectors, all of them use the same commit Model class
4) see 3
5) API doesn't talk to collector. Collector stores data in mongo and api retrieves data from mongo
6) it depends, number 3 still applies 
7) The link you posted shows how the data flows.

**Comment by Sbrenthughes** [comment]
I would look into the github collector on how to get started. We have it in the backlog to update documentation. So I’m closing this for now. Please open for any new questions or reach out on our gitter
