### ISSUE TITLE
Need help for building custom collector as I need to Integrate this with Azure Devops

### ISSUE THREAD

**Issue by ashu16815** [Hygieia/Hygieia#2538]
Hi Team, 

I need to work to make on building custom collector As I need to provide Dashboards for Azure Devops pipelines. 

Regards, 
Ankit Gupta,

**Comment by shishirchaturvedi** [comment]
@ashu16815 Adding new dashboard to Hygieia project requires these components,

1. Collector
2. UI widget
3. REST Endpoints to query aggregated data

**Hygieia Collector** is a Spring Boot process designed to collect & aggregate DevOps data and persist it to datastore(Default - MongoDB). You can take a look at [SCM collector](https://github.com/Hygieia/Hygieia/tree/master/collectors/scm/github) to understand how a collector is implemented. 

**UI Widgets** are maintained [here]( https://github.com/Hygieia/Hygieia/tree/master/UI/src/components/widgets). You can follow these widgets and create similar code for new widget. For example you can copy repo folder and rename to "AZURE_BUILD_WIDGET". Each widget in Hygieia is uniquely identified by its name. During widget creation widget name is passed in the REST API call and that way REST API can resolve its name by mapping it to a predertmined itentifier. An example [widget name] (https://github.com/Hygieia/Hygieia/blob/master/UI/src/components/widgets/repo/config.js#L215) which is mapped to Collector type SCM [here]( https://github.com/Hygieia/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/service/DashboardServiceImpl.java#L590)

- REST Endpoints are created as Spring Controller, please see [GitRequestController](https://github.com/Hygieia/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/rest/GitRequestController.java). You need to supply ComponentID and some more parameter unique to your widget. 

Other than above, you can find plethora of information on Hygieia by following its [online documentation](https://hygieia.github.io/Hygieia/getting_started.html).

cc: @tabladrum

**Comment by Sbrenthughes** [comment]
@ashu16815 please reopen if this doesn’t answer your question

**Comment by PradeepDoddarangaiah** [comment]
Is there any progress on integration between Azure Devops and Hygieia related to custom collectors?
