### ISSUE TITLE
Provide default collector configuration in application.properties file for each Spring Boot module

### ISSUE THREAD

**Issue by shishirchaturvedi** [Hygieia/Hygieia#2540]
While working on Hygieia, I have found it cumbersome to configure Hygieia by following its online documentation. It would be fruitful to provide a default application configuration in each module (via application.properties) so that Hygieia dashboard can be configured easily by overriding only few properties or by using application-{profile}.properties file.

**Comment by Sbrenthughes** [comment]
I am not sure I understand the request. The readmes under each collector should have an example properties file. Is that not what you are asking for here?

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes Of course I found all the properties from Hygieia documentation. In the spirit of simplifying installation of Hygieia, those properties(at least default ones) can be added to application.properties files for each Spring Boot sub modules. Given that spring boot allows us to override properties file through command line argument or through addition of profile specific properties file, providing application.properties file makes it easy for Hygieia developer to configure it quickly.

**Comment by Sbrenthughes** [comment]
We don’t really recommend combining properties files. I don’t see the benefit in having one larger property file or maybe I’m not following what you’re saying. Either way please provide suggestions here: https://github.com/Hygieia/Hygieia/issues/2537 as it was opened for community feedback on simplifying hyigieia.
