### ISSUE TITLE
Add the ability to return the jenkins build Parameters from collector 

### ISSUE THREAD

**Issue by joshonike** [Hygieia/Hygieia#2556]
Is there a way to get the Jenkins build parameters added to the build info in the mongo database? 

I would like the build parameters added to the stored values so we may sort, categorize, and display info for a build based on the build parameters passes into that job.  

This seems like it should be a List objects return similar to how codeRepos or sourceChangeSet are stored in the mongoDB.  

If you can point me towards the area to make changes I can also look at adding them in as well. Otherwise a good feature would be the ability to specify Jenkins build info in a configuration file that would then add that object to the MongoDB.

**Comment by tabladrum** [comment]
Like the idea. From Jenkins plugin, it is easy. Don’t know if Jenkins has api to access the build parameters- this is for the collector.

**Comment by joshonike** [comment]
How would I have the plugin send the parameters? I have not been able to achieve that.  

Jenkins does allow you to get the parameters from the API. It is the same way you get the logfile.

**Comment by tabladrum** [comment]
1. We need to update the build model class
https://github.com/Hygieia/Hygieia/blob/master/core/src/main/java/com/capitalone/dashboard/model/Build.java

2. Collector Change - 
https://github.com/Hygieia/Hygieia/blob/master/collectors/build/jenkins/src/main/java/com/capitalone/dashboard/collector/DefaultHudsonClient.java

3. Plugin Change in here https://github.com/Hygieia/Hygieia/blob/master/hygieia-jenkins-plugin/src/main/java/hygieia/builder/BuildBuilder.java
