### ISSUE TITLE
Dockerfiles do not build the code

### ISSUE THREAD

**Issue by tomgeorge** [Hygieia/Hygieia#2560]
Looking through the code, it appears that the `Dockerfile`s in the various directories do not actually *build* the binaries.  Rather, they expect them to already exist and add them into the image.

I'm working on adding OAuth2 support to the jenkins collector, and I'm trying to build the collector image so I can deploy it to openshift.  I had to hack the collector's `pom.xml` a lot to get it to build, as it depends on the top-level `pom.xml`.  I also edited the collector's `Dockerfile` to do a `mvn install`.  

Hoping to not butcher the `pom.xml` too much, I tried just running the image from the top level `Hygieia` directory, passing in the path to the `Dockerfile` I wanted.  When trying to use the maven structure as-is, running `docker build -f collector/build/jenkins/docker/Dockerfile`, I get messages about the `maven-surefire` plugin crashing, though it appears that it is only defined in the `UI-Tests` module.  

Admittedly, I do not have a lot of maven experience, I mostly use and and gradle, and I'm sure that there are good  reasons for the hierarchical project structure.  I'm wondering if there are any plans to:

+ Have the `Dockerfiles` actually build the binaries they expect to see in `dist`, `target`, etc.
+ As a consequence of this, it will probably be necessary to make the maven projects more independent of each other

**Comment by tomgeorge** [comment]
I did a little more reading, and found out that the `-pl` option exists in Maven, so I can use that to just build one module.  

Re: the builder images, this might be just a specific use case, but I still think there would be value in creating them for e.g. containerized CI systems, developer onboarding, openshift imagestreams and buildconfigs, etc.

**Comment by Sbrenthughes** [comment]
We are working on separating things okay. We have started with the core module. This issue will be resolved once we have finished that migration. I’m going to go ahead and close this.
