### ISSUE TITLE
Misleading Documentation

### ISSUE THREAD

**Issue by kjaeswar76** [Hygieia/Hygieia#2567]
The Bamboo collector inline [documentation](https://hygieia.github.io/Hygieia/bamboo.html)  of the properties file indicates that we should be using an API key. The erroneous snippet is shown below

```
# If using username/token for API authentication
# (required for Cloudbees Jenkins Ops Center) see sample
bamboo.servers[1]=http://username:token@bamboo.company.com

# Another option: If using same username/password Jenkins auth,
# set username/apiKey to use HTTP Basic Auth (blank=no auth)
bamboo.username=
bamboo.apiKey=
```

The only API key which we use in this context is the Hygieia API key set in the api.properties file, but in reality you have to pass the password of the user and not the API key. This is extremely misleading and I wasted a lot of time on this and figured out only after looking at the source code. Can this be fixed? @mspiegel @jdamick @davidroman @cgorshing @jaredsmith

**Comment by Sbrenthughes** [comment]
We have added this to the backlog to be updated. I am closing

**Comment by vishnuvangala** [comment]
@kjaeswar76  Thank you for bringing it up. It saved my time during setup.
