### ISSUE TITLE
error reset window in github collector

### ISSUE THREAD

**Issue by ysnoussi** [Hygieia/Hygieia#2571]
Hi,
Would be nice to have a reset error feature after time window in github collector similare to the one used in github graphql collector. Actually it's only a matter of calling `checkErrorOrReset` in CollectorItem.java

Let me know if you need a PR for that

**Comment by rvema** [comment]
Please submit a PR for this issue and then we can close this issue

**Comment by rvema** [comment]
@ysnoussi closing the issue due to inactivity
