### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by bharathbenoit** [Hygieia/Hygieia#2573]
Hi there. As per the tutorial provided - http://www.smlcodes.com/tutorials/hygieia-dashboard-tutorial/

I have undertaken every step mentioned here but I'm unable to login, sign up with a new user as well as display any demo data via gulp serve --local true command. 

I'm attaching my Api --> logs
[devopsdashboard-api-2018-11-13.0.log](https://github.com/Hygieia/Hygieia/files/2574691/devopsdashboard-api-2018-11-13.0.log)

I am seeing this however

[BS] Local URL: http://localhost:3001
[BS] External URL: http://16.168.144.169:3001
[BS] Serving files from: dist/
[Proxy] { Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080 }

Haven't configured any proxies as these are all local installs

**Comment by bharathbenoit** [comment]
Dashboard.properties is as follows

dbname=dashboarddb
#dbusername=[MogoDb Database Username, defaults to empty]
#dbpassword=[MongoDb Database Password, defaults to empty]
dbhost=localhost
dbport=27017

Arguments - --spring.config.location=dashboard.properties in Eclipse

Application.properties
# Default server configuration values
dbname=dashboard
#dbusername=dashboarduser
#dbpassword=1qazxSw2
dbhost=127.0.0.1
dbport=11500
server.contextPath=/api
server.port=8080

![image](https://user-images.githubusercontent.com/18154973/48393905-85f5ed00-e765-11e8-9bb1-1df7c45459a4.png)

**Comment by bharathbenoit** [comment]
Has anyone else encountered a similar issue?

**Comment by yogisdm** [comment]
Hi @bharathbenoit ,
Where you able to resolve this issue, because I am also facing the same issue
