### ISSUE TITLE
Premature EOF while running Jenkins collector

### ISSUE THREAD

**Issue by Naveenraaj** [Hygieia/Hygieia#2574]
Client exception loading build details: I/O error on GET request for "https://jenkinsurl/job/4/consoleText": Premature EOF; nested exception is java.io.IOException: Premature EOF. URL =https://jenkinsurl/job/4/

**Comment by subodhsbattina** [comment]
@Naveenraaj : There seems to be an issue with the response coming back for the build URL https://jenkinsurl/job/4/consoleText.

Would you be able to run the collector in your IDE in debug mode, and put a break point in the class "DefaultHudsonClient.java" class on the line 313 (ResponseEntity<String> result = makeRestCall(url)), and see what response you are getting back? May be this url is not valid.

**Comment by Naveenraaj** [comment]
@subodhsbattina Thank you , will try !!

**Comment by Naveenraaj** [comment]
@subodhsbattina iam receiving NullPointer exception in API console logs.. i am still trying to figure out the issue.

**Comment by Sbrenthughes** [comment]
Can you post your properties

**Comment by Sbrenthughes** [comment]
What type of job is that? Could you provide more information for use to recreate this issue?

**Comment by Naveenraaj** [comment]
It is a job for compiling .Net code, 

Explaining further...
I can see all the jobs from the folder(which i am trying to bring it in to dashboard), when i try to configure(build reports) in a new dashboard , as a drop down list
the problem is--
when i choose certain jobs, i get null pointer exception and when i choose certain job, it loads up the report graph as expected.

P.S. i have access to browse/build all the jobs from Jenkins GUI and access them through rest API through the appropriate URLs.

Any suggestion for me to proceed further, would be great !!

**Comment by Sbrenthughes** [comment]
Can you give the entire stack trace?

**Comment by fidelcoria** [comment]
@Naveenraaj was the premature EOF resolved? if so, how?
I think the null pointer exception is unrelated to the original issue you opened. You may want to open a new issue if you are not able to solve it yourself.

**Comment by fidelcoria** [comment]
We found a workaround. By increasing the timeout the connection is kept opened and no premature EOF.
```
public class RestOperationsSupplier implements Supplier<RestOperations> {
    @Override
    public RestOperations get() {
    	HttpComponentsClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory();
        requestFactory.setConnectTimeout(500000);
        requestFactory.setReadTimeout(500000);
        return new RestTemplate(requestFactory);
    }
}
```
What you really want to do is to paginate the requests.

**Comment by Naveenraaj** [comment]
thank you @fidelcoria , i will try to update mine and post in the thread with results 👍

**Comment by Sbrenthughes** [comment]
This is now configurable via the properties file
