### ISSUE TITLE
Name of the code-quality create api end point is hard-coded to 'Sonar'

### ISSUE THREAD

**Issue by isuru89** [Hygieia/Hygieia#2577]
We need to integrate a custom enterprise code quality tool into Hygieia through its api.

By looking at the [code here](https://github.com/Hygieia/Hygieia/blob/master/api/src/main/java/com/capitalone/dashboard/service/CodeQualityServiceImpl.java#L169) the collector's name has been hard-coded to __Sonar__.

I think the correct way to take the collector name, _optionally_, thorough api by adding a field to `CodeQualityCreateRequest`

**Comment by tabladrum** [comment]
You are right. We want to add a "toolName" to the CodeQualityCreateRequest - that would match with CollectorName. Do we want to send a PR?

**Comment by isuru89** [comment]
Sure. I will send a PR

**Comment by Sbrenthughes** [comment]
I would suggest the first.

**Comment by Sbrenthughes** [comment]
@isuru89 any update here?

**Comment by rvema** [comment]
@isuru89 Please see the code review comments on #2693 . As soon as they are addressed we will close this issue.
