### ISSUE TITLE
Required String parameter 'projectId' is not present - JIRA

### ISSUE THREAD

**Issue by bharathbenoit** [Hygieia/Hygieia#2583]
I seem to be getting the following issue upon getting the JIRA Collector up and running

Required String parameter 'projectId' is not present

2018-11-16 12:50:00,002 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2018-11-16 12:50:00,020 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-11-16 12:50:00,044 INFO  c.c.d.collector.CollectorTask - http://10.4.45.7:8080/
2018-11-16 12:50:00,045 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2018-11-16 12:50:00,048 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s

I have defined this in the application.properties file as follows

feature.jiraProxyUrl=<defined my proxy url>
feature.jiraProxyPort=<provided the port>
feature.jiraBaseUrl=<URL defined>
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraProjectId=MFJIR

**Comment by nireeshT** [comment]
@bharathbenoit  have you changed collections manually in Mongo?

**Comment by bharathbenoit** [comment]
No I haven't. What would i need to change there?

**Comment by nireeshT** [comment]
@bharathbenoit share jira props

**Comment by bharathbenoit** [comment]
Here's are the details contained within the application.properties file

# Database Name
dbname=<specified db name>

# Database HostName - default is localhost
dbhost=<db host>

# Database Port - default is 27017
dbport=<dbport>

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=<pwd>

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
#feature.teamQuery=teaminfo
#feature.trendingQuery=trendinginfo

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=arvov30.aus.hp.com
feature.jiraProxyPort=3128
feature.jiraBaseUrl=http://10.4.45.7:8080/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraProjectId=10000

# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64
feature.jiraCredentials=YmhhcmF0aC5iZW5vaXQ6UnVrc2hpa2Ex

# OAuth is not fully implemented; please blank-out the OAuth values:
#feature.jiraOauthAuthtoken=
#feature.jiraOauthRefreshtoken=
#		feature.jiraOauthRedirecturi=
#		feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10004

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10006

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
#feature.jiraTeamFieldName=

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=false

**Comment by bharathbenoit** [comment]
Any thoughts?
