### ISSUE TITLE
how to change widget place and width or height

### ISSUE THREAD

**Issue by yuhong02** [Hygieia/Hygieia#2585]
Hi all,

I would like to change widget display place, and the widget height, On the first configuration, I changed, but it didn't work, all the widget still display in same size.

In the page http://hygieia.github.io/Hygieia/widget_view.html, the Deploy widget is very big, I want to customize my widget as my need. How to do it? thanks a lot for help.
![image](https://user-images.githubusercontent.com/6858336/48693172-94d01a00-ec13-11e8-9b8f-0856c1609aea.png)

Thanks,
Yuhong

**Comment by nireeshT** [comment]
@yuhong02  look for widget.html & widget.js

**Comment by Sbrenthughes** [comment]
@yuhong02 Reopen if that wasn't enough information
