### ISSUE TITLE
Core Folder Missing

### ISSUE THREAD

**Issue by kjaeswar76** [Hygieia/Hygieia#2587]
When I clone the Hygieia code and build. I dont see the core folder. What am I missing? I have taken the code from the master branch.

As a result I am unable to generate the secret key required for encryption of private repositories  run the bitbucket collector as it uses the encryption.

Appreciate any help on this.

**Comment by nireeshT** [comment]
@kjaeswar76 https://github.com/Hygieia/hygieia-core

**Comment by kjaeswar76** [comment]
Thanks @rvema @nireeshT
