### ISSUE TITLE
No widget is active after creating dashboard using remoteCreate

### ISSUE THREAD

**Issue by yuhong02** [Hygieia/Hygieia#2590]
Hi all,
I tried to create dashboard using remoteCreate. The post body is as following, I got successfully creation message returned. "Successfully created dashboard: id =5bf3d17836d1a00009eae345". But, in fact, no widget is active. Could you please help check why no widget display? Thanks a lot for your help.
Post body:
{
  "staticCodeEntries":[
	    {
	      "description": "",
	      "options": {
	          "projectName": "testing",
	          "instanceUrl": "https://sonarServer"
	      },
	      "pushed": false,
	      "toolName":"Sonar"
	    }

  ],
  "metaData": {
    "applicationName": "Test",
    "componentName": "test",
    "owner": {
      "authType": "STANDARD",
      "username": "admin"
    },
    "template": "test",
    "title": "Test6",
    "type": "team"
  }
}

Returned message:
"Successfully created dashboard: id =5bf3d17836d1a00009eae345"

The dashboard shows null widget:
No widget displays. And check the configuration of dashboard, all dashboard is checked.

**Comment by Sbrenthughes** [comment]
Did you create a template called test?

**Comment by yuhong02** [comment]
Thanks a lot @Sbrenthughes. I will try and close this issue.
