### ISSUE TITLE
Octopus Integration

### ISSUE THREAD

**Issue by IAPOLINARIO** [Hygieia/Hygieia#2593]
What is the easiest way to collect Octopus data without writing a new collector? Is there any plans to release an Octopus collector in the near future?

**Comment by Sbrenthughes** [comment]
Generally speaking there are two ways to get data to Hygieia. 1) Collector (pull based) 2) Push based. Ex Jenkins plugin. 

From our end there aren’t plans. But we do accept contributions!

**Comment by georgejinu** [comment]
Hello Ismael, is that any update on the Octopus Integration with Hygieia? can you please let me know..

**Comment by IAPOLINARIO** [comment]
Hey @georgejinu,
Unfortunately, so far, no updates.
