### ISSUE TITLE
JIRA Dashboard not loading properly

### ISSUE THREAD

**Issue by hmangala** [Hygieia/Hygieia#2597]
Hi Team,

I am getting following error in api application.
![capture](https://user-images.githubusercontent.com/20920370/48891957-d571a280-ee62-11e8-9bfc-97646dd0fc1f.PNG)

c.c.d.rest.RestApiExceptionHandler - Required String parameter 'projectId' is not present

**Comment by Sbrenthughes** [comment]
Have you tried reviewing https://github.com/Hygieia/Hygieia/issues/2293

**Comment by Sbrenthughes** [comment]
@hmangala -Please refer to #2667. As this is the collector rewrite in progress
