### ISSUE TITLE
Unable to login (unable to see "Create Dashboard" option)

### ISSUE THREAD

**Issue by vishnuvangala** [Hygieia/Hygieia#2599]
Hi,
I tried a fresh installation of HYGIEIA with the official documentation. Finally I ended up with a basic page where there is no option to see "Create Dashboard" and even I'm unable to see the settings icon. Even after logging in, I dont see the logged in username at top right corner, it still shows LOGIN. Can someone please help? 
Here are my API properties:

# api.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017,127.0.0.1:27017,ip-x-x-x-x:27017
server.contextPath=/api
server.port=8080
logRequest=false
logSplunkRequest=false
corsEnabled=false
corsWhitelist=http://domain1.com:port,http://domain2.com:port
version.number=1.1

auth.expirationTime=15000
auth.secret=<Some_text>
auth.authenticationProviders=
#auth.ldapServerUrl=[LDAP Server URL, including port of your LDAP server]
#auth.ldapUserDnPattern=[LDAP User Dn Pattern, where the username is replaced with '{0}']

# LDAP Server URL, including port of your LDAP server
#auth.ldapServerUrl=[ldap://company.com:389]

# If using standard LDAP
# LDAP User Dn Pattern, where the username is replaced with '{0}'
#auth.ldapUserDnPattern=[uid={0},OU=Users,dc=your,dc=company,dc=com]

# If using ActiveDirectory
# This will be the domain part of your userPrincipalName
#auth.adDomain=[company.com]
# This will be your root dn
#auth.adRootDn=[dc=your,dc=company,dc=com]
# This will be your active directory URL (required for AD)
#auth.adUrl=[Need an example]

#monitor.proxy.host=[hostname of proxy server]
#monitor.proxy.type=[http|socks|direct]
#monitor.proxy.port=[port enabled on proxy server]
#monitor.proxy.username=[proxy username]
#monitor.proxy.password=[proxy password]

# This will be the page size for pagination on Hygieia landing page. If this property is not set, the default value is set to 10.
pageSize=10

# API token generated for basic authentication to secure APIs.
#key=[api token]

# SSO properties with header values from UI layer
#auth.userEid=[name of the header containing EID]
#auth.userEmail=[name of the header containing user's email]
#auth.userFirstName=[name of the header containing user's first name]
#auth.userLastName=[name of the header containing user's last name]
#auth.userMiddelInitials=[name of the header containing user's middle name]
#auth.userDisplayName=[name of the header containing user's display name]

![image](https://user-images.githubusercontent.com/24268077/48934894-c0ad1180-ef2b-11e8-95a3-a21cb5a5e260.png)

Created a new user admin and logged in and still I see LOGIN instead of username.

![image](https://user-images.githubusercontent.com/24268077/48934925-dae6ef80-ef2b-11e8-8f0e-bedd7f3a4999.png)

got below exception, but when I cleared the cache and logged in again.. even this is gone now.

 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception
io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.

Console Errors after clicking on login (admin):

![image](https://user-images.githubusercontent.com/24268077/48943961-e09ffd80-ef4a-11e8-84e1-a504db6ade3d.png)

No other exceptions in API logs. Attaching api logs as well.

[devopsdashboard-api-2018-11-23.0.log](https://github.com/Hygieia/Hygieia/files/2610775/devopsdashboard-api-2018-11-23.0.log)

Any help please?

**Comment by Sbrenthughes** [comment]
Can you try with a bare bones .properties file see example:
```
dbname=dashboarddb
dbhost=localhost
dbport=27017
server.contextPath=/api
server.port=8080

version.number=

auth.authenticationProviders=STANDARD
```

**Comment by vishnuvangala** [comment]
Thanks @Sbrenthughes  . I still don't understand which property caused me the issue. I just copy pasted the above properties given by you and it started working after a restart of api.  I remember even earlier I tried with the minimum required properties but didn't work. 
Thank you so much again. we can close the ticket now.

**Comment by dai-mk** [comment]
I also have this issue. There is no "Create Dashboard" button despite using the config from @Sbrenthughes .
