### ISSUE TITLE
Errors building docker image w/ latest release 

### ISSUE THREAD

**Issue by willyyang** [Hygieia/Hygieia#2606]
Following `http://hygieia.github.io/Hygieia/builddocker.html`, I should be able to clone this repo and run `mvn clean install`.. 

This fails with 
![screen shot 2018-11-27 at 4 51 02 pm](https://user-images.githubusercontent.com/6396257/49114051-3505ee80-f265-11e8-803e-d2a1629062ea.png)

On release `3.0.0` , fails at 
![screen shot 2018-11-27 at 4 57 19 pm](https://user-images.githubusercontent.com/6396257/49114177-8dd58700-f265-11e8-95ec-4706f83dbba0.png)

**Comment by rvema** [comment]
The version of the publisher plugin seems old. Did you get the latest code from the repo and try?

**Comment by willyyang** [comment]
The first error is using the version `git clone https://github.com/Hygieia/Hygieia.git` provides

**Comment by rvema** [comment]
That's weird. However can you do `git clone https://github.com/Hygieia/hygieia-core.git` followed by mvn clean install of hygieia-core. Then run mvn clean install of Hygieia?

**Comment by willyyang** [comment]
Able to run `mvn clean install` without errors now

**Comment by jochenparm** [comment]
I have this exact same error, freshly cloned the repository less than 30 minutes ago!

**Comment by Sbrenthughes** [comment]
Did you follow the suggested steps above?

**Comment by jochenparm** [comment]
There were no suggested steps? I just cloned the last revision of the master branch.

**Comment by Sharmakartik** [comment]
got same error as mentioned above with latest version 3.0.1(api-audit.jar dependency).
please help cant find solution.

Thanks

**Comment by Sbrenthughes** [comment]
Rvema suggested 
“That's weird. However can you do git clone https://github.com/Hygieia/hygieia-core.git followed by mvn clean install of hygieia-core. Then run mvn clean install of Hygieia?”
