### ISSUE TITLE
Hygieia - Jenkins Plugin Configuration issues

### ISSUE THREAD

**Issue by sid-arora** [Hygieia/Hygieia#2621]
Hi, 
I am not sure what i am missing here but when i provide the settings for the Hygieia plugin in Jenkins which is basically the server URL: http://localhost:8080/api, and click on Test connection - I get a null pointer exception. I get true when i access http://localhost:8080/api/ping through the browser. 

And because my configuration is wrong, when i select any of the Hygieia steps from PIpeline syntax in Jenkins, i get an HTTP 404 not found error. 

<img width="669" alt="hygieiaconfig" src="https://user-images.githubusercontent.com/7194210/49551305-be986a80-f8bc-11e8-8946-958f6292ad36.png">

**Comment by tabladrum** [comment]
Click “Apply” on Jenkins config system page or save and come back to do test connection.

**Comment by Sbrenthughes** [comment]
@sid-arora Any update here?
