### ISSUE TITLE
Jenkins collector issue

### ISSUE THREAD

**Issue by babujii** [Hygieia/Hygieia#2624]
I have install Hygieia dashboard on my server  and Jenkins build logs is not visible on the dashboard. Can you help me.

**Comment by Sbrenthughes** [comment]
We need more info.. Have you installed the Jenkins Collector? Have you ran the Jenkins Collector? Are you getting errors from the Jenkins Collector? If so what errors? Etc...

**Comment by babujii** [comment]
Yes, i have installed jenkins collector and there is no error.still build logs is not visible.

**Comment by Sbrenthughes** [comment]
Did you add the build job to a dashboard ?

**Comment by babujii** [comment]
Here is the log output.
[root@logserver ~]# cd /opt/hygieia/collectors/build/jenkins/target/logs/
[root@logserver logs]#

2018-12-10 04:38:30,009 INFO  c.c.d.collector.CollectorTask - -----------------------fetching builds---------------------http://206.181.129.100:7070 0s
2018-12-10 04:38:30,010 INFO  c.c.d.collector.CollectorTask - Inside build method     1544416710s
2018-12-10 04:38:30,010 INFO  c.c.d.collector.CollectorTask - Inside enabledJobs               0s
2018-12-10 04:38:30,010 INFO  c.c.d.collector.CollectorTask - Inside builddata                 0s
2018-12-10 04:38:30,010 INFO  c.c.d.collector.CollectorTask - Builds--------->12               0s
2018-12-10 04:38:30,015 INFO  c.c.d.collector.CollectorTask - Inside enabledJobs               0s
2018-12-10 04:38:30,015 INFO  c.c.d.collector.CollectorTask - Inside builddata                 0s
2018-12-10 04:38:30,015 INFO  c.c.d.collector.CollectorTask - Builds--------->4                0s
2018-12-10 04:38:30,017 INFO  c.c.d.collector.CollectorTask - Inside enabledJobs               0s
2018-12-10 04:38:30,017 INFO  c.c.d.collector.CollectorTask - Inside builddata                 0s
2018-12-10 04:38:30,017 INFO  c.c.d.collector.CollectorTask - Builds--------->1                0s
2018-12-10 04:38:30,017 INFO  c.c.d.collector.CollectorTask - New builds              0        0s
2018-12-10 04:38:30,018 INFO  c.c.d.collector.CollectorTask - New configs             0        0s
2018-12-10 04:38:30,018 INFO  c.c.d.collector.CollectorTask - Finished                         0s
^C
[root@logserver logs]#

[root@logserver target]# pwd
/opt/hygieia/collectors/build/jenkins/target
[root@logserver target]# ls -ltr
total 1017212
drwxr-xr-x. 3 root root        35 Dec  7 08:57 maven-status
drwxr-xr-x. 3 root root        25 Dec  7 08:57 generated-sources
drwxr-xr-x. 3 root root        54 Dec  7 08:57 classes
drwxr-xr-x. 3 root root        17 Dec  7 08:57 test-classes
drwxr-xr-x. 3 root root        30 Dec  7 08:57 generated-test-sources
drwxr-xr-x. 2 root root        28 Dec  7 08:57 maven-archiver
drwxr-xr-x. 2 root root      4096 Dec  7 10:31 surefire-reports
drwxr-xr-x. 3 root root        36 Dec  7 12:12 site
-rw-r--r--. 1 root root       104 Dec  7 12:15 pmd.xml
-rw-r--r--. 1 root root    265447 Dec  7 12:15 jacoco.exec
-rw-r--r--. 1 root root     32800 Dec  7 12:15 jenkins-build-collector-3.0.1.jar.original
-rw-r--r--. 1 root root  56429680 Dec  7 12:15 jenkins-build-collector-3.0.1.jar
-rw-r--r--. 1 root root      1187 Dec  7 12:52 jenkins.properties
drwxr-xr-x. 2 root root      4096 Dec 10 02:46 logs
-rw-------. 1 root root 481619275 Dec 10 04:39 nohup.out
[root@logserver target]# cat jenkins.properties | grep -v ^#
dbname=hyg

dbhost=localhost

dbport=27017

dbreplicaset=false
dbhostport=127.0.0.1:27017

dbusername=hyg

dbpassword=hyg

jenkins.cron= * * * * * *

jenkins.pageSize=1000

jenkins.folderDepth=10

jenkins.servers[0]=http://206.181.129.100:7070


jenkins.usernames[0]=admin
jenkins.apiKeys[0]=11663c9584a2d7ef76751910fb638c3c01

jenkins.saveLog=true

jenkins.searchFields[0]= options.jobName
jenkins.searchFields[1]= niceName

[root@logserver target]#

Jenkins collector screenshot:
--------------------------------
![image](https://user-images.githubusercontent.com/36594080/49711245-4f2bcd80-fc64-11e8-8aa8-71c6225841ea.png)

Can you check and help me on this please.
Note: I am using a master branch with tag v3.0.1

**Comment by babujii** [comment]
[root@logserver api]# cat dashboard.properties | grep -v ^#
dbname=hyg
dbusername=hyg
dbpassword=hyg
dbhost=localhost
dbport=27017
dbhostport=127.0.0.1:27017
server.contextPath=/api
server.port=8080



[root@logserver target]# cat jenkins.properties | grep -v ^#
dbname=hyg

dbhost=localhost

dbport=27017

dbreplicaset=false
dbhostport=127.0.0.1:27017

dbusername=hyg

dbpassword=hyg

jenkins.cron= * * * * * *

jenkins.pageSize=1000

jenkins.folderDepth=10

jenkins.servers[0]=http://206.181.129.100:7070

jenkins.usernames[0]=admin
jenkins.apiKeys[0]=11663c9584a2d7ef76751910fb638c3c01

jenkins.saveLog=true

jenkins.searchFields[0]= options.jobName
jenkins.searchFields[1]= niceName

[root@logserver target]#

Above provided the output. Can you help on this.

**Comment by Sbrenthughes** [comment]
If you paste `http://localhost:8080/api/collector/type/Build` in your browser, what do you get

**Comment by Sbrenthughes** [comment]
@babujii any update?

**Comment by Sbrenthughes** [comment]
@babujii Please Reopen if you are still facing issues

**Comment by babujii** [comment]
Still same issue, which branch is working one. Can you give me please.i will use that one..

**Comment by Sbrenthughes** [comment]
What do you get when you paste in the browser http://localhost:8080/api/collector/type/Build

**Comment by spyoungtech** [comment]
I have a similar issue. Result of /api/collector/type/Build is an empty array `[]`.

Also the Jenkins collector doesn't seem to respect settings. Despite setting the mongo host / port in settings, I see logs of error connecting to `localhost:27017` but it should be connecting to `db:27017`

**Comment by ansha1** [comment]
facing similar issue on which we are working #2685. 

link "http://10.132.208.173:8080/api/collector/type/Build" giving output "[]" on screen.

**Comment by Sbrenthughes** [comment]
@babujii take the latest master and check out what @ansha1 did to resolve this issue
