### ISSUE TITLE
getting error "Could not resolve dependencies"

### ISSUE THREAD

**Issue by ansha1** [Hygieia/Hygieia#2627]
[ERROR] Failed to execute goal on project api: Could not resolve dependencies for project com.capitalone.dashboard:api:jar:3.0.1: Failed to collect dependencies at com.capitalone.dashboard:core:jar:[3.1.0-SNAPSHOT,): No versions available for com.capitalone.dashboard:core:jar:[3.1.0-SNAPSHOT,) within specified range -> [Help 1]

Appreciate some help !

**Comment by udiakasnuke** [comment]
getting the similar error myself...

**Comment by udiakasnuke** [comment]
@Sharmakartik  - Not working for me... I am getting the above mentioned errors some dependency issue with jira-feature-collector

**Comment by Sharmakartik** [comment]
You are working on which OS

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by udiakasnuke** [comment]
Mac OS...

**Comment by Sharmakartik** [comment]
I have checked on windows.
U can install each and everything from scratch.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by udiakasnuke** [comment]
I did everything from scratch on Mac machine... Does Hygieia has some reservation for Mac machine, should i use Windows machine for Hygieia setup ? As i read in docs it supports Mac..

**Comment by Sharmakartik** [comment]
I don't know about Mac. May b plugin problem.
Else if I get any solution. I will get on this thread immediately.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by udiakasnuke** [comment]
Sure!! In the mean time i will try and arrange a Windows machine and setup everything from scratch again :( .

**Comment by Sharmakartik** [comment]
Best way to go on AWS EC2 INSTANCE.
SPIN UP IN SECONDS.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sbrenthughes** [comment]
@udiakasnuke your issue is with mvn not having connectivity to pull down a jira dependency. It is not with Hygieia.

**Comment by Sbrenthughes** [comment]
@ansha1 like @sharmakartik mentioned, have you downloaded and ran mvn clean install in Hygieia/hygieia-core first?

**Comment by Sharmakartik** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by udiakasnuke** [comment]
@Sbrenthughes - how do i set this up correctly... I haven't configured mvn to anything extra.. I just installed it and set it's path in bash_profile .... 

Thanks!! Any help is greatly appreciated!!

**Comment by udiakasnuke** [comment]
yes possible!!

**Comment by Sbrenthughes** [comment]
You need to look up how to configure maven with a proxy

**Comment by celamb4** [comment]
Documentation needs to be updated to show new structure.

**Comment by Sbrenthughes** [comment]
@ansha1 Any updates?

**Comment by udiakasnuke** [comment]
@Sbrenthughes  - Looked like it was a proxy issue... I created my mobile hotspot to work around this because i couldn't get the proxy details... it was built successfully then

**Comment by ansha1** [comment]
Hey @Sbrenthughes thanks for responding in such a short time !
We are in need of a dashboard which we can display on our LED display screen for our managers and scrum masters. And someone in my team suggested about Hygieia tool.

You should update your documentations about the fix you suggested above. It passed the last failure step for missing jar. Right now its failing for bower install, because i used root user for checking out code and running maven. Well i am creating a new user and will build again. 
I will update here once its done. 

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:bower (bower install) on project UI: Failed to run task: 'bower install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by ansha1** [comment]
You should enable it for root as well. Will ease our work :)

**Comment by admiresail** [comment]
@Sharmakartik 

I cloned Hygieia core and when I run "mvn clean install" , the build is failing with the below error:

_org.apache.maven.plugin.MojoExecutionException: You need to run build with JDK or have tools.jar on the classpath.If this occures during eclipse build make sure you run eclipse under JDK as well_

Can you please help ?? I am using windows machine, tried in unix box as well .. same error.

**Comment by mirageglobe** [comment]
latest pull from hygieia core and clean build results in these issues: 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.215 s
[INFO] Finished at: 2019-02-07T13:24:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.mysema.maven:apt-maven-plugin:1.1.3:process (default) on project core: java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated: javax.annotation.Generated -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

-- any recommended build environments? having tested in an alpine as well as local mac both resulting a frustrating compile errors. If there any working env configurations of hygieia anyone can share?
