### ISSUE TITLE
How to push commit data via DeployPublishStep

### ISSUE THREAD

**Issue by etsauer** [Hygieia/Hygieia#2628]
We are publishing deploy environment data to our hygieia stack using the Jenkins plugin. For example:

```
hygieiaDeployPublishStep applicationName: "${APP_NAME}", artifactDirectory: 'dist/', artifactGroup: 'uncontained.io', artifactName: 'index.html', artifactVersion: "${BUILD_NUMBER}-${dev_namespace}", buildStatus: 'Success', environmentName: "${dev_namespace}"
```

However, the team dashboard cannot calculate average lead time because the build and deploy widgets don't have the commit information in them. Is there some way to explicitly send a commit id in the publish steps?

cc: @pcarney8

**Comment by etsauer** [comment]
Another observation.. one of my jenkinsfiles pulls in a global library from github, and the build widget is interpretting that as my source code repository, and pulling commit data from it. It would be nice to have a parameter in the `hygieiaBuildPublishStep` to override that data.

**Comment by etsauer** [comment]
Bump. Any ideas?

**Comment by Sbrenthughes** [comment]
What version of the plugin are you using? I am thinking the latest solves the global library issue. 

Your deploy steps don’t need commit. You need to push the artifact data in the build and then once you do your first deploy with that same artifact name, version etc the commit data will automatically sync up. If this isn’t happening you are missing a step.

**Comment by Sbrenthughes** [comment]
@etsauer

**Comment by etsauer** [comment]
@Sbrenthughes thanks, that fixed it!
