### ISSUE TITLE
Can we remoteCreate a product dashboard?

### ISSUE THREAD

**Issue by liutsi** [Hygieia/Hygieia#2629]
Hi, actually we have 2 questions.
1. we need to create product dashboard by remoteCreate, but I've read through Hygieia Swagger API page and have drilled down into api source code, it seems that Hygieia hadn't implement remoteCreating product dashboard now.
2. we want to remoteCreate a pipeline widget in the team dashboard, just like above, I guess it's not implemented yet.
Just want to make sure if this is the case, if so, do we have any roadmap about remoteCreating product dashboard? And do we have any workaround now?
Really appreciate your help.

**Comment by Sbrenthughes** [comment]
You are correct it doesn't exist. Currently there are no plans to implement this in the near future.
