### ISSUE TITLE
Don't see the bamboo collector data in mongodb

### ISSUE THREAD

**Issue by udiakasnuke** [Hygieia/Hygieia#2632]
Hi,

My mongod, API, bamboo colllector is running fine. I can see the connections been accepted by mongod, collector is fetching the build plans as i can see in terminal but it's not reflecting in my mongoDB because of which i think it's not reflecting on dashboard build widget. Drop down shows nothing..

dashboard.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dashboarduser123
dbhost=localhost
dbport=27017
dbhostport=localhost:27017,127.0.0.1:27017,ip-172–31–26–184:27017
dbreplicaset=false
server.contextPath=/api
server.port=8080
corsEnabled=false
auth.expirationTime=10000
auth.authenticationProviders=STANDARD

application.properties
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbusername=dashboarduser
dbpassword=dashboarduser123
dbreplicaset=false
bamboo.savelog=false
bamboo.cron=0 0/5 * * * *
bamboo.servers[0]=https://bamboo.forge.company.com
bamboo.username=bamboo_user
bamboo.apiKey=bamboo_pass

Not sure what's going wrong here!! Someone please help!! Thanks!!

**Comment by Sbrenthughes** [comment]
This issue is being addressed in the other issue you already opened. https://github.com/Hygieia/Hygieia/issues/2631
