### ISSUE TITLE
Can someone please help in configuring Bamboo pipeline widget in hygieia. 

### ISSUE THREAD

**Issue by buradeshruti** [Hygieia/Hygieia#2633]
Jenkins has hygieia publisher plugin, is there any similar plugin for Bamboo? Any help in configuring Bamboo pipeline would be useful.

**Comment by Sbrenthughes** [comment]
We only have the Bamboo collector. Have you tried configuring it?

**Comment by Sbrenthughes** [comment]
As far as I know the bamboo collector does not pull artifact information which is what is used for the pipeline widget.
