### ISSUE TITLE
Sonar credentials as security token feature

### ISSUE THREAD

**Issue by RameshMuthuraj** [Hygieia/Hygieia#2634]
I wanna use Sonar security token property instead of sonar.username & sonar.password..

Let me know if its possible to pass this value ? since we used SAML for authentication

**Comment by Sbrenthughes** [comment]
Hey @RameshMuthuraj this is certainly possible it just isn't implemented for the sonar collector. We will add it to the backlog but if you want to work on this and create a PR that would be awesome!
