### ISSUE TITLE
cant create any job in hygieia dashboard

### ISSUE THREAD

**Issue by Sharmakartik** [Hygieia/Hygieia#2639]

**Comment by Sharmakartik** [comment]
please help to to create jobs in hygieia.

**Comment by Sharmakartik** [comment]
my gihub ang sonar collector are working fine.
my sonar collector fetching project from sonar server BUT 
my github collector is not working in Hygieia dashboard (repo type).

NEED HELP.

**Comment by Sbrenthughes** [comment]
Are you able to configure the sonar widget?

**Comment by Sharmakartik** [comment]
i have to create sonar widget under code analysis????

**Comment by Sharmakartik** [comment]
where static code ,functional test etc??
cant see any job under their panel..

**Comment by Sbrenthughes** [comment]
`http://localhost:8080/api/collector/type/SCM` navigate here. What does this return?

**Comment by Sharmakartik** [comment]
i have one more question??

1. which database we are using 
 1.a dashboard
 1.b dashboraddb(documents as well as .properties files)

when im putting in my chrome browser localhost:8080/api/dashboard (its giving json type data)
BUT not in localhost:8080/api/dashboarddb(as per in documents)

PLZ Clear my Confusion.

**Comment by Sbrenthughes** [comment]
Lets please fix one thing at a time. What does `http://localhost:8080/api/collector/type/SCM` return?

**Comment by Sharmakartik** [comment]
> `http://localhost:8080/api/collector/type/SCM` navigate here. What does this return?

i have done this 
getting a json format but in that got **string** type repo.
want github type repo...

HELP!!

**Comment by Sbrenthughes** [comment]
Can you just copy and paste the response here.

**Comment by Sharmakartik** [comment]
ok sure

**Comment by Sharmakartik** [comment]
[{"id":"5c1906c0d4c45e1638ad1a90","name":"GitHub","collectorType":"SCM","enabled":true,"online":true,"errors":[],"uniqueFields":{"branch":"","url":""},"allFields":{"password":"","personalAccessToken":"","branch":"","userID":"","url":""},"lastExecuted":1545156600054,"searchFields":["description"]}]

**Comment by Sharmakartik** [comment]
i think its working fine
but cant log into my dahboard.

**Comment by Sbrenthughes** [comment]
I am not sure what you mean log into the dashboard? Are you saying you can't login to hygieia?

**Comment by Sharmakartik** [comment]
yes.

**Comment by Sharmakartik** [comment]
green.

**Comment by Sbrenthughes** [comment]
Have you try to sign up?

**Comment by Sharmakartik** [comment]
yes. i am admin as well as a dummy user.
but now none is working

**Comment by Sbrenthughes** [comment]
Can you screenshot the dashboard page
and post it
