### ISSUE TITLE
Jira colloector not work, throw error : c.c.dashboard.util.ClientUtil - rapidViewId found is not number

### ISSUE THREAD

**Issue by yamazakei331** [Hygieia/Hygieia#2645]
jira:v7.12.3
hygieia:tag v3.0.0
application.properties file as follow
dbname=dash
dbhost=192.168.65.103
dbport=27017
dbusername=dash
dbpassword=dash

logging.file=./logs/jira.log

feature.pageSize=100

feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

feature.cron=0/15 * * * * *

feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.jiraBaseUrl=http://192.168.65.101:8080/
feature.jiraQueryEndpoint=rest/api/2/

feature.jiraCredentials=YWRtaW46MTIzNDU2

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

feature.jiraIssueTypeNames=Story

feature.jiraSprintDataFieldName=customfield_10100
feature.jiraEpicIdFieldName=customfield_10101
feature.jiraStoryPointsFieldName=customfield_10106
feature.jiraTeamFieldName=customfield_10203

feature.jiraBoardAsTeam=true
feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

jira fields
![image](https://user-images.githubusercontent.com/12411817/50420575-6c6eb780-0872-11e9-8dae-ebc8aac8cc07.png)
-----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/12411817/50420589-87412c00-0872-11e9-929b-bc3bdcd62c00.png)
-----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/12411817/50420599-9f18b000-0872-11e9-913c-260b2ea218fc.png)
-----------------------------------------------------------------------------------------------------------------

hygieia ui configuration
![image](https://user-images.githubusercontent.com/12411817/50420617-c8394080-0872-11e9-9d54-9267270cbfdb.png)

DB data
![image](https://user-images.githubusercontent.com/12411817/50420679-0e8e9f80-0873-11e9-9f94-ae5607342e18.png)

log informations
![image](https://user-images.githubusercontent.com/12411817/50420550-40533680-0872-11e9-9817-075734154688.png)

got 0 0 0
![image](https://user-images.githubusercontent.com/12411817/50420648-e1da8800-0872-11e9-9da3-90d758746a79.png)

pls help

**Comment by jochenparm** [comment]
I've got the same problem, I can see in the response that the rapidViewId is <null> in my case.
Any help please? Can I tell the collector to ignore this field somehow, since I don't think it's of any concern to me.

**Comment by Sbrenthughes** [comment]
Can you both test the collector rewrite found here: https://github.com/Hygieia/Hygieia/issues/2667

**Comment by Sbrenthughes** [comment]
@yamazakei331 Seems to have success with the comment above. Closing this out.

**Comment by jochenparm** [comment]
Giving some feedback: no, I wasn't able to fix the issue. I gave up on the Jira collector instead...
