### ISSUE TITLE
Github collector is not working properly

### ISSUE THREAD

**Issue by Aomine-Daiki-5** [Hygieia/Hygieia#2647]
When I am triggering the github collector, the job is running and is only connecting with 6 repo. I have downloaded the latest code from here and created the new jar file. But the result is still the same.

**Comment by Sbrenthughes** [comment]
@Aomine-Daiki-5 are those 6 repos public?

**Comment by Sbrenthughes** [comment]
So it is only connecting to 6 private repos?

**Comment by Sbrenthughes** [comment]
@Aomine-Daiki-5
