### ISSUE TITLE
Can make the collectors run as services in windows machine?

### ISSUE THREAD

**Issue by Aomine-Daiki-5** [Hygieia/Hygieia#2648]
I want to run the mongodb, API, and the collectors to run as services from a windows machine.  We are trying to install Hygieia and make it as a stand alone in that particular machine.

**Comment by Aomine-Daiki-5** [comment]
Yes,.
I have created the services from the jar file running the command
'sc create "GithubHygieia" binPath= "C:\Program Files\Java\jdk1.8.0_151\jre\bin\java.exe -jar D:\Hygieia\collectors\scm\github\target\github-scm-collector-2.0.5-SNAPSHOT.jar" type= own start= auto error= ignore'

But not able to trigger the services. Is there a documentation where it is defined to check the Hygieia jar files as Windows services?

**Comment by Sbrenthughes** [comment]
No not really most users either use Linux or deploy using docker.
