### ISSUE TITLE
Widgets in team dashboard lose data when switching between widget & pipeline views

### ISSUE THREAD

**Issue by KalhariL** [Hygieia/Hygieia#2656]
You can reproduce the issue using following steps.

Create a team dashboard with build,deploy, repo widgets
View widget view and ensure data is displayed properly in all widgets
Switch to pipeline view and click on save (not required to add environments)
Switch back to widget view and one widget is (usually build widget) in a not-configured state
Switch to pipeline view and click on configure, save (Save is a must, if you just switch between views this won't happen)
Switch back to widget view, another widget will be in a not-configured state
If you do it several times all widgets will go to not-configured state one by one

**Comment by Sbrenthughes** [comment]
Thank you for the detailed steps on how to recreate! I think there is a PR currently awaiting approve for this.

**Comment by KalhariL** [comment]
Hi, Thanks for the response. Yes if we refresh the page it's fine. It's not removing the widget entirely., the widget is displayed in a non-configured state as shown below 
![image](https://user-images.githubusercontent.com/46436360/50799773-92e02880-1331-11e9-98f8-c7e70b73a44b.png)

**Comment by Sbrenthughes** [comment]
Thank you for confirming. We will see if the existing PR addresses this. If not we will add it to the backlog to be fixed.

**Comment by KalhariL** [comment]
Great, if it gets fixed pls do update so that I can merge the solution. Thanks again.
