### ISSUE TITLE
Coverity data in hygieia

### ISSUE THREAD

**Issue by rajkumaradass** [Hygieia/Hygieia#2658]
We are looking to sync coverity code analysis data(from Coverity server) with  code quality widget in hygieia.  Currently it appears only sonar collector and jenkins code quality collector are available. Is there a way to fetch coverity data through jenkins code quality collector along with possibly running  jenkins-coverity plugin in jenkins. Appreciate if any thoughts on achieving this with existing collector/jenkins plugin.

Thanks

**Comment by rvema** [comment]
@rajkumaradass You would need to write a collector to start collecting data from coverity. Here is the link on how to create a collector - http://hygieia.github.io/Hygieia/create_collector.html

**Comment by rvema** [comment]
@rajkumaradass please confirm if this issue can be closed?

**Comment by rajkumaradass** [comment]
@rvema, Yes, I have written the collector. Could you please let me know the process if i can submit this as a contribution?

**Comment by rvema** [comment]
Please submit the PR and once it is reviewed and approved will automatically be merged to the project.

**Comment by rvema** [comment]
Closing this issue as its resolved.

**Comment by fidelcoria-aa** [comment]
I am also interested in seeing a Coverity Collector contributed to Hygieia. @rajkumaradass, are you still planning on submitting a PR?

**Comment by fidelcoria-aa** [comment]
@rajkumaradass I have submitted a PR #2757 with a coverity collector implementation
