### ISSUE TITLE
Jira - Unable to display Scrum data in dashboard 

### ISSUE THREAD

**Issue by harish123321** [Hygieia/Hygieia#2659]
Jira collector is not displaying any data on widget if I select sprint type is Scrum while configuring widget
Can any one help me what to do in order to display scrum data

**Comment by Sbrenthughes** [comment]
We are working on refactoring the Jira collector to address all the issues. Stay tuned.

**Comment by udiakasnuke** [comment]
@Sbrenthughes - I am also experiencing problems wherein i don't see any data been shown .. I selected project name, Team name and configured the UI with various other fields but i don't see any data been shown. Will your refactoring fix all these issues?? Thanks!!

**Comment by Sbrenthughes** [comment]
Please refer to the above comment and if you face issues follow up here #2667.
