### ISSUE TITLE
Code Repo widget only not showing pull requests

### ISSUE THREAD

**Issue by meetgds** [Hygieia/Hygieia#2662]
I have the bitbucket collector running and it is able to pull data from my repository. In the code repo widget, however, I can only see the commit data but can't see pull requests and other data. Do I have to change anything to see the pull requests?
![screen shot 2019-01-09 at 10 08 59 am 2](https://user-images.githubusercontent.com/16129018/50877220-e8cad400-13f6-11e9-8554-4a753b294e34.png)

**Comment by Sbrenthughes** [comment]
Looks like that collector wasn’t updated to add pull requests. Is that something you make the necessary changes and contribute back? You can check out the GitHub collector as a reference.

**Comment by meetgds** [comment]
I have started work on it and written a collector alrerady, which is fetching the pull data. But I have no clue about how I can create the widget for it, or make changes to the existing one. Is there a guide available for that somewhere?

**Comment by Sbrenthughes** [comment]
no need to write a new collector. Just update the existing one to pull the PR. Give me a little time and I will give you an example data model.

**Comment by Crozy** [comment]
I have also this problem. 

If the solution exists I am interested.

**Comment by shishirchaturvedi** [comment]
@meetgds @Sbrenthughes I have working solution in local code. There is OSS code review going for my code changes. I am hoping to submit a PR to add PR data for Bitbucket collector soon(possibly tomorrow).

**Comment by meetgds** [comment]
Thanks @shishirchaturvedi , were you able to display the data on the UI too? I also have local changes to fetch the data but have not made any progress on the UI side.

**Comment by shishirchaturvedi** [comment]
@meetgds After enhancing scm collector I can see pull-request on UI. There is no code change required on UI.

**Comment by Sbrenthughes** [comment]
@shishirchaturvedi update on the PR?

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes Internal OSS review is taking longer than I expected. Hope to get it completed by tomorrow.

**Comment by rvema** [comment]
@shishirchaturvedi Please address the code review comments and we will get this merged as soon as possible.

**Comment by ojasvijagtap** [comment]
@shishirchaturvedi @Sbrenthughes  did you get chance to check on this? 
We are waiting for your changes to pull. 
Thanks in advance.

**Comment by Sbrenthughes** [comment]
Still waiting for @shishirchaturvedi response

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes I am blocked on this issue: https://github.com/Hygieia/Hygieia/issues/2766
I will finalize my PR after CLA is review is complete.

**Comment by Sbrenthughes** [comment]
I believe you had things cleared up with our Open Source Office. Let me know what else you need from us.

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes  I have got clarification on OSS process from @SanthiSridharan. Based on that discussion I have got Corporate CLA signed by the legal team at my end. I am waiting for confirmation that the Corporate CLA was submitted successfully and can be tracked. 
@SanthiSridharan or @Sbrenthughes Can you please confirm that Corporate CLA filled by `Matthew(Matt) Elliott <melliott@pandora.com>` has been received at your end? 
After getting this confirmation we can go ahead with this PR merge. Please let me know if you have any further question.

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes I have received confirmation the Corporate CLA. Please go ahead on merging my PR.

**Comment by Sjnahak** [comment]
@shishirchaturvedi  @meetgds   can you help me with the issue i have passed and tried url (different format) repo widget.
first case i get i can't see pull request data
second case bucket.org is added in api call
More details in : https://github.com/Hygieia/hygieia-scm-bitbucket-collector/issues/27
