### ISSUE TITLE
Issue with Rally collector configuration

### ISSUE THREAD

**Issue by admiresail** [Hygieia/Hygieia#2669]
N Rally, I am unable to save the widget as after clicking save button nothing is happening and rally log is not having any info.

From api.log, I got the following error

 

2019-01-09 22:13:34,535 WARN  c.c.d.rest.RestApiExceptionHandler - Bad Request - bind exception:

org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors

Field error in object 'collectorItemRequest' on field 'collectorId': rejected value [null]; codes [NotNull.collectorItemRequest.collectorId,NotNull.collectorId,NotNull.org.bson.types.ObjectId,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [collectorItemRequest.collectorId,collectorId]; arguments []; default message [collectorId]]; default message [may not be null]

        at com.capitalone.dashboard.rest.RestApiExceptionHandler.handleMethodArgumentNotValid(RestApiExceptionHandler.java:60) [api.jar!/:3.0.1]

        at org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(ResponseEntityExceptionHandler.java:167) [spring-webmvc-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]

Please help to resolve the issue.

**Comment by admiresail** [comment]
@Sbrenthughes please advise on the above issue. We are unable to save anything in the dashboard for rally.

**Comment by Sbrenthughes** [comment]
Can you post your properties for the collector

**Comment by admiresail** [comment]
dbname=dashboard
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=127.0.0.1
dbport=27017
dbreplicaset=false
rally.cron=0 0/5 * * * *
rally.servers[0]=http://rallydev.com
rally.usernames[0]=myrallyuserid
rally.passwords[0]=myrallypassword

I selected the 'Rally' option which is outside the main dashboard configuration window instead of the one which was mentioned in Feature-->Rally and it worked. Please update the documentation. Thank you!!!!

**Comment by Sbrenthughes** [comment]
Can you clarify what documentation needs updating?

**Comment by Sbrenthughes** [comment]
Closed as your issue is resolved

**Comment by siva-veeraraj** [comment]
am facing the same issue now. i dont see any data in the feature collection in the mongodb and i couldnt save the rally configuration in the dashbaord. Please advice
