### ISSUE TITLE
Inconsistencies in docker property-builder script causing unexpected failure due to misconfiguration

### ISSUE THREAD

**Issue by spyoungtech** [Hygieia/Hygieia#2681]
Have been tracking down the source of a frustrating issue where Jenkins build collector doesn't seem to respect settings from configuration.

Commented out these lines from the `properties-builder.sh` and it resolved the issue

```
if [ "$TEST_SCRIPT" != "" ]
then
        #for testing locally
        PROP_FILE=application.properties
else
	PROP_FILE=config/hygieia-jenkins-build-collector.properties
fi
```

It would seem this would allow for the properties file to be created in the wrong location. Where the config would be written to `config/hygieia-jenkins-build-collector.properties` but the application will be started with 

```
--spring.config.location=$PROP_FILE
```
Where `$PROP_FILE` is provided by the Dockerfile as `ENV PROP_FILE /hygieia/config/application.properties`

**Comment by spyoungtech** [comment]
Also noteworthy is that this "local testing" block doesn't appear in all the collectors' `properties-builder.sh`. 

Similar code is found in scripts for xldeploy, appdynamics, and gitlab. I don't use those collectors, but presumably, this problem would exist for those using these collectors with docker-compose.

**Comment by Sbrenthughes** [comment]
Please see MatthewBeasley’s comment here: https://github.com/Hygieia/Hygieia/issues/2489. It describes how to override the properties file.

**Comment by spyoungtech** [comment]
Thanks for that link @Sbrenthughes . Looking forward to changes in the docker setup.

I have a couple reservations about overriding the environment variable, particularly because the `PROP_FILE` variable in the shell script can change based on the presence of this `TEST_SCRIPT` environment variable, and will change regardless of what value is supplied in the environment variable.

In other words, I believe these lines in `properties-builder.sh` to be harmful. Yes, one can override the dockerfile default location to accommodate, but that is treating the symptom rather than root cause.

The Dockerfile cmd will always start the app with the location in environment variable; behaves as expected. The properties-builder script will not respect the environment variable, which is the root cause of this issue.

I would suggest that the environment variable be respected in all cases and that instead of using those lines in the shell script... A tester should override the environment variable instead of using a separate variable `TEST_SCRIPT`.

**Comment by daniel-ng** [comment]
Thanks for your work, @Sbrenthughes .

Agree with @spyoungtech . Which is why I never did the PR for documentation - I felt that it should be fixed rather than workaround documented. 

Glad to see it will be addressed in the Docker setup overhaul.

**Comment by spyoungtech** [comment]
Also noticed that api-audit properties file contains a similar issue. The propfile location is hard-coded:

https://github.com/Hygieia/Hygieia/blob/master/api-audit/docker/properties-builder.sh#L19

**Comment by rvema** [comment]
This has been resolved.
