### ISSUE TITLE
ServiceNow CMDB support

### ISSUE THREAD

**Issue by jigneshmehta1984** [Hygieia/Hygieia#2684]
Is there a plan for adding ServiceNow CMDB support? In absense of ServiceNow CMDB, we are not able to leverage Hygieia Executive Dashboard.

**Comment by rvema** [comment]
@jigneshmehta1984 Please feel free to contribute by creating a ServiceNow collector. Here is the link on how to create a collector - http://hygieia.github.io/Hygieia/create_collector.html

**Comment by rvema** [comment]
Closing this issue by requesting contribution back

**Comment by jigneshmehta1984** [comment]
Is it possible to provide some kind of mapping of data model of servicenow and hpsm with respect to CMDB collection to create a collector?
