### ISSUE TITLE
Hygieia Jira widget not showing data for teams

### ISSUE THREAD

**Issue by syedafirdaus** [Hygieia/Hygieia#2690]
Jira collector is putting data to mongo db in backend but not populating on UI widget. When I choose Team field as Any, it shows data but it is not appropriate. But when I choose specific team, it shows all 0s. Any idea?
<img width="289" alt="jira" src="https://user-images.githubusercontent.com/42797555/51758614-18aef280-20ec-11e9-85eb-f257af1186e1.PNG">
<img width="290" alt="jira1" src="https://user-images.githubusercontent.com/42797555/51758616-1b114c80-20ec-11e9-97ec-e04022a1f288.PNG">

![image](https://user-images.githubusercontent.com/42797555/51758658-32503a00-20ec-11e9-8c4d-6708047c7315.png)

**Comment by Sbrenthughes** [comment]
The current implementation has too many issues. That is why we are working on the refactor here: https://github.com/Hygieia/Hygieia/issues/2667

**Comment by erictice** [comment]
Was this ever resolved?

**Comment by rvema** [comment]
Jira widget has some issues and is yet to be implemented in new UI. If you have bandwidth you may contribute it back

**Comment by erictice** [comment]
Is this also an issue with GitHub SCM collector and the new UI.  I am
having a similar issue where it doesn’t seem to be pulling issues or
updates from GitHub

**Comment by rvema** [comment]
@Courtneyp123 can you take a quick look at this issue?

**Comment by Courtneyp123** [comment]
@erictice what repo are you looking at specifically? Did it work in the past with the information you provided in the configuration?
