### ISSUE TITLE
Core - why separate project?

### ISSUE THREAD

**Issue by stevegal** [Hygieia/Hygieia#2692]
How come this has moved out of the main repo. Especially as I can't seem to find it on man central. makes building the project harder.

**Comment by spyoungtech** [comment]
I like the direction of splitting out collectors and such. One difficulty I've found with the split of Hygieia Core is that I couldn't find exactly which version of Core I should be using with a particular tagged release of Hygieia. For example, there is no 3.0.1 tag for Hygieia-Core.

**Comment by rvema** [comment]
We are working on splitting the components and creating their own repos. Please hang on :)

**Comment by rvema** [comment]
Can we close this as its not an issue? Please clone the hygieia-core project and run mvn clean install to resolve any issues you may be seeing
