### ISSUE TITLE
Query Regarding Team Dashboard Creation 

### ISSUE THREAD

**Issue by prateekasthana** [Hygieia/Hygieia#2695]
While Creating  a New Team Dashboard.  Business Service and business application Drop Down is always blank , I did not get any help on How to Populate these fields. Any Help is appreciated. 

Thanks in Advance. 
![11111](https://user-images.githubusercontent.com/26957140/51843112-5d2ece00-2338-11e9-8c33-677de96e95af.png)

**Comment by Sbrenthughes** [comment]
This is populated by running the /cmdb/hpsm collector.

**Comment by Sbrenthughes** [comment]
Just as an update they are also not required for creating a team dashboard.

**Comment by Sbrenthughes** [comment]
Please open a new issue if you need help with the cmdb collector setup
