### ISSUE TITLE
[Caused by: PR 2696]Latest Hygieia build is not including submodules

### ISSUE THREAD

**Issue by shishirchaturvedi** [Hygieia/Hygieia#2701]
https://github.com/Hygieia/Hygieia/pull/2696 has introduced erroneous behavior to the build. Hygieia latest source code in my development machine is only including root project. Thus none of the submodules are getting included in the build.  I saw this behavior on the PR build as well. I noticed it when I committed breaking changes to my PR and PR build succeeded.

Build for PR https://github.com/Hygieia/Hygieia/pull/2696 finished in less than 2 mins 
https://travis-ci.com/Hygieia/Hygieia/builds/98879888

My latest PR build finished in less than a minute: https://travis-ci.com/Hygieia/Hygieia/builds/99158830 which is wrong. 

cc: @chbrown13 @rvema @Sbrenthughes

**Comment by rvema** [comment]
#2702 is on the way to fix this.

**Comment by rvema** [comment]
@shishirchaturvedi please update your workspace and this issue should be resolved now

**Comment by shishirchaturvedi** [comment]
@rvema Latest code build looks good now. Thank you for your prompt response.
