### ISSUE TITLE
Sample Data for Hygieia

### ISSUE THREAD

**Issue by jigneshmehta1984** [Hygieia/Hygieia#2704]
If sample data is available for Hygieia, it will be easier to evaluate Hygieia and integrate with other products like Hygieia Executive Dashboard. This would significantly promote Hygieia adoption.

**Comment by rvema** [comment]
This is WIP as we are trying to build a starter package that can be leveraged by users with sample data. We will keep you updated on this

**Comment by rvema** [comment]
To begin with once you start running the appropriate collectors you should have  the necessary data (github, Jenkins, jira etc.)

**Comment by jigneshmehta1984** [comment]
Yes. I was able to add data and integrate Hygieia with Hygiea Executive Dashboard by putting dummy entries in CMDB and linking team dashboard with CMDB entries (Product in CMDB -> Business Service for Dashboard and Component in CMDB -> Business Application in Dashboard).
