### ISSUE TITLE
How to automatically grab new build Jenkins jobs in Hygieia?

### ISSUE THREAD

**Issue by manuq21** [Hygieia/Hygieia#2710]
Hello, installed Hygieia as part of a project we have, and the idea is for Hygieia to automatically refresh the build jobs status (successful, failure, unstable and aborted) for all the build jobs run in each of the Jenkins folders/projects.
For ex, we have a Jenkins folder that represents a project in Jenkins, and for that project/folder several jobs run per day (more than 100 sometimes). We need to have all those jobs automatically loaded in Hygieia with their status.
So how can we automatically refresh each Jenkins build job status on Hygieia ? 

We checked that we can add a build widget, and after a new build job is run in Jenkins, we are able to see it listed on Hygieia to add it manually, but first we are adding a single job and second we are doing it manually. We need Hygieia to refresh that status data automatically for each Jenkins run job.

thanks

**Comment by rvema** [comment]
We have a Hygieia Jenkins Publisher Plugin, you could leverage that. The plugin needs to be installed on all Jenkins masters and that way all the build information can be pushed from Jenkins to Hygieia on a event basis. This will eliminate the need to run Jenkins Collector. Do let me know if you need help.

**Comment by manuq21** [comment]
Hi rvema, we have the "Hygieia Publisher Plugin" installed in Jenkins, is that the one ?
Description of it: This plugin is publisher that can publish build status to Hygieia Dashboard.

If that's the one, do you have the specific steps to get it worked as you said, instead of using the Hygieia build collector ? 

Thanks!

**Comment by Sbrenthughes** [comment]
https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/hygieia-jenkins-plugin/hygieia-jenkins-plugin.md
