### ISSUE TITLE
Is there a way to automate dashboard creation?

### ISSUE THREAD

**Issue by cesarcabral** [Hygieia/Hygieia#2711]
Can a dashboard be automatically created after a new job is created in jenkins?
Because having to add a job in a team dashboard is not an issue but having to add hundreds manually is a pain...

**Comment by Sbrenthughes** [comment]
There is the remoteCreate/remoteUpdate APIs that you could use in your automation.

**Comment by cesarcabral** [comment]
Sounds good, can you point me how to use them?

**Comment by Sbrenthughes** [comment]
When you start the api locally go to http://localhost:8080/api/swagger/index.html and see dashboard-remote-controller

**Comment by Sbrenthughes** [comment]
I am closing. Please let us know if you have anymore questions

**Comment by chenthilan** [comment]
@Sbrenthughes what is the difference between the dashboard-controller and dashboard-remote-controller APIs under http://hygieiaAPIendpoint/api/swagger/index.html?

Both has a createDashboard (one with remote another without it)... the params are different. If i have to create a list of dashboards (for about 70 APIs), which one should i loop thru?
