### ISSUE TITLE
jira-widget in dashboard showing no data found

### ISSUE THREAD

**Issue by rishi-mukherjee** [Hygieia/Hygieia#2714]
![jira-widget](https://user-images.githubusercontent.com/47267131/52271308-48ba8900-2969-11e9-906a-1cb8b1d6ff7e.JPG)

**LOG SNIPPET:**

2019-02-05 17:03:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-02-05 17:03:00,025 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-05 17:03:00,025 INFO  c.c.d.collector.CollectorTask - https://support.mycompany.com/
2019-02-05 17:03:00,025 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-02-05 17:03:00,043 INFO  c.c.d.collector.CollectorTask - Team Data               0        0s
2019-02-05 17:03:02,237 INFO  c.c.d.collector.CollectorTask - Project Data            1        2s
2019-02-05 17:03:04,487 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 0
2019-02-05 17:03:04,487 INFO  c.c.d.collector.CollectorTask - Story Data              0        2s
2019-02-05 17:03:04,487 INFO  c.c.d.collector.CollectorTask - Finished                         4s

**properties**:

dbname=dashboard
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=9085
dbusername=
dbpassword=
logging.file=./logs/jira.log
feature.pageSize=1000
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
feature.jiraBaseUrl=https://support.mycompany.com/
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=cmlzaamVlOkNoaW50dSEkMjAxOA==
feature.jiraProjectId=11306 
feature.jiraIssueTypeId=Story
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10005
feature.jiraEpicIdFieldName=customfield_10006
feature.jiraStoryPointsFieldName=customfield_10002
feature.jiraTeamFieldName=
feature.jiraBoardAsTeam=true

**Comment by rishi-mukherjee** [comment]
One sample record from my mongo DB: (Please check if something I have forgot to fill it in Jira itself?)

{
    "_id" : ObjectId("5c5935a02867308408a177c5"),
    "_class" : "com.capitalone.dashboard.model.Feature",
    "collectorId" : ObjectId("5c5835e82867300ee41065c7"),
    "sId" : "409003",
    "sNumber" : "DSP-2526",
    "sName" : "Production checklist",
    "sTypeId" : "34",
    "sTypeName" : "Story",
    "sStatus" : "Backlog",
    "sState" : "Backlog",
    "sEstimate" : "0",
    "sEstimateTime" : 0,
    "sUrl" : "https://support.mycompany.com/browse/DSP-2526",
    "changeDate" : "2018-12-14T12:57:40.0000000",
    "isDeleted" : "False",
    "sOwnersID" : [ 
        "ramya.s"
    ],
    "sOwnersIsDeleted" : [],
    "sOwnersChangeDate" : [],
    "sOwnersState" : [ 
        "Active"
    ],
    "sOwnersUsername" : [ 
        "ramya.s"
    ],
    "sOwnersFullName" : [ 
        "Ramya S"
    ],
    "sOwnersShortName" : [ 
        "ramya.s"
    ],
    "sTeamIsDeleted" : "False",
    "sTeamAssetState" : "",
    "sTeamChangeDate" : "",
    "sSprintIsDeleted" : "False",
    "sSprintChangeDate" : "",
    "sSprintAssetState" : "",
    "sSprintEndDate" : "",
    "sSprintBeginDate" : "",
    "sSprintName" : "",
    "sSprintID" : "",
    "sEpicIsDeleted" : "False",
    "sEpicChangeDate" : "",
    "sEpicAssetState" : "",
    "sEpicType" : "",
    "sEpicEndDate" : "",
    "sEpicBeginDate" : "",
    "sEpicName" : "",
    "sEpicNumber" : "",
    "sEpicID" : "",
    "sProjectPath" : "",
    "sProjectIsDeleted" : "False",
    "sProjectState" : "",
    "sProjectChangeDate" : "",
    "sProjectEndDate" : "",
    "sProjectBeginDate" : "",
    "sProjectName" : "My Project",
    "sProjectID" : "12908",
    "issueLinks" : []
}

**Comment by rishi-mukherjee** [comment]
@MarkRx  can you please help me

**Comment by Sbrenthughes** [comment]
Can you pull latest and delete the scope, team and features collections? After that rerun.
