### ISSUE TITLE
Issue (failure) with dashboard ui on installation

### ISSUE THREAD

**Issue by mirageglobe** [Hygieia/Hygieia#2717]
docker - jdk8/alpine3.8/maven3.6.0
preinstalled nodejs/nodejs-npm/gulp/bower

any pointers will be great.. cheers. following is the log.
...
...
[INFO] com.capitalone.dashboard:UI 3.0.1 .................. FAILURE [  5.829 s]
[INFO] com.capitalone.dashboard:ui-tests 3.0.1 ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:35 min
[INFO] Finished at: 2019-02-06T16:58:25Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project UI: Failed to run task: 'npm install --ignore-scripts' failed. java.io.IOException: Cannot run program "/opt/Hygieia/UI/node/node" (in directory "/opt/Hygieia/UI"): error=2, No such file or directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI
The command '/bin/sh -c mvn clean install package' returned a non-zero code: 1

**Comment by poojithkumar** [comment]
[ERROR] bower angular-animate#~1.5.9                   ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-animate.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-animate.git/': error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
[ERROR]
[ERROR] Additional error details:
[ERROR] fatal: unable to access 'https://github.com/angular/bower-angular-animate.git/': error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia 3.0.1 ............. SUCCESS [  3.316 s]
[INFO] com.capitalone.dashboard:api 3.0.1 ................. SUCCESS [02:24 min]
[INFO] com.capitalone.dashboard:api-audit 3.0.1 ........... SUCCESS [ 47.444 s]
[INFO] com.capitalone.dashboard:nfrr-audit-collector 3.0.1  SUCCESS [ 45.577 s]
[INFO] com.capitalone.dashboard:rally-collector 3.0.1 ..... SUCCESS [ 20.529 s]
[INFO] com.capitalone.dashboard:artifactory-artifact-collector 3.0.1 SUCCESS [ 21.723 s]
[INFO] com.capitalone.dashboard:bamboo-build-collector 3.0.1 SUCCESS [ 17.732 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector 3.0.1 SUCCESS [ 23.673 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector 3.0.1 SUCCESS [ 13.677 s]
[INFO] com.capitalone.dashboard:jenkins-codequality 3.0.1 . SUCCESS [ 27.763 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector 3.0.1 SUCCESS [ 18.255 s]
[INFO] com.capitalone.dashboard:aws-cloud-collector 3.0.1 . SUCCESS [ 25.502 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector 3.0.1 SUCCESS [ 15.624 s]
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector 3.0.1 SUCCESS [ 14.841 s]
[INFO] com.capitalone.dashboard:jira-feature-collector 3.0.1 SUCCESS [ 51.884 s]
[INFO] com.capitalone.dashboard:versionone-feature-collector 3.0.1 SUCCESS [ 18.886 s]
[INFO] com.capitalone.dashboard:gitlab-feature-collector 3.0.1 SUCCESS [ 27.375 s]
[INFO] com.capitalone.dashboard:chat-ops-collector 3.0.1 .. SUCCESS [  6.135 s]
[INFO] com.capitalone.dashboard:appdynamics-performance-collector 3.0.1 SUCCESS [ 17.068 s]
[INFO] com.capitalone.dashboard:bitbucket-scm-collector 3.0.1 SUCCESS [ 16.540 s]
[INFO] com.capitalone.dashboard:github-scm-collector 3.0.1  SUCCESS [ 25.235 s]
[INFO] com.capitalone.dashboard:github-graphql-scm-collector 3.0.1 SUCCESS [ 24.890 s]
[INFO] com.capitalone.dashboard:subversion-collector 3.0.1  SUCCESS [  7.485 s]
[INFO] com.capitalone.dashboard:gitlab-scm-collector 3.0.1  SUCCESS [ 19.353 s]
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector 3.0.1 . SUCCESS [ 19.401 s]
[INFO] com.capitalone.dashboard:nexus-iq-collector 3.0.1 .. SUCCESS [ 16.523 s]
[INFO] com.capitalone.dashboard:score-collector 3.0.1 ..... SUCCESS [ 25.768 s]
[INFO] com.capitalone.dashboard:jira-xray-testresult-collector 3.0.1 SUCCESS [ 46.610 s]
[INFO] Hygieia Publisher Plugin 2.1.9-SNAPSHOT ............ SUCCESS [03:00 min]
[INFO] com.capitalone.dashboard:UI 3.0.1 .................. FAILURE [ 47.284 s]
[INFO] com.capitalone.dashboard:ui-tests 3.0.1 ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:43 min
[INFO] Finished at: 2019-02-07T10:05:09+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:bower (bower install) on project UI: Failed to run task: 'bower install --config.proxy=http://web-proxy.eu.softwaregrp.net:8080' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI






help me to solve this

**Comment by mirageglobe** [comment]
> [ERROR] bower angular-animate#~1.5.9 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-animate.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-animate.git/': error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
> [ERROR]
> [ERROR] Additional error details:
> [ERROR] fatal: unable to access 'https://github.com/angular/bower-angular-animate.git/': error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] com.capitalone.dashboard:Hygieia 3.0.1 ............. SUCCESS [ 3.316 s]
> [INFO] com.capitalone.dashboard:api 3.0.1 ................. SUCCESS [02:24 min]
> [INFO] com.capitalone.dashboard:api-audit 3.0.1 ........... SUCCESS [ 47.444 s]
> [INFO] com.capitalone.dashboard:nfrr-audit-collector 3.0.1 SUCCESS [ 45.577 s]
> [INFO] com.capitalone.dashboard:rally-collector 3.0.1 ..... SUCCESS [ 20.529 s]
> [INFO] com.capitalone.dashboard:artifactory-artifact-collector 3.0.1 SUCCESS [ 21.723 s]
> [INFO] com.capitalone.dashboard:bamboo-build-collector 3.0.1 SUCCESS [ 17.732 s]
> [INFO] com.capitalone.dashboard:jenkins-build-collector 3.0.1 SUCCESS [ 23.673 s]
> [INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector 3.0.1 SUCCESS [ 13.677 s]
> [INFO] com.capitalone.dashboard:jenkins-codequality 3.0.1 . SUCCESS [ 27.763 s]
> [INFO] com.capitalone.dashboard:sonar-codequality-collector 3.0.1 SUCCESS [ 18.255 s]
> [INFO] com.capitalone.dashboard:aws-cloud-collector 3.0.1 . SUCCESS [ 25.502 s]
> [INFO] com.capitalone.dashboard:udeploy-deployment-collector 3.0.1 SUCCESS [ 15.624 s]
> [INFO] com.capitalone.dashboard:xldeploy-deployment-collector 3.0.1 SUCCESS [ 14.841 s]
> [INFO] com.capitalone.dashboard:jira-feature-collector 3.0.1 SUCCESS [ 51.884 s]
> [INFO] com.capitalone.dashboard:versionone-feature-collector 3.0.1 SUCCESS [ 18.886 s]
> [INFO] com.capitalone.dashboard:gitlab-feature-collector 3.0.1 SUCCESS [ 27.375 s]
> [INFO] com.capitalone.dashboard:chat-ops-collector 3.0.1 .. SUCCESS [ 6.135 s]
> [INFO] com.capitalone.dashboard:appdynamics-performance-collector 3.0.1 SUCCESS [ 17.068 s]
> [INFO] com.capitalone.dashboard:bitbucket-scm-collector 3.0.1 SUCCESS [ 16.540 s]
> [INFO] com.capitalone.dashboard:github-scm-collector 3.0.1 SUCCESS [ 25.235 s]
> [INFO] com.capitalone.dashboard:github-graphql-scm-collector 3.0.1 SUCCESS [ 24.890 s]
> [INFO] com.capitalone.dashboard:subversion-collector 3.0.1 SUCCESS [ 7.485 s]
> [INFO] com.capitalone.dashboard:gitlab-scm-collector 3.0.1 SUCCESS [ 19.353 s]
> [INFO] com.capitalone.dashboard:hpsm-cmdb-collector 3.0.1 . SUCCESS [ 19.401 s]
> [INFO] com.capitalone.dashboard:nexus-iq-collector 3.0.1 .. SUCCESS [ 16.523 s]
> [INFO] com.capitalone.dashboard:score-collector 3.0.1 ..... SUCCESS [ 25.768 s]
> [INFO] com.capitalone.dashboard:jira-xray-testresult-collector 3.0.1 SUCCESS [ 46.610 s]
> [INFO] Hygieia Publisher Plugin 2.1.9-SNAPSHOT ............ SUCCESS [03:00 min]
> [INFO] com.capitalone.dashboard:UI 3.0.1 .................. FAILURE [ 47.284 s]
> [INFO] com.capitalone.dashboard:ui-tests 3.0.1 ............ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 16:43 min
> [INFO] Finished at: 2019-02-07T10:05:09+05:30
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:bower (bower install) on project UI: Failed to run task: 'bower install --config.proxy=http://web-proxy.eu.softwaregrp.net:8080' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :UI
> 
> help me to solve this

Hi kurma. yours looks like git is unable to access the url. you sure if its not timed out/firewall .. might be worth trying to run from another connection.

@all if anyone can help in ^ the node issue (its already installed but why is it trying to run node/node?) thanks

**Comment by poojithkumar** [comment]
I tried from another also...it didn't work too...

**Comment by rvema** [comment]
@andrewalvintran Can you look into this issue?

**Comment by mirageglobe** [comment]
Just an update to help.. it seems that the issue is caused by the npm plugin defined in pom.xml (UI/pom.xml)

I disabled the installation by (frontend-maven-plugin) and manually installed npm/bower/gulp as well as running gulp before mvn clean install package (run in both UI and root)
  <properties>
    <frontend-maven-plugin.skip>true</frontend-maven-plugin.skip>
  </properties>

the issue is noted in the following maven plugin (allowing running executables in maven project)
https://github.com/mojohaus/exec-maven-plugin/issues/111

Problem: node nor bower/gulp is unable to be executed via maven for some reason. manual execution is possible.
