### ISSUE TITLE
Hygieia backend setup failure

### ISSUE THREAD

**Issue by poojithkumar** [Hygieia/Hygieia#2720]
ile:/C:/opt/Hygieia-master/api/target/api.jar!/lib/jjwt-0.6.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/jackson-databind-2.5.0.jar!/, jar:file:/C:/ opt/Hygieia-master/api/target/api.jar!/lib/jackson-annotations-2.5.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/jackson-core-2.5.0.jar!/, jar:file:/C:/o pt/Hygieia-master/api/target/api.jar!/lib/jackson-core-asl-1.9.13.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/jackson-mapper-asl-1.9.13.jar!/, jar:file:/ C:/opt/Hygieia-master/api/target/api.jar!/lib/logback-classic-1.1.3.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/logback-core-1.1.3.jar!/, jar:file:/C:/op t/Hygieia-master/api/target/api.jar!/lib/slf4j-api-1.7.13.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/commons-lang-2.6.jar!/, jar:file:/C:/opt/Hygieia-ma ster/api/target/api.jar!/lib/guava-18.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/joda-time-2.7.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.j ar!/lib/springfox-swagger2-2.4.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/swagger-annotations-1.5.6.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/ api.jar!/lib/swagger-models-1.5.6.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/springfox-spi-2.4.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.j ar!/lib/springfox-core-2.4.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/springfox-schema-2.4.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar !/lib/springfox-swagger-common-2.4.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/springfox-spring-web-2.4.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/ta rget/api.jar!/lib/spring-plugin-core-1.2.0.RELEASE.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/spring-plugin-metadata-1.2.0.RELEASE.jar!/, jar:file:/C:/o pt/Hygieia-master/api/target/api.jar!/lib/springfox-swagger-ui-2.4.0.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/classmate-1.3.1.jar!/, jar:file:/C:/opt/ Hygieia-master/api/target/api.jar!/lib/joda-convert-1.8.1.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/commons-io-2.1.jar!/, jar:file:/C:/opt/Hygieia-mast er/api/target/api.jar!/lib/commons-beanutils-1.9.2.jar!/, jar:file:/C:/opt/Hygieia-master/api/target/api.jar!/lib/commons-collections-3.2.1.jar!/]                           2019-02-08 21:50:23,743 ERROR o.s.boot.SpringApplication - Application startup failed                                                                                        org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat servlet container                                                       at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:165) ~[spring-boot-1.3.0.RELEASE.jar!/: 1.3.0.RELEASE]                                                                                                                                                                       at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:290) ~[spring-boot-1.3.0 .RELEASE.jar!/:1.3.0.RELEASE]                                                                                                                                                        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141) ~[spring-boot-1.3.0.RELEASE.jar!/:1 .3.0.RELEASE]                                                                                                                                                                        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.R ELEASE]                                                                                                                                                                              at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]                                           at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]                                             at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) ~[spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]                                               at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]                          at com.capitalone.dashboard.Application.main(Application.java:37) [api.jar!/:3.0.1]                                                                                          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]                                                                                               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]                                                                                               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_201]                                                                                           at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_201]                                                                                                           at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [api.jar!/:3.0.1]                                                                          at java.lang.Thread.run(Unknown Source) [na:1.8.0_201]                                                                                                               Caused by: java.lang.IllegalStateException: Tomcat connector in failed state                                                                                                         at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:159) ~[spring-boot-1.3.0.RELEASE.jar!/: 1.3.0.RELEASE]                                                                                                                                                                       ... 15 common frames omitted                                                                                                                                         java.lang.reflect.InvocationTargetException                                                                                                                                          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                                                                                                               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                                                                                                           at java.lang.reflect.Method.invoke(Unknown Source)                                                                                                                           at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)                                                                                            at java.lang.Thread.run(Unknown Source)                                                                                                                              Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat servlet container                                            at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:165)                                            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:290)                             at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)                                             at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)                                                               at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)                                                   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)                                                                                            at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347)                                                                                              at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)                                                                                                at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)                                                                          at com.capitalone.dashboard.Application.main(Application.java:37)                                                                                                            ... 6 more                                                                                                                                                           Caused by: java.lang.IllegalStateException: Tomcat connector in failed state                                                                                                         at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:159)                                            ... 15 more
--

command used:
java -jar api.jar --spring.config.location=C:\opt\Hygieia-master\api\dashboard.properties -Djasypt.encryptor.password=hygieiasecret

help me solve the problem.
Thank you

**Comment by rvema** [comment]
Can you try with 

> java -Djasypt.encryptor.password=hygieiasecret -jar api.jar --spring.config.location=C:\opt\Hygieia-master\api\dashboard.properties

**Comment by rvema** [comment]
Also do check the contents of the dashboard.properties file. If possible paste it here which helps in debugging the issue.
