### ISSUE TITLE
standard login and Ldap login in hygieia 

### ISSUE THREAD

**Issue by vkg1234** [Hygieia/Hygieia#2723]
Hi , can you tell me how standard login and ldap login work in hygieia . which file are used for standard login and ldap login in UI and Api

**Comment by nireeshT** [comment]
@vkg1234  standard login is authentication/authorization provided with in Hygieia(i.e sign up users via UI in Hygiea) User data is store in MongoDB connected to Hygieia instance. You can also integrate Hygieia with LDAP (aka SSO) with your organization active directory. Refer https://github.com/Hygieia/Hygieia/issues/1731 for LDAP configuration
