### ISSUE TITLE
> `http://localhost:8080/api/collector/type/SCM` navigate here. What does this return?

### ISSUE THREAD

**Issue by poojithkumar** [Hygieia/Hygieia#2729]
> `http://localhost:8080/api/collector/type/SCM` navigate here. What does this return?

i have done this 
getting a json format but in that got **string** type repo.
want github type repo...

HELP!!

_Originally posted by @Sharmakartik in https://github.com/Hygieia/Hygieia/issues/2639#issuecomment-448313764_

hey .when i run above command i get
[]

**Comment by Sbrenthughes** [comment]
Can you update this with information about an actual issue please? The above could happen for many reasons. Without more information we cannot help.

**Comment by Sbrenthughes** [comment]
Please reopen and provide answers to the listed questions.
