### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project api: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find resource '${pr oject.parent.basedir}/pmd.xml'

### ISSUE THREAD

**Issue by varshinichowdary27** [Hygieia/Hygieia#2743]
Not able to exceute mvn install, throwing below error.

[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ api ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:api ....................... FAILURE [  4.327 s]
[INFO] com.capitalone.dashboard:api-audit ................. SKIPPED
[INFO] com.capitalone.dashboard:nfrr-audit-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:rally-collector ........... SKIPPED
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SKIPPED
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SKIPPED
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:score-collector ........... SKIPPED
[INFO] com.capitalone.dashboard:jira-xray-testresult-collector SKIPPED
[INFO] Hygieia Publisher Plugin ........................... SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] com.capitalone:dashboard ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.388 s
[INFO] Finished at: 2019-02-22T13:03:52+05:30
[INFO] Final Memory: 108M/770M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project api: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find resource '${pr
oject.parent.basedir}/pmd.xml'. -> [Help 1]

**Comment by rvema** [comment]
Can you ensure you have the latest hygieia-core and hygieia projects?

**Comment by varshinichowdary27** [comment]
Installed the latest version of hygieia core and hygieia master from github.
Also can you please specify the project structure of entire hygieia project.

**Comment by rvema** [comment]
can you explain - `installed the latest version`?

**Comment by varshinichowdary27** [comment]
yes, i am cloning from github

**Comment by rvema** [comment]
I am unable to recreate this issue, I just cloned both the repos and did `mvn clean install -U` without any issues. here are my java and maven versions 

> `mvn--version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
Maven home: /usr/local/Cellar/maven@3.5/3.5.4/libexec
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"`

**Comment by varshinichowdary27** [comment]
i am facing this issue while mvn clean install ( hygieia-master )
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project api: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find resource '${pr
oject.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project api-audit: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find resource
 '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project nfrr-audit-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not fi
nd resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project rally-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find re
source '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project artifactory-artifact-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Co
uld not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project bamboo-build-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not
find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project jenkins-build-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not
 find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project jenkins-cucumber-test-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: C
ould not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project jenkins-codequality: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not fin
d resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project sonar-codequality-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could
 not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project aws-cloud-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not fin
d resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project udeploy-deployment-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Coul
d not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project xldeploy-deployment-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Cou
ld not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project jira-feature-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not
find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project versionone-feature-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Coul
d not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project gitlab-feature-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could no
t find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project chat-ops-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find
 resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project appdynamics-performance-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException:
 Could not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project bitbucket-scm-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not
 find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project github-scm-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not fi
nd resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project github-graphql-scm-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Coul
d not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project subversion-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not fi
nd resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project gitlab-scm-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not fi
nd resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project hpsm-cmdb-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not fin
d resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project nexus-iq-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find
 resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project score-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Could not find re
source '${project.parent.basedir}/pmd.xml'. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd (pmd) on project jira-xray-testresult-collector: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.6:pmd failed: org.apache.maven.reporting.MavenReportException: Co
uld not find resource '${project.parent.basedir}/pmd.xml'. -> [Help 1]

**Comment by varshinichowdary27** [comment]
is it possible for you to provide hygieia core and hygieia master jars.

**Comment by geetha19983b** [comment]
I am also facing exact issue in the rally collector during initial build of Hygiea master.Can you please let me know what is the solution
![rallycollector](https://user-images.githubusercontent.com/10776102/53853794-ec409d00-3fec-11e9-92ed-78de011214b8.png)

**Comment by poojithkumar** [comment]
go to hygieia core directory first clean and run ( mvn clean install ).
then run hygieia  .
@varshinichowdary27  i think you are not run the hygieia core.

**Comment by sundeepk1** [comment]
[INFO] Reactor Summary:
[INFO]
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  3.814 s]
[INFO] com.capitalone.dashboard:api ....................... FAILURE [ 52.108 s]
[INFO] com.capitalone.dashboard:api-audit ................. SKIPPED
[INFO] com.capitalone.dashboard:nfrr-audit-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:rally-collector ........... SKIPPED
[INFO] com.capitalone.dashboard:artifactory-artifact-collector SKIPPED
[INFO] com.capitalone.dashboard:bamboo-build-collector .... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SKIPPED
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SKIPPED
[INFO] com.capitalone.dashboard:jenkins-codequality ....... SKIPPED
[INFO] com.capitalone.dashboard:sonar-codequality-collector SKIPPED
[INFO] com.capitalone.dashboard:aws-cloud-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:xldeploy-deployment-collector SKIPPED
[INFO] com.capitalone.dashboard:jira-feature-collector .... SKIPPED
[INFO] com.capitalone.dashboard:versionone-feature-collector SKIPPED
[INFO] com.capitalone.dashboard:gitlab-feature-collector .. SKIPPED
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:appdynamics-performance-collector SKIPPED
[INFO] com.capitalone.dashboard:bitbucket-scm-collector ... SKIPPED
[INFO] com.capitalone.dashboard:github-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:github-graphql-scm-collector SKIPPED
[INFO] com.capitalone.dashboard:subversion-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:gitlab-scm-collector ...... SKIPPED
[INFO] com.capitalone.dashboard:hpsm-cmdb-collector ....... SKIPPED
[INFO] com.capitalone.dashboard:nexus-iq-collector ........ SKIPPED
[INFO] com.capitalone.dashboard:score-collector ........... SKIPPED
[INFO] com.capitalone.dashboard:jira-xray-testresult-collector SKIPPED
[INFO] Hygieia Publisher Plugin ........................... SKIPPED
[INFO] com.capitalone.dashboard:UI ........................ SKIPPED
[INFO] com.capitalone.dashboard:ui-tests .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:48 min
[INFO] Finished at: 2019-04-02T02:13:45Z
[INFO] Final Memory: 69M/234M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project api: There are test failures.
[ERROR]
[ERROR] Please refer to /home/vagrant/WORKDIR/Hygieia/api/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api
vagrant@ubuntu-bionic:~/WORKDIR/Hygieia$

**Comment by sundeepk1** [comment]
I am getting the above build failure

**Comment by poojithkumar** [comment]
Run the core and check the jar file in .m2 folder

**Comment by rvema** [comment]
@varshinichowdary27 and @sundeepk1 are you still having an issue with the above?

**Comment by sundeepk1** [comment]
I am not sure as what caused the error, Below were the steps that I took to have a successful build.

1. Deleted the directory
2. removed the installed java version
3. installed openjdk-8-jdk and openjdk-8-jre 
4. cloned the repo again
5. ran the mvn build commands

this time it was successful .

**Comment by rvema** [comment]
Closing the issue as build was successful.
