### ISSUE TITLE
Opensource library_policy collection sample json data

### ISSUE THREAD

**Issue by rikameajay1** [Hygieia/Hygieia#2744]
Hi can anyone provide me sample json data of library_policy collection.
I require it for setting up exec-dashboard.
I havent configured open-source collector so I dont have any data for library_policy and running exec-analysis jar is throws error since I dnt have library_policy.

**Comment by Sbrenthughes** [comment]
I am planning on submitting a PR to address this issue today.

**Comment by Sbrenthughes** [comment]
Here is the open PR. Should be merged today. Closing this issue.

https://github.com/Hygieia/ExecDashboard/pull/39
