### ISSUE TITLE
error while building through repo 

### ISSUE THREAD

**Issue by eliyahasan** [Hygieia/Hygieia#2754]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project hygieia-publisher: ExecutionException; nested exception is java.util.concurrent.ExecutionException: java.lang.RuntimeException: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command wascmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_191\jre\bin\java" -javaagent:C:\\Users\\Hp\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=D:\\Foree\\Hygeia\\Hygieia\\hygieia-jenkins-plugin\\target\\jacoco.exec -jar D:\Foree\Hygeia\Hygieia\hygieia-jenkins-plugin\target\surefire\surefirebooter2107236746754719281.jar D:\Foree\Hygeia\Hygieia\hygieia-jenkins-plugin\target\surefire\surefire8152455453918882943tmp D:\Foree\Hygeia\Hygieia\hygieia-jenkins-plugin\target\surefire\surefire_06774596843793472068tmp"
[ERROR] -> [Help 1]

**Comment by kheinz04** [comment]
Do you have the latest version of the code?

**Comment by eliyahasan** [comment]
$ /d/user/Hygeia/hygieia (master)
$ git pull
Already up to date.

**Comment by kheinz04** [comment]
We recently updated the project to remove bower so there may be some dependency issues. Try deleting 'node_modules', 'dist', and 'bower_components' from your UI folder manually, then try rebuilding. This should force your project to use the latest set of dependencies. You can also make sure npm is up to date by running 'npm update'.

Also make sure you have the latest version of the core downloaded and built.
We recommend having the latest version of node as well.

These were the resolutions to the main issues our team was having after the update. Let us know if you are still having problems after trying these out.

**Comment by nireeshT** [comment]
@eliyahasan  what triggered this failure ?

**Comment by Sbrenthughes** [comment]
Closed for no response in 27 days
