### ISSUE TITLE
Hygieia: Jenkins code quality collector not showing jobs

### ISSUE THREAD

**Issue by yash4necro** [Hygieia/Hygieia#2765]
I am using Jenkins to display jacaco/junit build data in my Hygieia Dashboard. 
My jenkins build shows the Code Coverage Trend and Test Result Trend. 
My application.properties file is as below:

> dbname=dashboarddb
dbhost=localhost
dbusername=dashboarduser
dbpassword=dbpassword
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
jenkins-codequality.servers[0]=http://localhost:8080/
jenkins-codequality.cron=0 0/1 * * * *
jenkins-codequality.artifactRegex.junit=TEST-.*\\.xml
jenkins-codequality.artifactRegex.findbugs=findbugsXml.xml
jenkins-codequality.artifactRegex.pmd=pmd.xml
jenkins-codequality.artifactRegex.checkstyle=checkstyle-result.xml
jenkins-codequality.artifactRegex.jacoco=jacoco.xml
server.port=9091 

Post running the collector I could not see any errors but not data is picked either. The dashboard itself if not showing any jobs running 
![image](https://user-images.githubusercontent.com/24870997/53717220-7833b700-3e7d-11e9-90b0-fd483cf09800.png)

Is it possible to get Junit build data from jenkins to hygieia dashboard?

**Comment by nireeshT** [comment]
@yash4necro share collector error log.
