### ISSUE TITLE
Open Source Contribution process for Hygieia project

### ISSUE THREAD

**Issue by shishirchaturvedi** [Hygieia/Hygieia#2766]
Recently, I started a conversation for my opensource contribution in Hygieia project and I was instructed to remove my copyright (the entity I am representing) section from the source code I wanted to contribute.
In this context, I am opening this issue in a hope that we can solidify OSS contribution process for Hygieia project. 
I have explored some other popular opensource project and how they manage OSS contributions. Here I will take the example of Spring Framework and Apple’s Swift project and highlight their OSS contribution process.

- **Spring Framework**: Spring project enforces contributors to sign [Contributor’s License Agreement](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#code-of-conduct) Please see [Pivotal CLA](https://cla.pivotal.io/about) for more details on why this is needed.

- **Swift**: Contributing guide to swift opensource project can be found in [Swift Contribution Guide]( https://swift.org/contributing/#contributing-code)
Swift project maintainers clearly mention list of copyright headers in the [CONTRIBUTORS.txt](https://swift.org/CONTRIBUTORS.txt) file. This file include all the contributors. Please see their license details [Swift License](https://swift.org/community/#license)

These projects protect copyright and make contributors copyright easily traceable.
Looking forward to collaborating and I am happy to provide additional details on this topic(if required).

@Sbrenthughes @tabladrum

**Comment by Sbrenthughes** [comment]
Can you please provide some examples of outside contributions to those projects which has a copyright that does not belong to that project?

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes I don't think that I will have great visibility into that but I can explore commit history of those projects. As I mentioned Spring Framework asks each contributor to sign CLA and swift project asks to add a generic header along with adding contributors in a CONTRIBUTORS.txt file.

**Comment by tabladrum** [comment]
@SanthiSridharan can you help?

**Comment by testorgsanthi** [comment]
@Tabladrum & @Sbrenthughes  - Thanks for the re-direct. 

Hello Shishir, 

We are reviewing this and will provide a response.

**Comment by shishirchaturvedi** [comment]
@testorgsanthi I am following up on this issue. Do you have any update?

**Comment by shishirchaturvedi** [comment]
@chtompki I have filled up CLA forms but haven't received its web response. It was mentioned on the CLA for that for any future changes will be done through `OpenSource@Capitalone.com` so I have reached out that email. Unfortunately, I haven't received any response from them. Could you please look into it and help me track my CLA form. I need web response(final CLA copy) of my CLA form to review it with my legal team. Thanks.

**Comment by chtompki** [comment]
yep...I'll follow up with them today.

**Comment by shishirchaturvedi** [comment]
@chtompki Great. Thank you.

**Comment by shishirchaturvedi** [comment]
@chtompki Any progress on CLA web response issue?

**Comment by chtompki** [comment]
@sbrenthughes - I think that Shishir has probably gotten things sorted out. Let me know if there’s anything I can do to help move this along

**Comment by shishirchaturvedi** [comment]
@chtompki I have filled up CLA forms but haven't received its web response.

**Comment by Sbrenthughes** [comment]
@SanthiSridharan can you help with this? I’m not really sure the process for this form.

**Comment by SanthiSridharan** [comment]
@shishirchaturvedi You can see the CLA form when you signed it. 
It is available in this link - You can also see this link in the *[Hygieia Document in Contribution section](http://hygieia.github.io/Hygieia/contribute.html)*. 
https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform

Hope this helps.

**Comment by SanthiSridharan** [comment]
@shishirchaturvedi Once you sign the CLA as an individual you can continue to contribute. Hygieia Maintainers can accept your contributions from that point onwards.

**Comment by SanthiSridharan** [comment]
@shishirchaturvedi We do not send any acknowledgement for the CLA signature. Hygieia maintainers will check that you have signed the CLA before they accept the contributions from you.

**Comment by shishirchaturvedi** [comment]
@SanthiSridharan My legal team wants to review the final CLA agreement which I have submitted. Do you have any way of exporting final CLA form which I have submitted?

**Comment by SanthiSridharan** [comment]
HI Shishir , if you see the form that you submitted, it just captures your date and name and your personal details. Otherwise the terms etc ate the same. 
We only capture the response sheet with these details and not save a form with the details.

**Comment by SanthiSridharan** [comment]
Additionally, I can share a snoop shot of your response that is saved in our data store if you send me our email Id for communication. Let me know if that helps.

**Comment by shishirchaturvedi** [comment]
That should work. Please send me snapshot at - shishirchaturvedi.0206@gmail.com.
Thanks.

**Comment by shishirchaturvedi** [comment]
@SanthiSridharan FYI, I haven't received your email yet.

**Comment by SanthiSridharan** [comment]
Hi Shishir - I checked the individual response sheet as well as corporate claims didn’t see your signature.

Did you submit this form ? ( this is the link to individual CLa that is made available by Hygieia in the contribute section) 

https://docs.google.com/forms/d/e/1FAIpQLSfwtl1s6KmpLhCY6CjiY8nFZshDwf_wrmNYx1ahpsNFXXmHKw/viewform

**Comment by shishirchaturvedi** [comment]
@Sbrenthughes I had submitted corporate CLA form using this link: https://docs.google.com/forms/d/e/1FAIpQLSeAbobIPLCVZD_ccgtMWBDAcN68oqbAJBQyDTSAQ1AkYuCp_g/viewform

**Comment by shishirchaturvedi** [comment]
@SanthiSridharan Could you track my CLA forms?

**Comment by SanthiSridharan** [comment]
I have sent you an email response to your query in our mailbox. Hope that answers your questions.

**Comment by rvema** [comment]
@shishirchaturvedi Is this still an issue?

**Comment by shishirchaturvedi** [comment]
This issue is resolved. I will close it.
