### ISSUE TITLE
jenkins/sonar collectors are not able store data in db 

### ISSUE THREAD

**Issue by ansha1** [Hygieia/Hygieia#2773]
I have been facing this issue from quite a long time. Only once, it worked for me when I changed the db with new one. However, after system restart it is again pushing data in db. 
-----------------------------
> show dbs
admin      0.000GB
config     0.000GB
dashboard  0.001GB
testdb     0.000GB
local      0.000GB
>
------------------------------
Here i have created db "testdb" abd used it in api and jenkins collector. Nevertheless, not sure how "dashboard" is created automatically. 
------------------------------------
api.properties
-----------------------------------
dbname=testdb
dbusername=testdb
dbpassword=testdb
dbhost=127.0.0.1
dbport=27017
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
logRequest=false
logSplunkRequest=false
corsEnabled=false
#corsWhitelist=http://domain1.com:port,http://domain2.com:port
#version.number=1.0.0

auth.expirationTime=3600000
======================================
Using mongo 4.0 version 
---------------------------------
application.propertes for jenkins 
---------------------------
# Database Name
dbname=testdb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
#dbreplicaset=[false if you are not using MongoDB replicaset]
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=testdb

# Database Password - default is blank
dbpassword=testdb

# Collector schedule (required)
jenkins.cron=* * * * * *

# The page size
jenkins.pageSize=1000

# The folder depth - default is 10
jenkins.folderDepth=10

# Jenkins server (required) - Can provide multiple
jenkins.servers[0]=http://10.132.209.175:8080/jenkins/

jenkins.usernames[0]=devops
jenkins.apiKeys[0]=***************************

# determines if build console log is collected - defaults to false
jenkins.saveLog=true

# Search criteria enabled via properties (max search criteria = 2)
jenkins.searchFields[0]= options.jobName
jenkins.searchFields[1]= niceName
----------------------------------------------------------------
Note: in Jenkins logs its fetching the number of jobs and new jobs. However, in dB nothing is getting stored. I cannot see drop down for my jobs on dashboard. 

http://10.132.208.173:8080/api/collector/item/type/build/
This url giving blank page with "[]". This is priority issue for me right now i have demo coming next week. Can someone from the hygieia team can setup some time to have a meeting or call to work on this issue. I am looking for a permanent fix. Trust me i have reviewed all tickets raised in your project for this issue. 

I have worked with @Sebastian on my other jira ticket #2685 . It was a coincidence, which worked after switching db.
==================================================

**Comment by ansha1** [comment]
@Sbrenthughes can you please help on this bug ?
Let me know your availability if we can have a webex or call. I work in IST India hours. But if you are available we can setup some time in CST time zone. 

Really appreciate your help on this!

**Comment by Sbrenthughes** [comment]
Sure, let me do some research on how to recreate this and then we can setup sometime.

**Comment by ansha1** [comment]
Sure 
Thanks for your timely response ! looking forward to work with you.

**Comment by ansha1** [comment]
@prateekdevisingh

**Comment by Sbrenthughes** [comment]
@ansha1 can you reach out to me on gitter?

**Comment by Sbrenthughes** [comment]
@ansha1 can you add what you did to fix this and close the issue?

**Comment by ansha1** [comment]
After a long going struggle in resolving this issue, we found collectors were not able to push data in to tables in DB, to fix this we allocated ports to each collector.  We are using Ubuntu 16.04 machine 

we used -Dserver.port=8888 with launch command to allocate specific port to a collector. Further we want to integrate fisheye with hygieia.

**Comment by ansha1** [comment]
Really want to appreciate your efforts @Sbrenthughes

**Comment by HarshitMit** [comment]
@ansha1 Can we have a quick call to discuss about this fix. Just wanted to understand if this is similar to the issue that i'm facing #2801. 

I also work in IST hours and can reach out to you on call if it works for you.
