### ISSUE TITLE
SonarQube Widget Values

### ISSUE THREAD

**Issue by amvda** [Hygieia/Hygieia#2776]
Hi, I'm currently trying to display metrics on my sonar widget. From checking on the DB, I don't see the following being populated:

new_violations
new_critical_violations
new_major_violations
new_blocker_violations

sonar properties file
# For Sonar version 6.3 and above
sonar.metrics[0]=ncloc,violations,new_vulnerabilities,critical_violations,major_violations,blocker_violations,tests,test_success_density,test_errors,test_failures,coverage,line_coverage,sqale_index,alert_status,quality_gate_details,new_violations,new_critical_violations,new_major_violations,new_blocker_violations

Can you please help me understand how I can achieve values on those specific fields?
Thanks.!

**Comment by amvda** [comment]
@Sbrenthughes  - any ideas?

**Comment by amvda** [comment]
From my observation, values for these fields are inside the periods array. Any hint how those can be populated to the DB? Thanks.

**Comment by chrisgallivan** [comment]
We were able to make this work. email me at chris.gallivan@fcagroup.com and I will share how we did it.

**Comment by Sbrenthughes** [comment]
Closing as this is a duplicate of https://github.com/Hygieia/Hygieia/issues/2719. @chrisgallivan Please feel free to contribute back those changes. The community would appreciate it.
