### ISSUE TITLE
Hygieia: Configuring Code Analysis widget with Jacoco Coverage report

### ISSUE THREAD

**Issue by yash4necro** [Hygieia/Hygieia#2792]
Hi
I am trying to publish Jacoco Coverage trend published via Jenkins build on my Hygieia: Code Quality widget.
In Jenkins my Jacoco Code Coverage shows data:
![image](https://user-images.githubusercontent.com/24870997/54532175-27f44300-49ad-11e9-9bbc-1c1bdd8b3522.png)

But is inconsistant with Hygieia: Jenkins-codequality module.

The JSON object I get from Jenkins for code quality is like: 
{"branchCoverage":{"covered":0,"missed":44815,"percentage":0,"percentageFloat":0.0,"total":44815},"classCoverage":{"covered":3,"missed":109,"percentage":3,"percentageFloat":2.6785715,"total":112},"complexityScore":{"covered":13,"missed":24606,"percentage":0,"percentageFloat":0.052804746,"total":24619},"instructionCoverage":{"covered":61,"missed":378392,"percentage":0,"percentageFloat":0.01611825,"total":378453},"lineCoverage":{"covered":27,"missed":68241,"percentage":0,"percentageFloat":0.03955001,"total":68268},"methodCoverage":{"covered":13,"missed":2197,"percentage":1,"percentageFloat":0.5882353,"total":2210}}

Please suggest is it possible to integrate Jenkins jacoco code coverage report with existing Hygieia Code Quality widget 
![image](https://user-images.githubusercontent.com/24870997/54532511-ec0dad80-49ad-11e9-9dac-6b83aaff3226.png)

or I have to create a new collector altogether to display this data.

 Thanks in advance

**Comment by yash4necro** [comment]
Any help appreciated

**Comment by Sbrenthughes** [comment]
Would you be able to paste a copy of .xml generated?

**Comment by yash4necro** [comment]
PFA the attached test results xml.
[report.txt](https://github.com/Hygieia/Hygieia/files/3021392/report.txt)

**Comment by Sbrenthughes** [comment]
@yash4necro Thanks, I am hoping to get to this soon.

**Comment by stevegal** [comment]
If you output your jacoco report in xml it'll load.
