### ISSUE TITLE
udeploy collector

### ISSUE THREAD

**Issue by HarshitMit** [Hygieia/Hygieia#2801]
facing some issues while trying to get the udeploy collector integrated with the dashboard.I am able to see the apps being pulled from udeploy in the logs but the same isn't reflecting in the widget on the dashboard.

We already have a working setup for Jenkins where we are able to view the builds on the build widget but we are facing issues while trying to get that working for udeploy and Bitbucket(public repo)

[udeploy_prop.txt](https://github.com/Hygieia/Hygieia/files/3013341/udeploy_prop.txt)
[udeploy-collector.log](https://github.com/Hygieia/Hygieia/files/3013335/udeploy-collector.log)

**Comment by HarshitMit** [comment]
@Sbrenthughes Can you please take a look.

**Comment by Sbrenthughes** [comment]
If this is local can you comment out `dbreplicaset=false`
and `dbhostport=localhost:27017,127.0.0.1:27017`

**Comment by HarshitMit** [comment]
@Sbrenthughes no, this is not a local deployment. I'm trying to connect it to an udeploy dev of my organization.

I tried commenting out the above mentioned properties but still the same issue 

![image](https://user-images.githubusercontent.com/48964639/55099894-95f3e500-50e6-11e9-9af7-e29b8d34f863.png)

**Comment by HarshitMit** [comment]
@Sbrenthughes 
Now  I can see some of the udeploy applications being in mongodb when I give db.collector_items.find() but still these applications aren't reflecting in the dashboard.

**Comment by cahi** [comment]
I am facing the same problem. which udeploy version are you trying to get data from? I have seen that the requests that are made to udeploy return no results, maybe the API changed from 6.x to 7.x?

**Comment by HarshitMit** [comment]
@cahi  Well, I'm able to fetch the data from udeploy to the mongodb instance but am unable to see that 
 data in the udeploy widget on the dashboard.

**Comment by Sbrenthughes** [comment]
@HarshitMit check out https://github.com/Hygieia/Hygieia/issues/2773. Changing the port it is running on could cause it to place it in the right mongo db.

**Comment by HarshitMit** [comment]
@Sbrenthughes  I am not sure if the data from udeploy is being pushed in the right table in mongodb but I do see the data being present in mongodb when I run **db.collector_items.find()**

{ "_id" : ObjectId("dk12371e"), "_class" : "com.capitalone.dashboard.model.UDeployApplication", "description" : "XXXXX", "enabled" : false, "errors" : [ ], "pushed" : false, "collectorId" : ObjectId("5c52ff606a866d1dfaa8d4b6"), "lastUpdated" : NumberLong(0), "options" : { "applicationId" : "837fae26-314d-4c97-9cea-e6f7376ebfd7", "applicationName" : "xmmdnyz", "instanceUrl" : "https://udeploy.XXXXXXX" } }
{ "_id" : ObjectId("255f571f"), "_class" : "com.capitalone.dashboard.model.UDeployApplication", "description" : "xxxxx", "enabled" : false, "errors" : [ ], "pushed" : false, "collectorId" : ObjectId("5c52ff606a866d1dfaa8d4b6"), "lastUpdated" : NumberLong(0), "options" : { "applicationId" : "192093e5-5466-4457-8d70-25a82cc3361e", "applicationName" : "lmnkjsabf", "instanceUrl" : "https://udeploy.XXXXXXX" } }
{ "_id" : ObjectId("255f5720"), "_class" : "com.capitalone.dashboard.model.UDeployApplication", "description" : "XXX", "enabled" : false, "errors" : [ ], "pushed" : false, "collectorId" : ObjectId("5c52ff606a866d1dfaa8d4b6"), "lastUpdated" : NumberLong(0), "options" : { "applicationId" : "b19569f7-c0d9-453c-8e38-7810c9a27207", "applicationName" : "", "instanceUrl" : "https://udeploy.XXXXXXX" } }

But, I'll still take a look at #2773 and check with @ansha1 to get more insight on the issue.

**Comment by HarshitMit** [comment]
Finally it's working now. Checked out the latest api code changes and that kinda seems to have fixed the issue.
