### ISSUE TITLE
docker containers exited with code 126

### ISSUE THREAD

**Issue by guruprasadsane** [Hygieia/Hygieia#2803]
while running docker-compose up, all the container creation is getting exited with error 
sonar-codequality-collector_1      | /bin/sh: 1: ./properties-builder.sh: Permission denied
appdynamics-collector_1            | /bin/sh: 1: ./properties-builder.sh: Permission denied
gitlab-scm-collector_1             | /bin/sh: 1: ./properties-builder.sh: Permission denied
artifactory-artifact-collector_1   | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_appdynamics-collector_1 exited with code 126
hygieia-app_sonar-codequality-collector_1 exited with code 126
hygieia-app_gitlab-scm-collector_1 exited with code 126
hygieia-app_artifactory-artifact-collector_1 exited with code 126
nexus-iq-collector_1               | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_nexus-iq-collector_1 exited with code 126
jenkins-codequality-collector_1    | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_jenkins-codequality-collector_1 exited with code 126
udeploy-collector_1                | /bin/sh: 1: ./properties-builder.sh: Permission denied
bamboo-build-collector_1           | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_udeploy-collector_1 exited with code 126
hygieia-app_bamboo-build-collector_1 exited with code 126
subversion-collector_1             | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_subversion-collector_1 exited with code 126
versionone-collector_1             | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_versionone-collector_1 exited with code 126
score-collector_1                  | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_score-collector_1 exited with code 126
gitlab-feature-collector_1         | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_gitlab-feature-collector_1 exited with code 126
bitbucket-collector_1              | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_bitbucket-collector_1 exited with code 126
github-graphql-collector_1         | /bin/sh: 1: ./properties-builder.sh: Permission denied
jenkins-build-collector_1          | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_github-graphql-collector_1 exited with code 126
hygieia-app_jenkins-build-collector_1 exited with code 126
chat-ops-collector_1               | /bin/sh: 1: ./properties-builder.sh: Permission denied
jira-collector_1                   | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_chat-ops-collector_1 exited with code 126
github-collector_1                 | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_jira-collector_1 exited with code 126
hygieia-app_github-collector_1 exited with code 126
xldeploy-collector_1               | /bin/sh: 1: ./properties-builder.sh: Permission denied
jenkins-cucumber-test-collector_1  | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_xldeploy-collector_1 exited with code 126
hygieia-app_jenkins-cucumber-test-collector_1 exited with code 126
hpsm-cmdb-collector_1              | /bin/sh: 1: ./properties-builder.sh: Permission denied
api_1                              | /bin/sh: 1: ./properties-builder.sh: Permission denied
hygieia-app_hpsm-cmdb-collector_1 exited with code 126
hygieia-app_api_1 exited with code 126

**Comment by guruprasadsane** [comment]
Fixed it by making changes to Dockerfile. closing.

**Comment by JFDonaghy** [comment]
Hi @guruprasadsane,

Do you mind sharing what changes you made to Dockerfile? I'm having a similar issue and I'm not sure what to fix. Thanks!

**Comment by GeorgesBat** [comment]
hi @guruprasadsane , do you mind sharing the changes as well
@JFDonaghy  did you manage to find what changes needed to be done?

**Comment by rvema** [comment]
If you find the solution, please contribute back by creating a PR for the same.

**Comment by GeorgesBat** [comment]
@rvema I did not
@guruprasadsane apparently did and it's an old issue
he made changes to the Dockerfile but did not share them...

**Comment by GeorgesBat** [comment]
> Fixed it by making changes to Dockerfile. closing.
@guruprasadsane can you please reopen the PR or comment how you managed to solve it?
thank you
