### ISSUE TITLE
Issue when installing hygieia with docker-compose

### ISSUE THREAD

**Issue by arunmk108** [Hygieia/Hygieia#2805]
[docker-compose.override.hygieia.yml.txt](https://github.com/Hygieia/Hygieia/files/3024625/docker-compose.override.hygieia.yml.txt)
[docker-compose.yml.txt](https://github.com/Hygieia/Hygieia/files/3024626/docker-compose.yml.txt)

Hi 
Today i have cloned latest code from github repo(### https://github.com/Hygieia/Hygieia). Before docker compose command, i just done one change in override file(### docker-compose-override.hygieia.yml

) i.e. added one collector(jenkins) environment details like below.
###   jenkins-build-collector:
      environment:
        - JENKINS_CRON= 0 * * * * *
        - JENKINS_MASTER= http://awszzzz.com:8080
        - JENKINS_USERNAME= admin
        - JENKINS_API_KEY=zzzz
and then ran a docker-compose build command(docker-compose up -d) to install,
but iam endup with below error. Can anyone please help on this.
Attached my docker yaml files above for reference. Thanks

[hygieia@awsawsxxx01 ~]$ git clone https://github.com/Hygieia/Hygieia.git
Cloning into 'Hygieia'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 40253 (delta 2), reused 14 (delta 1), pack-reused 40224
Receiving objects: 100% (40253/40253), 72.23 MiB | 7.09 MiB/s, done.
Resolving deltas: 100% (18137/18137), done.
[hygieia@awsxxx01 ~]$ ls
[hygieia@awsxxx01 ~]$ cd Hygieia/
[hygieia@awsxxx01 Hygieia]$ mv docker-compose.override.yml docker-compose.override.hygieia.yml
[hygieia@awsxxx01 Hygieia]$ nano docker-compose.override.hygieia.yml
[root@awsxxx01 Hygieia]# ll
drwxrwxr-x.  4 hygieia hygieia   117 Mar 29 16:55 api
drwxrwxr-x.  4 hygieia hygieia   120 Mar 29 16:55 api-audit
drwxrwxr-x.  2 hygieia hygieia    23 Mar 29 16:55 certs
-rw-rw-r--.  1 hygieia hygieia   553 Mar 29 16:55 CHANGELOG.md
-rw-rw-r--.  1 hygieia hygieia  7956 Mar 29 16:55 checkstyle.xml
-rw-rw-r--.  1 hygieia hygieia   903 Mar 29 16:55 circle.yml
drwxrwxr-x. 14 hygieia hygieia   221 Mar 29 16:55 collectors
drwxrwxr-x.  2 hygieia hygieia    62 Mar 29 16:55 db
-rw-rw-r--.  1 hygieia hygieia  1478 Mar 29 17:00 docker-compose.override.hygieia.yml
-rw-rw-r--.  1 hygieia hygieia  3745 Mar 29 16:55 docker-compose.yml
-rw-rw-r--.  1 hygieia hygieia   271 Mar 29 16:55 Dockerfile
-rw-rw-r--.  1 hygieia hygieia   146 Mar 29 16:55 features.md
-rw-rw-r--.  1 hygieia hygieia   146 Mar 29 16:55 Hygieia2.md
drwxrwxr-x.  3 hygieia hygieia   120 Mar 29 16:55 hygieia-jenkins-plugin
-rw-rw-r--.  1 hygieia hygieia  3457 Mar 29 16:55 hygieia.json
-rw-rw-r--.  1 hygieia hygieia 11357 Mar 29 16:55 LICENSE
-rw-rw-r--.  1 hygieia hygieia    36 Mar 29 16:55 MAINTAINERS
drwxrwxr-x.  3 hygieia hygieia    37 Mar 29 16:55 media
-rw-rw-r--.  1 hygieia hygieia   212 Mar 29 16:55 mongosrc.js
-rwxrwxr-x.  1 hygieia hygieia  7112 Mar 29 16:55 mvnw
-rw-rw-r--.  1 hygieia hygieia  5186 Mar 29 16:55 mvnw.cmd
-rw-rw-r--.  1 hygieia hygieia    27 Mar 29 16:55 package-lock.json
-rw-rw-r--.  1 hygieia hygieia  4113 Mar 29 16:55 pmd.xml
-rw-rw-r--.  1 hygieia hygieia 11126 Mar 29 16:55 pom.xml
-rw-rw-r--.  1 hygieia hygieia  4687 Mar 29 16:55 README.md
-rw-rw-r--.  1 hygieia hygieia   145 Mar 29 16:55 release.md
-rwxrwxr-x.  1 hygieia hygieia   231 Mar 29 16:55 rev-version.sh
-rw-rw-r--.  1 hygieia hygieia   143 Mar 29 16:55 Setup.md
drwxrwxr-x.  4 hygieia hygieia    34 Mar 29 16:55 test-servers
drwxrwxr-x.  2 hygieia hygieia    98 Mar 29 16:55 travis-utilities
drwxrwxr-x.  6 hygieia hygieia   187 Mar 29 16:55 UI
drwxrwxr-x.  3 hygieia hygieia   113 Mar 29 16:55 UI-protractor-tests
drwxrwxr-x.  3 hygieia hygieia   155 Mar 29 16:55 UI-tests
-rwxrwxr-x.  1 hygieia hygieia    87 Mar 29 16:55 wrap.sh

[root@awsxxx01 Hygieia]# **docker-compose up -d**
Creating network "hygieia_default" with the default driver
Creating volume "hygieia_db-data" with default driver
Creating volume "hygieia_certs" with default driver
Pulling db (mongo:latest)...
latest: Pulling from library/mongo
34667c7e4631: Already exists
d18d76a881a4: Already exists
119c7358fbfc: Already exists
2aaf13f3eff0: Already exists
f7833eaffdda: Pull complete
8287cb5b9daf: Pull complete
ea00040a145a: Pull complete
eeb70119a2ba: Pull complete
066b6bd644f8: Pull complete
17862d4a3122: Pull complete
1cdcc815e975: Pull complete
73e0e2953af7: Pull complete
f719605a4369: Pull complete
Digest: sha256:07b8ccd32d40f47892ff5d074626cb9a866f49742658ce872dd1095cb51d9264
Status: Downloaded newer image for mongo:latest
Building db-setup
Step 1/6 : FROM mongo:latest
 ---> 0d183f48c313
Step 2/6 : ADD db-setup.sh /tmp/db-setup.sh
 ---> 681dc3cc5b28
Step 3/6 : ADD db-setup.js /tmp/db-setup.js
 ---> 8532d0b0f342
Step 4/6 : RUN chmod +x /tmp/db-setup.sh
 ---> Running in ea0944f063cb
Removing intermediate container ea0944f063cb
 ---> 40d519ced14f
Step 5/6 : RUN chmod +x /tmp/db-setup.js
 ---> Running in e7983893f54c
Removing intermediate container e7983893f54c
 ---> 4c7d5020a136
Step 6/6 : CMD ["/tmp/db-setup.sh"]
 ---> Running in 74ed6a729d50
Removing intermediate container 74ed6a729d50
 ---> c7e2d82fb3dc
Successfully built c7e2d82fb3dc
Successfully tagged hygieia_db-setup:latest
WARNING: Image for service db-setup was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building api
Step 1/9 : FROM openjdk:8-jre
8-jre: Pulling from library/openjdk
e79bb959ec00: Pull complete
d4b7902036fe: Pull complete
1b2a72d4e030: Pull complete
de423484a946: Pull complete
ceaac3b844f7: Pull complete
88f01b722a52: Pull complete
c23be56a9ac1: Pull complete
Digest: sha256:e69c4d4ab747eba05dd839d8a23eb42afe6491e14c10fb4e4119263bca74d525
Status: Downloaded newer image for openjdk:8-jre
 ---> d55d64383c12
Step 2/9 : VOLUME ["/hygieia/logs"]
 ---> Running in 3bef1f24c853
Removing intermediate container 3bef1f24c853
 ---> 0bab874fc9b6
Step 3/9 : RUN mkdir /hygieia/config
 ---> Running in 08d8cc4ff2f8
Removing intermediate container 08d8cc4ff2f8
 ---> 207fc7f992f7
Step 4/9 : EXPOSE 8080
 ---> Running in 3775ed8e0a26
Removing intermediate container 3775ed8e0a26
 ---> d51d46d84761
Step 5/9 : ENV PROP_FILE /hygieia/config/application.properties
 ---> Running in dc4ba4dfdeba
Removing intermediate container dc4ba4dfdeba
 ---> 7002f3dfabaa
Step 6/9 : WORKDIR /hygieia
 ---> Running in ccfc5226e307
Removing intermediate container ccfc5226e307
 ---> 6dda748ba749
**Step 7/9 : COPY target/*.jar /hygieia
ERROR: Service 'api' failed to build: COPY failed: no source files were specified**
[root@awsxxx01 Hygieia]#

**Comment by arunmk108** [comment]
Got the point. We needs to build the code first and create the jar files before running the docker-compose file. Rest of the things, compose file will take care.
![image](https://user-images.githubusercontent.com/28533803/55271401-83aeae00-5282-11e9-9356-0585b8f7337f.png)
![image](https://user-images.githubusercontent.com/28533803/55271413-b3f64c80-5282-11e9-8db1-d734608b373d.png)

**Comment by larsen-mallick** [comment]
I get the below error when trying to run Hygieia on Docker in Windows 10 -

\Hygieia>docker-compose up
ERROR: Service 'ui' depends on service 'api' which is undefined.

I have completed all the prior steps and including mvn clean install.

**Comment by rvema** [comment]
@larsen-mallick the docker compose is broken , we need help with fixing it. contribute back if you have bandwidth
