### ISSUE TITLE
Hygieia - MongDB connection refused

### ISSUE THREAD

**Issue by mySphere** [Hygieia/Hygieia#2815]
Hi,
I ran the docker compose up and getting exit code 1 for most of the collectors.  I think the connectivity with MongoDB is not working for all collectors.  I was able to validate the mongod and mongo connections working outside of docker.  Below is the log  output for hygieia_db_setup container with exit code 1.  Any help appreciated.

MongoDB shell version v4.0.6
connecting to: mongodb://db:27017/admin?gssapiServiceName=mongodb
2019-04-03T01:15:06.946+0000 E QUERY    [js] Error: couldn't connect to server db:27017, connection attempt failed: SocketException: Error connecting to db:27017 (172.18.0.2:27017) :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:343:13
@(connect):1:6
exception: connect failed

![image](https://user-images.githubusercontent.com/47803497/55448385-8c122c00-5595-11e9-9527-4719d6305203.png)

**Comment by rvema** [comment]
Currently we have tested Hygieia with Mongo v3.4. We are yet to check the compatibility with 4.x, Is it possible for you to use Mongo3.4?

**Comment by mySphere** [comment]
Oh didn’t realize Mongodb “version” could be the issue.  Trying a fresh install of 4.0 to see if it works, otherwise will install 3.4 next.  I have spent a lot of time debugging several issues with 4.0 - is the version specific issue/resolution noted anywhere, git or elsewhere?  Maybe I missed a note that Hygieia currently works or is tested with 3.4 only.

Thanks for your response.

**Comment by Sbrenthughes** [comment]
Closing this since you have opened a new issue.
