### ISSUE TITLE
How to configure artifactory widget?

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [Hygieia/Hygieia#2817]
Can any body help me how to configure widget on ui i am not able to find any widget on ui like artifact.

**Comment by Sbrenthughes** [comment]
Currently there is no artifactory Widget.

**Comment by gopiprasanthpotipireddy** [comment]
why there is a collector called artifactory and how can we consume it?

**Comment by Sbrenthughes** [comment]
We have this issue noted here https://github.com/Hygieia/Hygieia/issues/2075. As a duplicate to https://github.com/Hygieia/Hygieia/issues/2075
