### ISSUE TITLE
Rally Collector configuration values are not stored in Mongo Database

### ISSUE THREAD

**Issue by nitingoyal8** [Hygieia/Hygieia#2819]
I have tried all the solution provided by @Sbrenthughes but still unable to get the rallyserver value inserted in database.

Is there anything which I should be doing. 

Step taken so far - 

1. Deleted the beans file and recreated the jar
2. Deleted the document from database and re run the collector
3. Deleted the database as well and re executed all the steps

here is my config file - 

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=127.0.0.1

# Database Port - default is 27017
dbport=27017

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Collector schedule (required)
rally.cron=0 0/5 * * * *

# Rally server(s) (required) - Can provide multiple
rally.servers[0]=https://rally1.rallydev.com

# Rally username/password for the provided server- with read-access to all resources.
rally.usernames[0]=<username>
rally.passwords[0]=<password>

#logging.level.com.capitalone.dashboard.collector=DEBUG

Actually, I see where the collector didn't insert the server URL. Can you try deleting that row and rerunning the collector?

_Originally posted by @Sbrenthughes in https://github.com/Hygieia/Hygieia/issues/2725#issuecomment-462887484_

**Comment by Sbrenthughes** [comment]
Are you running this collector on your local machine?

**Comment by nitingoyal8** [comment]
yes I am running on local machine.

**Comment by nitingoyal8** [comment]
Any pointer? Anything I should be looking at. I have dropped the old database and executed using -Dserver.port option, no luck. Now started to look into the code, but its little hard and time consuming to understand.

**Comment by Sbrenthughes** [comment]
Can you show the logs ?

**Comment by nitingoyal8** [comment]
Sure, I just commented out if block in RallyCollectorTask.java 

```
/*if(rallySettings.getServers()==null) {
				rallySettings.setUsernames(new ArrayList<>());
				rallySettings.setPasswords(new ArrayList<>());
				rallySettings.setServers(new ArrayList<>());
			} else {
				rallySettings.getUsernames().clear();
				rallySettings.getServers().clear();
				rallySettings.getPasswords().clear();
			}*/
```

and recompiled. Now I am able to see the data in mongo database as well as job is fetching the records.

2019-04-11 16:10:03,852 INFO  com.capitalone.dashboard.Application - Started Application in 14.242 seconds (JVM running for 16.027)
2019-04-11 16:10:04,780 INFO  c.c.d.collector.CollectorTask - Fetched projects   68            1s
2019-04-11 16:10:04,967 INFO  c.c.d.collector.CollectorTask - New projects           68        0s
2019-04-11 16:10:05,023 INFO  c.c.d.collector.CollectorTask - Updated                 0        0s
2019-04-11 16:10:05,023 INFO  c.c.d.collector.CollectorTask - Finished                         1s
