### ISSUE TITLE
Hygieia maven package error "package org.omg.PortableInterceptor does not exist"

### ISSUE THREAD

**Issue by pavankjadda** [Hygieia/Hygieia#2829]
I downloaded the latest version of the Hygieia and trying to package it with the following command
```
$ mvn clean install package

```
I got following error message

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project api: Compilation failure
[ERROR] /Users/johnd/Downloads/Hygieia/api/src/main/java/com/capitalone/dashboard/service/CommitServiceImpl.java:[23,35] package org.omg.PortableInterceptor does not exist
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :api
```

**Comment by Sbrenthughes** [comment]
Did you install Hygieia-core first without any issues?

**Comment by pavankjadda** [comment]
> Did you install Hygieia-core first without any issues?

Yes

**Comment by Sbrenthughes** [comment]
Have you tried without “package” at the end?

**Comment by pavankjadda** [comment]
Quick question. Hygieia core downloaded into Hygieia-core directory and packaged using `$ mvn clean install package` and Hygieia downloaded into Hygieia. Do we need to combine both? How does packaging Hygieia-core help Hygieia? What's the directory for both?

**Comment by pavankjadda** [comment]
> Have you tried without “package” at the end?

Yes. Same error

**Comment by chtompki** [comment]
That class file comes from the `rt.jar` that ships with java. What compiler are you using?

**Comment by pavankjadda** [comment]
maven

**Comment by rvema** [comment]
can you run `java -version` and let us know what you see? Also do you have a environment variable named `JAVA_HOME` setup? if so please provide information regarding the same.

**Comment by pavankjadda** [comment]
> can you run `java -version` and let us know what you see? Also do you have a environment variable named `JAVA_HOME` setup? if so please provide information regarding the same.

Thanks for asking me that. I have `Java 11` and `Java 8` installed on macOS and I used `jenv` to change the default version to Java 8. For some reason, my terminal took Java 11 as the default version. Changing default Java version to Java 8 solved my issue. I am not sure if Hygieia is compatible with Java 11. Thanks anyway.

**Comment by heffrey** [comment]
@pavankjadda what was your resolution for this? I am having very similar issues.

**Comment by pavankjadda** [comment]
I was using Java 11, Hygieia supports only Java 8

**Comment by heffrey** [comment]
Great, thanks. To further add for any other lost souls: when running `/usr/libexec/java_home -V` I had several versions installed. 

I had to manually set JAVA_HOME to the path leading to Java 8. Simply relying on `$(/usr/libexec/java_home)` to decide the version was futile. In my case this was  `/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home`

**Comment by jsam2412** [comment]
Downloading and pointing to JDK 8 version solved my issue.
Thanks @pavankjadda !!!

**Comment by rvema** [comment]
Thanks for sharing the solution

**Comment by Sbrenthughes** [comment]
NOTE: We have also found that this can happen when mvn is overriding the JAVA_HOME in .mavenrc.

**Comment by KrzysztofMaziarczyk** [comment]
JDK 8 helped indeed

**Comment by ozbillwang** [comment]
A comment for easily running with jdk 8, or other java version in the future, in official maven docker container.

```
 maven:3-jdk-8
```
so the command will be:
```
docker run -it --rm  -v "$(pwd):/apps"   -v "$(pwd)/settings.xml:/root/.m2/settings.xml" -w /apps   maven:3-jdk-8 mvn clean install package
```

**Comment by chrisj-au** [comment]
Fix for me was to get jdk8 as people mentioned.  Use 'sudo update-alternatives --config java' to change version in Ubuntu.
