### ISSUE TITLE
Hygieia Jenkins Plugin is not holding the commits in build stage and Environment Stages

### ISSUE THREAD

**Issue by harish123321** [Hygieia/Hygieia#2832]
I have a Jenkins Job which will trigger for every commit in GitHub. I am using Hygieia Jenkins Plugin to publish all data. I can able to get all data in team dashboard but I am not getting any commit data in build stage and no data is displayed in environments stages of product dashboard.

If I run Jenkins Collector I am getting commits in build stage but not showing the metrics.

[
<img width="494" alt="Capture" src="https://user-images.githubusercontent.com/43177923/55983802-8c7b8880-5c61-11e9-85cd-1ee69ada061e.PNG">
](url)

Can anyone help me out.

**Comment by user20170** [comment]
Can someone explain what data the environment columns use to correlate with commit and build column's data?

I believe here is the scenario many people would tend to use 
* Commit data **pulled** successfully from Github **collector**. 
* 1. Build data **pulled** successfully from Jenkins **collector**.  - OR -   
* 2. Build data **pushed** successfully from Jenkins through Hygieia **plugin** installed in Jenkins.
* Deployment data **pushed** successfully from Jenkins through Hygieia **plugin** installed in Jenkins via the hygieiaDeployPublishStep function.

Outcome: The commit and Build columns in product dashboard display fine. However the environment columns show empty. What is needed to build the correlation between deployment data and commit/build data? I believe that goes missing in the above scenario for some reason, and hence the environment columns show empty. Or maybe my understanding is incorrect, and I should rather simply ask *how to make it work?*

Any pointers to the code would be appreciated, and will help us hone in better.

**Comment by Sbrenthughes** [comment]
What are you using to populate the next stage after build? Jenkins plugin? If so can you paste the plugin step you are using?

**Comment by IATVirtusa** [comment]
Here i am pasting my product dashboard view as well as jenkins artifact and publisher step.

![Screenshot (28)](https://user-images.githubusercontent.com/48546034/58151598-c0e25b80-7c87-11e9-98e8-ee5330e6e728.png)
![Screenshot (29)](https://user-images.githubusercontent.com/48546034/58151600-c0e25b80-7c87-11e9-9870-05d7ea36a2aa.png)

**Comment by Sbrenthughes** [comment]
Are you using the auto publish functionality? If so these steps will only work when using a Jenkinsfile.

**Comment by rvema** [comment]
@IATVirtusa Can you confirm if you have implemented the above recommendations ?

**Comment by gopiprasanthpotipireddy** [comment]
now its working fine using Jenkinsfile.

**Comment by rvema** [comment]
closing the issue since it was resolved
