### ISSUE TITLE
Hygieia Product Dashboard Issue

### ISSUE THREAD

**Issue by anayyadav** [Hygieia/Hygieia#2836]
Hi friends, 
I am trying to configure product dashboard in Hygieia. I am having an issue in displaying the data in product dashboard. 

![Capture](https://user-images.githubusercontent.com/22302511/56358124-3cef0c80-61cd-11e9-9ec0-bdb9e8e3ac6b.PNG)

I request you to please help me in fixing this issue.

**Comment by Sbrenthughes** [comment]
How are you getting your build data?

**Comment by anayyadav** [comment]
I am getting my build data from Jenkins. And I can see the build metric in Team dashboard.

**Comment by Sbrenthughes** [comment]
1) Are you using plugin or collector?
2) How are you doing an scm check out in jenkins?

**Comment by user20170** [comment]
I believe this issue is similar to https://github.com/Hygieia/Hygieia/issues/2832 and I posted a [comment](https://github.com/Hygieia/Hygieia/issues/2832#issuecomment-485852391) there.
