### ISSUE TITLE
Future for api-audit and nfrr collector

### ISSUE THREAD

**Issue by fidelcoria-aa** [Hygieia/Hygieia#2838]
related issues (closed without satisfying answer)
#2133 
#2145 

I looked through the UI code and did not see an "nfrr" widget. Is this the vision?
What is the end user UseCase for audit and nfrr? Is the intention for users to create their own clients for api-audit?

Thanks

**Comment by Sbrenthughes** [comment]
Currently, yes, the end user is expected to consume that information outside of Hygieia. We currently don't have any plans to expose that data via the Hygieia UI. If someone provides a PR for those changes we'd be willing to review/ merge.
