### ISSUE TITLE
How to give JIRA CLOUD credentials ....it is not accepting     xxxxxx@gmail.com:password so how to get basic authentication

### ISSUE THREAD

**Issue by mitunmbj** [Hygieia/Hygieia#2849]
2019-04-24 16:44:00,005 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-04-24 16:44:00,037 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-24 16:44:00,037 INFO  c.c.d.collector.CollectorTask - https://mitunmbj.atlassian.net/
2019-04-24 16:44:00,037 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-24 16:44:00,037 INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-04-24 16:44:00,038 INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 432251. Collector is about to refresh Team/Board information
2019-04-24 16:44:00,974 ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API: https://mitunmbj.atlassian.net/rest/agile/1.0/board?startAt=0
2019-04-24 16:44:00,974 INFO  c.c.d.collector.CollectorTask - Board Data Collected. Added  0        0s
2019-04-24 16:44:01,481 ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
org.springframework.web.client.HttpClientErrorException: 401 null

**Comment by mitunmbj** [comment]
my property file


dbname=admin
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=[host1:port1,host2:port2,host3:port3]
dbusername=admin123
dbpassword=password
logging.file=./logs/jira.log
feature.pageSize=50
feature.deltaStartDate=2019-03-01T00:00:00.000000
feature.masterStartDate=2019-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2019-03-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

feature.jiraProxyUrl=
feature.jiraProxyPort=
feature.jiraBaseUrl=https://mitunmbj.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/

feature.jiraCredentials=bWl0dW5tYmpAZ21haWwuY29tOnppcHB5b3Bz

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

feature.jiraIssueTypeNames=Story,Bug,Task,Sub-Task,Epic

feature.jiraSprintDataFieldName=customfield_10021

feature.jiraEpicIdFieldName=customfield_10011

feature.jiraStoryPointsFieldName=customfield_10016

feature.jiraTeamFieldName=

feature.jiraStoryIds[0]=10001
feature.jiraStoryIds[1]=10004
feature.jiraStoryIds[2]=10002
feature.jiraStoryIds[3]=10003
feature.jiraEpicId=10000

feature.todoStatuses[0]=To Do
feature.doingStatuses[0]=In Progress
feature.doneStatuses[0]=Done

#feature.collectorItemOnlyUpdate=

#feature.maxNumberOfFeaturesPerBoard=

feature.jiraBoardAsTeam=true

**Comment by mitunmbj** [comment]
**if i pasted and ran https://mitunmbj.atlassian.net/rest/agile/1.0/board?startAt=0 it show the correct data**

{"maxResults":50,"startAt":0,"total":2,"isLast":true,"values":[{"id":3,"self":"https://mitunmbj.atlassian.net/rest/agile/1.0/board/3","name":"HYG board","type":"scrum","location":{"projectId":10002,"displayName":"Hygieia (HYG)","projectName":"Hygieia","projectKey":"HYG","projectTypeKey":"software","avatarURI":"/secure/projectavatar?size=small&s=small&avatarId=10324","name":"Hygieia (HYG)"}},{"id":5,"self":"https://mitunmbj.atlassian.net/rest/agile/1.0/board/5","name":"JAV board","type":"scrum","location":{"projectId":10004,"displayName":"java8 (JAV)","projectName":"java8","projectKey":"JAV","projectTypeKey":"software","avatarURI":"/secure/projectavatar?size=small&s=small&avatarId=10324","name":"java8 (JAV)"}}]}

**Comment by mitunmbj** [comment]
**But jira collector fails to bring information**

**Comment by Sbrenthughes** [comment]
Did you generate jiraCredentials using `echo -n username:password | base64`?

**Comment by mitunmbj** [comment]
@Sbrenthughes i made collector by using jira at local it has ordinary password so it was easy to crack .....well in jira web to login attlassian im using gmail and my own password how to change it as basic authentication

**Comment by Sbrenthughes** [comment]
If you are able to generate an API token. See https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-basic-authentication/, Looking at the `Supplying basic auth headers` section.

**Comment by mitunmbj** [comment]
@Sbrenthughes i found it
echo -n xxxxxxxxx@gmail.com:<the api token generated at atlassian> | base64
and it done for me
and i am closing the issue now
