### ISSUE TITLE
Jenkins Hygieia publisher is not pushing deployment data to Hygieia

### ISSUE THREAD

**Issue by Blessie7** [Hygieia/Hygieia#2850]
Hi, I am using jenkins hygieia publisher plugin to push build and deploy data to Hygieia. I am able to see build data populated in Hygieia but not the deployment data. Request your help in resolving the issue.

**Comment by rvema** [comment]
Can you let me know the syntax you used in your pipeline code?

**Comment by Blessie7** [comment]
I am using a freestyle job in Jenkins. I have configured all the parameters according to documentation available.

**Comment by rvema** [comment]
Did you configure the plugin via Global settings in Jenkins? If so at this point we support build, sonar and custom reflex patterns for collectors. Can you post a screenshot of the configuration just to confirm if we are on the same page.

**Comment by Blessie7** [comment]
Yes, I have configured the plugin on configure system page and the connection test on the endpoint was successful. Hence I was able to see build results in Hygieia. For sonar, I am using collector. We are not allowed to use API of UCD. So I want to go with the Jenkins Hygiea publisher for configuring deploy widget. 
Below is the configuration in Jenkins:
I have checked Publish deployment results and Publish Deploy start status.

Application Name: myapp
Environment Name: DEV
Artifact Directory: target
Artifact File Name Pattern: .zip
Artifact Group: org.mycompany
Artifact Version: 1.0-SNAPSHOT

**Comment by Blessie7** [comment]
Here is the log in Jenkins
Hygieia: Automatically publishing build data to Hygieia using hygieia-publisher version 2.1.9-SNAPSHOT (private-ae661508-root), Please refresh your browser to see the status.
Hygieia: Auto Published Build Complete Data. Response Code: 201. 5cc04385f2896743bcfd11e7,5cc03ef4f2896743bcfd11e2
Hygieia: Auto Published Sonar Result. Nothing to publish
Hygieia: *** Hygieia publish completed in 0 seconds at 2019-04-24T07:07:49.107 ***

![image](https://user-images.githubusercontent.com/20610136/56713663-f1e67380-674f-11e9-818e-441cec357e4c.png)


I don't see any UCD data being pushed to Hygieia in Jenkins console output. Please let me know if I am missing something.

**Comment by rvema** [comment]
@Blessie7 The jenkins log output you have shown is from the auto configuration i.e. from Global preferences (This capability currently takes care of Build, Sonar and Custom Regex patterns). Can you search for other references of Hygieia in the jenkins log?

**Comment by Blessie7** [comment]
I can see the logs of only build data being published. No traces of deployment data.

**Comment by Blessie7** [comment]
I have checked the option to Publish Deployment Results. Not sure why Jenkins isn't pushing the results to Hygieia. 

I am not using udeploy collector. 

Please let me know if I need to do any additional configuration in Jenkins/Hygieia.

**Comment by Sbrenthughes** [comment]
I have found that if the global plugin is turned on you cannot use these steps. 

> Here is the log in Jenkins
> Hygieia: Automatically publishing build data to Hygieia using hygieia-publisher version 2.1.9-SNAPSHOT (private-ae661508-root), Please refresh your browser to see the status.
> Hygieia: Auto Published Build Complete Data. Response Code: 201. 5cc04385f2896743bcfd11e7,5cc03ef4f2896743bcfd11e2
> Hygieia: Auto Published Sonar Result. Nothing to publish
> Hygieia: *** Hygieia publish completed in 0 seconds at 2019-04-24T07:07:49.107 ***
> 
> ![image](https://user-images.githubusercontent.com/20610136/56713663-f1e67380-674f-11e9-818e-441cec357e4c.png)
> 
> I don't see any UCD data being pushed to Hygieia in Jenkins console output. Please let me know if I am missing something.

**Comment by Blessie7** [comment]
Thanks for your prompt response. So, in order to get the publisher plugin working, global settings should be disabled? I assume this is the settings in Configure System page on Jenkins, where we provide the Hygieia server url, UI url and auth token.

**Comment by Sbrenthughes** [comment]
Yes, that is correct. Another option is to switch to Jenkinsfile and use the publish steps. The global push could be left enabled doing this.

**Comment by Blessie7** [comment]
@rvema @Sbrenthughes Thank you so much for your support. I am able to see the deployment data in Hygieia now.

**Comment by mohanelango** [comment]
Hi,
Can anyone help me how to create properties file for hygieia jenkins collectors. Sample  properties would be a great help..

**Comment by Sbrenthughes** [comment]
@mohanelango Please open a new issue this one is not related to the collector.
