### ISSUE TITLE
delete subversion-collector from the repository

### ISSUE THREAD

**Issue by chtompki** [Hygieia/Hygieia#2854]
Now that we have the https://github.com/Hygieia/hygieia-subversion-scm-collector and that it's released with `3.0.2`, we can delete the component from this project.

**Comment by blaktek** [comment]
I'm attempting to run the commands to put items into a docker image, and i'm running into this error..  I'm thinking because of this change?

"ERROR: build path /home/nix/work/hygiea/Hygieia/collectors/scm/subversion either does not exist, is not accessible, or is not a valid URL"

**Comment by kkorada** [comment]
I am also getting same error with latest version. Any fix ?

**Comment by rvema** [comment]
There is a pending PR out there which will fix the issue, please hold on

**Comment by rvema** [comment]
@kkorada Until then you can modify the docker-compose.yml by removing the block for subversion collector to get over the issue.

**Comment by kkorada** [comment]
getting error if i remove subversion block from compose file

`Service subversion-collector has neither an image nor a build context specified. At least one must be provided.`
