### ISSUE TITLE
Custom collector to fetch data from Pivotal Cloud Foundry

### ISSUE THREAD

**Issue by Blessie7** [Hygieia/Hygieia#2860]
Hi, We are looking for a custom collector that would fetch the data from Pivotal Cloud Foundry. Our requirement is to use the API endpoints similar to below to fetch details like  Version of application in each environment, status of services, application health, listener status, etc

1. Application version in each environment
API endpoint - http://<pcf-environment-url>/<application-name>/cloudfoundryapplication/info
RESPONSE - {"eureka":{"instance":{"metadata-map":{"user":{"password":"${eureka.instance.metadata-map.user.password}","name":"${eureka.instance.metadata-map.user.name}"}}},"UCD_Deployed_Version":"myApp-114"}}}

2. Application Health
API ENDPOINT - http://<pcf-environment-url>/<application-name>/cloudfoundryapplication/health 
RESPONSE - "hystrix":{"status":"UP"},"redis":{"status":"UP","details":{"version":"4.0.8"}}

3. Listener Status
API ENDPOINT - http://<pcf-environment-url>/<application-name>/admin/listenerStatus
RESPONSE - {"success":true,"messages":[],"responseBody":"['Listener': 'container', 'Active': 'true', 'Running': 'true', 'Active Consumers': '10']"}

Please let us know if this is feasible and any pointers to start with the custom collector. This would help us to monitor the applications closely on Hygieia dashboard. I appreciate any kind of help on this.
Thanks.

**Comment by Sbrenthughes** [comment]
Here is some documentation to get started. You can then take a look at the github collector to see further example of how to create a collector. 
https://hygieia.github.io/Hygieia/create_collector.html
