### ISSUE TITLE
Fix UI port in Hygieia

### ISSUE THREAD

**Issue by Blessie7** [Hygieia/Hygieia#2861]
Hi, Is there any way to fix the port that UI runs on? Port number keeps on increasing by 1(3000,3001,3002...), everytime I run the API and UI.

**Comment by Sbrenthughes** [comment]
the port will change if there is already something running on said port.

**Comment by Sbrenthughes** [comment]
Is this issue still needed? @Blessie7

**Comment by Blessie7** [comment]
After killing the gulp processes, I was able to run UI in 3000 port. Issue is no longer needed, thank you.
