### ISSUE TITLE
How to run Hygieia API, UI and collectors as service

### ISSUE THREAD

**Issue by Blessie7** [Hygieia/Hygieia#2862]
Can we configure Hygieia to run as service on Linux machine which runs API, UI and all the required collectors?

**Comment by rvema** [comment]
Yes, we use it as a service and systemctl start/stop to control the execution.

**Comment by Blessie7** [comment]
Could you please share any steps/documentation for this?

**Comment by rvema** [comment]
Sure, let me send the necessary information  in private message in Gitter. Also we will update the documentation to reflect the same

**Comment by Blessie7** [comment]
Would wait for the information. Thanks you.

**Comment by Blessie7** [comment]
Hi @rvema 
Request you to share the documentation.
Thanks.

**Comment by Sbrenthughes** [comment]
This can be easily searched for on google. `Spring boot systemd example`

**Comment by Blessie7** [comment]
Thanks for the info. How to pass the values of spring.config.name and spring.config.location using init.d or system.d? Could you please share any documentation that is specific to Hygieia?

**Comment by Blessie7** [comment]
> Sure, let me send the necessary information in private message in Gitter. Also we will update the documentation to reflect the same

Hi, Any update on this please?

**Comment by rvema** [comment]
@Blessie7  here is a sample service configuration for Hygieia API. 

> [Unit]
> Description=HygieiaAPIJavaDaemon
> 
> [Service]
> ExecStart=/usr/bin/java -Dserver.port=**** -Dlogging.config=file:/hygieia/api/logback_api.xml -jar /hygieia/api/api.jar --spring.config.name=api --spring.config.location=/hygieia/api/api.properties
> Restart=always
> User=*******
> Group=*******
> respawn=true
> WorkingDirectory=/hygieia/api
> 
> [Install]
> WantedBy=multi-user.target

**Comment by rvema** [comment]
@Blessie7 Please let us know if you have enough information so that we can close this issue

**Comment by rvema** [comment]
Closing this issue as the requested information was provided

**Comment by Navya-V** [comment]
> @Blessie7 here is a sample service configuration for Hygieia API.
> 
> > [Unit]
> > Description=HygieiaAPIJavaDaemon
> > [Service]
> > ExecStart=/usr/bin/java -Dserver.port=**** -Dlogging.config=file:/hygieia/api/logback_api.xml -jar /hygieia/api/api.jar --spring.config.name=api --spring.config.location=/hygieia/api/api.properties
> > Restart=always
> > User=*******
> > Group=*******
> > respawn=true
> > WorkingDirectory=/hygieia/api
> > [Install]
> > WantedBy=multi-user.target

May i know here which command you used ?
