### ISSUE TITLE
Bitbucket Collector not fetching any data

### ISSUE THREAD

**Issue by nitingoyal8** [Hygieia/Hygieia#2863]
Configured application.properties as per the document - 

`
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=127.0.0.1

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=127.0.0.1:27017

# Database Username - default is blank
dbusername=

# Database Password - default is blank
dbpassword=

# Collector schedule (required)
git.cron=0 0/1 * * * *

# Mandatory parameters
git.host=http://scm.******.com:<port>
git.api=/rest/api/1.0/

# Maximum number of days to go back in time when fetching commits
git.commitThresholdDays=15

# Page size for rest calls
#   Only applicable to Bitbucket Server.
#   Only applicable to Bitbucket Cloud.
git.pageSize=25

# Bitbucket product
#   Set to 'cloud' to use Bitbucket Cloud (formerly known as Bitbucket)
#   Set to 'server' to use Bitbucket Server (formerly known as Stash)
#   More information can be found here:
#   https://github.com/capitalone/Hygieia/issues/609
git.product=server

logging.level.com.capitalone.dashboard=INFO
logging.level.com.capitalone.dashboard.collector=INFO
logging.level.com.atlassian.git=INFO

# Bitbucket key for private repos
bitbucket.key=<Key Generated using Hygieia Core>
`

Successfully connecting to database but not fetching any data from repo.

**Database Entry -** 
{ "_id" : ObjectId("5cbf45bc95cd9456c40a5ff8"), "_class" : "com.capitalone.dashboard.model.Collector", "name" : "Bitbucket", "collectorType" : "SCM", "enabled" : true, "online" : false, "errors" : [ ], "uniqueFields" : { "branch" : "", "url" : "" }, "allFields" : { "lastUpdateCommit" : "", "password" : "", "lastUpdate" : ISODate("2019-04-29T16:25:00.018Z"), "branch" : "", "userID" : "", "url" : "" }, "lastExecuted" : NumberLong("1556555100123"), "searchFields" : [ "description" ] }

**Logs** 
2019-04-29 09:24:00,001 INFO  c.c.d.collector.CollectorTask - Running Collector: Bitbucket
2019-04-29 09:24:00,055 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-29 09:24:00,055 INFO  c.c.d.collector.CollectorTask - Starting...
2019-04-29 09:24:00,055 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-04-29 09:24:00,226 INFO  c.c.d.collector.CollectorTask - Repo Count              0        0s
2019-04-29 09:24:00,226 INFO  c.c.d.collector.CollectorTask - New Commits             0        0s
2019-04-29 09:24:00,226 INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by mitunmbj** [comment]
bro convert git api /rest/api/1.0 to /api/2.0/repositories
git.api=/api/2.0/repositories and give a try

**Comment by Sbrenthughes** [comment]
Do did you create a dashboard and add an SCM widget?

**Comment by nitingoyal8** [comment]
@Sbrenthughes - thank you, it works, But its strange that all other collectors work differently.

**Comment by Sbrenthughes** [comment]
Most collectors will not collect data for a widget until the widget is configured. However, some collectors need to pull certain pieces of data before they can be configured to collect anything specific. 

That being said, please let me know of any collectors that pull all data by default. This type of pull is very inefficient when it comes to large amounts of data.

**Comment by psripathy** [comment]
I am running into the same problem. Can you please post the solution here. I am using Bitbucket server and api URL **/rest/api/1.0**. The **api/2.0/repositories** is not a valid endpoint for our bitbucket setup.
