### ISSUE TITLE
JIRA COLLECTER NOT FETCHING the (".....NEW DATA.....") Jira collector working fine but once i created new project in jira it is not fetching. Rather i have to clear the data in mongodb then it is fetching all the data freshly but it affects othe collectors and api....How to solve this 

### ISSUE THREAD

**Issue by mitunmbj** [Hygieia/Hygieia#2864]
In hygieia for example i configured jira and it brought all data and it also displayed it clearly in UI now i deleted the old one and created a new board and data but the UI only replicate the old data and showing the new data . when checked the MongoDB it is containing the old data whereas the the new data is not replacing the old data 
WHAT TO DO.....EXPECTING SPEED REPLY
Thanks

**Comment by Sbrenthughes** [comment]
I am not able to follow what you are saying. Can give a little more detail about what exactly you are trying to do?

**Comment by mitunmbj** [comment]
@Sbrenthughes  the new data is not replacing the old data in database 
example: I configured jira cloud and brings me data and shows metrics now 
i cleared the previous data (like board team issues) in jira cloud and produced new data there
Now while im running the collector it still shows the old data and new data is not collected

**Comment by Sbrenthughes** [comment]
If you stop the collector delete the board, then recreate it, and then recreate it the data will stay because the collector was not able to detect the boarding being deleted. But that should not stop the collector from collecting new data. What do the logs look like?

**Comment by mitunmbj** [comment]
@Sbrenthughes it will just show unauthorized as the collector matches the new data to the old one

**Comment by mitunmbj** [comment]
@Sbrenthughes I cannot configure 2 private at a same time in bitbucket

**Comment by Sbrenthughes** [comment]
I am more confused. Is this about the JIra collector?

**Comment by mitunmbj** [comment]
fast reply plz

**Comment by Sbrenthughes** [comment]
> @Sbrenthughes I cannot configure 2 private repos at a same time in bitbucket



> @Sbrenthughes it will just show unauthorized as the collector matches the new data to the old one

Do these comments relate to your issue?

**Comment by mitunmbj** [comment]
cleared it by feature.refreshTeamAndProjectHours=1
for each one hour by re running collector it is bring data
