### ISSUE TITLE
Hygieia cloud dashboard

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [Hygieia/Hygieia#2873]
Do hygieia have support to create cloud view dashboard on GCP. Any documentation or roadmap available to support GCP. (Simmillar to AWS collector)

**Comment by rvema** [comment]
@ajayakumar-jayaraj we do not have the support as of now, However if you have time you can create a collector for populating Data from GCP. The instructions to create a collector can be found at https://hygieia.github.io/Hygieia/create_collector.html
