### ISSUE TITLE
unable to create admin user 

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [Hygieia/Hygieia#2876]
unable to create admin user from console, api connectivity is green , updated the auth setttings as below , still getting auth error , not sure what if i am  missing , any help on this- name: AUTH_EXPIRATION_TIME
value: "7200000"
    - name: AUTH_AUTHENTICATION_PROVIDERS
      value: STANDARD
    - name: AUTH_SECRET
      value: *****
 
error: "Unauthorized"
message: "Full authentication is required to access this resource"
path: "/api/registerUser/"
status: 401
timestamp: 1557153861992

**Comment by rvema** [comment]
What headers are you passing in?

**Comment by mitunmbj** [comment]
go to database

switch to admin database (# use admin)

u will be switched to admindatabase

db.createUser(
{	user: "dashboarduser",
	pwd: "dbpassword",

	roles:[{role: "userAdminAnyDatabase" , db:"admin"}]})


create admin user

and now on create all property file based on this 
dbname=admin
dbuser=dashboarduser
dbpassword=dbpassword

**Comment by Sbrenthughes** [comment]
@ajayakumar-jayaraj any update here?

**Comment by rvema** [comment]
closing the issue due to inactivity
