### ISSUE TITLE
Can Hygieia also support Nexus Repository?

### ISSUE THREAD

**Issue by wwei1896** [Hygieia/Hygieia#2882]
I am using Nexus OSS Repository as the artifacts store tool.
Can Hygieia also support to get collector data of Nexus OSS Repository beside JFrog Artifactory.

Thanks

**Comment by Sbrenthughes** [comment]
Hygieia can be integrated with any tool. All you need to do is build the collector.

**Comment by wwei1896** [comment]
hi  
thank you for the reply.
I want to know how can I build the collector for Nexus OSS Repository, can you pls give some advice. 
Thanks
