### ISSUE TITLE
Deploy Widget - Up and Down arrows.

### ISSUE THREAD

**Issue by ojasvijagtap** [Hygieia/Hygieia#2885]
Hi, I have configured deploy widget in Hygieia using Hygieia publisher plugin of Jenkins. My Jenkins job is pipeline job. 
I can see environment and deployment time however "up" and "down" arrows are zero. 
![image](https://user-images.githubusercontent.com/20609631/57533582-c1800700-7303-11e9-9d9d-bf3bed17bb2f.png)

I know arrows are to display total count of online and office servers in the deployment though i am not able to figure out a way to configure them. 

Any pointer would be of great help. 

Thanks in advance.

**Comment by Sbrenthughes** [comment]
That data is only available via udeploy. The jenkins plugin doesn't not push that type of data.

**Comment by ojasvijagtap** [comment]
@Sbrenthughes Thank you for your quick response. Really appreciate it.  

Would like to know if you have any plans of enhancing jenkins plugin to push that data too.

**Comment by Sbrenthughes** [comment]
No, because to my knowledge, Jenkins is only used as a deployment tool. Not a tool to monitor server status.

**Comment by ojasvijagtap** [comment]
Sure. Thanks for confirming.
