### ISSUE TITLE
BitBucket Collector Issue with api 1.0

### ISSUE THREAD

**Issue by vbottu** [Hygieia/Hygieia#2901]
I am trying to connect to the internal bitbucket server and the connection is successful from the collector but the query url to fetch the commits is causing problem , it throwing 404  ERROR c.c.d.c.DefaultBitbucketCloudClient - 404 on the endpoint commits?sha=master&since=2019-05-15T19:44Z, Please see the exception in the image attached. I am not sure if the query url being built by the default bitbucket cloud client is right
![image](https://user-images.githubusercontent.com/19859827/57805201-110a6c80-7722-11e9-95c2-0d08b5d64ab7.png)

**Comment by Sbrenthughes** [comment]
@shishirchaturvedi Can you provide some help here since you have a lot knowledge with that collector?

**Comment by shishirchaturvedi** [comment]
@vbottu Please see this REST [specification document](https://docs.atlassian.com/bitbucket-server/rest/5.13.1/bitbucket-rest.html#idm45902677006336). The search parameter `Since` should be a valid commit.

**Comment by vbottu** [comment]
@shishirchaturvedi thank you, i was using the wrong bitbucket type.

**Comment by Sbrenthughes** [comment]
@shishirchaturvedi I appreciate you help here!
