### ISSUE TITLE
Gitlab feature collector not working properly

### ISSUE THREAD

**Issue by MerlijnElderhuis** [Hygieia/Hygieia#2906]
Hi! I'm using Hygieia for a study project, currently I'm trying to use the gitlab feature collector to display some issues into the dashboard. I'm running into a problem where the gitlab-feature-collector is raising a java nullpointerexception, as displayed in the logs I will put below. Depending on what information I fill into the widget, the exception is more elaborate or simple. I tried filling in the group name, project name, group id, and project id, all with no success. I'm running Hygieia using docker-compose. I have little experience in Java so for some advanced debugging I would need a little help :) Thanks in advance!

My application.properties and docker-compose.override are as follows:
application.properties:
MONGODB_HOST=db
MONGODB_PORT=27017
docker-compose.override:
gitlab-feature-collector:
    environment:
    - MONGO_PORT=27017
    - MONGO_HOST=db
    - GITLAB_CRON=0 * * * * *
    - GITLAB_API_TOKEN=*****

Simple logs:
gitlab-feature-collector_1 | 2019-05-16 10:20:00,265 ERROR c.c.d.collector.FeatureCollectorTask - java.lang.NullPointerException
gitlab-feature-collector_1 | 2019-05-16 10:20:00,265 ERROR c.c.d.collector.FeatureCollectorTask - java.lang.NullPointerException
gitlab-feature-collector_1 | 2019-05-16 10:20:00,265 ERROR c.c.d.collector.FeatureCollectorTask - java.lang.NullPointerException
gitlab-feature-collector_1 | 2019-05-16 10:20:00,265 ERROR c.c.d.collector.FeatureCollectorTask - java.lang.NullPointerException
gitlab-feature-collector_1 | 2019-05-16 10:20:00,265 INFO c.c.d.collector.CollectorTask - Issues Added/Updated 0 0s
gitlab-feature-collector_1 | 2019-05-16 10:20:00,265 INFO c.c.d.collector.CollectorTask - Issues Deleted 0 0s

More elaborate logs:
gitlab-feature-collector_1 | 2019-05-16 10:16:00,001 INFO c.c.d.collector.CollectorTask - Running Collector: GitlabFeature
gitlab-feature-collector_1 | 2019-05-16 10:16:00,008 INFO c.c.d.collector.CollectorTask - -----------------------------------
gitlab-feature-collector_1 | 2019-05-16 10:16:00,008 INFO c.c.d.collector.CollectorTask - Starting...
gitlab-feature-collector_1 | 2019-05-16 10:16:00,008 INFO c.c.d.collector.CollectorTask - -----------------------------------
gitlab-feature-collector_1 | 2019-05-16 10:16:00,351 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
gitlab-feature-collector_1 | java.lang.NullPointerException: null
gitlab-feature-collector_1 | at org.apache.commons.collections.CollectionUtils.addAll(CollectionUtils.java:687) ~[commons-collections-3.2.1.jar!/:3.2.1]
gitlab-feature-collector_1 | at com.capitalone.dashboard.gitlab.DefaultGitlabClient.makePaginatedGitlabRequest(DefaultGitlabClient.java:80) ~[gitlab-feature-collector.jar!/:3.0.2-SNAPSHOT]
gitlab-feature-collector_1 | at com.capitalone.dashboard.gitlab.DefaultGitlabClient.getProjectsForTeam(DefaultGitlabClient.java:45) ~[gitlab-feature-collector.jar!/:3.0.2-SNAPSHOT]
gitlab-feature-collector_1 | at com.capitalone.dashboard.collector.FeatureService.getProjectsForWidget(FeatureService.java:67) ~[gitlab-feature-collector.jar!/:3.0.2-SNAPSHOT]
gitlab-feature-collector_1 | at com.capitalone.dashboard.collector.FeatureService.getProjectsToUpdate(FeatureService.java:52) ~[gitlab-feature-collector.jar!/:3.0.2-SNAPSHOT]
gitlab-feature-collector_1 | at com.capitalone.dashboard.collector.FeatureServiceFastClassBySpringCGLIBFastClassBySpringCGLIB612f32dd.invoke(<generated>) ~[gitlab-feature-collector.jar!/:3.0.2-SNAPSHOT]
gitlab-feature-collector_1 | at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
gitlab-feature-collector_1 | at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651) ~[spring-aop-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
gitlab-feature-collector_1 | at com.capitalone.dashboard.collector.FeatureServiceEnhancerBySpringCGLIBEnhancerBySpringCGLIB8604e9d4.getProjectsToUpdate(<generated>) ~[gitlab-feature-collector.jar!/:3.0.2-SNAPSHOT]
gitlab-feature-collector_1 | at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:92) ~[gitlab-feature-collector.jar!/:3.0.2-SNAPSHOT]
gitlab-feature-collector_1 | at com.capitalone.dashboard.collector.FeatureCollectorTas

**Comment by Sbrenthughes** [comment]
Are these the only environment variables you are passing?
```
environment:
- MONGO_PORT=27017
- MONGO_HOST=db
- GITLAB_CRON=0 * * * * *
- GITLAB_API_TOKEN=*****
```

**Comment by MerlijnElderhuis** [comment]
Those are indeed the only environment variables I'm passing. The links you posted are of the GitLab SCM collector, I also use that and it's working collecting, but the issues I'm experiencing are with the GitLab Feature collector (used for grabbing scrum/kanban issues). Looking at 
https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/collectors/feature/feature-gitlab.md
the only required parameters that are needed are the ones I provided in my environments file. The collector is running and keeps trying to collect data, yet at the point where the issues should be collected the java nullexception pops up.

**Comment by MerlijnElderhuis** [comment]
@Sbrenthughes do you have an idea about how to solve this issue?

**Comment by Sbrenthughes** [comment]
Ah I apologize. Looks like the API being used is returning null. Do you no what version you are using?

**Comment by MerlijnElderhuis** [comment]
I'm using the most recent version, just cloned it from GitHub.

**Comment by Sbrenthughes** [comment]
@zhenweiding since you have experience with the gitlab SCM collector (gitlab APIs), do you think you could take a look at this? It has to do with the feature portion of GitLab.

**Comment by zhenweiding** [comment]
@MerlijnElderhuis There is my gitlab feature's configure in "docker-compose.yml":

  gitlab-feature-collector:
    build: collectors/feature/gitlab
    image: hygieia-gitlab-feature-collector
    volumes:
      - /Users/dingzhenwei/devops/Hygieia-3.0.1/logs:/hygieia/logs
      - /Users/dingzhenwei/devops/Hygieia-3.0.1/config:/hygieia/config
    environment:
      - MONGO_DATABASE=dashboarddb
      - **MONGO_PORT=tcp://db:27017**
      - MONGO_USERNAME=******
      - MONGO_PASSWORD=******
      - GITLAB_HOST=gitlab.com
      - GITLAB_PROTOCOL=https
      - GITLAB_PORT=443
      - GITLAB_CRON=0 */15 * * * *
      - GITLAB_API_TOKEN=******
      - GITLAB_COMMIT_THRESHOLD_DAYS=20
      - SKIP_PROPERTIES_BUILDER=false
    depends_on:
      - db-setup

I think the point is the [**MONGO_PORT**]'s value, please try again with the correct config value.

**Comment by MerlijnElderhuis** [comment]
@zhenweiding Thanks for the quick response, that seemed to have fixed it!
