### ISSUE TITLE
Hygieia Publisher HygieiaTestPublishStep Error

### ISSUE THREAD

**Issue by vbottu** [Hygieia/Hygieia#2908]
I am trying to publish unit test results to hygieia from my pipeline using HygieiaTestPublishStep, when i try to generate pipeline script it throws the below error
no public field ‘testResultType’ (or getter method) found in class jenkins.plugins.hygieia.workflow.HygieiaTestPublishStep
Please find the attached screenshot 
![image](https://user-images.githubusercontent.com/19859827/57865940-1cae6f80-77c4-11e9-8b18-3250235a9472.png)

**Comment by Sbrenthughes** [comment]
Are you using the latest version?

**Comment by vbottu** [comment]
Yes , I am using the latest version. Checked out the code from master branch and created a hpi and uploaded that to my jenkins instance

**Comment by vbottu** [comment]
@Sbrenthughes could you let me if I am missing something here?

**Comment by Sbrenthughes** [comment]
@rvema do you have any suggestions here?

**Comment by stevegal** [comment]
Think was my PR from a few days ago. I'll correct

**Comment by Sbrenthughes** [comment]
Code has been merged can you update and validate?

**Comment by vbottu** [comment]
Thanks, I will update and validate.

**Comment by Sbrenthughes** [comment]
Any update?

**Comment by rvema** [comment]
@vbottu Can you let us know so that we can close this issue?

**Comment by Sbrenthughes** [comment]
Please reopen if this has not be resolved with the latest
