### ISSUE TITLE
AWS collector needs to collect information from Multiple AWS accounts.

### ISSUE THREAD

**Issue by zerolaser** [Hygieia/Hygieia#2910]
Currently AWS collector can only collect information from one aws accounts.
may be I need to run the jar multiple times with different aws profiles to collect the data from different accounts. 
Either way If i need to integrate all the information different aws accounts into one dashboard. where it can show the utilization by environment. 
Currently hygieia is lacking this. 

![image](https://user-images.githubusercontent.com/7926653/57878644-53d64e00-77cf-11e9-8189-17f11c9bf024.png)

May be have drop down under account and grab the information based on the account ? 
Also, currently the dashboards cannot be modified. lets just say we need select specific instance usage its not available. 
@Sbrenthughes is there any future roadmap to add this as a feature?

**Comment by Sbrenthughes** [comment]
You'll need to deploy a collector in each account likely. There are no plans to enhance this collector in the near future.
