### ISSUE TITLE
change the order of these widgets

### ISSUE THREAD

**Issue by zerolaser** [Hygieia/Hygieia#2920]
Right now when you create a dashboard. there is no proper way to arrange these widgets the way you want. 
What I need this is to drag and change the order of the widgets or while creating the dashboard there needs to be an option to prioritize these widgets based on numbering.

**Comment by anayyadav** [comment]
you can create a custom template and arrange them accordingly. 


![image](https://user-images.githubusercontent.com/22302511/58010535-2b6f8c00-7b0e-11e9-8789-9def86a9098f.png)

**Comment by zerolaser** [comment]
@anayyadav I don't see this view at all in my hygieia. all i see is create a new dashboard and edit existing dashboards. I think,  I'm just a regular user of hygieia. how do i grant admin permissions ?

**Comment by anayyadav** [comment]
you can create a custom templates. 
you can go to above page by clicking on setting icon in top right of your screen.
![image](https://user-images.githubusercontent.com/22302511/58072906-c9229400-7bbe-11e9-9f13-15ab97e46cee.png)

**Comment by Sbrenthughes** [comment]
you can create the user `admin` and login using it to gain access to the admin user. Other than what @anayyadav suggested, you won't be able to do any more customization in this version of the UI. Once  the UI is upgraded to the latest version of Angular you will have more control. The upgrade is expected to start rolling out over the next few months.
