### ISSUE TITLE
hygiea jenkins build collector is failing

### ISSUE THREAD

**Issue by imranmaddekar** [Hygieia/Hygieia#2921]
Hi Team,

I am trying to up UI, API, DB and Jenkins Build Collector in docker-compose setup.

I have cloned the hygiea repositories and executed maven commands for building the required jar files.

Then modified the docker.compose.yml file like below.
version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    build: db
    depends_on:
      - db

  api:
    build: api
    image: hygieia-api
    depends_on:
      - db-setup
    ports:
      - "8080:8080"

  ui:
    build: UI
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"

  jenkins-build-collector:
    build: collectors/build/jenkins
    image: hygieia-jenkins-build-collector
    depends_on:
      - db-setup

volumes:
  db-data:
  certs:

And modified the docker-compose.override.yml
version: '3'
services:
  api:
     # environment: # for a full list check the corresponding properties-builder file
     #   - DB_DATABASE: dashboarddb
     #   - DB_HOST: db
     #   - DB_PORT: 27017
     #   - DB_USERNAME: dashboarduser
     #   - DB_PASSWORD: dbpassword
     # volumes:
     #   - ./logs:/hygieia/logs

  ui:
    # environment:

  jenkins-build-collector:
    environment:
    - JENKINS_CRON=2 * * * * *
    - JENKINS_MASTER=http://my-jenkins-server
    - JENKINS_USERNAME=<api-user>
    - JENKINS_API_KEY=<my-api-key>

Error:
The build collector is not getting up and throws error as MONGO_PORT not defined.

**Comment by anayyadav** [comment]
you need to changes  in properties-builder.sh in api\docker\properties-builder.sh:
server.contextPath=/api
server.port=8080

and make sure your environment variable are same in both docker-compose file and properties-builder.sh.

-------------------------------
properties-builder.sh in jenkins:

#!/bin/bash

# mongo container provides the HOST/PORT
# api container provided DB Name, ID & P
cat > $PROP_FILE <<EOF
#Database Name
dbname=${DB_NAME:-dashboard}
#Database HostName - default is localhost
dbhost=${DB_HOST:-db}
#Database Port - defaultis 27017
dbport=${DB_PORT:-27017}
#Database Username - default is blank
dbusername=
#${HYGIEIA_API_ENV_SPRING_DATA_MONGODB_USERNAME:-dashboarduser}
#Database Password - default is blank
dbpassword=
#${HYGIEIA_API_ENV_SPRING_DATA_MONGODB_PASSWORD:-dbpassword}
#Collector schedule (required)
jenkins.cron=${JENKINS_CRON:-0 0/1 * * * *}
#The page size
jenkins.pageSize=${JENKINS_PAGE_SIZE:-1000}
# The folder depth - default is 10
jenkins.folderDepth=${JENKINS_FOLDER_DEPTH:-10}
#Jenkins server (required) - Can provide multiple
jenkins.servers[0]=${JENKINS_SERVER}
#jenkins.niceNames[0]=[YourJenkins]
#jenkins.environments[0]=[DEV,QA,INT,PERF,PROD]
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
jenkins.usernames[0]=${JENKINS_USERNAME}
jenkins.apiKeys[0]=${JENKINS_APIKEY}
jenkins.searchFields[0]= options.jobName
jenkins.searchFields[1]= niceName
EOF

echo "
===========================================
Properties file created `date`:  $PROP_FILE
Note: passwords & apiKey hidden
===========================================
`cat $PROP_FILE |egrep -vi 'password|apiKey'`
"

exit 0


-----------
NOTE: also give execution permission to properties-builder.sh file using:
chmod +x \properties-builder.sh

**Comment by Sbrenthughes** [comment]
Please reopen if this doesn't solve the issue.

**Comment by kkorada** [comment]
Hi I am getting same error while using docker compose up, it expecting MONGO_PORT to be set. But who sets it ? what do guys mean by `mongo container provides the HOST/PORT`

**Comment by SuriDotInc** [comment]
> MONGO_PORT

What I learned from building docker image one service at a time, is that , the docker image is expecting MONGO_PORT=tcp://<ip>:<port> format, You can try putting this variable in docker-compose.yml for the service you got errored out. OR 

you can run one service at a time with the following 

docker run -d -t --link=mongodb:mongo -v /logs/jenkins:/hygieia/logs -e   "MONGO_PORT=tcp://10.40.11.193:27017"  -e "JENKINS_MASTER=http://<DOMAIN>/jenkins" -e "JENKINS_USERNAME=readonly" -e "JENKINS_API_KEY=readonly" myhygjenkinscollector:latest
