### ISSUE TITLE
Are xml files supported in HygieiaTestPublishStep?

### ISSUE THREAD

**Issue by vbottu** [Hygieia/Hygieia#2924]
I am trying to include HygieiaTestPublisStep in my pipeline and when generating pipeline syntax from jenkins I am seeing the below error

``no public field ‘testResultType’ (or getter method) found in class jenkins.plugins.hygieia.workflow.HygieiaTestPublishStep``

Attaching the screenshot for reference. 
![image](https://user-images.githubusercontent.com/19859827/58122331-0727b400-7bcf-11e9-8fb4-f09398edf437.png)
I am not sure whether xml files are supported yet

**Comment by Sbrenthughes** [comment]
This is the same issue you opened up here https://github.com/Hygieia/Hygieia/issues/2908. Closing this.
