### ISSUE TITLE
collectorid and componentid 

### ISSUE THREAD

**Issue by poojithkumar** [Hygieia/Hygieia#2925]
how can get collectorid and componentid  of specific url ?

**Comment by Sbrenthughes** [comment]
What do you mean of a specific url?

**Comment by poojithkumar** [comment]
I just want to connect Jenkins and github collector together and make one
new .
If I get url of my repo in Jenkins can I call github collector at backend.
 Thanks

**Comment by Sbrenthughes** [comment]
Okay I am still lost. What is the end product/goal?

**Comment by poojithkumar** [comment]
If Jenkins build is triggered by github pull request. We get information
about github repo url that make the Jenkins build.

  Using that url I want data regarding  issue (example) details.
Thanks

**Comment by Sbrenthughes** [comment]
I don't believe we have an easy way to get the collectorItemId and component Id based on a repo URL

**Comment by poojithkumar** [comment]
Can u suggest some best way for that

**Comment by Sbrenthughes** [comment]
You can probably get the collector Item by using `/collector/item/type/{collectorType}` it is int he CollectorController.java and then you'd probably need to create an api to get a list of components by collectorItemId.

**Comment by poojithkumar** [comment]
How can I get list of components using collector I'd.. is there any API for
that?

**Comment by Sbrenthughes** [comment]
> You can probably get the collector Item by using `/collector/item/type/{collectorType}` it is in the CollectorController.java and then **you'd probably need to create an api to get a list of components by collectorItemId**.

**Comment by poojithkumar** [comment]
how did u get componentId and collectorId in repo widget ?


Thanks

**Comment by Sbrenthughes** [comment]
`/collector/item/type/{collectorType}` gives you the collectorId. You'll need to create an API to get the componentId. Take a look a the CollectorController.java. It should have enough to help you figure out how to do that.

**Comment by rvema** [comment]
@poojithkumar Do you still need this issue to be open?
