### ISSUE TITLE
Hygieia dashboard view for only authenticated users

### ISSUE THREAD

**Issue by rstmna** [Hygieia/Hygieia#2932]
Hygieia allows any unauthenticated user to view the dashboard list without login first.
We want only authenticated users to view any data on hygieia dashboards otherwise users should be redirected to login page first.

**Comment by Sbrenthughes** [comment]
What is the issue for anyone being about to view dashboards?

**Comment by rstmna** [comment]
We have to implement RBAC to view dashboards. So only authenticated users can view dashboards that they are authorized for.

**Comment by rvema** [comment]
@rstmna This feature is not available currently and we have not received enough requests for such a need. However since this is specific to your needs you are free to make modifications to the source code per your needs and use it.
