### ISSUE TITLE
Jira Collector Username Authorization issue

### ISSUE THREAD

**Issue by ssrivastava-papajohns** [Hygieia/Hygieia#2944]
I have created a new Jira cloud trial account. In the hygieia documentation username:password(encoded in base64) is mentioned for collector authentication. I am trying to authorize Jira with collector using email:password(encoded in base64) format but it's not working.  

I searched on the internet and found that Jira has already removed username field from Jira.

https://confluence.atlassian.com/cloud/blog/2018/06/say-goodbye-to-usernames-in-atlassian-cloud?_ga=2.159559613.184535873.1559202112-814553513.1559113992.

I tried to hit the API using postman with email:password and also bypassing basic auth key in header. but it's not working there also.

I am not sure with the issue, But I have a prod instance of Jira, Where older user can able to login using username:password but new users are getting 401.

**Comment by Sbrenthughes** [comment]
This has already been raised. Have you looked at this issue? https://github.com/Hygieia/Hygieia/issues/2849

**Comment by Sbrenthughes** [comment]
I am sure @mitunmbj can provide further detail if needed.

**Comment by Sbrenthughes** [comment]
Any update here?
