### ISSUE TITLE
Data not populating on deploy dashboard

### ISSUE THREAD

**Issue by ajayakumar-jayaraj** [Hygieia/Hygieia#2946]
i have configured jenkins collector and it is populating data in build dashboard but it is NOT populating any info on deploy dashboard. Please help on this and let me know  if I am missing something.

![image](https://user-images.githubusercontent.com/32649250/58800720-9624cb00-85d6-11e9-809a-754a79bbc36b.png)

![image](https://user-images.githubusercontent.com/32649250/58800736-a0df6000-85d6-11e9-9bc3-c8247ce3809a.png)

**Comment by rvema** [comment]
@ajayakumar-jayaraj The jenkins collector at this point is capable of populating only the build widget. The deploy widget is populated by any of the collectors under deploy folder of Hygieia project. At this moment there are collectors for xdeploy and udeploy. If you use a different toolset for deployment or would like to use Jenkins as a mode of deployment then you may leverage the hygieia-publisher-plugin (Hygieia plugin for Jenkins) to push data into Hygieia from Jenkins by adding a deploy step to your Jenkins pipeline. Please see this link for more details - https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/hygieia-jenkins-plugin/hygieia-jenkins-plugin.md. If this is information is sufficient please go ahead and close this issue. Thanks

**Comment by IATVirtusa** [comment]
@rvema  jenkins-Hygieia publisher is publishing deployment information to deploy widget, but in the product dashboard i am not able to see any commits and other stats like avg time and standard deviation for the environments like Dev and QA. i am able to see the commit and build info in product dashboard.

**Comment by gopiprasanthpotipireddy** [comment]
@IATVirtusa @rvema I am having the same issue with jenkins-Hygieia publisher plugin here i am attaching the screens
![Screenshot (27)](https://user-images.githubusercontent.com/14222254/58880453-86e86f00-86f5-11e9-8ab6-4376c2e1baf4.png)

**Comment by ajayakumar-jayaraj** [comment]
> @ajayakumar-jayaraj The jenkins collector at this point is capable of populating only the build widget. The deploy widget is populated by any of the collectors under deploy folder of Hygieia project. At this moment there are collectors for xdeploy and udeploy. If you use a different toolset for deployment or would like to use Jenkins as a mode of deployment then you may leverage the hygieia-publisher-plugin (Hygieia plugin for Jenkins) to push data into Hygieia from Jenkins by adding a deploy step to your Jenkins pipeline. Please see this link for more details - https://github.com/Hygieia/Hygieia/blob/gh-pages/pages/hygieia/hygieia-jenkins-plugin/hygieia-jenkins-plugin.md. If this is information is sufficient please go ahead and close this issue. Thanks

@rvema Thanks for the info . I have configured Jenkins plugin and followed the link you shared. I am able to get metrics in build dashboard , but still i am not seeing data in deploy dashboard. can you please advise on it..

**Comment by Sbrenthughes** [comment]
@ajayakumar-jayaraj are you using a Jenkinsfile or post build steps? Right now Post build steps do not publish deploy data. For now, To get deploy data, you need to migrate to a Jenkinsfile for your jobs. We will be fixing this in the future.

**Comment by ajayakumar-jayaraj** [comment]
@rvema @Sbrenthughes 


![image](https://user-images.githubusercontent.com/32649250/58976714-21988a80-8796-11e9-8013-e08b9ff82ab4.png)

hygieiaDeployPublishStep applicationName: 'hygieia-test', artifactDirectory: 'app/target', artifactGroup: 'com.mycompany.app', artifactName: '*.jar', artifactVersion: '', buildStatus: 'Success', environmentName: 'uat'

**Comment by gopiprasanthpotipireddy** [comment]
@rvema can you share the sample jenkinsfile for hygiea-jenkins plugin. it is helpful.

**Comment by rvema** [comment]
@gopiprasanthpotipireddy one way is use to use the post build step in your jenkins job.
<img width="1442" alt="Screen Shot 2019-06-06 at 9 14 04 AM" src="https://user-images.githubusercontent.com/7529330/59035553-8528c380-883b-11e9-8f41-07bd11f68b3d.png">

For steps in pipeline, please see some example syntax of various steps:

`hygieiaDeployPublishStep applicationName: "someapp", artifactDirectory: 'dist/', artifactGroup: 'somegroup', artifactName: 'somename', artifactVersion: "someversion", buildStatus: 'Success', environmentName: "someenviroment"`

`hygieiaSonarPublishStep ceQueryIntervalInSeconds: 10, ceQueryMaxAttempts: 30`

`hygieiaTestPublishStep buildStatus: 'Success', testApplicationName: 'Cucumbertest', testEnvironmentName: 'Dev', testFileNamePattern: '*.json', testResultsDirectory: '/', testType: 'Functional'`

`hygieiaBuildPublishStep buildStatus: 'Success'`

**Comment by gopiprasanthpotipireddy** [comment]
@rvema  what is the exact steps in jenkinsfile to get metrics in product dashboard. do i need to use both hygieiaDeployPublishStep and hygieiaArtifactPublishStep or any one of this is enough?

**Comment by gopiprasanthpotipireddy** [comment]
The same issue i rised here.
https://github.com/Hygieia/Hygieia/issues/2893

**Comment by rvema** [comment]
@gopiprasanthpotipireddy each of the mentioned steps are discrete and you would need to invoke all the steps if you need information about all of them.

**Comment by gopiprasanthpotipireddy** [comment]
![image](https://user-images.githubusercontent.com/14222254/59086851-94ce0800-8920-11e9-9139-c0e77e961983.png)
@rvema now i am able to get the commits in dev stage but not the metrics using jenkinsfile.

**Comment by gopiprasanthpotipireddy** [comment]
![image](https://user-images.githubusercontent.com/14222254/59098576-4af41a80-893e-11e9-861b-fd45bd642e21.png)
the product view is like in the attachment. @rvema can you suggest any doc regarding the metrics logic.

**Comment by gopiprasanthpotipireddy** [comment]
@rvema i am able to see the stage metrics in the product view.

**Comment by rvema** [comment]
closing the issue since it was resolved.
