### ISSUE TITLE
Integrate Jenkins into Hygieia Dash (Setup using Docker)

### ISSUE THREAD

**Issue by srivasis** [Hygieia/Hygieia#2952]
Hello,
I recently started a Hygieia Dashboard by running the ui and api as docker containers. I want to integrate Jenkins into Hygieia and cannot find any instructions on how to do so, especially for docker. I did find instructions for integration if the dash was deployed not through docker but nothing for docker container deployment.
Thank you in advance.

**Comment by rvema** [comment]
@srivasis Can you check this project - https://github.com/Hygieia/hygieia-starter-kit and see if that helps

**Comment by srivasis** [comment]
Will do, thank you!

**Comment by srivasis** [comment]
I am just starting off with Hygieia and i know some of these questions might be very basic. So, I am trying to figure out how this works in a larger scheme of things. The hygieia-ui docker image i pulled contains the frontend part of the dash and the hygieia-api is the one that talks to the mongodb. How exactly are the collectors then configured if you are working with docker? According to the architecture picture on this page https://hygieia.github.io/Hygieia/architecture.html and my understanding of the docker containers i have created i believe i have the ui, api and mongo db setup but nothing available for the collectors. Could someone give me more information on this or point me in the right direction thanks.

**Comment by mitunmbj** [comment]
i can help u

**Comment by rvema** [comment]
@srivasis There is another project that creates the docker images and deploys. However it works only with AWS as the target environment would be ECS. Please check this out - https://github.com/Hygieia/hygieia-aws-quickstart . Also please confirm if this issue is still relevant.

**Comment by srivasis** [comment]
Deployed Hygieia through docker-compose after installing the hygieia-jenkins plugin on the Jenkins server. It works perfectly, there was another issue with the plugin not showing all builds but there was a simple checkbox for that on the configurations page for the plugin in Jenkins. Thank you for all the help @rvema
