### ISSUE TITLE
Sonar integration in Docker-contained EC2

### ISSUE THREAD

**Issue by JFDonaghy** [Hygieia/Hygieia#2954]
Hello everyone,

I'm very new to DevOps and want to learn how to incorporate collectors like Sonarqube and Fortify into Hygieia using an EC2 image that contains Docker.

I've already found a few sonar examples such as the one here https://github.com/docker-library/docs/tree/master/sonarqube, but I am having trouble since my portainer image already uses port 9000. I'm not sure what to change the port to in the 
$ docker run -d --name sonarqube -p 9000:9000 sonarqube
command.

Right now, I don't have anything from Sonarqube or Fortify to pull in, but I am trying to be ready because that will be my next step.

Thank you very much!

**Comment by rvema** [comment]
@JFDonaghy Are you having trouble to bring up the sonar server on any port other than 9000? and then try configuring with Hygieia?

**Comment by JFDonaghy** [comment]
Thank you very much for reaching out! I found a video that helped me realize that you can change the port, by un-commenting a line in the sonar.properties file (for anyone looking at this later: search for TCP port).

I still have other problems to fix (like a 'bean' error), but I will close this issue.
