### ISSUE TITLE
No result was available from Jira unexpectedly - defaulting to blank response. The reason for this fault is the following:RestClientException{statusCode=Optional.of(500)

### ISSUE THREAD

**Issue by sriharshakatakam** [Hygieia/Hygieia#2960]
2019-06-09 00:00:00,461 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:50, serverValue:1696}] to localhost:27017
2019-06-09 00:00:00,491 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-09 00:00:00,494 INFO  c.c.d.collector.CollectorTask - http://company url/
2019-06-09 00:00:00,495 INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-06-09 00:00:39,584 INFO  c.c.d.collector.CollectorTask - Team Data            2514       39s
2019-06-09 00:00:41,429 INFO  c.c.d.collector.CollectorTask - Project Data          609        1s
2019-06-09 00:00:52,992 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 0 pageSize 25
2019-06-09 00:00:57,002 ERROR c.c.d.client.DefaultJiraClient - No result was available from Jira unexpectedly - defaulting to blank response. The reason for this
fault is the following:RestClientException{statusCode=Optional.of(500), errorCollections=[ErrorCollection{status=500, errors={}, errorMessages=[Internal server er
ror]}]}
2019-06-09 00:00:57,004 INFO  c.c.d.c.story.StoryDataClientImpl - Loop i 25 pageSize 0
2019-06-09 00:00:57,004 INFO  c.c.d.collector.CollectorTask - Story Data             25       15s
2019-06-09 00:00:57,005 INFO  c.c.d.collector.CollectorTask - Finished                        56s

**Comment by sriharshakatakam** [comment]
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=25

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 0/10 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo

feature.jiraTeamFieldName=

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=
#feature.jiraProxyPort=
feature.jiraBaseUrl=http://company url/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
		feature.jiraOauthRedirecturi=
		feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10004

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10006

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customfield_12200

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

**Comment by Sbrenthughes** [comment]
This is not the latest version of the collector. Please use the latest and try again.
