### ISSUE TITLE
Jira Collector fetching data But Not showing in UI

### ISSUE THREAD

**Issue by mitunmbj** [Hygieia/Hygieia#2966]
I configured jira early with my atlassian account and it worked fine and bought data and also propagated in UI now same thing i am doiing for my client.....It is a jira server ...i configured jira and it also fetched data but now its not propagating data in UI

**Comment by rvema** [comment]
If I understand correctly you switched the jira endpoints and ran the collector to collect data but you are not seeing the data on UI?
