### ISSUE TITLE
[Help Wanted] Hygieia Jenkins Integration

### ISSUE THREAD

**Issue by bargemb** [Hygieia/Hygieia#2968]
Is there any reason why Hygieia Jenkins plugin not available on https://plugins.jenkins.io/ ?

What is recommended way to get data into hygieia from Jenkins ?
Pull (Using various collectors like Jenkins, Jenkins Code Quality, Jenkins Cucumber)
Push (Manually installing plugin on Jenkins using hpi file)

Which one of these methods is stable ? Is Hygieia-Jenkins plugin is supported on Cloudbees Jenkins ?

**Comment by rvema** [comment]
Working on publishing it, we I’ll update once done

**Comment by rvema** [comment]
Regarding the second question, we recommend installing the hpi file on the Jenkins masters.

**Comment by bargemb** [comment]
Thanks @rvema
