### ISSUE TITLE
Hygieia-Jenkins Plugin hygieiaBuildPublishStep Broken

### ISSUE THREAD

**Issue by srivasis** [Hygieia/Hygieia#2987]
Hi, so over the last few weeks I have been working on setting up a Hygieia Dashboard. I have been able to successfully install all the collectors and see a really cool dashboard. I did find a problem with the hygieia-jenkins plugin though. When you specify the buildStatus on the pipeline syntax for hygieiaBuildPublishStep it does not filter out builds that do not meet the criteria. Additionally I could not find where in mongodb did the buildStatus information get stored. If someone has any idea how to find any information on this or knows the fix, please help. Thank you.

**Comment by rvema** [comment]
Are you using a freestyle job or a pipeline in jenkins? In Mongo the build information goes into `Builds`  collection

**Comment by srivasis** [comment]
I am using Jenkins pipeline. The builds table has it, thank you for that. I still don't know why the pipeline does not filter the builds though.

**Comment by rvema** [comment]
@srivasis Can you help me understand your issue so that I can help?

**Comment by srivasis** [comment]
The issue was within the settings on Jenkins server. After debugging the source code within the plugin project it led me there and it was a simple fix.

**Comment by rvema** [comment]
@srivasis Can you let us know what configuration.setting change that you had to do so that we can improve our documentation. Also if you find any gaps in the documentation please feel free to contribute back by adding the respective changes.

**Comment by dilipdmane** [comment]
In what mongodb collection , Hygiea jenkin plugin pushes build status ?

**Comment by rvema** [comment]
builds collection

**Comment by ysbre** [comment]
@srivasis can you elaborate on the settings you changed?
