### ISSUE TITLE
Monitor widget shows jenkins server is down (like a warning sign) But my jenkins server is up only 

### ISSUE THREAD

**Issue by mitunmbj** [Hygieia/Hygieia#3006]
I configured the Monitor widget .......And it marks Hygiea server, Localhost, Sonarqube server etc all in healthy status according to their health but it always  marks jenkins as down like a warning sign though jenkins server is up and running

**Comment by rvema** [comment]
@mitunmbj The monitor widgets have been verified with http endpoints but never tried on https.

**Comment by mitunmbj** [comment]
@rvema But my endpoint is http://52.xx.xx.45:8080 what to bro?

**Comment by rvema** [comment]
@mitunmbj Do you have access to the API instance logs and do you see any relevant stacktrace?

**Comment by mitunmbj** [comment]
@rvema i cant understand bro

**Comment by mitunmbj** [comment]
@rvema can u say step by step

**Comment by koroshi** [comment]
i have see my jenkins by default(i don't know if there are some config about this),the main url http://localhost:8080, redirect and in postman its return a 403 code.Is there any method let me monitor the jenkins server health, i doesn't find anything health check url in jenkins .

**Comment by rvema** [comment]
closing this issue as it was resolved
