### ISSUE TITLE
What is the use of team widget and log widget and what does it monitor

### ISSUE THREAD

**Issue by mitunmbj** [Hygieia/Hygieia#3007]

**Comment by Sbrenthughes** [comment]
@stevegal

**Comment by stevegal** [comment]
the Log widget is for the operations side of your application when it is deployed into an environment. It charts the number of times an event has happened in the logs being tracked based on the the filters provided and charts these up in each collection period. You can use it to provide a monitor dashboard within Hygieia for your application. At the moment there is only 1 collector which collects from cloudwatch, but there is nothing preventing other collectors from publishing this data.

Hope that helps.

**Comment by nireeshT** [comment]
Team widget is to display resource tracking at team level. It will display open reqs / full-time/part-time resources count for a team and enables recruitment prioritization. Collector is WIP.

**Comment by rvema** [comment]
closing the issue as the necessary information was provided
