### ISSUE TITLE
Score popup explanation messages

### ISSUE THREAD

**Issue by fidelcoria-aa** [Hygieia/Hygieia#3012]
The meaning of the Scores is not evident to users. Explanation messages make the scores more actionable. For example build widget can be like this:
![image](https://user-images.githubusercontent.com/41026947/60285851-0ec83000-98d4-11e9-83da-a85a5a5fe9f1.png)

Code quality like this:
![image](https://user-images.githubusercontent.com/41026947/60285897-34553980-98d4-11e9-850e-2a0ec760b1da.png)

deploy like this:
![image](https://user-images.githubusercontent.com/41026947/60285936-4df68100-98d4-11e9-93fe-7ff6c64d1616.png)

Github is a little problamatic... the current category name "Commits per day" is flat out wrong
see #3011. If that is resolved by fixing the category name the detail would look like this:
![image](https://user-images.githubusercontent.com/41026947/60286553-62874900-98d5-11e9-82c7-f88c81d8b57b.png)

**Comment by fidelcoria-aa** [comment]
I will wait for those changes to be merged before making PR for this.

**Comment by rvema** [comment]
@fidelcoria-aa which PR is dependent on this? We can prioritize merging soon.

**Comment by fidelcoria** [comment]
PR #3013 should be merged first

**Comment by rvema** [comment]
@fidelcoria #3013 has been merged now.

**Comment by fidelcoria-aa** [comment]
@rvema Thanks! I have created the PR for this. It is mentioned above this comment.

**Comment by rvema** [comment]
@fidelcoria I merged #3015 as well
