### ISSUE TITLE
Monitor widget setup using dashboard/remoteCreate

### ISSUE THREAD

**Issue by adhish70** [Hygieia/Hygieia#3023]
Hello
I am trying to setup the monitor widget using the /dashboard/remoteCreate endpoint. I am unable to find the documentation which mentions all the parameters that needs to be there. Any help would be greatly appreciated.

Thank You

**Comment by rvema** [comment]
@adhish70 At this point the API does not support creation of monitor widget. We do not have any plans to incorporate the same as we are reconsidering the existence of this widget. If you need to make it work you would need to modify DashboardRemoteServiceImpl.create() in the api project (https://github.com/Hygieia/api)
