### ISSUE TITLE
Need help with Custom Collector - Cherwell

### ISSUE THREAD

**Issue by nitingoyal8** [Hygieia/Hygieia#3038]
Need help with custom collector for Cherwell. Its a similar CMDB like Service Now / HPSM and i need to have Cherwell data in order to bring Executive Dashboard.

Any input will be great help.

**Comment by Sbrenthughes** [comment]
Sure, can you give an example of your data model for cherwell?

**Comment by Sbrenthughes** [comment]
Since there has been no reply I am closing this. Please Reopen and provide further details.
