### ISSUE TITLE
Push instead of pull?

### ISSUE THREAD

**Issue by cruisehall** [Hygieia/Hygieia#3046]
I’ve been looking for a tool to aggregate DevOps events (and, eventually, metrics) from a variety of distributed sources. 

Hygieia’s feature set is the strongest I’ve found, but from what I’ve read it seems like the architecture is decidedly built on a “pull” model (I.e. via collectors).

I’m sure there are good reasons for this, but I’m wondering if Hygieia supports a “push” model out of the box, or if this capability has been discussed or road-mapped? If not, I’d love to discuss the merits of the push approach and learn how (or if) others would recommend implementing such a hook.

Thanks folks!

**Comment by rvema** [comment]
Very valid point, we have this kind of behavior implemented for Jenkins and GitHub. Also It kind of boils down to the support offered by the tools to support this kind of event based push.

**Comment by rvema** [comment]
Can we close this issue as we are aware of this and take into account with any newer developments?
