### ISSUE TITLE
api file not found

### ISSUE THREAD

**Issue by aalabi3** [Hygieia/Hygieia#3074]
after recloning Hygieia on another machine I realized that there is no api file and the machine that had all of the original files connects to the Hygieia UI but lacks API connectivity. is there updated documentation on how to proceed with setup and configurations of the api through alternate means/ or was the file just not uploaded?

**Comment by rvema** [comment]
@aalabi3 API is still needed and this project has been migrated to its own repository, Going forward all components within Hygieia project will be under their own repositories. Here is the link to the new repository - https://github.com/Hygieia/api
