### ISSUE TITLE
Installation Procedure References Non-Existent Directories/Targets

### ISSUE THREAD

**Issue by vortextube** [Hygieia/Hygieia#3079]
The installation instructions reference a directory in the Hygieia project called 'API'

https://hygieia.github.io/Hygieia/setup.html#download-or-clone-hygieia-1

The directory does not exist.

Are there validated build instructions?

**Comment by rvema** [comment]
This is a duplicate of https://github.com/Hygieia/Hygieia/issues/3074 . please check the issue
