### ISSUE TITLE
unable to find Jenkins folder in collector folder

### ISSUE THREAD

**Issue by Q3188** [Hygieia/Hygieia#3087]
Hi I am setting up Hygieia for a devops solution in Jenkins. I am unable to the Jenkins folder inside collector folder as given in the document. Please help me to find the same.

**Comment by rvema** [comment]
@Q3188 We are in the mid of migrating the components of Hygieia into their own repositories. Jenkins collector has its own repository now and here is the link to the same [hygieia-build-jenkins-collector](https://github.com/Hygieia/hygieia-build-jenkins-collector) .. We will get the documentation fixed ASAP.

**Comment by rvema** [comment]
@Q3188 The documentation has been updated. Please check the latest documentation
