### ISSUE TITLE
hygieia\collectors\feature\jira Folder not exists

### ISSUE THREAD

**Issue by TruJan34** [Hygieia/Hygieia#3117]
I want to use JIRA Collector.
As per documentation https://hygieia.github.io/Hygieia/jira.html
I dont see \hygieia\collectors\feature\jira  folder to execute mvn install.

So not able to generate the output file jira-feature-collector.jar 

The folder structure is as below.
![image](https://user-images.githubusercontent.com/12947132/63347888-bbbfa600-c375-11e9-8f56-d6d53a693356.png)

I am able to see JIRA Dashboard as in below screenshot.
![image](https://user-images.githubusercontent.com/12947132/63348027-1527d500-c376-11e9-9dce-890ee1562c3b.png)
But not able to Configure Feature Widget as Agile Content Tool Type dropdown is empty.

So am i missing something.
Someone please help me out.

**Comment by rvema** [comment]
@TruJan34 Please see the note about repository migration in the documentation. `** Note: The collectors are being migrated to their own repositories. Please see Module breakout section of Hygieia-2019-Roadmap-(draft,-work-in-progress) for the latest information on the repositories. Documentation will be updated after the migration is complete.`

Jira Collector has been migrated to its own repository and here is the link to the source - https://github.com/Hygieia/hygieia-feature-jira-collector
