### ISSUE TITLE
Hygieia Issue: Not able to see data in hygieia build widget for jenkins

### ISSUE THREAD

**Issue by Harshita-Yadav** [Hygieia/Hygieia#3127]
Installed Mongo
Downloaded Hygieia V1.2.0
Successfully ran mvn clean compile install package
Created application.properties in corresponding config folders for Hudson Collector.
Run hudson collector with java -jar
Run gulp serve in the UI folder

Everything appears to come up ok
I see data has been created in mongo
I can add a dashboard in the UI .

But, I can not succesffuly add Build widgets for Jenkins via the UI.

this is the widget dashboard and we are using build widget-
![widget1](https://user-images.githubusercontent.com/29685797/64021554-df42d780-cb51-11e9-9cbd-7f65e037c2b6.jpg)

widget

on click of configure and adding the server and jobname , it is getting logged out. Below is the snippet-
![buildwidgetsearch](https://user-images.githubusercontent.com/29685797/64021583-ed90f380-cb51-11e9-8c63-10197938a538.JPG)

buildwidgetsearch

Automatically it is coming to login page-
![login1](https://user-images.githubusercontent.com/29685797/64021606-f97cb580-cb51-11e9-8d9a-c7a418eb7495.jpg)

login

And after logging again to the widget dashboard, we are getting build widget with no data-
![build_widget1](https://user-images.githubusercontent.com/29685797/64021619-026d8700-cb52-11e9-9cdd-396e316b6ba7.jpg)

build_widget

Now, when I checked in db, I am getting all the jenkins jobs in collector_items.
But not able to show it in build widget.

**Comment by rvema** [comment]
@Harshita-Yadav For the logout issue we pushed the fix. Please get the latest [api](https://github.com/Hygieia/api) and [UI](https://github.com/Hygieia/Hygieia) and retry and let us know?

**Comment by Harshita-Yadav** [comment]
Thanks @rvema for the response. But I can't find any documents available for the updated version of hygieia. How to make connection to our jenkins server as there is no COLLECTOR now, do we need to write our own collector? 
API is also not present. Please help to understand this new version.

**Comment by rvema** [comment]
@Harshita-Yadav The documentation will be updated shortly. In a nutshell all components within the Hygieia project have been migrated to their own repositories. Please see this wiki page for more details - [2019-Roadmap](https://github.com/Hygieia/Hygieia/wiki/Hygieia-2019-Roadmap-(draft,-work-in-progress)).

**Comment by Sbrenthughes** [comment]
Ragha has also pushed a fix for the random redirects to login.

**Comment by shubhamk0305** [comment]
Hi team,

Currently i am using Hygieia 3.0.2 version

I have configured the dashboard and configured the Jenkins widget and SVN widget in dashboard.
i can see count of data there,but not getting graph visual.
![Dashboard](https://user-images.githubusercontent.com/50317418/64677723-323d5880-d489-11e9-9a6f-033bad5ddf62.PNG)

**Comment by shubhamk0305** [comment]
![graph dadboard error](https://user-images.githubusercontent.com/50317418/64703994-93335380-d4be-11e9-98d2-f76529a51007.PNG)


I am getting error for graph

**Comment by shubhamk0305** [comment]
@Sbrenthughes can you help me out to solve this issue.

**Comment by Sbrenthughes** [comment]
Use the latest UI from master.

**Comment by harshareddy208** [comment]
Hi @Sbrenthughes @rvema , can you please inform by when you will provide the documentation on updated Hygieia version so that we can use it in our project?
