### ISSUE TITLE
Numbers are cut off in widget graphs/axis

### ISSUE THREAD

**Issue by gerardrecinto** [Hygieia/Hygieia#3141]
Hello, as you can see in the images below, I have circled in red that the number 1 in the build widget under Builds per day is cut off on the y axis. Same for the Github Repo widget for the 7 on top of the graph. 

![image](https://user-images.githubusercontent.com/10230481/64718487-28145d80-d47b-11e9-84ae-357a6a72ed8c.png)
![image](https://user-images.githubusercontent.com/10230481/64718498-2ea2d500-d47b-11e9-91c9-ccbc93709715.png)

**Comment by gerardrecinto** [comment]
I fixed this on my local repository. I'm going to make a pull request.

**Comment by rvema** [comment]
@gerardrecinto Thanks a lot for your effort. Please ensure that you sign the CLA before you submit the PR. Here is the link to the [CLA](http://hygieia.github.io/Hygieia/contribute.html)

**Comment by gerardrecinto** [comment]
Closing this issue since I did not submit a Pull Request.
