### ISSUE TITLE
Unable To Run Dashboard Using Docker-Compose

### ISSUE THREAD

**Issue by mohsinzaheer25** [Hygieia/Hygieia#3145]
I'm trying to run the Hygieia Dashboard using docker-compose by following this below URL Instructions and it throw me this error when I run `docker-compose up -d` command.

```
docker-compose up -d
ERROR: Service 'ui' depends on service 'api' which is undefined.
```

I even try to pull `hygieia-api:latest` image and it's not available. Any help is appreciated.

**Steps URL:**
http://hygieia.github.io/Hygieia/builddocker.html

**Comment by itmatters** [comment]
Experienced the same issue: What worked for me:

- Clone or download sources from https://github.com/Hygieia/api
- Build sources
`mvn clean install`    
- Build docker image 
`docker build -t hygieia-api .`
- Add the following section to the docker-compose.yml:
```
api:
    image: hygieia-api
    depends_on:
      - db.
```
Then start Hygieia Dashboard using docker-compose as described with:
```docker-compose up -d
```

**Comment by dasaradhan** [comment]
version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    build: db
    depends_on:
      - db

  api:
  image: hygieia-api
  depends_on:
  - db

  ui:
    build: UI
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  db-data:
  certs:

**Comment by mohsinzaheer25** [comment]
I was able to use the other image and it worked for me. Thanks @itmatters @dasaradhan , for your help.

**Comment by drewkhoury** [comment]
This is still not fixed in the main repo though

**Comment by Niraj-Fonseka** [comment]
Yeah I believe things are not very up to date now because they are in the process of splitting up the project into modules
