### ISSUE TITLE
Does hygieia supports blackduck

### ISSUE THREAD

**Issue by prabhurs123** [Hygieia/Hygieia#3146]
Just want to know, does Hygieia support Blackduck? If yes could you please share some info.

**Comment by Sbrenthughes** [comment]
Yeah Hygieia can support it. However, to my knowledge there isn't a collector that has been contributed to integrate.

**Comment by prabhurs123** [comment]
ok thanks. I have seen a collector in this git location https://github.com/matjukov-nikolaj/blackduck  but its not working.

**Comment by rvema** [comment]
@prabhurs123 we do not have it in our roadmap, you are welcome to create one and contribute back. Thanks!
