### ISSUE TITLE
The commits are not showing up on Team Dashboard.

### ISSUE THREAD

**Issue by SuriDotInc** [Hygieia/Hygieia#3147]
For Some reason, the Team Dashboard is not showing the commits data, The data is being shown on the individual swim lane, but not on the Team Dashboard.
<img width="1111" alt="hygieia_image" src="https://user-images.githubusercontent.com/40207902/65043213-7b2d5b00-d928-11e9-9449-cc021e89256e.png">

**Comment by Sbrenthughes** [comment]
Do you have an SCM collector running? If so which one?

**Comment by rvema** [comment]
@SuriDotInc Do you have database access? If so can you check the `builds` collection and see the commits are present?

**Comment by rvema** [comment]
How did you run the build?
