### ISSUE TITLE
Unable to build the source

### ISSUE THREAD

**Issue by chandan4747** [Hygieia/Hygieia#3154]
Running "mvn clean install" is failing with the below message:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project api: Compilation failure: Compilation failure:
[ERROR] /C:/Root/TADP/HygieiaPlugin/Hygieia-3.0.2/api/src/main/java/com/capitalone/dashboard/service/BinaryArtifactServiceImpl.java:[116,19] cannot find symbol
[ERROR]   symbol:   method setBuildInfo(com.capitalone.dashboard.model.Build)
[ERROR]   location: variable ba of type com.capitalone.dashboard.model.BinaryArtifact
[ERROR] /C:/Root/TADP/HygieiaPlugin/Hygieia-3.0.2/api/src/main/java/com/capitalone/dashboard/service/BinaryArtifactServiceImpl.java:[155,30] cannot find symbol
[ERROR]   symbol:   method getBuildInfo()
[ERROR]   location: variable ba of type com.capitalone.dashboard.model.BinaryArtifact
[ERROR] /C:/Root/TADP/HygieiaPlugin/Hygieia-3.0.2/api/src/main/java/com/capitalone/dashboard/service/BinaryArtifactServiceImpl.java:[156,30] cannot find symbol
[ERROR]   symbol:   method getBuildInfo()
[ERROR]   location: variable ba of type com.capitalone.dashboard.model.BinaryArtifact
[ERROR] -> [Help 1]

**Comment by rvema** [comment]
@chandan4747 please delete your workspace and re clone the repositories from https://github.com/Hygieia . Please check the documentation for more information as they have been updated.
