### ISSUE TITLE
Hygieia udeploy widget is showing old data 

### ISSUE THREAD

**Issue by praveen7kom** [Hygieia/Hygieia#3155]
Hi, 
I am able to get udeploy data on Hygieia dashboard but it is showing the old data instead of showing the new deployment information. could you please let me know if you have any workaround to solve this issue? thanks.

**Comment by praveen7kom** [comment]
Can someone throw some ideas on the troubleshooting steps for udeploy widget showing old deploy data instead of showing the recent? Thank you.

**Comment by rvema** [comment]
@praveen7kom do you have the udeploy collector? Can you check if the collector has run?

**Comment by praveen7kom** [comment]
Well, Udeploy collector is running fine and see the logs pulling data for many applications. i can see data on dashboard as well but the problem is it is showing the deployment data from 2017 and 2018 though we have very recent deployments. and i dont see any errors in logs. Any particular setting that can change this behavior ?

**Comment by rvema** [comment]
@praveen7kom you need to debug the udeploy collector and see why its not collecting the data. The UI just visually represents the data collected by the collector.

**Comment by praveen7kom** [comment]
I have the DEBUG logs enabled but no clue in the logs. Below are the sample logs. I would like to know how exactly we change/control the data shown in the widget. Why the udeploy collector cant pull the latest but the oldest data.

2019-10-01 12:06:32,007 DEBUG c.c.d.e.EnvironmentComponentEventListener - Attempting to find new artifacts to process for environment 'xxxxx'
2019-10-01 12:06:32,315 DEBUG c.c.d.e.EnvironmentComponentEventListener - Attempting to update pipeline xxxxxxxxx3df5adf183
