### ISSUE TITLE
Can't seem to stay logged in

### ISSUE THREAD

**Issue by bmwRacer42** [Hygieia/Hygieia#3158]
Have setup a new Hygieia using all latest code.  All running locally on my laptop.  I have a setup an admin user as described in wiki using Sign Up.   I can then authenticate fine.  However when I click to add a dashboard or the gear for admin pages I get redirected back to the login.

I have found this error in the api logs

2019-10-01 15:26:44,933 [http-nio-8080-exec-1] ERROR c.c.d.rest.RestApiExceptionHandler - An Authentication object was not found in the SecurityContext
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext

# api.properties
dbname=dashboarddb
dbusername=dashboarduser
dbpassword=dbpassword
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
server.contextPath=/api
server.port=8080
logRequest=false
logSplunkRequest=false
corsEnabled=false
version.number=@application.version.number@
auth.expirationTime=1000
auth.secret=hygieiasecret
auth.authenticationProviders=STANDARD
# This will be the page size for pagination on Hygieia landing page. If this property is not set, the default value is set to 10.
pageSize=10
# API token generated for basic authentication to secure APIs.
key=

using node 8.16.1
all data looks good in mongodb
have done clean install and gotten successful build.

Start up for api is:
java -jar api.jar --spring.config.location=C:\hygieia\api\api.properties -Djasypt.encryptor.password=hygieiasecret

**Comment by rvema** [comment]
`auth.expirationTime` is in milliseconds. try removing the property as by default it is set to 1 day.

**Comment by bmwRacer42** [comment]
thanks....should have realized that.  things are working like a charm
