### ISSUE TITLE
Github collector data

### ISSUE THREAD

**Issue by continuum-aditya-pingale** [Hygieia/Hygieia#3172]
![image](https://user-images.githubusercontent.com/52907319/66989554-32f98800-f0e2-11e9-93f2-eea4024f33de.png)

Can someone explain me this data
how is last 14 days data less than last 7 days data
also why is that red sign on the top of collector. There is no error in my collector or api logs

**Comment by continuum-aditya-pingale** [comment]
@Sbrenthughes can you please guide me here? thanks

**Comment by continuum-aditya-pingale** [comment]
@tabladrum @nireeshT  can anyone please help me with this?

**Comment by rvema** [comment]
If you click on the red button then it should tell the error.

**Comment by continuum-aditya-pingale** [comment]
Error collecting data:
but there are no error in collector logs or api logs

**Comment by rvema** [comment]
Do you have access to the db? Can you check the contents of the collector_item for this widget?

**Comment by rvema** [comment]
The collector item will have the reason behind the rtrot

**Comment by continuum-aditya-pingale** [comment]
![image](https://user-images.githubusercontent.com/52907319/68020483-9c71bd00-fcc4-11e9-909f-864192aaac69.png)

can you please explain this?
It is a private repo. The data for other repos is fetched correctly

**Comment by rvema** [comment]
The token might have expired, how are you authenticating against the private repo through the widget?

**Comment by continuum-aditya-pingale** [comment]
with the same github access token

**Comment by rvema** [comment]
How did you configure the widget to authenticate against the private repository? Are you sure the credentials provided have access to this private repository?

**Comment by continuum-aditya-pingale** [comment]
it works for few repos and for few it fetches incorrect data

**Comment by rvema** [comment]
Can you elaborate on the incorrect data?

**Comment by continuum-aditya-pingale** [comment]
![image](https://user-images.githubusercontent.com/52907319/68214700-eed41600-0003-11ea-85bc-cd383b0e2df4.png)

in the image the last 14 days data is less than last 7 days data for pulls

**Comment by rvema** [comment]
> ![image](https://user-images.githubusercontent.com/52907319/68214700-eed41600-0003-11ea-85bc-cd383b0e2df4.png)
> 
> in the image the last 14 days data is less than last 7 days data for pulls

This issue was fixed last week, Can you refresh your UI code and retry? - #3182

**Comment by Sbrenthughes** [comment]
Please reopen if this issue has not been resolved.
