### ISSUE TITLE
Create Pipeline Widget using API

### ISSUE THREAD

**Issue by vigneshsriram** [Hygieia/Hygieia#3180]
I am trying to create the Pipeline widget using the API 

> api/updateDashboardWidgets/{id}/widget

Some values(not all) are getting updated in the MongoDB but not showing on the UI. 
If I do a get /dashboard after updating the dashboard from the API I get the following:
`{
    id: "5db9a4bc3038910009b15e19",
    name: "pipeline",
}`

if I do an update manually from the UI and do a get /dashboard I get the following:
`{
    id: "5db9a4bc3038910009b15e19",
    name: "pipeline",
    options: {
        id: "pipeline0",
        mappings: {
            Env1: "build"
            },
        prod: "Env1",
        order: {
            0: "Env1"
            }
        }
}`

Both of these are under widgets

**Comment by rvema** [comment]
This is not supported at this point. please contribute back the feature if you can.
