### ISSUE TITLE
A question on commit-data.js

### ISSUE THREAD

**Issue by hx70176** [Hygieia/Hygieia#3187]
Starting from line 35 of Hygieia/UI/src/components/widgets/product/js/commit-data.js, it has below comment:
        // querying pipeline commits by date will only return production commits that have
        // moved to prod since that last request. this way we can avoid sending 90 days
        // of production commit data with each request. all other environments will show
        // a current snapshot of data
 
Can someone help elaborate on this, I could not find any code in UI or API repo which actually implements the logic of “only return production commits that have moved to prod since last request”.

**Comment by tareks** [comment]
This is probably a case of the blind leading the blind, but it appears that the code right underneath does that base on `var now` declared right above.
```
        // get our pipeline commit data. start by seeing if we've already run this request
        db.lastRequest.where('[type+id]').equals(['pipeline-commit', collectorItemId]).first().then(processLastRequestResponse);

        function processLastRequestResponse(lastRequest) {
            // if we already have made a request, just get the delta
            pipelineData
                .commits(dateBegins, nowTimestamp, collectorItemId)
                .then(function (response) {
                    return processPipelineCommitResponse(response, lastRequest);
                })
                .then(processPipelineCommitData)
                .finally(function () {
                    dependencies.cleanseData(db.prodCommit, ninetyDaysAgo);
                });
```

I'm not sure why you're looking at this, but I'm having trouble loading any data into the product dashboard (commits, build, or deploy stages). It appears that the `db.request.where` statement returns an empty result and `processLastRequestResponse` never gets executed.

**Comment by hx70176** [comment]
Thanks for helping out, @tareks .   I was able to get the pipeline data loaded and displayed on Product dashboard.

I'm having browser out-of-memory issues with Hygieia though.   If I leave product dashboard open overnight, it will crash, and once it crashed once, the subsequent new instances would crash much faster, like within an half an hour and sometimes minutes.  After some client side debugging, I found out the prodCommit table in IndexedDB had hundred of thousand commit entries although we only had several hundred unique commits from the backend API.  It appears that processPipelineCommitResponse() keeps writing the same commit data into prodCommit  table upon every data refresh.  Eventually the data build up large enough and can not be loaded into memory at once for Hygieia to calculate metrics.

My understanding is that the reason for writing prod stage commit data into IndexedDB is to avoid 
retrieving  90 days of data from backend and to retrieve incremental data and then combine with the data in IndexedDB to construct the full 90 days of data. But I don't see the code is actually doing that. It always send request for date range between Now-90 Days and Now and thus the same data get stored in IndexedDB over and over again.  Hence my original question to get the more clarification on the original design/implementation.

For now, in commit-data.js, I simply removed usages of IndexDB for prodCommit  and instead use  the response from backend API for calculation and rendering since the response already contains full 90 days of data from anyway.   I don't have the out-of-memory issue anymore.

I also tried another approach. First get the timestamp of lastRequest and then use that timestamp as the beginDate to pass onto backend API call. Still backend API is not honoring the beginDate and still returns full 90 days of data. I will need to look into backend API implementation a little more to understand what is happening.

**Comment by splatthy** [comment]
Looks like this got marked stale and closed.  I'm running into a similar memory issue though in the UI on a product dashboard with only 5 team dashboards that have been collecting for a < 3 months.  Chrome spikes to like 4 GB of memory usage and then just gives up and kills the tab.

@hx70176 - You wouldn't happen to have a snippet of what you changed in commit-data.js would you?  I'm sure I could figure it out but would be doing it from scratch.

Separately wanted to get this re-opened since there wasn't really a conclusion to it and see what the official solution is.
