### ISSUE TITLE
Product Dashboard not displaying any data in Commit section and Deploy stage

### ISSUE THREAD

**Issue by vivekshm** [Hygieia/Hygieia#3188]
We started CI/CD only for Dev environment intially.

We have Hygieia 3.0.2 version, NPM version 6.4.1 and Node 10.11.1.

We have SVN for repo widget and Jenkins for build widget and both are configured in Team Dashboard using collectors and data is refelected in repo widget as soon as developer commits the code in SVN. But nothing is displayed in Commit stage and Build stage in product dashboard, however I can see data in Build stage.

Apart from that, I am using Hygieia publisher plug-in for deployment and changes in team dashboard reflected in deployment widget. The same SVN branch is configured in deployment job for build and deploy as in CI job in Jenkins.

We tried to look into pipeline table in mongodb, I can only see two stages Build and Dev (Deployment), seems commit stage is missing.

We also tried to clear the browser data with no success.

Can anyone please help me on this.
![dashboard](https://user-images.githubusercontent.com/57887662/69028499-2c6b7280-09f8-11ea-8354-a53da1a1782e.JPG)

![Capture](https://user-images.githubusercontent.com/57887662/69029029-db5c7e00-09f9-11ea-9def-b922d413fe20.JPG)

I have 1 dummy commit in SVN without executing CI/CD, its reflected in the team dashboard in SVN repo.

I tried to make changes end to end, check-in, check-out, Execute CI (Pull SVN, Build, Sonar), Execute CD (Pull SVN, Package and Deploy using MSDeploy), but getting same results. I am using .NET application. The changes are reflected in Team dashboard in Jenkins, Deployment and Repo widgets.

**Comment by vivekshm** [comment]
Mongodb Pipeline collection:

![Capture](https://user-images.githubusercontent.com/57887662/69028691-be737b00-09f8-11ea-9894-1124e5938088.JPG)

**Comment by vivekshm** [comment]
I have 1 dummy commit in SVN without executing CI/CD.

**Comment by vivekshm** [comment]
Please do the needful.

**Comment by ysbre** [comment]
@vivekshm I have the same issue. Have you found the fix?

**Comment by rvema** [comment]
You have a dummy commit to SVN, Have you done a build on the commit and deployed to any environment? The Dashboard will show the data if its capable of capturing the commits part of a build and if the build also performed deploy to an environment.

**Comment by rvema** [comment]
looking at the toolset, I dont believe we have a collector available for MS Build.

**Comment by vivekshm** [comment]
> @vivekshm I have the same issue. Have you found the fix?
Not yet.


> looking at the toolset, I dont believe we have a collector available for MS Build.
We are using jenkins collector and shown in build widget.
We have done dummy commit to SVN and build it through jenkins and then deployed to dev environment, but not getting anything in the Build and Deploy stage in Product dashboard, however the changes are reflected in the team dashboard SVN repo, Deploy and Jenkins widgets.

**Comment by vivekshm** [comment]
Can anyone help me to troubleshoot, any configurations  required more to achieve the same.

**Comment by rvema** [comment]
@vivekshm Since you don't have a means to collect the build information from your build solution (MSBUILD) and feed Hygieia this will not work for you. If you are familiar with the apis exposed by MSBUILD you may try creating a collector for collecting data from MSBUILD and feed to hygieia. You may take [hygieia-build-jenkins-collector](https://github.com/Hygieia/hygieia-build-jenkins-collector) or [hygieia-build-bamboo-collector](https://github.com/Hygieia/hygieia-build-bamboo-collector) as reference for building your collector. Without the information about builds we cannot associate the commits to build and hence deployment

**Comment by vivekshm** [comment]
Thanks Ragha for feedback. I am already using Jenkins collector for build in Team dashboard. PFA the screenshot. Let me know if you required any further info.
![Hyg](https://user-images.githubusercontent.com/57887662/69424547-eb07f980-0d4e-11ea-8ff8-b21b6f7161a3.png)

**Comment by rvema** [comment]
@vivekshm for the deploy can you share you configured the deploystep in your jenkins pipeline.

**Comment by vivekshm** [comment]
Once the artifacts are successfully deployed to dev environment using MSDeploy. I used Hygieia Publisher plugin to push the notification to Hygieia UI. Please find the below screenshot

![Build](https://user-images.githubusercontent.com/57887662/70208852-9f911a80-1754-11ea-91f8-6f6a2b33f54e.JPG)

**Comment by vivekshm** [comment]
Did you get a chance to see the issue Ragha?

**Comment by Sbrenthughes** [comment]
I don't believe the SVN collector has not been updated to handle commit data for the product dashboard. See https://github.com/Hygieia/Hygieia/issues/1333 for more details
