### ISSUE TITLE
Dockerfiles are coupled to build process

### ISSUE THREAD

**Issue by chyno** [Hygieia/Hygieia#3189]
The Docker files should not be dependence on first locally building the Java project.  The Docker files should use multisource Dockfile to build the project and then create the image.  
Reason:
- Not all people (like me ) have correct Java environment to build projects.  Only requirement should be Docker.
- You do not have any documentation as far as I can see so it is hard to figure out what to do.

I could create pull request with solution if you are interested.

Here is example for the API:
FROM  adoptopenjdk/maven-openjdk8 AS build-env
COPY . ./
RUN mvn install clean
RUN mvn package

FROM openjdk:8-jre
VOLUME ["/hygieia/logs"]
RUN mkdir /hygieia/config

EXPOSE 8080

ENV PROP_FILE /hygieia/config/application.properties
WORKDIR /hygieia

COPY --from=build-env target/*.jar /hygieia
# COPY target/*.jar /hygieia
COPY docker/properties-builder.sh /hygieia/

RUN sed -i 's/\r$//' properties-builder.sh
CMD ./properties-builder.sh &&\
  java -Djava.security.egd=file:/dev/./urandom -jar *.jar --spring.config.location=$PROP_FILE

Thanks,
John

**Comment by rvema** [comment]
@chyno The docker files are in the process of being fixed. The docker images will be available in Dockerhub shortly. check back in a week. The documentation will be updated with links to the images in dockerhub.
