### ISSUE TITLE
Any collector if failed,why will data be displayed on hygieia dashboard 

### ISSUE THREAD

**Issue by Navya-V** [Hygieia/Hygieia#3201]
while a collector is run,and fails for some reason .the previous data is displayed on dashboard .
how many changes are on properties file the output shown on the dashboard is the same .What may be the cause? is there any kind of cache that we have to clear.

**Comment by rvema** [comment]
The dashboard displays the data collected until the last successful run. if the collector run failed for some reason then the data displayed is from last run of the collector. Hope this helps.

**Comment by Navya-V** [comment]
Thanks for the info @rvema
