### ISSUE TITLE
Can we display details of branch owner who committed the change along with last committed date

### ISSUE THREAD

**Issue by nanipriyanka** [Hygieia/Hygieia#3207]
Hi Team, 

We have 4 projects in GIT hub. Lets assume them as A1, A2, A3 & A4. For all the four projects we have setup corresponding Multibranch jenkins pipeline jobs. Once I setup dashboard I would like to display data of no.of commits in a week, last committed date with owner. Jenkins URL etc. Is it possible with Hygieia?

I have added below image for more details. And also kindly let me know if I can make use of any other database other than Mongo DB.  

![image](https://user-images.githubusercontent.com/41240418/71361131-08332080-25b8-11ea-9acc-58da60a31107.png)

**Comment by rvema** [comment]
@nanipriyanka for Q1 - Currently it is not supported but you may fork it and modify to your needs. We did not come across this kind of requirement. For Q2 - We will be working on making this product to support most of the no-sql databases may be in Q1 or early Q2 of 2020. Hope this answers
