### ISSUE TITLE
Can we show gitlab CD/CD or Pipeline in hygieia like jenkins and bamboo?

### ISSUE THREAD

**Issue by waiyanwh** [Hygieia/Hygieia#3210]
Hello ,

Most of our projects repo are located in gitlab and use gitlab ci/cd for our deployment.
So, I tried hygieia and it can only show the push/commit/issues/pull . Not include CI/CD process of gitlab pipeline. All I want to know is , is there any plan to add more collector to hygieia for gitlab.
BTW, Thanks for this awesome project.

**Comment by rvema** [comment]
Currently we don't have a collector for Gitlab CICD, However if you understand the webhook for Gitlab CICD you may enhance the hygieia api to translate the payload from gitlab and convert to the canonical model support for deployment widget. We have a reference implementation for Github and Sonar webhook and a custom implementation for builds, hence we need a way to parse the payload from gitlab and invoke the leverage the existing service methods to achieve this functionality. Hope this helps.
