### ISSUE TITLE
GitHub org and repo name

### ISSUE THREAD

**Issue by friederbluemle** [hygieia/hygieia#3218]
Originally mentioned in #3217

To be more in line with prevalent naming conventions on GitHub, it would be great if the organization **and** repository of this project could by renamed to **all-lowercase**:

```
From
https://github.com/Hygieia/Hygieia

To
https://github.com/hygieia/hygieia
```

Note:

- Automatic redirects will be set up by GitHub, **no** links will be broken
- This does _not_ affect the regular, _stylized_ spelling of **Hygieia** - it's a separate field on the org/repo page, see the following links for examples

URL | | link | Stylized Name
--- | --- | --- | ---
`https://github.com/microsoft` | ✅ | @microsoft | Microsoft
`https://github.com/google`    | ✅ | @google    | Google
`https://github.com/github`    | ✅ | @github    | GitHub
`https://github.com/linkedin`  | ✅ | @linkedin  | LinkedIn
`https://github.com/Hygieia`   | ❌ | @Hygieia   | Hygieia

**Comment by friederbluemle** [comment]
@probot - Please don't close this.

**Comment by rvema** [comment]
Yes agreed this needs to be discussed among the members and needs to be open.

**Comment by rvema** [comment]
@friederbluemle We will get this discussion prioritized at a later time and update you.

**Comment by friederbluemle** [comment]
Thank you @rvema

**Comment by friederbluemle** [comment]
Sorry, just carefully checking - Has this been prioritized yet? It should really only take 1 min to fix and this issue has been open since January.

Thank you!

**Comment by friederbluemle** [comment]
Hi @rvema - Hope you had a good start of the year!

Any updates on this issue? Like I said, fixing this should take only a couple of minutes. If it helps, please include anyone else you think should be involved. Thanks!

**Comment by rvema** [comment]
@friederbluemle Thanks for the reminder, I will resume the conversation in this regard.

**Comment by rvema** [comment]
trying to continue in the discussion area.

**Comment by rvema** [comment]
@friederbluemle The Organization has been renamed to `hygieia` . We will work on renaming some of the underlying repos to comply with the lower case standard. Please close the issue when you have time.

**Comment by friederbluemle** [comment]
Awesome, thanks a lot @rvema :+1: Should we close the issue now, or leave it open until the repo name has been addressed as well?
 
![screenshot-2021-03-19_231806_391624425](https://user-images.githubusercontent.com/743291/111861325-74f7b080-890a-11eb-884b-06b0d7dac462.png)

**Comment by friederbluemle** [comment]
I just noticed this issue has been resolved! Thanks @rvema and team 👏
 
![image](https://user-images.githubusercontent.com/743291/125599379-ed863573-5f43-43bd-9f6d-cb65af9c2d64.png)
