### ISSUE TITLE
The browser session gets reset to login screen in few seconds frequently. 

### ISSUE THREAD

**Issue by karthikmsc05** [Hygieia/Hygieia#3223]
The browser session gets reset to login screen in few seconds frequently. We need to relogin frequently to view dashboard.

**Comment by rvema** [comment]
@karthikmsc05 what is the value set for `auth.expirationTime=` in your api.properties

**Comment by karthikmsc05** [comment]
@rvema Right now in api.properties i dont see auth.expirationTime= property is set. Please let me know if i need to set with what value ?
