### ISSUE TITLE
Not able to get data in the Hygieia Widgets

### ISSUE THREAD

**Issue by shubhamk0305** [Hygieia/Hygieia#3226]
Hi team,

I am currently using latest Hygieia 3.1.0

I am able to login the dashboard and configured the dashboard with the build and Jira widgets.

![image](https://user-images.githubusercontent.com/50317418/75753934-cf4ebf00-5d51-11ea-970e-a6439c7d9202.png)

i am able to fetch data in widgets but not able to see data in graphs 

![image](https://user-images.githubusercontent.com/50317418/75754036-fa391300-5d51-11ea-83dc-66180195c656.png)

 node -v
v10.16.3

npm -v
6.9.0

npx -v
6.9.0

mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T22:11:47+05:30)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_242, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.12.1.el7.x86_64", arch: "amd64", family: "unix"

any lead would be helpful

**Comment by shubhamk0305** [comment]
@rvema  @Sbrenthughes  need help on this issue

**Comment by dwij2812** [comment]
@shubhamk0305 just keep the collectors running for some time initially as it takes some time to initialize and populate the db. Restart them after some time and you will see they will be populated. I know its weird but that's how i also got it running.
