### ISSUE TITLE
Issue with guild serve in UI

### ISSUE THREAD

**Issue by annguyen281** [Hygieia/Hygieia#3229]
Hi Team, I'm facing this issue with "gulp serve" in Hygieia/UI

![image](https://user-images.githubusercontent.com/3479104/76159548-5a65f580-6154-11ea-8be4-ff27e1989234.png)

**Comment by emily-solo** [comment]
I also got error when running gulp serve, with a bit different error msg. 
Is there recommended version to be used? My env set up is:
CLI 2.2.0
gulp 3.9.1
java 1.8
node v12.16.2
npm 6.14.4
mvn 3.3.9

![image](https://user-images.githubusercontent.com/38956906/79609229-3975b600-80ab-11ea-8267-cc3b19f39561.png)

**Comment by rvema** [comment]
Node 12 is not supported, please try using node 8. The upgrade/rewrite is in progress and you may check the progress in https://www.github.com/Hygieia/UI

**Comment by emily-solo** [comment]
@rvema Thanks! Issue resolved after using node v8.1.4
