### ISSUE TITLE
mvn clean package -pl api docker:build fail with below error .

### ISSUE THREAD

**Issue by kadaliphani** [Hygieia/Hygieia#3251]
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: api @
[ERROR] Could not find the selected project in the reactor: api -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException 
 
ERROR: Service 'ui' depends on service 'api' which is undefined.

host not found in upstream "api" in /etc/nginx/conf.d/default.conf
nginx: [emerg] host not found in upstream "api" in /etc/nginx/conf.d/default.conf

[ERROR] Failed to execute goal on project api: Could not resolve dependencies for project com.capitalone.dashboard:api:jar:3.0.2-SNAPSHOT:

**Comment by karlpanganiban** [comment]
I assume you want to build a docker image for API? Based from this document? https://hygieia.github.io/Hygieia/api.html

I experienced the same error.. what i did was this:

1. Run 'mvn install' inside /api
- you must see a BUILD SUCCESS in the end
- then you will see the generated *.jar file inside the /target _(this is iimportant)_

2. Use the Dockerfile in the /api folder. Build the image using the docker file
- e.g. docker build . -t your_api_image_name
