### ISSUE TITLE
Hygieia deployment on ECS

### ISSUE THREAD

**Issue by sseshachala** [Hygieia/Hygieia#3273]
We are trying to deploy Hygieia on ECS as single task and multiple container defintions. The mongo - we are using document db in same vpc. Connectivity to mongo is ok - but when we deploy the task definition, UI comes up - API connectivity is ok - but when we try to login we get the follow error. Can some one help me resolve this issue? What is it we have missed?

{"timestamp":1594602169537,"status":500,"error":"Internal Server Error","exception":"org.springframework.data.mapping.model.MappingInstantiationException","message":"Failed to instantiate com.capitalone.dashboard.model.Authentication using constructor public com.capitalone.dashboard.model.Authentication(java.lang.String,java.lang.String) with arguments null,null","path":"/api/login"}

**Comment by rvema** [comment]
Have you looked into the project [hygieia-aws-quickstart](https://github.com/Hygieia/hygieia-aws-quickstart)

**Comment by sseshachala** [comment]
Yes - it requires lot of customizations for ECS deployment it is not not seamless as it is documented. we have customized and pushed our changes o ctphpe repo on dockerhub.

**Comment by rvema** [comment]
do ping @chrisbelyea or @ryanshriver on that repository and they will be able to help you
