### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by jbadeau** [Hygieia/Hygieia#3275]
This project seems very interesting but its very hard to understand what repos work together:

I am currently working with:

https://github.com/Hygieia/UI - master
https://github.com/Hygieia/api - master
https://github.com/Hygieia/hygieia-scm-bitbucket-collector - master

The bitbucket collector doesn't seem to work properly

Can you please explain what repos are meant to work together

**Comment by rvema** [comment]
@jbadeau if bitbucket collector does not seem to work well for you, please create an issue against that repository providing the necessary details for getting the necessary help.

**Comment by rvema** [comment]
Hopefully this link helps - http://hygieia.github.io/Hygieia/architecture.html

**Comment by jbadeau** [comment]
Hi, my issue is not really the collector but where there is a list of what repos work with what repos.

I would Luke to create a helm chart but I do t know what goes with what?
