### ISSUE TITLE
Unable to open Hygieia UI Dashboard in browser on a public URL

### ISSUE THREAD

**Issue by Fisher1993** [Hygieia/Hygieia#3276]
Hi,

I am trying to open the Hygieia's UI Dashboard on a public URL. Nginx proxy server is configured in between the Internet and the Linux 7 VM. I have followed all the necessary steps, finally, run the 'gulp serve' command but the UI is not visible (Getting: 'Cannot GET /hygieia' in the browser) on the public URL.
I can see this - 
![image](https://user-images.githubusercontent.com/29776735/88049684-30e1bf80-cb73-11ea-9ef5-70584e555877.png)
error in the browser's console log.

Before that, I was getting this - 
![image](https://user-images.githubusercontent.com/29776735/88049932-8e760c00-cb73-11ea-9308-f6f2881ec1e9.png)
error, which I suppressed it by commenting out the 'Content-Security-Policy' lines under some of these - 

![image](https://user-images.githubusercontent.com/29776735/88050144-edd41c00-cb73-11ea-8d19-0c824066b8a9.png)

files.

System details:
- RHEL 7
- Maven: 3.6.3
- Node: 8.17.0
- NPM: 6.13.4
- Gulp: CLI version: 2.3.0

Someone's help would be much helpful and be appreciated...

**Comment by Courtneyp123** [comment]
@Fisher1993 let's get you onboarded with the new UI.  It is currently updated to Angular 8 and much easier to set up.  Could you try this: https://hygieia.github.io/Hygieia/newUI.html ? Let me know how it works for you.

**Comment by Fisher1993** [comment]
> @Fisher1993 let's get you onboarded with the new UI. It is currently updated to Angular 8 and much easier to set up. Could you try this: https://hygieia.github.io/Hygieia/newUI.html ? Let me know how it works for you.

@Courtneyp123 Sure, I will try... Thanks :)

**Comment by Fisher1993** [comment]
> > @Fisher1993 let's get you onboarded with the new UI. It is currently updated to Angular 8 and much easier to set up. Could you try this: https://hygieia.github.io/Hygieia/newUI.html ? Let me know how it works for you.
> 
> @Courtneyp123 Sure, I will try... Thanks :)

>@Courtneyp123 The UI is not accessible with the 'links' command in Linux. Any idea?

**Comment by Courtneyp123** [comment]
> > > @Fisher1993 let's get you onboarded with the new UI. It is currently updated to Angular 8 and much easier to set up. Could you try this: https://hygieia.github.io/Hygieia/newUI.html ? Let me know how it works for you.
> > 
> > 
> > @Courtneyp123 Sure, I will try... Thanks :)
> 
> > @Courtneyp123 The UI is not accessible with the 'links' command in Linux. Any idea?

Is this to download the project? Which step are you using that for?

**Comment by Fisher1993** [comment]
> > > > @Fisher1993 let's get you onboarded with the new UI. It is currently updated to Angular 8 and much easier to set up. Could you try this: https://hygieia.github.io/Hygieia/newUI.html ? Let me know how it works for you.
> > > 
> > > 
> > > @Courtneyp123 Sure, I will try... Thanks :)
> > 
> > 
> > > @Courtneyp123 The UI is not accessible with the 'links' command in Linux. Any idea?
> 
> Is this to download the project? Which step are you using that for?

@Courtneyp123 The UI has already been built and I am running the 'ng serve' command, after execution, I am unable to see the UI dashboard using Linux's 'links' command. If it gets successful I should be able to see it on a public URL.

**Comment by Courtneyp123** [comment]
> > > > > @Fisher1993 let's get you onboarded with the new UI. It is currently updated to Angular 8 and much easier to set up. Could you try this: https://hygieia.github.io/Hygieia/newUI.html ? Let me know how it works for you.
> > > > 
> > > > 
> > > > @Courtneyp123 Sure, I will try... Thanks :)
> > > 
> > > 
> > > > @Courtneyp123 The UI is not accessible with the 'links' command in Linux. Any idea?
> > 
> > 
> > Is this to download the project? Which step are you using that for?
> 
> @Courtneyp123 The UI has already been built and I am running the 'ng serve' command, after execution, I am unable to see the UI dashboard using Linux's 'links' command. If it gets successful I should be able to see it on a public URL.

Okay, if you have your api running and run ng serve, you should be able to go to your localhost url to see the dashboard.  Were you able to fix this issue with links?

**Comment by Fisher1993** [comment]
> > > > > > @Fisher1993 let's get you onboarded with the new UI. It is currently updated to Angular 8 and much easier to set up. Could you try this: https://hygieia.github.io/Hygieia/newUI.html ? Let me know how it works for you.
> > > > > 
> > > > > 
> > > > > @Courtneyp123 Sure, I will try... Thanks :)
> > > > 
> > > > 
> > > > > @Courtneyp123 The UI is not accessible with the 'links' command in Linux. Any idea?
> > > 
> > > 
> > > Is this to download the project? Which step are you using that for?
> > 
> > 
> > @Courtneyp123 The UI has already been built and I am running the 'ng serve' command, after execution, I am unable to see the UI dashboard using Linux's 'links' command. If it gets successful I should be able to see it on a public URL.
> 
> Okay, if you have your api running and run ng serve, you should be able to go to your localhost url to see the dashboard. Were you able to fix this issue with links?

Nope, I couldn't fix the issue... Do we need to make changes to the Nginx reverse proxy server?

**Comment by rvema** [comment]
@stevegal any thoughts on this issue?
