### ISSUE TITLE
New UI not loading completely behind the Nginx proxy server

### ISSUE THREAD

**Issue by Fisher1993** [Hygieia/Hygieia#3294]
Hi,

I am trying to open the New UI on a public URL. Nginx proxy server is between the Hygieia and the Internet. After running the 'ng serve --host <IP address of the host machine>' the Hygieia's UI is not completely up. It shows the revolving loading circle till eternity...

![image](https://user-images.githubusercontent.com/29776735/89502510-be174c00-d7e2-11ea-9915-e23a41b1ef88.png)

Any idea?

**Comment by Courtneyp123** [comment]
@Fisher1993 Hello, are you still running into this issue?

**Comment by Fisher1993** [comment]
Hi @Courtneyp123 , I used the old UI. The problem was with the Nginx proxy configuration for the Hygieia UI. We added 
![image](https://user-images.githubusercontent.com/29776735/95453268-2374ee00-0988-11eb-9cbd-b6701592d688.png)
This line to the proxy configuration and the issue got resolved. Thanks for your reply BTW...

**Comment by Fisher1993** [comment]
Hi @Courtneyp123 , I used the old UI. The problem was with the Nginx proxy configuration for the Hygieia UI. We added 
![image](https://user-images.githubusercontent.com/29776735/95453268-2374ee00-0988-11eb-9cbd-b6701592d688.png)
This line to the proxy configuration and the issue got resolved. Thanks for your reply BTW...

**Comment by Courtneyp123** [comment]
Great, I will close this issue then. Thanks for the update!
