### ISSUE TITLE
Do we really need Hygieia Core to Run the Hygieia api 

### ISSUE THREAD

**Issue by vishnu123sai** [Hygieia/Hygieia#3306]
Do we really need Hygieia Core to Run the Hygieia api , i have ran the api with out core it is working fine for me. I just want to know what is the use of Hygieia Core repo, are we having any dependency with that

**Comment by rvema** [comment]
not required unless you want to make dependent changes. `hygieia-core` is a library dependency of api. You may download the latest jar from maven central and try running it skipping the project checkout and compilation
