### ISSUE TITLE
Hygieia Folder Structure

### ISSUE THREAD

**Issue by VivekBuzruk** [Hygieia/Hygieia#3318]
There are too many repositories under one folder in https://github.com/Hygieia. Just wondering whether it is a good idea to create folder hierarchy like (ie. as per architecture)  ==>
1] UI
2] Middleware 
      a) core, b) api ...  future common ...
3] Collectors ... 
      a) Build, b) SCM ......
.....
which will contain respective repositories (if required with a tag like WIP, Proposed, Stable...). I also find few repositories tagged as WIP, but in general may be good idea to further isolate new rewrite from old structure as per architectural layer.

Think about it and all the best.

**Comment by rvema** [comment]
Here is the [Architecture Link](http://hygieia.github.io/Hygieia/architecture.html). The Organization is maintained by several members and by consensus have moved to this folder layout.

**Comment by VivekBuzruk** [comment]
My suggestion is about **Static architecture**. 

To repeat, there are multiple collectors for various SCMs (and sometimes, more than one for same SCM). Can't we combine them under one folder called SCM_Collectors?
