### ISSUE TITLE
Product Dashboard without deployment tool or pipeline setup

### ISSUE THREAD

**Issue by sumitlalani** [Hygieia/Hygieia#3328]
Hi Team,
Need small help, we configured Hygieia. Have integrated with BitBucket, Bamboo, Sonar and JIRA. Could see details about commit, build, issues etc on team dashboard. But product dashboard is empty and not pulling any details.
Went through similar issues in github, looks like some jenkin plugins is required to pass data to team dashboard. We are using bamboo for build and deployment. Not using uDeploy or XL Deploy or any other deployment tool.
Can we use Product dashboard with bamboo and without any deployment tool? Also is pipeline setup mandatory for Product dashboard?
Couldn't configure pipeline as no value is present in environment dropdown. Also, are there any steps or documentation which I can refer to setup Pipeline, Environment and Product dashboard?

**Comment by wanggerui** [comment]
I why what also can't build up, build a few days, a little helpless, there is no better tutorial

**Comment by rvema** [comment]
@sumitlalani there is no direct out of the box integration with bamboo, if you have a way to push data by creating an adapter that would work for you. You would need to invoke /api/v3/build endpoint in the [api](https://github.com/Hygieia/api) project and specifically [/api/v3/build](https://github.com/Hygieia/api/blob/master/src/main/java/com/capitalone/dashboard/rest/BuildController.java#L67) endpoint.
