### ISSUE TITLE
Incomplete removal of dashboards

### ISSUE THREAD

**Issue by AndriiKhodyriev** [Hygieia/Hygieia#3334]
I created 2 Team dashboards ("Team Dashboard" and "Second Demo Team").
Added widgets to them and customize them.
After that I deleted the dashboard named "Second Demo Team"
![image](https://user-images.githubusercontent.com/12627485/101776484-a980f280-3af9-11eb-97fc-3dc92dc35255.png)
And I created a product dashboard - and when I try to add an existing dashboard to it, I see that there is a dashboard that I deleted earlier.
![image](https://user-images.githubusercontent.com/12627485/101776552-c4ebfd80-3af9-11eb-9478-899ce29d75ad.png)
What could be the problem ? Or is this a known bug?
There are only 2 dashboards in the database (Team and Product)
![image](https://user-images.githubusercontent.com/12627485/101776761-1dbb9600-3afa-11eb-9ef1-a187de1f4750.png)

**Comment by AndriiKhodyriev** [comment]
upd:

I also noticed that if there were widgets on the remote dashboard (for example, repo), then the bitbucket collector tries to get an update from BB to the repository that was in the dashboard

**Comment by rvema** [comment]
@AndriiKhodyriev There are several issues with Product dashboard. For team dashboard please use the new [UI](https://github.com/hygieia/UI)

**Comment by AndriiKhodyriev** [comment]
@rvema I am currently using the latest UI
The problem is not critical of course (I think it is not planned to delete dashboards), but I noticed it and decided to describe it, thanks!
