### ISSUE TITLE
CCLA?

### ISSUE THREAD

**Issue by rzheleva** [hygieia/Hygieia#3346]
Hi Team, 

May you please advise if this project provides the option of contributors signing a corporate version of the CLA Capital One Services, LLC Individual Contributor License Agreement v2.0 (https://cla-assistant.io/hygieia/Hygieia)?

VMware Inc. has signed the Capital One Services, LLC Sofware Grant and Corporate Contributor License Agreement v1.0 and I am wondering if you will accept us adding new contributors to Schedule A for v. 1.0 for this project.

Please advise.

In case you are not sure, may you please point me to a CLA manager or someone else with whom I may discuss this issue. 

Thanks, 
Radi

**Comment by rvema** [comment]
@rzheleva We have stopped supporting Corporate CLA which was running into  maintenance issues as its literally hard to track the employment status with the company signing the CLA and support only individual CLA. hope this helps

**Comment by rzheleva** [comment]
Thank you, @rvema!
