### ISSUE TITLE
ProxyPass URL must be absolute /api

### ISSUE THREAD

**Issue by CianLawlor** [hygieia/hygieia#3413]
Docker API container is reachable at http://localhost:8080/api/ping
![image](https://user-images.githubusercontent.com/68199389/125623804-cf769566-8735-4e66-8a09-ed39792eb4da.png)

Built UI image without issue but get this error when running it:
![image](https://user-images.githubusercontent.com/68199389/125624048-6039f7d7-a3ef-4afd-8bc1-38534c787f84.png)

No documentation or GitHub issues helped.

Thanks.

**Comment by YeWang555** [comment]
Hey were you able to find a solution for the issue?
