### ISSUE TITLE
Broken GH Link on Main Hygieia Org Page

### ISSUE THREAD

**Issue by kensipe** [hygieia/hygieia#3440]
The description for the github Hygieia organization page:  https://github.com/hygieia
has a link of http://hygieia.github.io/Hygieia/getting_started.html which 404s

The solution is to make it:  http://hygieia.github.io/hygieia/getting_started.html

I would submit a PR if it could be fixed that way... but it needs an org owner to update.

I see other parts of code (mostly pom files) which need updates as well.  I will send PRs for those.

**Comment by rvema** [comment]
Please create a PR and I will take care of the merge

**Comment by kensipe** [comment]
@rvema creating PRs for affected projects... but the main org page doesn't make a PR... it is a github configuration outside of code

**Comment by kensipe** [comment]
for clarity: 
<img width="772" alt="hygieia-page" src="https://user-images.githubusercontent.com/27497/145110972-8eae618c-1f7e-4a77-8f34-96a5aabfc21a.png">

**Comment by kensipe** [comment]
PRs:
https://github.com/hygieia/hygieia-docker-collector/pull/13
https://github.com/hygieia/hygieia-scm-subversion-collector/pull/28
https://github.com/hygieia/hygieia-codequality-sonar-collector/pull/81
https://github.com/hygieia/hygieia-helm-collector/pull/12
https://github.com/hygieia/hygieia-iac-terraform-collector/pull/10
https://github.com/hygieia/hygieia-workflow-github-collector/pull/6

**Comment by kensipe** [comment]
there are 2 archived projects with bad links as well.. but they are archived

**Comment by aswink19** [comment]
Fixed the link!
