### ISSUE TITLE
hygieia/api dockerfile outdated

### ISSUE THREAD

**Issue by YeWang555** [hygieia/hygieia#3446]
the document site instruction seems like doesn't match the most recent code in master, application.properties file is src/main/resources/ but dockerfile seems like is completely outdated, can someone update the dockerfile or give guide to update the dockerfile ?

**Comment by abjoseph** [comment]
Hi @YeWang555, I see you closed this issue as completed, was the Dockerfile updated or did your company decide to go in another direction?
