### ISSUE TITLE
Website URL in Repository Details is a broken link

### ISSUE THREAD

**Issue by tdemaio** [hygieia/hygieia#3477]
The website URL in this repo does not work. This appears to be due to the case of the "H" in the URL: 
[http://hygieia.github.io/Hygieia](http://hygieia.github.io/Hygieia)

If changed to "h", the site loads. 
[https://hygieia.github.io/hygieia]( https://hygieia.github.io/hygieia)

Steps to reproduce: go to the [repo](https://github.com/hygieia/hygieia), click the link for the website associated with the repo.

Maybe use the Jekyll plugin to fix the redirect and cover this case? via https://stackoverflow.com/a/48389490

Short term, a project admin could update the website URL in the repo config so that people coming to the repo can click through and see your site.

This link:
![Screen Shot 2022-10-06 at 12 15 05 PM](https://user-images.githubusercontent.com/9117026/194365494-a59866a6-a173-45f3-9de2-45b371ac5b65.png)

Love what you have been building - thanks for sharing!

**Comment by aswink19** [comment]
Thanks for bringing this up. Fixed!
