### ISSUE TITLE
Need clarification on Fortify Collector

### ISSUE THREAD

**Issue by ghouspasha** [Hygieia/Hygieia#562]
@tabladrum Regarding HP Fortify Collector,Could you pls help me to 
1. how to get exact web service url for fortify
    ``` properties
    fortify.server=http://myfortify/ssc/fm-ws/services
    ```
2. is fortify a REST or SOAP service?

**Comment by tabladrum** [comment]
You need to configs:

fortify.token= ?????
fortify.server=http://myfortify/ssc

Fortify latest version is Rest. But current the collector that we use is 4.30 supported only.

**Comment by ghouspasha** [comment]
@tabladrum currently I am using 4.21 version, can u pls tell me the changes that needs to be done for 4.30 collector code

**Comment by tabladrum** [comment]
I think the current collector should support 4.21 too.

**Comment by ghouspasha** [comment]
@tabladrum  For Jira collector we have this type of query in Feature Repository 
@Query(value = "{'sTeamID' : ?0 , 'isDeleted' : 'False', $and : [{'sSprintID' : {$ne : null}} , {'sSprintBeginDate' : {$lte : ?1}} , {'sSprintEndDate' : {$gte : ?1}}]}, $orderby: { 'sStatus' :-1 }", fields = "{'sSprintID' : 1, 'sSprintName' : 1,'sSprintBeginDate' : 1, 'sSprintEndDate' : 1}")
	List<Feature> getCurrentSprintDetail(String sTeamID, String currentISODateTime);
I want to retrieve spring details whose start date is less than current date and end date greater than current date.
From where do I need to pass these values?
Pls help

**Comment by ghouspasha** [comment]
@tabladrum : When i am parsing .fpr file from hp fortify collector, I am getting mismatch in the count
Values from collector:
Severity-->blocker value-->9
Severity-->major value-->450
Severity-->critical value-->72

Values from hp fortify ssc UI:
Severity-->blocker value-->0
Severity-->major value-->50
Severity-->critical value-->12

Please help!!

**Comment by tabladrum** [comment]
We are aware of this mapping issue. We did a custom mapping. Will correct it.

**Comment by ghouspasha** [comment]
@tabladrum : could you please let us know once this mapping issue is resolved.
Thanks in advance. It will be really great if this issue is fixed asap :)

**Comment by tabladrum** [comment]
Working on it. I know the changes need to be made.

**Comment by ghouspasha** [comment]
@tabladrum : I tried from my end as well to map this but couldn't make it. any update ?

**Comment by amitmawkin** [comment]
@tabladrum  any update on this, can this be closed?

**Comment by tabladrum** [comment]
I need to correct some mapping. Will get to it before year end.

**Comment by avadhmr** [comment]
Any update on this?

**Comment by tabladrum** [comment]
Not yet.

**Comment by avadhmr** [comment]
fyi - I have noticed that the fortify collector eats too much memory resulting into other process getting killed. seems to me that it is introducing some memory leaks

**Comment by Booma-Baskaran** [comment]
@tabladrum - Any update about the mapping mismatch? We are also facing this issue.

**Comment by Arush1989** [comment]
Hi,

Regarding the fortify token to be put in the properties file, can anyone please clarify which token is this exactly.

Fortify has a number of tokens. I have tried with authentication token which we get after sending a post request to fortify api, but that doesn't work. Please provide more details about the fortify token.

Thanks

**Comment by rvema** [comment]
closing the issue due to inactivity

**Comment by satishkumar-dev** [comment]
how cam i get below configurations ?

fortify.token= ?????
fortify.server=http://myfortify/ssc
