### ISSUE TITLE
Hygieia unable to handle unstable Jenkins builds

### ISSUE THREAD

**Issue by jas5843** [Hygieia/Hygieia#680]
When a build is marked as unstable by Jenkins, Hygieia marks this change set (collection of GitHub commits) as a failure (red). The next successful running of this job should mark these as successful (green) and move the change set forward in Hygieia. However, Hygieia does not handle this properly and instead will keep the change set from an unstable build in the commit stage for as long as this data persists. Furthermore, an unstable build should show as a yellow status in Hygieia, providing more clarity to the user as requested in this issue: [https://github.com/capitalone/Hygieia/issues/84](https://github.com/capitalone/Hygieia/issues/84)

**Comment by rvema** [comment]
This has been implemented and hence closing the issue
