### ISSUE TITLE
RTC Collector

### ISSUE THREAD

**Issue by vijayct2001** [Hygieia/Hygieia#683]
Is it possible to do a RTC collector? I know RTC will support REST API..

**Comment by rodrigosiviero** [comment]
I asked the same thing and I think there's someone from IBM/Urbancode working with some integration, if I get more info I'll post here.

**Comment by andyct** [comment]
We are also interested in RTC collector. Any info, please share.

**Comment by rohanb3** [comment]
Hi,

Anyone having any updates on the RTC collector for hygieia, please let know. We are looking to use hygieia dashboard with RTC.

**Comment by tabladrum** [comment]
It does not look like we are going to support RTC unless it is contributed by the community.
