### ISSUE TITLE
Clarification on StaticAnalysis API for Security Collector

### ISSUE THREAD

**Issue by mickfeech** [Hygieia/Hygieia#694]
I'm parsing some veracode xml scans, have all the data ready to POST to the API however looking for clarification on the descriptions of the data to POST as I've created items and they aren't showing in the dashboard.  Can I get descriptions on the following items?

```
{
  "hygieiaId": "string",
  "niceName": "string",
  "projectId": "string",
  "projectName": "string",
  "projectUrl": "string",
  "projectVersion": "string",
  "serverUrl": "string",
}
```

**Comment by mickfeech** [comment]
I've switched to just inserting the data directory into the database.  I'd be more than happy to help test the API whenever the change is added, however.

**Comment by Mahendra1260** [comment]
@tabladrum .I am using checkMarx scan for the security scan. Any way i can integrated that with UI?

**Comment by tabladrum** [comment]
We are going to work on allowing other tools to push SCA data. Please stay tuned.

**Comment by Saini01Basu** [comment]
Any update on checkmarx integration with Hygieia?
