### ISSUE TITLE
Jenkins-Hygieia plugin: Need to publish test results even if build fails

### ISSUE THREAD

**Issue by tabladrum** [Hygieia/Hygieia#708]
Some teams fail the Jenkins build if cucumber tests fail (fully or partly). Currently the plugin publishes results only if the build is successful or unstable. The config should have an option to publish the results even if build fails.

**Comment by Sbrenthughes** [comment]
@tabladrum is this still relevant?

**Comment by tabladrum** [comment]
This implemented already.
