### ISSUE TITLE
What appetite is there to have non java collectors?

### ISSUE THREAD

**Issue by mickfeech** [Hygieia/Hygieia#713]
What appetite is there to have non-java collectors? I have a couple of collectors that I have written in python.  They either cover capability gaps of current collectors or are completely new collectors.

**Comment by RobertKelly** [comment]
I think it's good to have other options.  We are building some Node.js collectors.  It's just less overhead in our minds.  I think that for what these collectors do, it makes sense to have a minimal amount of complexity around them.

**Comment by amitmawkin** [comment]
All Contributions are welcome ... w.r.t Collectors.
The architecture around collectors is open and not tied to any programming platform. 
Collectors are an independent piece of software whose sole task is to collect Data .
 We really like where we can do  a push vs a pull, but in case a push is not possible pull is fine.

What Collectors are you working on ?

**Comment by mickfeech** [comment]
I have a jenkins collector (build) that works with folders and pipeline, same with a cucumber collector (functional tests). I also have a veracode collector (security code) and an openshift collector (deploy) that I'm working on. 

I'll finish them up next week and send a pull request.  How would you guys prefer non java collectors be stored in the repository if it's no java? Follow same format as the Java collectors?

**Comment by tabladrum** [comment]
We probably should create a separate project/module for collectors keeping UI and API as the main project.

**Comment by mickfeech** [comment]
Once there is a landing spot I'll send some pull requests

**Comment by tabladrum** [comment]
Perfect. Thanks!

**Comment by jimzucker** [comment]
@tabladrum This is a relatively small project,  creating multiple repos will make management of compatibility more work, I would recommend keeping 1 repo for the project. If we do want to split it we have to define the rules for version compatibility/release management etc.

**Comment by vijayct2001** [comment]
@mickfeech , Could you please share openshift collector.
