### ISSUE TITLE
Request:  Document Data Structure 

### ISSUE THREAD

**Issue by mickfeech** [Hygieia/Hygieia#716]
I'd request that you document the data structure for all the documents you store in the mongo database for use in the UI.  This would assist in increasing the velocity at which additional collectors could be developed.  There is currently a lot of trial and error when developing new collectors to ensure it's posted appropriately so the UI will pick it up.

**Comment by tabladrum** [comment]
👍

**Comment by Sbrenthughes** [comment]
http://hygieia.github.io/Hygieia/dbschema.html
