### ISSUE TITLE
Deploying old applications does not properly reflect in the product dashboard

### ISSUE THREAD

**Issue by MarkRx** [Hygieia/Hygieia#816]
If an older version of a component is deployed it will not be reflected properly in the product dashboard. This is because the EnvironmentComponentEventListener always adds the commits from the builds from the latest artifacts. There is no logic to remove commits. Thus if an older version is deployed into an environment newer commits will still exist in the pipeline document resulting in an inaccurate dashboard.

**Comment by MarkRx** [comment]
In order to fix this I think the following has to happen:

1. Artifacts need to store information about the scmRevisionNumber, scmUrl, and scmBranch that was used to create them. For a MVP we should assume an artifact comes from one repository.
2. Commits need to store information to allow a graph to be built in memory. A commit can store its parent commits (more than one for merges). A graph can be built in memory based on the HEAD information from the artifact. For scm we might be able to assume all scm revision numbers less than the one stored on the artifact are ancestors.
3. With the information from 1 and 2 determine the commits for the artifact being deployed in the environment in EnvironmentComponentEventListener. We would have to correlate the component version with the artifact version for now until a more flexible association mechanism can be devised.

**Comment by tabladrum** [comment]
Will work on it this week.

**Comment by MarkRx** [comment]
@tabladrum what do you plan on doing exactly so I don't bump in to your changes? Also I suggest working off of PR #815 for storing information in artifacts

**Comment by tabladrum** [comment]
Let me first digest your analysis first. Are you open for a conf call tomorrow or Friday?

**Comment by MarkRx** [comment]
Yes I am.

**Comment by MarkRx** [comment]
PR #824 for part of point 2. Even if this solution isn't used I think having the scm parent revision information will prove to be useful in the future.

**Comment by tabladrum** [comment]
Please send me your contact info to my work email: tapabrata.pal@capitalone.com. I will put something on the calendar.
