### ISSUE TITLE
Definition of "Component"?

### ISSUE THREAD

**Issue by MarkRx** [Hygieia/Hygieia#820]
A concept of "component" is used throughout Hygieia, especially in the context of deployments. For example, environment_component collection associates environment data to "components". Component.java has this:

> /**
> - A self-contained, independently deployable piece of the larger application. Each component of an application
> - has a different source repo, build job, deploy job, etc.
>   *
>   */

So here is my question: which of the two scenario's best illustrates a component?
Suppose I have an application with two parts that come from two wars: myapp-api.war and myapp-ui.war. These are deployed together. For the sake of argument suppose they are built separately and come from separate repositories.
1. **Components live at the artifact level**. They are what comes out of builds. Both myapp-api.war and myapp-ui.war are components. They happen to be deployed together.
2. **Components live at the deployment level**. They consist of a collection of artifacts. In this example my component is a deployment package that consists of myapp-api.war and myapp-ui.war. They are always deployed together.

I've been assuming that number 2 is the definition that is being used - namely tracking deployment packages as opposed to individual artifacts. However, it doesn't appear that Hygieia is setup to handle this situation the way I devised it. In particular, the product dashboard can only watch 1 artifact from 1 build that comes from 1 repository. The scenario I setup has 1 component : 2 builds : 2 repositories.

**Comment by tabladrum** [comment]
A component is a generic place holder in Hygieia. It may or may not be tied to a single or multiple artifact. It is there just to allow future growth.
