### ISSUE TITLE
Bug: Saving a Code Repo widget after data has been collected results in duplicate collector_items

### ISSUE THREAD

**Issue by MarkRx** [Hygieia/Hygieia#826]
Duplicate collector_items can be created which results in strange behavior. Below is an example for SCM collector_items but I suspect this may happen in other places.

Steps to reproduce
1. Create a dashboard and set it up the "Code Repo" widget to use a repository that has not been used.
2. Wait for a scm collector to run
3. Refresh the page. Open the widget and save it.

There will now be 2 collector_items that correspond to the same repo + branch + scm type combination.

This is because once the scm collector runs the collector might have additional options tacked on. For example, the BitbucketCollector adds the "lastUpdate" and "lastCommit" options. Hence findByCollectorAndOptions does not find the existing collector_item since the incoming item.getOptions() do not contain this information.
CollectorServiceImpl.java:

```
    public CollectorItem createCollectorItem(CollectorItem item) {
        CollectorItem existing = collectorItemRepository.findByCollectorAndOptions(
                item.getCollectorId(), item.getOptions());
        if (existing != null) {
            item.setId(existing.getId());
        }
        return collectorItemRepository.save(item);
    }
```

I think findByCollectorAndOptions needs to be changed to allow items to show up if they have additional properties that do not exist in the incoming map. Will have to check mongo documentation if this can be done.

**Comment by MarkRx** [comment]
A sparse unique index (or partial if minimum mongo version is 3.2) could be added to collectoritem for options:
{'options.scm':1,
'options.branch':1,
'options.url':1}

I think findByCollectorAndOptions would have to be manually implemented to search for the properties in the map.

**Comment by MarkRx** [comment]
Looks like when changing settings we are calling CollectorServiceImpl /collector/item which is always creating a new collector item overwriting an old one if it already exists. As a result the additional metadata information is lost (such as last update time).

**Comment by Sbrenthughes** [comment]
@MarkRx can you confirm this issue has been resolved in the latest release?

**Comment by tabladrum** [comment]
I don't see this occurring any more.
